force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <description>SP-168: new Object for storing all the Additional charges and asset during Contract creation.</description>
    <label>Additional Charges</label>
    <nameField>
        <displayFormat>add-{00000}</displayFormat>
        <label>Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchAdditionalChargeStartDate.cls
global class BatchAdditionalChargeStartDate implements Database.Batchable<sObject> {
	
	String query = 'select id,Start_Date__c,Id_Opportunity__r.closeDate,createdDate  from Additional_Charges__c where Start_Date__c = null';
	
	global BatchAdditionalChargeStartDate() {
		
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		List<Additional_Charges__c> updateAddtCharges = new List<Additional_Charges__c>();
   		for(Additional_Charges__c addt : (List<Additional_Charges__c>)scope){
   			addt.Start_Date__c = addt.Id_Opportunity__r.closeDate;
   			updateAddtCharges.add(addt);
   		}
   		update updateAddtCharges;
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}