force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <description>SP-168: new Object for storing all the Additional charges and asset during Contract creation.</description>
    <label>Additional Charges</label>
    <nameField>
        <displayFormat>add-{00000}</displayFormat>
        <label>Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <label>Id Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Run_Approval_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Run_Approval_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to true in Approval Process APAC_Standard_Approval_For_Add_Charges to deal with sel-approval issue. Visible for all profiles, but not added to any Layout.</description>
    <label>Run Approval Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>To be sent</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>termination date for Additional Charges termination SP-235</description>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>0% Commission Upselling</fullName>
            </value>
            <value>
                <fullName>Bad debtor</fullName>
            </value>
            <value>
                <fullName>Best Price Guarantee</fullName>
            </value>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Business Temporarily out of service</fullName>
            </value>
            <value>
                <fullName>Cannot Contact</fullName>
            </value>
            <value>
                <fullName>Capacity - Competitors</fullName>
            </value>
            <value>
                <fullName>Capacity - Driver Issue</fullName>
            </value>
            <value>
                <fullName>Capacity - Order Volume</fullName>
            </value>
            <value>
                <fullName>Capacity - Own Website</fullName>
            </value>
            <value>
                <fullName>Change of Business Name</fullName>
            </value>
            <value>
                <fullName>Comission too high</fullName>
            </value>
            <value>
                <fullName>Commission Upselling</fullName>
            </value>
            <value>
                <fullName>Contract never received</fullName>
            </value>
            <value>
                <fullName>DH Delivery</fullName>
            </value>
            <value>
                <fullName>Does not accept Online Payment</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Exclusive with competitor</fullName>
            </value>
            <value>
                <fullName>Franchise Contract - Commission Change</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>High Failure Rate</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Issues with payments to restaurant</fullName>
            </value>
            <value>
                <fullName>Language issues</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Legal Issue</fullName>
            </value>
            <value>
                <fullName>Logistics Issue</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
            <value>
                <fullName>Low Rating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AdditionalChargesSelector.cls
public inherited sharing class AdditionalChargesSelector {

    public static List<Additional_Charges__c> getActiveAdditionalChargesForAccount(Id accountId) {
        return [SELECT id,termination_date__c
        FROM Additional_Charges__c
        WHERE Id_Account__c =:accountId and termination_date__c=null];
    }

    /*******************************************************************************************************
    * @description Queries for Additional Charges records by provided Opportunity Ids.
    * @param keys Set<ID> Opportunity.
    * @return List<Additional Charges>
    */
    public static List<Additional_Charges__c> getAdditionalChargesForOpportunity (final set<Id> setOppId){
        List<Additional_Charges__c> listAddCharges = new List<Additional_Charges__c>();
        try {
            listAddCharges = [select Id, Interval__c, Id_List_Product_Price__c, Quantity__c, Unit_Cost__c, Sub_Product_Name__c, Budget__c, Status__c  from Additional_Charges__c
                              where Id_Opportunity__c =: setOppId];
        } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return listAddCharges;
    }

    /*******************************************************************************************************
    * @description Queries for Additional Charges records by provided Booking Id.
    * @param keys Set<String> Booking Id.
    * @return List<Additional Charges>
    */
    public static List<Additional_Charges__c> getAdditionalChargesByBookingID (final set<String> setBookingId){
        List<Additional_Charges__c> listAddCharges = new List<Additional_Charges__c>();
        try {
            listAddCharges = [select Name, Id,Termination_Date__c,Status__c,Termination_Reason__c,Interval__c, Quantity__c, Unit_Cost__c, Sub_Product_Name__c, Budget__c
                              from Additional_Charges__c
                              where Booking_Api_Id__c = :setBookingId and Status__c IN ('Active','Expired','To be sent', 'Draft')];
        } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return listAddCharges;
    }
  
    /*******************************************************************************************************
    * @description Queries for Terminated Additional Charges records by provided Booking Id.
    * @param bookingIds Set<String> Booking Id.
    * @return List<Additional Charges>
    */
    public static List<Additional_Charges__c> getTerminatedByBookingIds (final Set<String> bookingIds){
        List<Additional_Charges__c> listAddCharges = new List<Additional_Charges__c>();
        try {
            listAddCharges = [select Id,Termination_Date__c,Status__c,Termination_Reason__c,Booking_Api_Id__c
            from Additional_Charges__c
            where Booking_Api_Id__c = :bookingIds and Status__c = 'Terminated'];
          } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return listAddCharges;
    }

     /*******************************************************************************************************
    * @description Returns a list of Additional Charges with related Process Instances
    * @param Set<Id> set of record ids
    * @return List<Additional Charges>
    */
    public static List<Additional_Charges__c> getAdditionalChargesWithProcessInstances (Set<Id> addChargesIds){
        List<Additional_Charges__c> listAddCharges = new List<Additional_Charges__c>();
        try {
            listAddCharges =  [SELECT Id,Run_Approval_Trigger__c,(SELECT ID, SubmittedById FROM ProcessInstances ORDER BY CreatedDate DESC) FROM Additional_Charges__c WHERE ID IN :addChargesIds];
        } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return listAddCharges;
    }

}