force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <description>SP-168: new Object for storing all the Additional charges and asset during Contract creation.</description>
    <label>Additional Charges</label>
    <nameField>
        <displayFormat>add-{00000}</displayFormat>
        <label>Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>To be sent</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flat Commission</fullName>
            </value>
            <value>
                <fullName>Ad Sales</fullName>
            </value>
            <value>
                <fullName>Premium Placement</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/recordTypes/Talabat_Additional_Charges.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Additional_Charges</fullName>
    <active>true</active>
    <label>Talabat Additional Charges</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/Talabat_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>Talabat_List_Product_Group</fullName>
    <active>true</active>
    <label>Talabat List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this attribute activates the product, so that this product is able to select in the opportunity</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/Talabat_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>Talabat_List_Product_Price</fullName>
    <active>true</active>
    <label>Talabat List Product Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Talabat_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Talabat Sales Process</businessProcess>
    <description>Talabat Opportunity</description>
    <label>Talabat Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Midas_Exception__c.field-meta.xml
<CustomField>
    <fullName>Midas_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that indicates whether there was an exception when approving/canceling a booking in Midas</description>
    <inlineHelpText>Field that indicates whether there was an exception when approving/canceling a booking in Midas</inlineHelpText>
    <label>Midas Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/Talabat_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>Talabat Opportunity Line Item</label>
</RecordType>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tarifs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/Talabat_Tarif.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Tarif</fullName>
    <active>true</active>
    <label>Talabat Tarif</label>
</RecordType>

force-app/main/default/classes/NcrRetry_Test.cls
/**
* @author Mantas Jurkunas
* @date 15.11.2019
*
* @description Test class for NcrRetry functionality
*
*/
@IsTest
private class NcrRetry_Test {

    @isTest static void testRestBookingServiceSuccess() {
        Test.setMock(HttpCalloutMock.class, new MidasCalloutMock(false));

        Test.startTest();
            Database.executeBatch(new NcrRetry_Batch());
        Test.stopTest();
        for (Opportunity_Line_Item__c lineItem: OpportunityLineItem_Selector.getAll()) {
            System.assertEquals(false, lineItem.Midas_Exception__c);
        }
    }

    @isTest static void testRestBookingServiceError() {
        Test.setMock(HttpCalloutMock.class, new MidasCalloutMock(true));

        Test.startTest();
        Database.executeBatch(new NcrRetry_Batch());
        Test.stopTest();
        for (Opportunity_Line_Item__c lineItem: OpportunityLineItem_Selector.getAll()) {
            System.assertEquals(true, lineItem.Midas_Exception__c);
        }
    }

    @TestSetup
    public static void setup() {

        Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Case','Additional_Charges__c'});
        UnitTestDataFactory.getRecordtypeValues();

        Country__c beh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        insert beh;

        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',Business_Rule_Value__c='TestTemplate',Id_Country__c=beh.id,Is_Active__c=true,Parent__c=true,Process_Name__c='OppQuoteProcess',Record_Type_Id__c='Talabat_Account',Type__c='Process');
        Business_Config__c b2 = new Business_Config__c(Business_Rule_Name__c = 'Status__c', Business_Rule_Value__c = 'Accepted', Id_Country__c = beh.id, Is_Active__c = true, Parent__c = true, Process_Name__c = 'OppTypeAndStageProcess', Record_Type_Id__c = 'Talabat_Opportunity_Quote', Type__c = 'Process');
        Business_Config__c b3 = new Business_Config__c(Business_Rule_Name__c = 'Product Only', Business_Rule_Value__c = 'stageName=Quality Check Request,Probability=95', Id_Country__c = beh.id, Is_Active__c = true, Parent__c = false, Process_Name__c = 'OppTypeAndStageProcess', Record_Type_Id__c = 'Talabat_Opportunity_Quote', Type__c = 'Process');
        Business_Config__c b4 = new Business_Config__c(Business_Rule_Name__c = 'opportunity stage', Business_Rule_Value__c = 'Closed Won', Id_Country__c = beh.id, Is_Active__c = true, Parent__c = false, Process_Name__c = 'Opportunity Contract Process', Record_Type_Id__c = 'Talabat_Opportunity', Type__c = 'Process');
        Business_Config__c b5 = new Business_Config__c(Business_Rule_Name__c = 'AdditionalCharges RecordType', Business_Rule_Value__c = 'Talabat_Additional_Charges', Id_Country__c = beh.id, Is_Active__c = true, Parent__c = false, Process_Name__c = 'Opportunity Contract Process', Record_Type_Id__c = 'Talabat_Opportunity', Type__c = 'Process');
        Business_Config__c b6 = UnitTestDataFactory.createBusinessConfig('EmailConfiguration', 'Process', 'EmailTemplateMap', '{"New Business":"Talabat_NB_EmailTemplate","UpgradeUpsell":"Talabat_ProductOnly_EmailTemplate","Premium Placement":"Talabat_PP_EmailTemplate"}', beh.Id, 'Talabat_Opportunity_Quote', true, true);
        Business_Config__c b7 = UnitTestDataFactory.createBusinessConfig('EmailConfiguration', 'Process', 'EmailSubject', 'Partnership Confirmation', beh.Id, 'Talabat_Opportunity_Quote', true, false);
        Business_Config__c b8 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','Enable','True',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b9 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','opportunityName','Premium Placement',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b10 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','opportunityType','Product Only',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b11 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','businessType','Upgrade/Upsell',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b12 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','stageName','Verbal Agreement',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b13 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','oppLineItemType','Product',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b14 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','discountType','%',beh.Id,'Talabat_Opportunity',true,false);
        Business_Config__c b15 = UnitTestDataFactory.createBusinessConfig('Booking_Service','Process','tarifName','Premium Placement',beh.Id,'Talabat_Opportunity',true,false);

        insert new List<sObject> { b1, b2, b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13,b14,b15};

        Account acco = UnitTestDataFactory.createAccount('TEST', beh, 'Talabat_Account');
        acco.Type = 'Branch - main';
        acco.Backend_ID__c = '83G63';
        acco.GRID__c = '4O2N63';
        insert acco;
        List<account> accountlist = new List<account>();
        accountlist.add(acco);

        list<Contact> contacts = UnitTestDataFactory.CreateContacts(accountlist, 'Best', 'Burger', 'Mr', 'Employee', 1, 'test', 'Talabat_Contact');
        contacts[0].Contact_Role__c = 'Owner';
        insert contacts;

        Company__c com_bh = UnitTestDataFactory.createCompany('Talabat Bahrain', 'Talabat', beh);
        insert com_bh;

        Tarif__c t = UnitTestDataFactory.createTarif(com_bh, beh, 'Premium Placement SE', 'Talabat_Tarif', false);
        insert t;
        t.Is_Active__c = true;
        update t;

        Opportunity oppt = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'Talabat_Opportunity', Date.today());
        oppt.Business_Type__c = 'Upgrade/Upsell';
        oppt.Id_Tarif__r = t;
        oppt.StageName = 'Verbal Agreement';
        oppt.CurrencyIsoCode = 'BHD';
        oppt.Source_System__c = 'MIDAS';
        oppt.Type = 'Product Only';
        oppt.Country__c = beh.Id;

        Opportunity oppt2 = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'Talabat_Opportunity', Date.today());
        oppt2.Business_Type__c = 'Upgrade/Upsell';
        oppt2.Country__c = beh.Id;
        oppt2.Id_Tarif__r = t;
        oppt2.StageName = 'Verbal Agreement';
        oppt2.CurrencyIsoCode = 'BHD';
        oppt2.Source_System__c = 'MIDAS';
        oppt2.Type = 'Product Only';

        Opportunity oppt3 = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'Talabat_Opportunity', Date.today());
        oppt3.Business_Type__c = 'Upgrade/Upsell';
        oppt3.Id_Tarif__r = t;
        oppt3.StageName = 'Verbal Agreement';
        oppt3.CurrencyIsoCode = 'BHD';
        oppt3.Source_System__c = 'MIDAS';
        oppt3.Type = 'Product Only';
        oppt3.Country__c = beh.Id;

        insert new List<Opportunity>{oppt, oppt2, oppt3};

        List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com_bh, beh, 'Premium Placement API', 'Talabat_List_Product_Group');
        insert lpg;

        List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com_bh, beh, 'Premium Placement', lpg.id, 'Talabat_List_Product_Price', 1, true, 100, 1, false, 20);
        lpp.Displayed_Name__c = 'Premium Placement';
        lpp.Requires_Additional_Charge__c = true;
        insert lpp;

        List<Opportunity_Line_Item__c> lineItems = UnitTestDataFactory.createOpportunityLineItems(oppt, lpg.id, lpp.id, 2, true, 'Talabat_Opportunity_Line_Item', 1, '10', 299.0, 1, 1, 'Product');
        lineItems.addAll(UnitTestDataFactory.createOpportunityLineItems(oppt2, lpg.id, lpp.id, 2, true, 'Talabat_Opportunity_Line_Item', 1, '10', 299.0, 1, 1, 'Product'));
        lineItems.addAll(UnitTestDataFactory.createOpportunityLineItems(oppt3, lpg.id, lpp.id, 2, true, 'Talabat_Opportunity_Line_Item', 1, '10', 299.0, 1, 1, 'Product'));
        integer n = 0;
        for (Opportunity_Line_Item__c lineItem : lineItems) {
            n++;
            lineItem.Booking_Api_Id__c = '1234'+n;
            lineItem.Midas_Exception__c = true;
        }
        insert lineItems;

        List<Opportunity_Quote__c> quotes_1 = UnitTestDataFactory.createOpportunityQuotes(oppt, 1, 'Talabat_Opportunity_Quote', 'Accepted', 'TEST', 100, 100, 'Test', 'Test', 10);
        insert quotes_1;

        List<Opportunity_Quote_Line_Item__c> oqp=UnitTestDataFactory.createOpportunityQuoteLineItems(quotes_1[0],lpp.id,lpg.Name,2,true,'Talabat_Opportunity_Quote_Line_Item',1,'1',200.0,1,300.0,'Product');
        insert oqp;

        oppt.StageName = 'Closed Won';
        oppt2.StageName = 'Closed Lost';
        oppt3.StageName = 'Closed Won';
        update new List<Opportunity>{oppt, oppt2, oppt3};

        insert new Additional_Charges__c(
                Id_Opportunity__c = oppt.Id,
                Id_Account__c = oppt.AccountId,
                RecordTypeId = mapRecordtypes.get('Talabat_Additional_Charges').Id,
                Status__c = 'Terminated',
                Booking_Api_Id__c = lineItems[0].Booking_Api_Id__c,
                Termination_Date__c = Date.today()
        );


    }


    public class MidasCalloutMock implements HttpCalloutMock {

        private final Boolean fail;

        public MidasCalloutMock(Boolean fail) {
            this.fail = fail;
        }

        public HttpResponse respond(HttpRequest request) {
            HttpResponse response = new HttpResponse();
            if (request.getEndpoint().contains('callout:Midas_Heimdall?grant_type=client_credentials&scope=sales_force')) {
                String responseBody = '{"access_token" : "tokenMock"}';
                response.setBody(responseBody);
                response.setStatusCode(200);
            } else if (this.fail) {
                response.setStatusCode(500);
                response.setStatus('Internal server error');
            } else if (request.getEndpoint().contains('callout:Midas_Hannibal/sites/TB_BH/bookings/')) {
                Integer statusCode = checkRequestBody(request.getBody());
                response.setStatusCode(statusCode);
            } else {
                response.setStatusCode(404);
            }
            return response;
        }

    }

    /**
     * @description Check if the request is done for one opportunity at the time.
     * @param requestBody the request body
     * @return request status code
    */
    private static Integer checkRequestBody(String requestBody) {
        List<LibWebserviceHelper.oppLineItemBookingData> bookingData = (List<LibWebserviceHelper.oppLineItemBookingData>) JSON.deserialize(requestBody, List<LibWebserviceHelper.oppLineItemBookingData>.class);
        List<Opportunity_Line_Item__c> lineItems = OpportunityLineItem_Selector.getAll();
        Map<String, Opportunity_Line_Item__c> bookingLineItemMap = (Map<String, Opportunity_Line_Item__c>) ClsSObjectUtils.convertToSingleStringMap(lineItems, Opportunity_Line_Item__c.Booking_Api_Id__c.getDescribe().getLocalName());
        Set<Id> opportunityIds = new Set<Id>();
        for (LibWebserviceHelper.oppLineItemBookingData bookingItem: bookingData) {
            Id opportunityId = bookingLineItemMap.get(String.valueOf(bookingItem.id)).Id_Opportunity__c;
            if (opportunityIds.contains(opportunityId)) {
                continue;
            }
            opportunityIds.add(opportunityId);
        }
        return opportunityIds.size() > 1 ? 500: 204;
    }

}