force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <description>SP-168: new Object for storing all the Additional charges and asset during Contract creation.</description>
    <label>Additional Charges</label>
    <nameField>
        <displayFormat>add-{00000}</displayFormat>
        <label>Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <label>Id Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Opportunity_Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity Quote Line Item</label>
    <referenceTo>Opportunity_Quote_Line_Item__c</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>To be sent</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/recordTypes/PY_Additional_Charges.recordType-meta.xml
<RecordType>
    <fullName>PY_Additional_Charges</fullName>
    <active>true</active>
    <description>Record type for Pedidos Ya and in future to be global for all countries</description>
    <label>PY Additional Charges</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Restaurant</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Id_Opportunity_Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Id Opportunity Quote Line Item</label>
    <referenceTo>Opportunity_Quote_Line_Item__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity relating to this Asset</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/PY_Asset.recordType-meta.xml
<RecordType>
    <fullName>PY_Asset</fullName>
    <active>true</active>
    <description>Record Type For PedidosYa but to be applied globally in future</description>
    <label>PY_Asset</label>
</RecordType>

force-app/main/default/objects/Case/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/PY_Restaurant_Operations.recordType-meta.xml
<RecordType>
    <fullName>PY_Restaurant_Operations</fullName>
    <active>true</active>
    <businessProcess>PY General Process</businessProcess>
    <label>PY Restaurant Operations</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>this is the name of the product</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Asset__c.field-meta.xml
<CustomField>
    <fullName>Requires_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a product requires an asset</description>
    <label>Requires Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchAssetMigration.cls
/**
 * Created by w.novoa on 19.11.2018.
 */

global class BatchAssetMigration implements Database.Batchable<sObject>,Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC) {


        return Database.getQueryLocator([select id, Id_List_Product_Price__r.Product_Name__c,Id_Opportunity__r.OwnerId,
                                                    Id_Account__c, Id_Opportunity__r.CurrencyIsoCode,Id_Opportunity__c
                                        from Additional_Charges__c
                                        where Id_List_Product_Price__r.Requires_Asset__c = true
                                            And Id_Opportunity__c != null
                                            And RecordType.DeveloperName = 'PY_Additional_Charges'
                                        Order by Id_Opportunity__c
            ]);
    }
    //
    global void execute(Database.BatchableContext BC, List<Additional_Charges__c> scope) {

        map<String,Asset__c> mpOptbyAsset = new map<String,Asset__c>();
        map<String,String> mpAssetbyOpt = new map<String,String>();
        set<String> stOptWithOutAsset = new set<String>();

        for(Additional_Charges__c addCharge : scope){ // fetch all the opportunities
            stOptWithOutAsset.add(addCharge.Id_Opportunity__c);
        }
        for(Asset__c asset: [select id,Opportunity__c from Asset__c where Opportunity__c IN: stOptWithOutAsset]){
            stOptWithOutAsset.remove(asset.Opportunity__c);
        }

        List<Asset__c> listAssets = new List<Asset__c>();

        for(Additional_Charges__c addCharge : [select id, Id_List_Product_Price__r.Product_Name__c,Id_Opportunity__r.OwnerId,
                                                Id_Account__c, Id_Opportunity__r.CurrencyIsoCode,Id_Opportunity__c
                                                from Additional_Charges__c
                                                where Id_Opportunity__c IN :stOptWithOutAsset] ){
            if(stOptWithOutAsset.Contains(addCharge.Id_Opportunity__c)){
                Asset__c newAsset = new Asset__c();
                newAsset.name = addCharge.Id_List_Product_Price__r.Product_Name__c;
                newAsset.OwnerId = addCharge.Id_Opportunity__r.OwnerId;
                newAsset.Account__c = addCharge.Id_Account__c;
                newAsset.CurrencyIsoCode = addCharge.Id_Opportunity__r.CurrencyIsoCode;
                newAsset.RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('PY_Asset');
                //newAsset.Id_Opportunity_Quote_Line_Item__c = ;
                newAsset.Opportunity__c = addCharge.Id_Opportunity__c;
                newAsset.Status__c = 'Activated Successfully';
                listAssets.add(newAsset);
                mpOptbyAsset.put(newAsset.Opportunity__c,newAsset);
            }
        }


        if(!listAssets.isEmpty()){
            List<Database.saveResult> saveUpdateResults = Database.insert(listAssets);

            LoggingUtility.createLog('BatchAssetMigration','BATCH','Update Send Survey Flag',null);
            Boolean isError = false;
            for(Database.saveResult result : saveUpdateResults){
                if(!result.isSuccess()){
                    LoggingUtility.logError('BatchAssetMigration','BatchAssetMigration: Update failed for Asset ' + result.getId() +
                            ' Errors '  + result.getErrors() + '\n');
                    isError = true;
                }
            }

            // Do Logging in case of error.
            if(isError){
                LoggingUtility.commitLogs();
            }
        }

        List<case> lstCase = new List<case>();

        lstCase = [select id, Opportunity__c from case
                    where recordType.DeveloperName = 'PY_Restaurant_Operations'
                        AND (Type = 'Onboarding' OR Type = 'Logistics') AND Opportunity__c IN :mpOptbyAsset.keyset()];

        for(Case caso: lstCase){
            caso.Asset__c = mpOptbyAsset.get(caso.Opportunity__c).id;
        }


        if(!lstCase.isEmpty()){
            List<Database.saveResult> saveUpdateResults = Database.update(lstCase);

            LoggingUtility.createLog('BatchAssetMigration','BATCH','CreateCase',null);
            Boolean isError = false;
            for(Database.saveResult result : saveUpdateResults){
                if(!result.isSuccess()){
                    LoggingUtility.logError('BatchAssetMigration','BatchAssetMigration: Update failed for Case ' + result.getId() +
                            ' Errors '  + result.getErrors() + '\n');
                    isError = true;
                }
            }

            // Do Logging in case of error.
            if(isError){
                LoggingUtility.commitLogs();
            }
        }

    }


    global void finish(Database.BatchableContext BC) {

    }
}