force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Uses in Booking Rest Service. To store the information about external system name through which the booking was done.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIDAS</fullName>
            </value>
            <value>
                <fullName>Restaurant Portal Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Booking_Api_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Api_Id__c</fullName>
    <externalId>true</externalId>
    <label>Booking Api Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Midas_Exception__c.field-meta.xml
<CustomField>
    <fullName>Midas_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that indicates whether there was an exception when approving/canceling a booking in Midas</description>
    <inlineHelpText>Field that indicates whether there was an exception when approving/canceling a booking in Midas</inlineHelpText>
    <label>Midas Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Manager__c/Trigger_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Manager</label>
</CustomObject>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_Opp_Line_Item_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Opp_Line_Item_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Opp Line Item Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NcrRetry_Batch.cls
/**
* @author Mantas Jurkunas
* @date 15.11.2019
*
* @description Batch that controls the NCR retry process
*
*/

global with sharing class NcrRetry_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful, Schedulable {

	public static void schedule(String cronExpression) {
		System.schedule('NCR Retry', cronExpression, new NcrRetry_Batch());
	}

	global void execute(SchedulableContext SC) {
		Database.executeBatch(new NcrRetry_Batch());
	}

	global Database.QueryLocator start(Database.BatchableContext bc) {
		//Querying all Opportunities that have failed
        return Database.getQueryLocator([
				SELECT
					Id, Booking_Api_Id__c, Id_Opportunity__c, Id_Opportunity__r.Source_System__c,
					Id_Opportunity__r.Country__r.Name, Id_Opportunity__r.StageName, Id_Opportunity__r.Record_Country__c
				FROM Opportunity_Line_Item__c WHERE Midas_Exception__c = TRUE]);
    }

	global void execute(Database.BatchableContext bc, List<Opportunity_Line_Item__c> failedOpportunityLineItems) {
		List<Opportunity_Line_Item__c> lineItems = new NcrRetry_Utils().initialiseLineItemData(failedOpportunityLineItems).retryBookings().updateSuccessfulBookings();
		if (lineItems.isEmpty()) {
			LoggingUtility.commitLogs();
			return;
		}
		toggleTriggers(false);
		List<Database.SaveResult> saveResults = Database.update(lineItems, false);
		toggleTriggers(true);
		Map<Id, List<String>> errorMap = new Map<Id, List<String>>();
		for (Integer index = 0; index < lineItems.size(); index++) {
			if (saveResults[index].getId() != null) {
				continue;
			}
			List<String> errorMessages = new List<String>();
			for (Database.Error error: saveResults[index].getErrors()) {
				errorMessages.add(error.getMessage());
			}
			errorMap.put(lineItems[index].Id, errorMessages);
		}
		LoggingUtility.createLog('MIDAS_RETRY_DML', 'MIDAS_SELFBOOKING', 'NCR_RETRY_DML', null);
		LoggingUtility.logError('MIDAS_RETRY_DML', JSON.serialize(errorMap));
		LoggingUtility.captureTimeStamp('MIDAS_RETRY_DML','End');
		LoggingUtility.commitLogs();
    }

	global void finish(Database.BatchableContext BC) {


	}

	private static void toggleTriggers(Boolean isEnabled) {
		Trigger_Manager__c triggerManager = Trigger_Manager__c.getInstance();
		triggerManager.Deactivate_Opp_Line_Item_Trigger__c = isEnabled;
		upsert triggerManager;
	}



}