force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso__c.field-meta.xml
<CustomField>
    <fullName>Iso__c</fullName>
    <label>Iso</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Country_Selector.cls
/**
* @author Mantas Jurkunas
* @date 09.09.2019
*
* @description Selector class for Country__c
*/

public with sharing class Country_Selector {

    public static Country__c getByName(String countryName) {
        Country__c country;
        try {
            country = [SELECT Id, Name, Iso__c FROM Country__c WHERE Name = :countryName];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return country;
    }

}