force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country of Lead</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID to be transferred to account when lead record is converted</description>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/CD_Lead.recordType-meta.xml
<RecordType>
    <fullName>CD_Lead</fullName>
    <active>true</active>
    <businessProcess>CD Lead Process</businessProcess>
    <description>Click Delivery Lead Process</description>
    <label>CD Lead</label>
</RecordType>

force-app/main/default/classes/UnitTestBatchPopulateGrid.cls
@isTest
private class UnitTestBatchPopulateGrid {
	

	@testSetup static void setup() {

		UnitTestDataFactory.getRecordtypeValues();

		Country__c cnt = UnitTestDataFactory.createCountry('EC', 'Ecuador', 'USD');
		insert cnt;

		List<Lead> lds = UnitTestDataFactory.createLeads(2, cnt, 'test', 'test', 'USD', 'test', 'CD_Lead');
		insert lds;
	}

	@isTest static void batchPopulateGridCorrectly() {
		Test.startTest();
		Database.executeBatch(new BatchPopulateGrid('Lead'));
		Test.stopTest();

		for (Lead ld: [SELECT GRID__c FROM Lead]) {
			System.assert(String.isNotBlank(ld.GRID__c));
		}
	}
}