force-app/main/default/objects/Case/fields/Case_Reason_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_1__c</fullName>
    <label>Case Reason Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Across Journey</fullName>
            </value>
            <value>
                <fullName>Activation or deactivation of restaurant</fullName>
            </value>
            <value>
                <fullName>Billing inquiries</fullName>
            </value>
            <value>
                <fullName>Content update</fullName>
            </value>
            <value>
                <fullName>Contract and Sales inquiries</fullName>
            </value>
            <value>
                <fullName>Customer complaints or negative feedback</fullName>
            </value>
            <value>
                <fullName>Customer evaluations inquiry</fullName>
            </value>
            <value>
                <fullName>Customer inquiry before order placement</fullName>
            </value>
            <value>
                <fullName>Finance inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Live order inquiries by restaurant</fullName>
            </value>
            <value>
                <fullName>Live Order Process</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by customer</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other customer inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Other restaurant inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Partner data update</fullName>
            </value>
            <value>
                <fullName>Partner Feedback</fullName>
            </value>
            <value>
                <fullName>Post-Delivery</fullName>
            </value>
            <value>
                <fullName>Restaurant data update</fullName>
            </value>
            <value>
                <fullName>Restaurant Supply</fullName>
            </value>
            <value>
                <fullName>Sales inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Technical Inquiry</fullName>
            </value>
            <value>
                <fullName>Technical problems &amp; questions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_2__c</fullName>
    <label>Case Reason Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>9Cookies</fullName>
                <isActive>false</isActive>
                <label>9Cookies</label>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Basic profile change</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation by restaurant</fullName>
            </value>
            <value>
                <fullName>Cancellation of order by customer</fullName>
            </value>
            <value>
                <fullName>Change order details</fullName>
            </value>
            <value>
                <fullName>Changes to restaurant profile</fullName>
            </value>
            <value>
                <fullName>Change to order</fullName>
            </value>
            <value>
                <fullName>Contactless delivery</fullName>
            </value>
            <value>
                <fullName>Customer account</fullName>
            </value>
            <value>
                <fullName>Customer evaluations</fullName>
            </value>
            <value>
                <fullName>Customer reviews for partners</fullName>
            </value>
            <value>
                <fullName>Customer service complaint</fullName>
            </value>
            <value>
                <fullName>Deals update</fullName>
            </value>
            <value>
                <fullName>Delivery changes</fullName>
            </value>
            <value>
                <fullName>Delivery complaint</fullName>
            </value>
            <value>
                <fullName>Delivery inquiries</fullName>
            </value>
            <value>
                <fullName>Delivery Inquiry</fullName>
            </value>
            <value>
                <fullName>Delivery time</fullName>
            </value>
            <value>
                <fullName>Door Sticker Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Food complaint</fullName>
            </value>
            <value>
                <fullName>Food issue</fullName>
            </value>
            <value>
                <fullName>Frontend issue</fullName>
            </value>
            <value>
                <fullName>Front end website</fullName>
            </value>
            <value>
                <fullName>General customer complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_3__c</fullName>
    <label>Case Reason Level 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account deletion</fullName>
            </value>
            <value>
                <fullName>Account management feedback on existing issue required</fullName>
            </value>
            <value>
                <fullName>Account management meeting request</fullName>
            </value>
            <value>
                <fullName>Add items/ toppings</fullName>
            </value>
            <value>
                <fullName>Add menu category</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Address change</fullName>
            </value>
            <value>
                <fullName>Allergens Update</fullName>
            </value>
            <value>
                <fullName>App complaint by customer</fullName>
            </value>
            <value>
                <fullName>App does not receive orders</fullName>
            </value>
            <value>
                <fullName>App issue</fullName>
            </value>
            <value>
                <fullName>App problem ‒ 9Cookies</fullName>
            </value>
            <value>
                <fullName>App shows blank screen</fullName>
            </value>
            <value>
                <fullName>Automations - Backend Ticket</fullName>
            </value>
            <value>
                <fullName>Automations - Missed Contact</fullName>
            </value>
            <value>
                <fullName>Bank account details change</fullName>
            </value>
            <value>
                <fullName>Branded material request</fullName>
            </value>
            <value>
                <fullName>Calculation mistakes in invoice</fullName>
            </value>
            <value>
                <fullName>Cancellation reason inquiry</fullName>
            </value>
            <value>
                <fullName>Cannot apply</fullName>
            </value>
            <value>
                <fullName>Category hide or unhide</fullName>
            </value>
            <value>
                <fullName>Change/upload listing image</fullName>
            </value>
            <value>
                <fullName>Change/upload product photo</fullName>
            </value>
            <value>
                <fullName>Change account details</fullName>
            </value>
            <value>
                <fullName>Change delivery time</fullName>
            </value>
            <value>
                <fullName>Change of business registration</fullName>
            </value>
            <value>
                <fullName>Change of mind</fullName>
            </value>
            <value>
                <fullName>Change of owner</fullName>
            </value>
            <value>
                <fullName>Change or upload logo</fullName>
            </value>
            <value>
                <fullName>Changes in delivery fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CtrCaseReason.cls
public class CtrCaseReason {
    public String caseRecId{get;set;}
    public string json3to2 {get;set;}
    public string json2to1 {get;set;}
    public string json1toType {get;set;}
  
    public CtrCaseReason(ApexPages.StandardController controller) {
        Case c = (case)controller.getRecord();
        Map<String,Schema.SObjectType> objGlobalMap = Schema.getGlobalDescribe();
        Schema.SObjectType pType = objGlobalMap.get('Case');
        Map<String, Schema.SObjectField> objFieldMap = pType.getDescribe().fields.getMap();
        Schema.SObjectField caseType =objFieldMap.get('Type');
        Schema.SObjectField caseReason1 =objFieldMap.get('Case_Reason_Level_1__c');
        Schema.SObjectField caseReason2 =objFieldMap.get('Case_Reason_Level_2__c');
        Schema.SObjectField caseReason3 =objFieldMap.get('Case_Reason_Level_3__c');
      


        caseRecId=String.valueof(c.recordtypeid).substring(0,15);
        Map<String,String> Level3ToLevel2 = LibBitSet.getDependentOptionsImpl(caseReason3,caseReason2);
        Map<String,String>Level2ToLevel1  = LibBitSet.getDependentOptionsImpl(caseReason2,caseReason1);      
        Map<String,String>Level1toType = LibBitSet.getDependentOptionsImpl(caseReason1,caseType);
      
        json3to2=JSON.serialize(Level3ToLevel2);
        json2to1=JSON.serialize(Level2ToLevel1);
        json1toType=JSON.serialize(Level1ToType);
        json1toType=JSON.serialize(Level1ToType);


    }

  }