force-app/main/default/objects/Case/fields/Case_Reason_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_1__c</fullName>
    <label>Case Reason Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Across Journey</fullName>
            </value>
            <value>
                <fullName>Activation or deactivation of restaurant</fullName>
            </value>
            <value>
                <fullName>Billing inquiries</fullName>
            </value>
            <value>
                <fullName>Content update</fullName>
            </value>
            <value>
                <fullName>Contract and Sales inquiries</fullName>
            </value>
            <value>
                <fullName>Customer complaints or negative feedback</fullName>
            </value>
            <value>
                <fullName>Customer evaluations inquiry</fullName>
            </value>
            <value>
                <fullName>Customer inquiry before order placement</fullName>
            </value>
            <value>
                <fullName>Finance inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Live order inquiries by restaurant</fullName>
            </value>
            <value>
                <fullName>Live Order Process</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by customer</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other customer inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Other restaurant inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Partner data update</fullName>
            </value>
            <value>
                <fullName>Partner Feedback</fullName>
            </value>
            <value>
                <fullName>Post-Delivery</fullName>
            </value>
            <value>
                <fullName>Restaurant data update</fullName>
            </value>
            <value>
                <fullName>Restaurant Supply</fullName>
            </value>
            <value>
                <fullName>Sales inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Technical Inquiry</fullName>
            </value>
            <value>
                <fullName>Technical problems &amp; questions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_2__c</fullName>
    <label>Case Reason Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>9Cookies</fullName>
                <isActive>false</isActive>
                <label>9Cookies</label>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Basic profile change</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation by restaurant</fullName>
            </value>
            <value>
                <fullName>Cancellation of order by customer</fullName>
            </value>
            <value>
                <fullName>Change order details</fullName>
            </value>
            <value>
                <fullName>Changes to restaurant profile</fullName>
            </value>
            <value>
                <fullName>Change to order</fullName>
            </value>
            <value>
                <fullName>Contactless delivery</fullName>
            </value>
            <value>
                <fullName>Customer account</fullName>
            </value>
            <value>
                <fullName>Customer evaluations</fullName>
            </value>
            <value>
                <fullName>Customer reviews for partners</fullName>
            </value>
            <value>
                <fullName>Customer service complaint</fullName>
            </value>
            <value>
                <fullName>Deals update</fullName>
            </value>
            <value>
                <fullName>Delivery changes</fullName>
            </value>
            <value>
                <fullName>Delivery complaint</fullName>
            </value>
            <value>
                <fullName>Delivery inquiries</fullName>
            </value>
            <value>
                <fullName>Delivery Inquiry</fullName>
            </value>
            <value>
                <fullName>Delivery time</fullName>
            </value>
            <value>
                <fullName>Door Sticker Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Food complaint</fullName>
            </value>
            <value>
                <fullName>Food issue</fullName>
            </value>
            <value>
                <fullName>Frontend issue</fullName>
            </value>
            <value>
                <fullName>Front end website</fullName>
            </value>
            <value>
                <fullName>General customer complaint</fullName>
            </value>
            <value>
                <fullName>Technical issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_3__c</fullName>
    <label>Case Reason Level 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account deletion</fullName>
            </value>
            <value>
                <fullName>Account management feedback on existing issue required</fullName>
            </value>
            <value>
                <fullName>Account management meeting request</fullName>
            </value>
            <value>
                <fullName>Add items/ toppings</fullName>
            </value>
            <value>
                <fullName>Add menu category</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Address change</fullName>
            </value>
            <value>
                <fullName>Allergens Update</fullName>
            </value>
            <value>
                <fullName>App complaint by customer</fullName>
            </value>
            <value>
                <fullName>App does not receive orders</fullName>
            </value>
            <value>
                <fullName>App issue</fullName>
            </value>
            <value>
                <fullName>App problem ‒ 9Cookies</fullName>
            </value>
            <value>
                <fullName>App shows blank screen</fullName>
            </value>
            <value>
                <fullName>Automations - Backend Ticket</fullName>
            </value>
            <value>
                <fullName>Automations - Missed Contact</fullName>
            </value>
            <value>
                <fullName>Bank account details change</fullName>
            </value>
            <value>
                <fullName>Branded material request</fullName>
            </value>
            <value>
                <fullName>Calculation mistakes in invoice</fullName>
            </value>
            <value>
                <fullName>Cancellation reason inquiry</fullName>
            </value>
            <value>
                <fullName>Cannot apply</fullName>
            </value>
            <value>
                <fullName>Category hide or unhide</fullName>
            </value>
            <value>
                <fullName>Change/upload listing image</fullName>
            </value>
            <value>
                <fullName>Change/upload product photo</fullName>
            </value>
            <value>
                <fullName>Change account details</fullName>
            </value>
            <value>
                <fullName>Change delivery time</fullName>
            </value>
            <value>
                <fullName>Change of business registration</fullName>
            </value>
            <value>
                <fullName>Change of mind</fullName>
            </value>
            <value>
                <fullName>Change of owner</fullName>
            </value>
            <value>
                <fullName>Change or upload logo</fullName>
            </value>
            <value>
                <fullName>Changes in delivery fee</fullName>
            </value>
            <value>
                <fullName>Website issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Date_Time_Resolved__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Resolved__c</fullName>
    <description>SP-2331</description>
    <label>Date/Time Resolved</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Send_Survey__c.field-meta.xml
<CustomField>
    <fullName>Send_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Helper field. When checked by Batch will trigger workflow/outbound message to Qualtrics</description>
    <label>Send Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Survey_Date__c.field-meta.xml
<CustomField>
    <fullName>Survey_Date__c</fullName>
    <description>SP-2181
Field to track when Survey was sent to the customer</description>
    <label>Survey Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UnitTestBatchUpdateSendSurveyOnCase.cls
@isTest
private class UnitTestBatchUpdateSendSurveyOnCase{


    static Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Case'});
    @isTest static void testBatchUpdateSendSurveyOnCase() {
        UnitTestDataFactory.getRecordtypeValues();
        DateTime dateValue =  System.Now() - 3;
        Case newCase = new Case(RecordTypeId =mapRecordtypes.get('Talabat_Inbound_Case').id,status = 'Resolved',Date_Time_Resolved__c = dateValue,Country__c = 'Oman',
                Subject = 'test',Description = 'Test Desc', Platform__c = 'Talabat',Type='Customer',Order_Number__c = '0',Customer_Email__c = 'test@test.com',
                Case_Reason_Level_1__c ='Across Journey',Case_Reason_Level_2__c ='Technical issue',Case_Reason_Level_3__c ='Website issue');
        insert newCase;

        Database.QueryLocator queryLoc;
        Database.BatchableContext batchConx;
        List<Case> caseList = new List<Case>();
        BatchUpdateSendSurveyOnCase batchUpdate = new BatchUpdateSendSurveyOnCase('Select id,recordtype.developername, status,Date_Time_Resolved__c,Survey_Date__c, Send_Survey__c from Case where status = \'Resolved\' AND Survey_Date__c = null AND recordtype.developername = \'Talabat_Inbound_Case\'');
        queryLoc = batchUpdate.start(batchConx);

        Database.QueryLocatorIterator QIT = queryLoc.iterator();
        while (QIT.hasNext()) {
            Case caseRec = (Case) QIT.next();
            System.debug(caseRec);
            caseList.add(caseRec);
        }
        Test.startTest();
        batchUpdate.execute(batchConx, caseList);
        batchUpdate.finish(batchConx);
        Test.stopTest();

        Case caseRec = [select id,Send_Survey__c from Case where id IN :caseList];
        System.assertEquals(true,caseRec.Send_Survey__c);
    }

    @isTest static void testScheduleBatchUpdateSendSurveyOnCase() {
        UnitTestDataFactory.getRecordtypeValues();
        Id jobId;

        Test.startTest();
        ScheduledBatchUpdateSendSurveyOnCase scdJob = new ScheduledBatchUpdateSendSurveyOnCase();
        scdJob.batchSize = 200;
        DateTime currentDateTime = DateTime.Now().addHours(-3);
        String actualTime = currentDateTime.formatGMT('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        scdJob.queryString = 'Select id,recordtype.developername, status,Date_Time_Resolved__c,Survey_Date__c, Send_Survey__c from Case where status = \'Resolved\' AND Survey_Date__c = null AND recordtype.developername = \'Talabat_Inbound_Case\' and Date_Time_Resolved__c < ';
        jobId = System.schedule('test job', '0 0 0 * * ?', scdJob);
        Test.stopTest();

        CronTrigger[] jobs = [Select Id from CronTrigger Where Id = : jobId];

        System.assert(!jobs.isEmpty());

    }
}