force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Reason__c</fullName>
    <label>Closed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Take Online</fullName>
            </value>
            <value>
                <fullName>Take Online is not possible</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Not Successful</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Create Retention Task</fullName>
            </value>
            <value>
                <fullName>Create Take Offline Task for Non Contracted</fullName>
            </value>
            <value>
                <fullName>Take Offline</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Not Successful - Data Missing</fullName>
            </value>
            <value>
                <fullName>Not Successful - Commission is not correct</fullName>
            </value>
            <value>
                <fullName>Back Online</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Duplicated</fullName>
            </value>
            <value>
                <fullName>Auto Closed</fullName>
            </value>
            <value>
                <fullName>Escalated to AM</fullName>
            </value>
            <value>
                <fullName>Successful Call</fullName>
            </value>
            <value>
                <fullName>Call Scheduled</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (Agent)</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (AM)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (1 st Incident)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (Permanent)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Billable_Account__c.field-meta.xml
<CustomField>
    <fullName>Billable_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billable Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Child Billable Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_List_Price_Product__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Price_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Billable_Account__c.field-meta.xml
<CustomField>
    <fullName>Billable_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billable Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity_Quote__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote__c</fullName>
    <label>Opportunity Quote</label>
    <referenceTo>Opportunity_Quote__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Created&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Opportunity_Selector.cls
/**
* @author Mantas Jurkunas
* @date 18.03.2019
*
* @description Selector class for retrieving Opportunity records
*/

public with sharing class Opportunity_Selector {

    //Constants
    public static final String OPPORTUNITY_EMAILPATH_DOCUSIGN = 'DocuSign';
    public static final String OPPORTUNITY_EMAILPATH_CLASSIC = 'Classic';

    @TestVisible
    private static List<Opportunity> getAll() {
        List<Opportunity> opportunities = new List<Opportunity>();
        opportunities = [SELECT Id, StageName, Opportunity.Business_Type__c, Type,AccountId FROM Opportunity];
        return opportunities;
    }

    @TestVisible
    private static List<Opportunity> getAllWithChildren() {
        List<Opportunity> opportunities = new List<Opportunity>();
        try {
            opportunities = [
                    SELECT Id, StageName, Type, Business_Type__c,
                        (SELECT Id FROM Opportunity_Line_Items__r LineItems),
                        (SELECT Id, Status__c FROM Opportunity_Quotes__r Quotes),
                        (SELECT Id FROM Opportunity_Quote_Line_Items__r QuoteLineItems),
                        (SELECT Id, RecordType.DeveloperName, Type, Status, Closed_Reason__c FROM Cases__r Cases)
                    FROM Opportunity];
          } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
          }
    return opportunities;
    }

    /*******************************************************************************************************
    * @description Get quote records based on quote Id.
    * @param keys set of Opprtunity Quote Ids
    * @return Opportunity Quotes Map
    */
    public static Map<Id, Opportunity_Quote__c> getQuotesMap(final Set<Id> oppQuoteIds) {
        return new Map<Id, Opportunity_Quote__c> ([
            SELECT Id, Id_Account__r.Record_Country__c, Id_Account__r.Platform__c, Id_Account__r.Company_Code__c, 
            Id_Account__r.BillingCountry, Id_Account__r.BillingCity
            FROM Opportunity_Quote__c
            WHERE Id IN :oppQuoteIds
        ]);
    }
    
    public static Map<Id,Opportunity> getFromOppIdSet(Set<Id> oppIdsSet) {
        Map<Id,Opportunity> oppMap;
        try {
            oppMap = new Map<Id,Opportunity>([SELECT Business_Type__c,Type, Account.RecordTypeId, RecordTypeId, RecordType.developername, Record_Country__c,Preferred_Language__c
                                                FROM Opportunity 
                                                WHERE Id IN :oppIdsSet ]);
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return oppMap;
    }
    
    public static List<Opportunity> getSelected(List<ID> listOppID) {
        List<Opportunity> opportunities = new List<Opportunity>();
        try {
            opportunities = [SELECT Id, Business_Type__c, Type, RecordTypeId, Record_Country__c, Start_Date_uk__c, Probability, StageName,
                                    Email_Path__c, DocuSign_Envelopes_Consumed__c, Owner.Email
                                FROM Opportunity
                                WHERE Id IN: listOppID];
        } catch (QueryException e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return opportunities;
    }
  
      public static List<Opportunity> getOpportunityClosed(set<Id> oppId) {
        List<Opportunity> opportunities = new List<Opportunity>();
        try {
            opportunities = [Select Id from opportunity where Id IN : oppId and isClosed = true];
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }

        return opportunities;
    }


    public static List<Opportunity> getOpportunityByIdStage(set<Id> oppId,String strStage) {
        List<Opportunity> opportunities = new List<Opportunity>();
        try {
            opportunities = [Select Id from opportunity where Id IN : oppId and StageName != :strStage];
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return opportunities;
    }


    public static Opportunity getOpportunityById(Id oppId) {
        return [SELECT Id, StageName,Name, Selfbooking_Owner__c, Lost_Reason__c FROM Opportunity WHERE Id = :oppId LIMIT 1];
    }
    
      /*******************************************************************************************************
  * @description Get opportunites for selected Account to update the country
  * @param Set of Account Ids
  * @return List<Opportunity> to update country
  * @ticket : SSC-1533
  */

    public static List<Opportunity> getOpportunityAgainstAccounts(Set<Id> setOfAccountIds){

        List<Opportunity> lstOppty = new List<Opportunity>();
        try{
            lstOppty = [SELECT Id ,AccountId, Opportunity_Country__c
                        FROM Opportunity WHERE AccountId IN : setOfAccountIds
                        LIMIT : Limits.getLimitDMLRows()];
        }
        catch (QueryException e) {
            System.debug('Error: '+e.getMessage());
        }
        return lstOppty;
    }
    /*******************************************************************************************************
    * @Description: Get product name based on quote Id.
    * @Inputparam: Id of the opportunity
    * @return: String of Product Name
    */
    public static String fetchOQLIProductName(Id opptyId){
        String productName;
        List<Opportunity_Quote_line_item__c> listOfOpptylineItem =[SELECT Id,Id_Opportunity__c,Id_List_Product_Price__r.Product_Name__c
        FROM Opportunity_Quote_Line_Item__c
        WHERE Id_Opportunity__c =: opptyId limit 1];
        if(!listOfOpptylineItem.isEmpty() && String.isNotBlank(listOfOpptylineItem[0].Id_List_Product_Price__r.Product_Name__c)){
            productName = listOfOpptylineItem[0].Id_List_Product_Price__r.Product_Name__c;
        }
        return productName;
    }

}