force-app/main/default/objects/Add_on_Service__c/Add_on_Service__c.object-meta.xml
<CustomObject>
    <description>Add-on Services for Restaurants like : WhiteLable website, Phone Ordering, Pick-up service etc.</description>
    <label>Add-on Service</label>
    <nameField>
        <displayFormat>AOS-{000000}</displayFormat>
        <label>Add-on Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Add-on Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Add_on_Service__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Add-on Services</relationshipLabel>
    <relationshipName>Add_on_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Add_on_Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Final Check</fullName>
            </value>
            <value>
                <fullName>Please Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Add_On_Service_Selector.cls
/**
 * Created by danish.farooq on 6/25/20.
 */

public  inherited Sharing class Add_On_Service_Selector {
    /**
   * @description return AddOns for that opportunity
   * @param opptySet contains set Of Opportunity
   * @param addOnServiceLst contains current add Ons which are active
   * @param setOfStatus statuses of Addons
   * @return List of AddOns
   * @Jira SSC-3462
   */
    public static List<Add_on_Service__c> getAddOnServicesByOppty(Set<Id> opptySet,
                                                                  Set<string> setOfStatus){

        List<Add_on_Service__c> lstAddOnServices = new List<Add_on_Service__c>();

        lstAddOnServices = [SELECT ID, status__c, opportunity__c from
                            Add_On_Service__c where opportunity__c in :opptySet
                            AND Status__c IN : setOfStatus];
        return lstAddOnServices;
    }
}