force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <description>this holds the default Quantity</description>
    <label>Default Quantity</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_List_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Group__c</fullName>
    <description>this information gives you to which product group this product belongs</description>
    <label>List Product Group</label>
    <referenceTo>List_Product_Group__c</referenceTo>
    <relationshipName>Id_List_Price_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>holds the list price of the product</description>
    <label>List Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Maximum_Discount__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Discount__c</fullName>
    <label>Maximum Discount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>this is the name of the product</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type to determine the Asset Type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Online Marketing</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Premium placement</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Dish Level Photoshoot</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Car Leasing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Premium placement - 1 Month</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ListProductPriceSelector.cls
/* @author Chaitali Kumari
* @date 13.05.2019*
* @description Selector class to retrieve List Product Price records
*/

public with sharing class ListProductPriceSelector {

    /*******************************************************************************************************
   * @description Queries to get List Product Price record based on Name
   * @param String Record Type developerName (String), Record Country (String)
   * @return List of List Product Price
   */

    public static List<List_Product_Price__c> findListProdPriceByrecTypeandCountry(String recordType, String recCountry) {
        List<List_Product_Price__c> listProductPrice;
        try {
            listProductPrice = [select id,Displayed_Name__c,company__r.name,
                                Default_Quantity__c,Id_List_Product_Group__r.Name,
                                Product_Type__c,Product_Name__c
                               from List_Product_Price__c
                               where RecordType.DeveloperName = : recordType
                               and id_country__r.name=:recCountry];
        } catch(Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return listProductPrice;
    }
    
     /*******************************************************************************************************
    * @description Query List_Product_Price__c via record type name and product name values
    * @param recordTypeSet - record type api-name record set, productNames - set of products
    * @return List<List_Product_Price__c>
    */
    public static  List<List_Product_Price__c> getListProductPriceRecordsFilteredByRecordTtype (Set<String> recordTypeSet, Set<String> productNames){
        
        List<List_Product_Price__c> listProductPrices = new List<List_Product_Price__c>();
        try{

            listProductPrices = [Select id, Displayed_Name__c,Id_List_Product_Group__r.name, RecordType.DeveloperName, Id_List_Product_Group__c from List_Product_Price__c where RecordType.DeveloperName IN :recordTypeSet AND Displayed_Name__c IN :productNames];
        } catch (Exception e){

            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return listProductPrices;
    }
    /**
    * @Description: This method returns Product Price list from Id
      @param            : List of Product Id
      @Return             : Map of Product Price Id
      @TriggerContext     :  After Update
      @Ticket #            : SSC-1979
     */
    public static Map<Id, List_Product_Price__c> getActiveProductsById(List<Id> lstOfProduct) {
        Map<Id, List_Product_Price__c> productsMap ;
        try {
            productsMap = new Map<Id, List_Product_Price__c>([SELECT id,Displayed_Name__c,company__r.name,
                                                            Default_Quantity__c,Id_List_Product_Group__r.Name,
                                                            Product_Type__c,Product_Name__c,CurrencyIsoCode,List_Price__c,
                                                            Maximum_Discount__c
                                                            FROM List_Product_Price__c
                                                            WHERE Id = : lstOfProduct
                                                            LIMIT : limits.getLimitDmlRows()]);
        } catch(Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }

        return productsMap;
    }



}