force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <label>Commission in %</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>this hold the end date because the other end date is not writable</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Recurring_Fee__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Fee__c</fullName>
    <label>Recurring Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>Service type of contract. Says whether a contract is a main service or an additional service (surcharge)</description>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractSelector.cls
/**
* @author g.singh
* @date xx.03.2019
*
* @description Selector class for retrieving Contract records
*/
public inherited sharing class ContractSelector {

    public static final String ONLINE_STATUS_ACTIVE = 'Active';
    public static final String ONLINE_STATUS_TERMINATED = 'Terminated';
    public static final String ONLINE_STATUS_PENDINGACTIVATION = 'Pending Activation';

    /*******************************************************************************************************
    * @description Returns Active contracts for a single Account
    * @param accountId - Id - of the related Account
    * @return List<Contract>
    */
    public static List<Contract> getActiveContractsForAccount(Id accountId) {
        return ContractSelector.getActiveContractsForAccounts(new Set<Id>{accountId});
    }

    /*******************************************************************************************************
    * @description Returns Active contracts for a set of Accounts
    * @param accountIds - Set<Id> - Ids of related Accounts
    * @return List<Contract>
    */
    public static List<Contract> getActiveContractsForAccounts(Set<Id> accountIds) {
        return [SELECT Id, AccountId, Company__c, Company_Name__c, ContractNumber, StartDate, End_Date__c, Status, Service_Type__c,
                Commission__c, Recurring_Fee__c, RecordType.DeveloperName
        FROM Contract
        WHERE AccountId =: accountIds AND Status != 'Terminated' ORDER BY StartDate DESC];

    }

    /**
     * @description selector method for test purposes
     *
     * @return List<Contract>
     */
    @TestVisible
    private static List<Contract> getAll() {
        List<Contract> listObj = new List<Contract>();
        try {
            listObj = [SELECT Based_On__c, Commission_Type__c, Scaled__c, StartDate, Status, End_Date__c FROM Contract];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return listObj;
    }

    public static List<Contract> getContractsFromSwitchAccountsByIds(Set<Id> accountIds, Set<String> businessTypes) {
        List<Contract> contracts = new List<Contract>();
        try {
            contracts = [
                SELECT Id, AccountId, Id_Opportunity__c, Commission_Type__c, StartDate, End_Date__c, Id_Opportunity__r.Business_Type__c, Service_Type__c, RecordTypeId
                FROM Contract
                WHERE AccountId IN (SELECT AccountId FROM Opportunity WHERE Business_Type__c IN :businessTypes AND AccountId IN :accountIds)
                AND Status != 'Terminated'
            ];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return contracts;
    }

    /**
    * @description Queries all the contracts associated with the account implemented for SSC-1982 : Tlife Commission
    * @param accountIds [Set Of Account Id]
    * @param serviceTypeValues [All Service Types]
    * @param contractStatus [Contract Status]
    * @return List<Contract>
    */
    public static List<Contract> getContractsByServiceType(final Set<String> accountIds, final List<String>  serviceTypeValues,
            String contractStatus) {

        List<Contract> contractList = new List<Contract>();
        contractList = [
                SELECT Id,AccountId,Service_Type__c,Status FROM Contract WHERE AccountId IN : accountIds and
                Service_Type__c IN : serviceTypeValues and Status =: contractStatus
        ];
        return contractList;
    }
}