force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tarifs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Product_Only__c.field-meta.xml
<CustomField>
    <fullName>Product_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/Tarif_Member__c.object-meta.xml
<CustomObject>
    <description>this shows the services and products that belong to a specific tarif</description>
    <label>Tarif Member</label>
    <nameField>
        <displayFormat>TAI-{000000}</displayFormat>
        <label>Tarif Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tarif Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif_Member__c/fields/Id_Tarif_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif_Item__c</fullName>
    <description>this holds the id of tarif member</description>
    <label>Id Tarif Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/fields/Tarif_Name__c.field-meta.xml
<CustomField>
    <fullName>Tarif_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the tarif name</description>
    <label>Tarif Name</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Tarif Members</relationshipLabel>
    <relationshipName>Tarif_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>this helps in identifying product or service record id.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TarifSelector.cls
/**
* @author Chaitali Kumari
* @date 13.05.2019
*
* @description Selector class for retrieving Tarif records
*/
public with sharing class TarifSelector {

    /*******************************************************************************************************
   * @description Queries to get a tarif record based on certain filters. Should be inactive tarif as used for API only
   * @param String Name, Record Type developerName (String), Company Code (string), Record Country (String)
   * @return Tarif__c
   */

    public static Tarif__c findTarifRecordByTarifName(String pTarifName, String companyCode, String recCountry) {
        Tarif__c tarif;
        String tarifName = '%'+pTarifName+'%';
        try {
            tarif = [select id from Tarif__c where Name like :tarifName and recordtype.developername=:companyCode+'_Tarif'
                     and id_country__r.name=:recCountry LIMIT 1];
        } catch(Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return tarif;
    }

    /*******************************************************************************************************
* @description Queries to get a tarif record by set of country
* @param String   Countries (set<String>)
* @return map<id,Tarif__c>
*/

    public static  Map<Id, Tarif__c> findTarifRecordByCountries(set<Id> Countries) {
        Map<Id, Tarif__c> tariffsMap ;
        try {
            tariffsMap = new Map<Id, Tarif__c>([
                    SELECT Id, Is_Active__c, CreatedDate, LastModifiedDate, LastModifiedBy.Name, Name, Id_Country__c,
                            Id_Country__r.name, Company__c, Is_Locked__c,Product_Only__c,Categories__c,
                    (SELECT Id, Id_Tarif_Item__c, Tarif_Name__c, Type__c FROM Tarif_Members__r )
                    FROM Tarif__c
                    WHERE Id_Country__c IN : Countries
                    And Archived__c = false
                    ORDER BY LastModifiedDate DESC
                    LIMIT 700
            ]);
        } catch(Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return tariffsMap;
    }
}