force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Add_On__c/List_Add_On__c.object-meta.xml
<CustomObject>
    <label>List Add On</label>
    <nameField>
        <label>List Add On Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Add On</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Add_On__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Add On</relationshipLabel>
    <relationshipName>List_Add_On</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Contract_Addition__c.field-meta.xml
<CustomField>
    <fullName>Contract_Addition__c</fullName>
    <label>Contract Addition</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Add On</relationshipLabel>
    <relationshipName>List_Add_On</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Requires_Approval__c.field-meta.xml
<CustomField>
    <fullName>Requires_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusivity</fullName>
            </value>
            <value>
                <fullName>Deal / Promotion</fullName>
            </value>
            <value>
                <fullName>Extra Terms and Conditions</fullName>
            </value>
            <value>
                <fullName>Deals</fullName>
                <isActive>false</isActive>
                <label>Deals</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ListAddOn_Selector.cls
/**
 * Created by danish.farooq on 4/5/20.
 */
/**
 * Created by danish.farooq on 4/5/20.
* @Description: selector class use for return list add on data

 */
public with sharing class ListAddOn_Selector {
    /**
  * @Description: This method returns list of AddOn from Id
    @param            : List of Add on id
    @Return             : Map of AddOn
    @Ticket #            : SSC-1979
   */
    public static Map<Id, List_Add_On__c> getListAddOnById(List<Id> setOfAddOnIds){

        Map<Id, List_Add_On__c> addOnMap ;

        try{
            addOnMap = new Map<Id,List_Add_On__c>([SELECT Company__c,
                            Contract_Addition__c,Id,Id_Country__c,
                            Is_Active__c,Name,CurrencyIsoCode,
                            RecordTypeId,Requires_Approval__c,type__c
                            FROM List_Add_On__c
                            WHERE Id IN : setOfAddOnIds
                            LIMIT : limits.getLimitDmlRows()]);
        }
        catch(Exception ex){
            system.debug('Error : '  + ex.getMessage());
            LoggingUtility.commitLogs();
        }
        return addOnMap;
    }
}