force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/FP_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Product_Group</fullName>
    <active>true</active>
    <label>FP List_Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Default_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_Quantity__c</fullName>
    <description>this holds the default Quantity</description>
    <label>Default Quantity</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_List_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Group__c</fullName>
    <description>this information gives you to which product group this product belongs</description>
    <label>List Product Group</label>
    <referenceTo>List_Product_Group__c</referenceTo>
    <relationshipName>Id_List_Price_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this attribute activates the product, so that this product is able to select in the opportunity</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <description>holds the list price of the product</description>
    <label>List Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>this is the name of the product</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type to determine the Asset Type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Online Marketing</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Premium placement</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Dish Level Photoshoot</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Car Leasing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Premium placement - 1 Month</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FP_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Global Sales Process</businessProcess>
    <label>FP Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Installments__c.field-meta.xml
<CustomField>
    <fullName>Installments__c</fullName>
    <label>Installments</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/FP_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity_Quote</fullName>
    <active>true</active>
    <label>FP Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Opportunity_Quote__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Quote</label>
    <referenceTo>Opportunity_Quote__c</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/Shipment_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment order items</description>
    <label>Shipment Order Line Item</label>
    <nameField>
        <label>Shipment Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Order__c</fullName>
    <label>Shipment Order</label>
    <referenceTo>Shipment_Order__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MigrationScriptShipmentOrders_BatchTest.cls
/***
 * @description test class for MigrationScriptShipmentOrders_Batch class
 * @date 07.05.2020
 * @author Konrad Czykin
 */
@isTest
public class MigrationScriptShipmentOrders_BatchTest {

    @TestSetup
    public static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c country = UnitTestDataFactory.createCountry('TH', 'Thailand', 'THB');
        insert country;
        
        Company__c company = UnitTestDataFactory.createCompany('FP', 'FP', country);
        insert company;

        Account acc = UnitTestDataFactory.createAccount('Thailand Test Account', country, 'FP_Account');
        acc.phone = '+66123456789';
        acc.CurrencyIsoCode = 'THB';
        insert acc;

        Opportunity opp = UnitTestDataFactory.createOpportunity('Test Opportunity', acc, 'FP_Opportunity', Date.today());
        opp.StageName = 'Onboarding';
        opp.Business_Type__c = 'New Business';
        insert opp;

        List_Product_Group__c addChargesGroup = UnitTestDataFactory.createProductGroup(company, country, 'Add. Charges', 'FP_List_Product_Group');
        insert addChargesGroup;

        List_Product_Price__c simCard = new List_Product_Price__c(
            Is_Active__c = true,
            Id_List_Product_Group__c = addChargesGroup.Id,
            Product_Name__c = 'SIM Card',
            Product_Type__c = 'Hardware',
            Displayed_Name__c = 'SIM Card',
            List_Price__c = 0,
            Installments__c = 1,
            Default_Quantity__c = 1,
            Id_Country__c = country.Id,
            Company__c = company.Id);

        List_Product_Price__c tablet = new List_Product_Price__c(
            Is_Active__c = true,
            Id_List_Product_Group__c = addChargesGroup.Id,
            Product_Name__c = 'Tablet',
            Product_Type__c = 'Hardware',
            Displayed_Name__c = 'Tablet',
            List_Price__c = 0,
            Installments__c = 1,
            Default_Quantity__c = 1,
            Id_Country__c = country.Id,
            Company__c = company.Id);
        
        insert new List<List_Product_Price__c>{simCard, tablet};

        List<Opportunity_Quote__c> oppQ = UnitTestDataFactory.createOpportunityQuotes(opp, 1, 'FP_Opportunity_Quote', 'Accepted', 'Description', 0, 0, 'url', 'key', 0);
        insert oppQ;
    }

        @isTest
        public static void testCreateAllrecords(){
         
            Test.startTest();
                Database.executeBatch(new MigrationScriptShipmentOrders_Batch('FP','Thailand'));
            Test.stopTest();

            Opportunity opp = [SELECT Id FROM Opportunity limit 1];
            Account acc = [SELECT Id FROM Account limit 1];
            Opportunity_Quote__c oppQuote = [SELECT Id FROM Opportunity_Quote__c limit 1];
            List_Product_Price__c lppTablet = [SELECT Id FROM List_Product_Price__c WHERE Product_Name__c = 'Tablet'];
            List_Product_Price__c lppSIMCard = [SELECT Id FROM List_Product_Price__c WHERE Product_Name__c = 'SIM Card'];

            //check Shipment Order record
            List<Shipment_Order__c> lstSO = [SELECT Id, Status__c, Opportunity__c, Account__c FROM Shipment_Order__c];
            System.assertEquals(1, lstSO.size());
            System.assertEquals('Ready to be shipped', lstSO[0].Status__c);
            System.assertEquals(acc.Id, lstSO[0].Account__c);
            System.assertEquals(opp.Id, lstSO[0].Opportunity__c);

            //check tablet Shipment Order Line Item
            List<Shipment_Order_Line_Item__c> lstSOLI = [SELECT Id, List_Product_Price__c, Shipment_Order__c FROM Shipment_Order_Line_Item__c WHERE Name = 'Tablet'];
            System.assertEquals(1, lstSOLI.size());
            System.assertEquals(lppTablet.Id, lstSOLI[0].List_Product_Price__c);
            System.assertEquals(lstSO[0].Id, lstSOLI[0].Shipment_Order__c);

            //check SIM Card Shipment Order Line Item
            List<Shipment_Order_Line_Item__c> lstSOLIsim = [SELECT Id, List_Product_Price__c, Shipment_Order__c FROM Shipment_Order_Line_Item__c WHERE Name = 'SIM Card'];
            System.assertEquals(1, lstSOLIsim.size());
            System.assertEquals(lppSIMCard.Id, lstSOLIsim[0].List_Product_Price__c);
            System.assertEquals(lstSO[0].Id, lstSOLIsim[0].Shipment_Order__c);
            
            //check Tablet Quote Line Item
            List<Opportunity_Quote_Line_Item__c> lstOQLItablet = [SELECT Id, Id_Opportunity_Quote__c, Id_Opportunity__c FROM Opportunity_Quote_Line_Item__c WHERE Name = 'Tablet'];
            System.assertEquals(1, lstOQLItablet.size());
            System.assertEquals(oppQuote.Id, lstOQLItablet[0].Id_Opportunity_Quote__c);
            System.assertEquals(opp.Id, lstOQLItablet[0].Id_Opportunity__c);

            //check SIM Card Quote Line Item
            List<Opportunity_Quote_Line_Item__c> lstOQLIsim = [SELECT Id, Id_Opportunity_Quote__c, Id_Opportunity__c FROM Opportunity_Quote_Line_Item__c WHERE Name = 'SIM Card'];
            System.assertEquals(1, lstOQLIsim.size());
            System.assertEquals(oppQuote.Id, lstOQLIsim[0].Id_Opportunity_Quote__c);
            System.assertEquals(opp.Id, lstOQLIsim[0].Id_Opportunity__c);

            //check tablet Opportunity Line Item
            List<Opportunity_Line_Item__c> lstOLI = [SELECT Id, Delivery__c, Id_Opportunity__c, Id_List_Price_Product__c FROM Opportunity_Line_Item__c WHERE Name = 'Tablet'];
            System.assertEquals(1, lstOLI.size());
            System.assertEquals('Shipment', lstOLI[0].Delivery__c);
            System.assertEquals(lppTablet.Id, lstOLI[0].Id_List_Price_Product__c);

            //check SIM Card Opportunity Line Item
            List<Opportunity_Line_Item__c> lstOLIsim = [SELECT Id, Delivery__c, Id_Opportunity__c, Id_List_Price_Product__c FROM Opportunity_Line_Item__c WHERE Name = 'SIM Card'];
            System.assertEquals(1, lstOLIsim.size());
            System.assertEquals('Shipment', lstOLIsim[0].Delivery__c);
            System.assertEquals(lppSIMCard.Id, lstOLIsim[0].Id_List_Price_Product__c);
        }
}