force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/Yogiyo_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_List_Product_Group</fullName>
    <active>true</active>
    <description>this is the product group for korea</description>
    <label>Yogiyo List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Requires_Add_On__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Branding__c.field-meta.xml
<CustomField>
    <fullName>Requires_Branding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Branding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/Yogiyo_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_List_Product_Price</fullName>
    <active>true</active>
    <label>Yogiyo List Product Price</label>
</RecordType>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this service is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/recordTypes/Yogiyo_List_Service_Price.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_List_Service_Price</fullName>
    <active>true</active>
    <label>Yogiyo List Service Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_DataLoaded__c.field-meta.xml
<CustomField>
    <fullName>Is_DataLoaded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this helps us not to trigger some triggers when it is true</description>
    <label>Is DataLoaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Migration_Notes_AU__c.field-meta.xml
<CustomField>
    <fullName>Migration_Notes_AU__c</fullName>
    <description>Notes for AU Opportunity Migration</description>
    <label>Migration Notes AU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Setup_Fee_AU__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_AU__c</fullName>
    <description>Setup Fee for AU, for migration only</description>
    <label>Setup Fee AU</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date_uk__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_uk__c</fullName>
    <description>For Migration Only</description>
    <inlineHelpText>Use field it the Start Date is NOT ASAP. Automatically populated via tariffs.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TarrifName_AU__c.field-meta.xml
<CustomField>
    <fullName>TarrifName_AU__c</fullName>
    <description>Tarrif Name for AU, for migration only</description>
    <label>TarrifName_AU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Yogiyo_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Sales Proccess</businessProcess>
    <description>KR Opportunity Recordtype</description>
    <label>Yogiyo Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Booking_Api_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Api_Id__c</fullName>
    <externalId>true</externalId>
    <label>Booking Api Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/City_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>City_ZipCode__c</fullName>
    <label>Period / Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Has_Related_Tarif__c.field-meta.xml
<CustomField>
    <fullName>Has_Related_Tarif__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Related Tarif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_List_Price_Product__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Price_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Installments__c.field-meta.xml
<CustomField>
    <fullName>Installments__c</fullName>
    <label>Installments</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Listed_Price__c.field-meta.xml
<CustomField>
    <fullName>Listed_Price__c</fullName>
    <label>Listed Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>for midas PP api</description>
    <label>Position</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/Yogiyo_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>Yogiyo Opportunity Line Item</label>
</RecordType>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/Yogiyo_Tarif.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Tarif</fullName>
    <active>true</active>
    <label>Yogiyo Tarif</label>
</RecordType>

force-app/main/default/classes/UnitTestBatchPPMigration.cls
@isTest
private class UnitTestBatchPPMigration{

    static Map<String,RecordType> mapRecordTypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String>{'Opportunity','Opportunity_Line_Item__c'});
    static User testRunningUser = [SELECT Id,Username,Email FROM User WHERE Profile.PermissionsModifyAllData = true AND IsActive = true LIMIT 1];
    static{
    UnitTestDataFactory.getRecordtypeValues();
    }
    static void testData(){
        Country__c c = UnitTestDataFactory.createCountry('KR','Korea', 'KRW');
        insert c;
        Company__c com = UnitTestDataFactory.createCompany('Yogiyo', 'Yogiyo', c);
        insert com;

        Business_Config__c b1 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','opportunity_tarif_recordType','Yogiyo_Opportunity_Tarif_Item', c.id, 'Yogiyo_Opportunity', true, true);
        Business_Config__c b2 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','opportunity_product_recordType','Yogiyo_Opportunity_Line_Item', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b3 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','opportunity_service_recordType','Yogiyo_Opportunity_Line_Item', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b4 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','opportunity_quote_service_recordType','Yogiyo_Opportunity_Quote_Line_Item', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b5 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','opportunity_quote_product_recordType','Yogiyo_Opportunity_Quote_Line_Item', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b6 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','opportunity_quote_recordType','Yogiyo_Opportunity_Quote', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b7 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','Contract_recordType','Yogiyo_Contract', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b8 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','Asset_recordType','Yogiyo_Asset', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b9 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','AdditionalCharges_recordType','Yogiyo_Additional_Charges', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b10 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','enableAnnualEndDate','true', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b11 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','enableContractEndDate','false', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b12 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','AddOnRecordType','Yogiyo_Add_On', c.id, 'Yogiyo_Opportunity', true, false);
        Business_Config__c b13 = UnitTestDataFactory.createBusinessConfig('BatchSchedulerForOpportunity', 'Process','BrandingContentRecordType','Yogiyo_Branding_Content', c.id, 'Yogiyo_Opportunity', true, false);

        Account acc1 = UnitTestDataFactory.createAccount('BatchTestClassAccount1',c,'Yogiyo_Account');
        Account acc2 = UnitTestDataFactory.createAccount('BatchTestClassAccount2',c,'Yogiyo_Account');
        Account acc3 = UnitTestDataFactory.createAccount('BatchTestClassAccount2',c,'Yogiyo_Account');
        BatchOpportunityTarif_MigrationText__c cs = new BatchOpportunityTarif_MigrationText__c(name='FilterText',Value__c='Migration');
        
        insert new List<SObject>{b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,acc1,acc2,acc3,cs,b12,b13};


        Opportunity opp1 = new Opportunity(Setup_Fee_AU__c=155,Start_Date_uk__c=Date.newInstance(2014, 12, 21),name='BatchTestOpp1', recordtypeid=mapRecordTypes.get('Yogiyo_Opportunity').id,AccountId=acc1.id,CloseDate=Date.newInstance(2014, 12, 21), StageName='Prospecting', TarrifName_AU__c='testTarif1',Is_DataLoaded__c=true,Migration_Notes_AU__c='Migration');
        Opportunity opp2 = new Opportunity(Setup_Fee_AU__c=200,Start_Date_uk__c=Date.newInstance(2014, 12, 22),name='BatchTestOpp2', recordtypeid=mapRecordTypes.get('Yogiyo_Opportunity').id,AccountId=acc1.id,CloseDate=Date.today(), StageName='Prospecting', TarrifName_AU__c='testTarif2',Is_DataLoaded__c=true,Migration_Notes_AU__c='Migration');
        Opportunity opp3 = new Opportunity(Setup_Fee_AU__c=115,Start_Date_uk__c=Date.newInstance(2014, 12, 20),name='BatchTestOpp3', recordtypeid=mapRecordTypes.get('Yogiyo_Opportunity').id,AccountId=acc2.id,CloseDate=Date.today(), StageName='Prospecting', TarrifName_AU__c='testTarif2',Is_DataLoaded__c=true,Migration_Notes_AU__c='Migration');
        Opportunity opp4 = new Opportunity(Setup_Fee_AU__c=110,Start_Date_uk__c=Date.newInstance(2014, 12, 19),name='BatchTestOpp4', recordtypeid=mapRecordTypes.get('Yogiyo_Opportunity').id,AccountId=acc2.id,CloseDate=Date.today(), StageName='Prospecting', TarrifName_AU__c='testTarif1',Is_DataLoaded__c=true,Migration_Notes_AU__c='Migration');
        Opportunity opp5 = new Opportunity(Setup_Fee_AU__c=120,Start_Date_uk__c=Date.newInstance(2014, 12, 18),name='BatchTestOpp5', recordtypeid=mapRecordTypes.get('Yogiyo_Opportunity').id,AccountId=acc3.id,CloseDate=Date.today(), StageName='Prospecting', TarrifName_AU__c='testTarif1',Is_DataLoaded__c=true,Migration_Notes_AU__c='Migration');
        Opportunity opp6 = new Opportunity(Setup_Fee_AU__c=150,Start_Date_uk__c=Date.newInstance(2014, 12, 05),name='BatchTestOpp6', recordtypeid=mapRecordTypes.get('Yogiyo_Opportunity').id,AccountId=acc3.id,CloseDate=Date.today(), StageName='Prospecting', TarrifName_AU__c='testTarif2',Is_DataLoaded__c=true,Migration_Notes_AU__c='Migration');

        List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com,c,'Apple','Yogiyo_List_Product_Group');
        List_Product_Group__c lpg1 = UnitTestDataFactory.createProductGroup(com,c,'Setup Fee','Yogiyo_List_Product_Group');


        insert new List<SObject>{opp1,opp2,opp3,opp4,opp5,opp6,lpg,lpg1};

        List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com,c,'Ipad 4 Gen. 16GB',lpg.id,'Yogiyo_List_Product_Price',1,true,100,1,false,20);
        List_Product_Price__c lpp1 = UnitTestDataFactory.createProduct(com,c,'Super Hero Setup 1',lpg1.id,'Yogiyo_List_Product_Price',1,true,100,1,false,20); 
        lpp1.Requires_Branding__c = true;
        lpp1.Requires_Add_On__c = true;
        List_Product_Price__c lpp2 = UnitTestDataFactory.createProduct(com,c,'Super Hero Setup 2',lpg1.id,'Yogiyo_List_Product_Price',1,true,50,1,true,20);  


        List_Service_Price__c lsp = UnitTestDataFactory.createService(com,c,'testService1','Yogiyo_List_Service_Price',12,12,25,5,null,true,200,'Commission Fee','Commission Fee');
        List_Service_Price__c lsp1 = UnitTestDataFactory.createService(com,c,'testService2','Yogiyo_List_Service_Price',12,12,13,5,null,true,null,'Commission Fee','Commission Fee');

        Tarif__c t = UnitTestDataFactory.createTarif(com,c,'testTarif1','Yogiyo_Tarif',false);
        Tarif__c t1 = UnitTestDataFactory.createTarif(com,c,'testTarif2','Yogiyo_Tarif',false);

        insert new List<sObject>{lpp,lpp1,lpp2,lsp,lsp1,t,t1};

        Tarif_Member__c tm = UnitTestDataFactory.createTarifMember(lpp.id,'Yogiyo_Tarif_Member',t.id,'Product');
        Tarif_Member__c tm1 = UnitTestDataFactory.createTarifMember(lpp1.id,'Yogiyo_Tarif_Member',t.id,'Product');
        Tarif_Member__c tm2 = UnitTestDataFactory.createTarifMember(lsp.id,'Yogiyo_Tarif_Member',t.id,'Service');
        Tarif_Member__c tm3 = UnitTestDataFactory.createTarifMember(lsp1.id,'Yogiyo_Tarif_Member',t1.id,'Service');
        Tarif_Member__c tm4 = UnitTestDataFactory.createTarifMember(lpp2.id,'Yogiyo_Tarif_Member',t1.id,'Product');
        
        Opportunity_line_item__c opl = new Opportunity_Line_Item__c(name = 'jdfj',
                                                                        Id_List_Price_Product__c =lpp.id ,
                                                                        Listed_Price__c = 20.00,
                                                                        Quantity__c = 1,
                                                                        Total_Amount__c = 20,
                                                                        Id_Opportunity__c= opp1.id,
                                                                        Product_Group__c = lpg.id, 
                                                                        Installments__c = 1,
                                                                        Has_Related_Tarif__c =true, 
                                                                        recordtypeId = mapRecordTypes.get('Yogiyo_Opportunity_Line_Item').id,
                                                                        CurrencyIsoCode = opp1.CurrencyIsoCode,
                                                                        
                                                                        City_ZipCode__c='849594',
                                                                        Position__c='0',
                                                                        Start_Date__c=Date.today(),
                                                                        Booking_Api_Id__c='8383',
                                                                        Discount__c='10',
                                                                       
                                                                        Category__c='dsjbjv',


                                                                        Line_Item_Type__c='Product',
                                                                        sub_type__c='Premium Placement'
                                                                        
                                                                        
                                                                        
                                                                         
                                                                         
                                                                        );
     

        insert new List<sObject>{tm,tm1,tm2,tm3,tm4,opl};

        t.Is_Active__c = true;
        t1.Is_Active__c = true;
        update new List<Tarif__c>{t,t1};
        
        
    }
    
    

    @isTest static void testBatchPPMigration(){
        testData();
        Test.startTest();
        System.runAs(testRunningUser){
            BatchPPmigration batch = new BatchPPmigration();
            Database.executeBatch(batch,500);

        }
        Test.stopTest();
        
                                                           




    }
    


    
}