force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Talabat_Contract.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Contract</fullName>
    <active>true</active>
    <label>Talabat Contract</label>
</RecordType>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <description>this is commission Type</description>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this service is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/recordTypes/Talabat_List_Service_Price.recordType-meta.xml
<RecordType>
    <fullName>Talabat_List_Service_Price</fullName>
    <active>true</active>
    <label>Talabat List Service Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Id_Tarif__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Tarif</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_DataLoaded__c.field-meta.xml
<CustomField>
    <fullName>Is_DataLoaded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this helps us not to trigger some triggers when it is true</description>
    <label>Is DataLoaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Migration_Notes_AU__c.field-meta.xml
<CustomField>
    <fullName>Migration_Notes_AU__c</fullName>
    <description>Notes for AU Opportunity Migration</description>
    <label>Migration Notes AU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Setup_Fee_AU__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_AU__c</fullName>
    <description>Setup Fee for AU, for migration only</description>
    <label>Setup Fee AU</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date_uk__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_uk__c</fullName>
    <description>For Migration Only</description>
    <inlineHelpText>Use field it the Start Date is NOT ASAP. Automatically populated via tariffs.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TarrifName_AU__c.field-meta.xml
<CustomField>
    <fullName>TarrifName_AU__c</fullName>
    <description>Tarrif Name for AU, for migration only</description>
    <label>TarrifName_AU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Talabat_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Talabat Sales Process</businessProcess>
    <description>Talabat Opportunity</description>
    <label>Talabat Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <description>This will be copy from List service price when the Oportunity line item is created</description>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <formula>IF(ISPICKVAL(Commission_Type_Picklist__c, &apos;&apos;), 
TEXT(Id_List_Service_Price__r.Commission_Type__c), 
TEXT(Commission_Type_Picklist__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/Talabat_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>Talabat Opportunity Line Item</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Tarif__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Tarif</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <description>This will be copy from List service price when the Oportunity line item is created</description>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <formula>IF(ISPICKVAL(Commission_Type_Picklist__c, &apos;&apos;),  
    TEXT(Id_List_Service_Price__r.Commission_Type__c),
    TEXT(Commission_Type_Picklist__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/recordTypes/Talabat_Opportunity_Quote_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Quote_Line_Item</fullName>
    <active>true</active>
    <label>Talabat Opportunity Quote Line Item</label>
</RecordType>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/Talabat_Tarif.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Tarif</fullName>
    <active>true</active>
    <label>Talabat Tarif</label>
</RecordType>

force-app/main/default/objects/Trigger_Manager__c/Trigger_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Manager</label>
</CustomObject>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_Contract_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Contract_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Contract Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CommissionRemediation_Batch_Test.cls
/**
* @author Mantas Jurkunas
* @date 15.07.2019
*
* @description Test for CommissionRemediation_Batch class
* @see CommissionRemediation_Batch
*/
@IsTest
public with sharing class CommissionRemediation_Batch_Test {
    @TestSetup
    public static void setup() {
        Trigger_Manager__c triggerManager = new Trigger_Manager__c( Deactivate_Contract_Trigger__c = true );
        insert triggerManager;
        Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Opportunity', 'Contract'});
        UnitTestDataFactory.getRecordtypeValues();

        Country__c bh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        Country__c ec = UnitTestDataFactory.createCountry('EC', 'Ecuador', 'USD');
        insert new List<Country__c> {ec, bh};

        Company__c com = UnitTestDataFactory.createCompany('Talabat', 'Talabat', bh);
        insert com;

        Account acc1 = UnitTestDataFactory.createAccount('BatchTestClassAccount1', bh, 'Talabat_Account');
        Account acc2 = UnitTestDataFactory.createAccount('cd account', ec, 'CD_Account');
        insert new List<Account> {acc1, acc2};

        List_Service_Price__c lsp = UnitTestDataFactory.createService(com,bh,'testService1','Talabat_List_Service_Price',12,12,25,5,null,true,null,'Commission','ServiceType');
        lsp.Based_On__c = 'Orders';
        lsp.Commission_Type__c = 'Percentage';
        lsp.Scaled__c = true;
        insert lsp;
        Tarif__c t = UnitTestDataFactory.createTarif(com, bh , 'Free Tarif', 'Talabat_Tarif', false);
        insert t;

        Opportunity opp1 = new Opportunity(
                Setup_Fee_AU__c = 155,
                Start_Date_uk__c = Date.newInstance(2014, 12, 21),
                Name = 'BatchTestOpp1',
                RecordTypeId = mapRecordtypes.get('Talabat_Opportunity').Id,
                AccountId = acc1.Id,
                CloseDate = Date.newInstance(2014, 12, 21),
                StageName = 'Prospecting',
                TarrifName_AU__c = 'testTarif1',
                Id_Tarif__c=t.Id,
                Is_DataLoaded__c = true,
                Migration_Notes_AU__c = 'Migration');

        insert new List<Opportunity> {opp1};

        Opportunity_Quote__c newQuote = new Opportunity_Quote__c(Id_Opportunity__c=opp1.Id,Status__c='Approved',Id_Account__c=acc1.Id);
        insert newQuote;

        Opportunity_Line_Item__c oppService = UnitTestDataFactory.createOpportunityLineItemService('testService3',opp1,lsp.Id,true,'Talabat_Opportunity_Line_Item',12,null,Date.today(),'Commission Fee',null);
        insert oppService;

        List<Opportunity_Quote_Line_Item__c> oppQuoteLine =  UnitTestDataFactory.createOpportunityQuoteLineItems(newQuote,1,false,'Talabat_Opportunity_Quote_Line_Item',12,1,true, 0, Date.today(),'Commission Fee','Service');
        oppQuoteLine[0].Id_Opportunity__c=opp1.Id;
        oppQuoteLine[0].Id_List_Service_Price__c=lsp.Id;
        insert oppQuoteLine ;
        newQuote.Status__c='Accepted';
        update newQuote;

        Contract con1 = new Contract(Name = 'test1',
                AccountId = acc1.Id,
                Id_Opportunity__c = opp1.Id,
                Status = 'Draft',
                StartDate = Date.today().addYears(-1),
                End_Date__c = Date.today(),
                Id_Opportunity_Quote_Line_Item__c=oppQuoteLine[0].Id,
                RecordTypeId = mapRecordtypes.get('Talabat_Contract').Id);
        Contract con2 = new Contract(Name = 'test2',
                AccountId = acc2.Id,
                Id_Opportunity__c = opp1.Id,
                Status = 'Draft',
                StartDate = Date.today().addYears(-1),
                Id_Opportunity_Quote_Line_Item__c=oppQuoteLine[0].Id,
                End_Date__c = Date.today(),
                RecordTypeId = mapRecordtypes.get('Talabat_Contract').Id);
        insert new List<Contract> {con1, con2};

        con1.Status = 'Activated';
        con2.Status = 'Activated';
        update new List<Contract> {con1, con2};
    }

    @IsTest
    public static void test_OpportunityLineItemRemediation() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Opportunity_Line_Item__c.class));
        Test.stopTest();
        List<Opportunity_Line_Item__c> listObj = OpportunityLineItem_Selector.getAll();
        for (Opportunity_Line_Item__c obj: listObj) {
            System.assertEquals('Orders', obj.Based_On__c);
            System.assertEquals('Percentage', obj.Commission_Type_Picklist__c);
            System.assert(obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_QuoteLineItemRemediation() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Opportunity_Quote_Line_Item__c.class));
        Test.stopTest();
        List<Opportunity_Quote_Line_Item__c> listObj = OpportunityQuoteLineItem_Selector.getAll();
        for (Opportunity_Quote_Line_Item__c obj: listObj) {
            System.assertEquals('Orders', obj.Based_On__c);
            System.assertEquals('Percentage', obj.Commission_Type_Picklist__c);
            System.assert(obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_CommissionRemediation() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Contract.class));
        Test.stopTest();
        List<Contract> listObj = ContractSelector.getAll();
        for (Contract obj: listObj) {
            System.assertEquals('Orders', obj.Based_On__c);
            System.assertEquals('Percentage', obj.Commission_Type__c);
            System.assert(obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_OpportunityLineItemRemediationRecordType() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Opportunity_Line_Item__c.class, 'Talabat_Opportunity'));
        Test.stopTest();
        List<Opportunity_Line_Item__c> listObj = OpportunityLineItem_Selector.getAll();
        for (Opportunity_Line_Item__c obj: listObj) {
            System.assertEquals('Orders', obj.Based_On__c);
            System.assertEquals('Percentage', obj.Commission_Type_Picklist__c);
            System.assert(obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_QuoteLineItemRemediationRecordType() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Opportunity_Quote_Line_Item__c.class, 'Talabat_Opportunity'));
        Test.stopTest();
        List<Opportunity_Quote_Line_Item__c> listObj = OpportunityQuoteLineItem_Selector.getAll();
        for (Opportunity_Quote_Line_Item__c obj: listObj) {
            System.assertEquals('Orders', obj.Based_On__c);
            System.assertEquals('Percentage', obj.Commission_Type_Picklist__c);
            System.assert(obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_CommissionRemediationRecordType() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Contract.class, 'Talabat_Opportunity'));
        Test.stopTest();
        List<Contract> listObj = ContractSelector.getAll();
        for (Contract obj: listObj) {
            System.assertEquals('Orders', obj.Based_On__c);
            System.assertEquals('Percentage', obj.Commission_Type__c);
            System.assert(obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_NegativeRemediation() {
        Boolean batchFailed = true;
        try {
            Test.startTest();
            Database.executeBatch(new CommissionRemediation_Batch(Opportunity.class));
            Test.stopTest();
            batchFailed = false;
        } catch (CommissionRemediation_Batch.CommissionRemediationException e) {}
        System.assert(batchFailed);
    }

    @IsTest
    public static void test_NegativeOpportunityLineItemRemediationRecordType() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Opportunity_Line_Item__c.class, 'BTS_Opportunity'));
        Test.stopTest();
        List<Opportunity_Line_Item__c> listObj = OpportunityLineItem_Selector.getAll();
        for (Opportunity_Line_Item__c obj: listObj) {
            System.assertNotEquals('Orders', obj.Based_On__c);
            System.assertNotEquals('Percentage', obj.Commission_Type_Picklist__c);
            System.assert(!obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_NegativeQuoteLineItemRemediationRecordType() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Opportunity_Quote_Line_Item__c.class, 'BTS_Opportunity'));
        Test.stopTest();
        List<Opportunity_Quote_Line_Item__c> listObj = OpportunityQuoteLineItem_Selector.getAll();
        for (Opportunity_Quote_Line_Item__c obj: listObj) {
            System.assertNotEquals('Orders', obj.Based_On__c);
            System.assertNotEquals('Percentage', obj.Commission_Type_Picklist__c);
            System.assert(!obj.Scaled__c);
        }
    }

    @IsTest
    public static void test_NegativeCommissionRemediationRecordType() {
        Test.startTest();
        Database.executeBatch(new CommissionRemediation_Batch(Contract.class, 'BTS_Opportunity'));
        Test.stopTest();
        List<Contract> listObj = ContractSelector.getAll();
        for (Contract obj: listObj) {
            System.assertNotEquals('Orders', obj.Based_On__c);
            System.assertNotEquals('Percentage', obj.Commission_Type__c);
            System.assert(!obj.Scaled__c);
        }
    }

}