force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>ClientId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>ClientSecret</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>A company that a user belongs to. A user can belong to more than one company</description>
    <label>Company Name</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yogiyo</fullName>
            </value>
            <value>
                <fullName>Talabat</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>PY</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>FP</fullName>
            </value>
            <value>
                <fullName>YE</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>HS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>The country of the different countries. Will be used together with the record types to handle business processes for different countries</description>
    <inlineHelpText>2 digit ISO Country Code</inlineHelpText>
    <label>CountryCode</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>EC</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>KR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>EG</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>JO</fullName>
            </value>
            <value>
                <fullName>KW</fullName>
            </value>
            <value>
                <fullName>OM</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PY</fullName>
            </value>
            <value>
                <fullName>UY</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>DO</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnitTestClsWebserviceCalloutAdSalesKR.cls
@isTest
private class UnitTestClsWebserviceCalloutAdSalesKR {

	private static User testUser_kr = UnitTestDataFactory.createUser('Yogiyo Sales Team', 'yogiyotestuser@deliveryhero.com', 'Yogiyo','KR');
	private static Country__c testCountry_kr;
	private static Company__c testCompany_kr;


	//KR testdata
    static {
    	insert testUser_kr;
    	System.runAs(testUser_kr){
    		testCountry_kr = UnitTestDataFactory.createCountry('KR','Korea','KRW');
			insert testCountry_kr;

			testCompany_kr = UnitTestDataFactory.createCompany('Yogiyo', 'Yogiyo', testCountry_kr);
			insert testCompany_kr;

			testUser_kr.CountryCode__c = 'KR';
			testUser_kr.Company_Name__c = 'Yogiyo';
			update testUser_kr;
			Integration_Config__c iconfig = new Integration_Config__c(Name = 'KR_YogiyoBackend',
					Endpoint__c='https://www.yogiyo.co.kr/salesforce/restaurant/',
					ClientId__c='salesforce', ClientSecret__c='salesforceSecret');
			Integration_Config__c iconfig1 = new Integration_Config__c(Name = 'KR_YogiyoBackend_STG',
					Endpoint__c='https://www.yogiyo.co.kr/salesforce/restaurant/',
					ClientId__c='salesforce', ClientSecret__c='salesforceSecret');

			insert new List<SObject>{iconfig,iconfig1};

    	}
    }
    @isTest static void getFixAmountCommissionDistricts_Pass(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());
        
        FixedCommissionWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getFixAmountCommissionDistricts('4712');
        
        Test.stopTest();
        
        System.assertNotEquals(null, wrapper.mapCategories);
        System.assertNotEquals(null, wrapper.mapDistricts);
        System.assertNotEquals(null, wrapper.mapDistrictPrices);
    }
	
	@isTest static void getAvailableDistrictsAndCategories_Pass() {

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('0815');

		Test.stopTest();

		System.assertEquals(false,wrapper.errorFlag);
		System.debug('wrapper.mapCategories: '+wrapper.mapCategories);
		System.assertNotEquals(null, wrapper.mapCategories);
		System.assertNotEquals(null, wrapper.mapDistricts);
		System.assertNotEquals(null, wrapper.mapDistrictPrices);
		System.assertNotEquals(null, wrapper.mapTypeDistricts);


	}

	@isTest static void getAvailableDistrictsAndCategories_Pass_Decimal_Amounts() {

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('0816');

		Test.stopTest();

		System.assertEquals(false,wrapper.errorFlag);
		System.debug('wrapper.mapCategories: '+wrapper.mapCategories);
		System.assertNotEquals(null, wrapper.mapCategories);
		System.assertNotEquals(null, wrapper.mapDistricts);
		System.assertNotEquals(null, wrapper.mapDistrictPrices);
		System.assertNotEquals(null, wrapper.mapTypeDistricts);

		System.assertEquals(50000.00, wrapper.mapDistrictPrices.get('Super-4006'));


	}
	
	@isTest static void getAvailableDistrictsAndCategories_Fail() {
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('4711');

		Test.stopTest();

		System.assertEquals(true,wrapper.errorFlag);
		System.assertEquals(Label.AdSalesKR404,wrapper.errorMessage);
		
	}

	@isTest static void getAvailableDistrictsAndCategories_Incomplete() {
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('0021');

		Test.stopTest();

		System.assertEquals(true,wrapper.errorFlag);
		System.assertEquals(Label.AdSalesKRIncomplete,wrapper.errorMessage);
		
	}

	@isTest static void getAvailableDistrictsAndCategories_Incomplete_null() {
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('0022');

		Test.stopTest();

		System.assertEquals(true,wrapper.errorFlag);
		System.assertEquals(Label.AdSalesKRException,wrapper.errorMessage);
		
	}

	@isTest static void getAvailableDistrictsAndCategories_no_basic_category() {
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('0023');

		Test.stopTest();

		System.assertEquals(false,wrapper.errorFlag);
		System.assertNotEquals(null, wrapper.mapCategories);
		System.assertNotEquals(null, wrapper.mapDistricts);
		System.assertNotEquals(null, wrapper.mapDistrictPrices);
		System.assertNotEquals(null, wrapper.mapTypeDistricts);

		System.assertEquals(null, wrapper.mapDistrictPrices.get('Basic-4006'));
		System.assertEquals(50000,wrapper.mapDistrictPrices.get('Super-4006'));
		
	}

	@isTest static void getAvailableDistrictsAndCategories_no_super_category() {
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new UnitTestMockWebserviceAdSalesKR());

		DistrictPriceCategoryWrapper wrapper = ClsWebserviceCalloutAdSalesKR.getAvailableDistrictsAndCategories('0024');

		Test.stopTest();

		System.assertEquals(false,wrapper.errorFlag);
		System.assertNotEquals(null, wrapper.mapCategories);
		System.assertNotEquals(null, wrapper.mapDistricts);
		System.assertNotEquals(null, wrapper.mapDistrictPrices);
		System.assertNotEquals(null, wrapper.mapTypeDistricts);

		System.assertEquals(30000, wrapper.mapDistrictPrices.get('Basic-4006'));
		System.assertEquals(null,wrapper.mapDistrictPrices.get('Super-4006'));
		
	}
	
}