force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Add_On__c/List_Add_On__c.object-meta.xml
<CustomObject>
    <label>List Add On</label>
    <nameField>
        <label>List Add On Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Add On</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Add_On__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Add On</relationshipLabel>
    <relationshipName>List_Add_On</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Contract_Addition__c.field-meta.xml
<CustomField>
    <fullName>Contract_Addition__c</fullName>
    <label>Contract Addition</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Add On</relationshipLabel>
    <relationshipName>List_Add_On</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exclusivity</fullName>
            </value>
            <value>
                <fullName>Deal / Promotion</fullName>
            </value>
            <value>
                <fullName>Extra Terms and Conditions</fullName>
            </value>
            <value>
                <fullName>Deals</fullName>
                <isActive>false</isActive>
                <label>Deals</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this attribute activates the product, so that this product is able to select in the opportunity</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this service is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>holds the country of the record</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this shows if this is enable</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>this gives the type of service</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Premium Placement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tarifs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/Yogiyo_Tarif.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Tarif</fullName>
    <active>true</active>
    <label>Yogiyo Tarif</label>
</RecordType>

force-app/main/default/objects/Tarif_Member__c/Tarif_Member__c.object-meta.xml
<CustomObject>
    <description>this shows the services and products that belong to a specific tarif</description>
    <label>Tarif Member</label>
    <nameField>
        <displayFormat>TAI-{000000}</displayFormat>
        <label>Tarif Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tarif Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif_Member__c/fields/Id_Tarif_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif_Item__c</fullName>
    <description>this holds the id of tarif member</description>
    <label>Id Tarif Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/fields/Tarif_Name__c.field-meta.xml
<CustomField>
    <fullName>Tarif_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the tarif name</description>
    <label>Tarif Name</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Tarif Members</relationshipLabel>
    <relationshipName>Tarif_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>this helps in identifying product or service record id.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/recordTypes/Yogiyo_Tarif_Member.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Tarif_Member</fullName>
    <active>true</active>
    <label>Yogiyo Tarif Member</label>
</RecordType>

force-app/main/default/classes/UnitTestAddOnTrigger.cls
@isTest
public with sharing class UnitTestAddOnTrigger {
    
    private static Map<String, RecordType> mapRecordtypesKR = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Opportunity', 'Account', 'List_Product_Group__c', 'List_Product_Price__c', 'List_Service_Price__c', 'Tarif__c', 'Tarif_Member__c', 'Tarif_Item__c', 'Opportunity_Line_Item__c'});
    
    @TestSetup
    public static void setupData(){
		Country__c c = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        insert c;
        Company__c com = UnitTestDataFactory.createCompany('Yogiyo', 'Yogiyo', c);
        insert com;

        Tarif__c t = new Tarif__c(Company__c = com.id, Id_Country__c = c.id, Is_Active__c = false, Name = 'testTarif1', RecordTypeId = mapRecordtypesKR.get('Yogiyo_Tarif').id);
		insert t;
		
		t.Is_Active__c = true;
		update t;
		  
    	// Create Add Ons
    	List_Add_On__c addon = new List_Add_On__c();
    	addOn.name	= 'test';
    	addOn.is_Active__c = true;
    	addOn.Contract_Addition__c = 'test';
    	addOn.type__c = 'Deal / Promotion';
    	insert addOn;
    	
    	// create tarif Member
    	Tarif_Member__c tm = new Tarif_Member__c(Id_Tarif_Item__c = addOn.id, RecordTypeId = mapRecordtypesKR.get('Yogiyo_Tarif_Member').id, Tarif_Name__c = t.id, Type__c = 'AddOn');
    	insert tm;
    }
    
    @isTest
    public static void testAddOnTrigger(){
		List_Add_on__c addON = [Select Id,Is_Active__c from List_Add_on__c limit 1];
    	Test.startTest();
			addOn.Is_Active__c = false;
			try{
				update addOn;
			}catch(exception e){}
    	Test.stopTest();
    }
    
}