force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/FP_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Product_Group</fullName>
    <active>true</active>
    <label>FP List_Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/FP_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Product_Price</fullName>
    <active>true</active>
    <label>FP List Product Price</label>
</RecordType>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this service is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/recordTypes/FP_List_Service_Price.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Service_Price</fullName>
    <active>true</active>
    <label>FP List Service Price</label>
</RecordType>

force-app/main/default/classes/ListProductPriceSelector_Test.cls
@isTest
public with sharing class ListProductPriceSelector_Test {
    @TestSetup
    public static void setUpData(){
        // create RecordType__c custom setting
        UnitTestDataFactory.getRecordtypeValues();	
        
        // create Country
        Country__c HKCoutry = UnitTestDataFactory.createCountry('HK','Hong Kong', 'HKD');
        insert HKCoutry;
        
        // create company
        Company__c com = UnitTestDataFactory.createCompany('Hungryhouse', 'uk', HKCoutry);
        insert com;

                
        // Create commissions
        List<List_Service_price__c> commissions = UnitTestDataFactory.createServices(com, HKCoutry, 3,'FP_List_Service_Price',12,12,16, 8, 1,'Commission Fee', 
                                                                                     true, 0,'','Percentage', 'Commission Fee');
        
        insert commissions;
        
        // Create Product Group
        List<List_Product_group__c> groups = UnitTestDataFactory.createProductGroups(Com, HKCoutry, 1, 'FP_List_Product_Group');
        insert groups;
        
        // Create Products
        List<List_Product_price__c> products = UnitTestDataFactory.createProducts(com, HKCoutry,groups[0].id, 2,'FP_List_Product_Price',
                                                                                  0, true, 100, 1, false,20);
        insert products;
        
    }
    
    @isTest
    public static void TestAll(){
        List<List_Product_Price__c> lppList = ListProductPriceSelector.findListProdPriceByrecTypeandCountry('FP_List_Product_Price','Hong Kong');
        ListProductPriceSelector.getListProductPriceRecordsFilteredByRecordTtype(new Set<String>{},new Set<String>{});
        ListProductPriceSelector.getActiveProductsById(new List<Id>{});
        System.assertEquals(False, lppList.isEmpty());
    }
}