force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/FP_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Product_Group</fullName>
    <active>true</active>
    <label>FP List_Product Group</label>
</RecordType>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Categories__c.field-meta.xml
<CustomField>
    <fullName>Categories__c</fullName>
    <label>Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tarifs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tarif__c/fields/Product_Only__c.field-meta.xml
<CustomField>
    <fullName>Product_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/FP_Tarif.recordType-meta.xml
<RecordType>
    <fullName>FP_Tarif</fullName>
    <active>true</active>
    <label>FP Tarif</label>
</RecordType>

force-app/main/default/classes/TarifSelector_Test.cls
@isTest
public with sharing class TarifSelector_Test {
    private static Map<String, RecordType> mapRecordtypesKR = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Tarif__c','List_Product_Group__c'});

    @TestSetup
    public static void setUpData(){
        // create RecordType__c custom setting
        UnitTestDataFactory.getRecordtypeValues();	
        
        // create Country
        Country__c c = UnitTestDataFactory.createCountry('HK','Hong Kong', 'HKD');
        insert new List<Country__c>{c};
        
        // create company
        Company__c com = UnitTestDataFactory.createCompany('Hungryhouse', 'uk', c);
        insert com;

        // Create Product Group
        List<List_Product_group__c> groups = UnitTestDataFactory.createProductGroups(Com, c, 1, 'FP_List_Product_Group');
        insert groups;

        // Create Tarif
        Tarif__c t = new Tarif__c(Company__c = com.id, Id_Country__c = c.id, Is_Active__c = false, Name = 'testTarif1', RecordTypeId = mapRecordtypesKR.get('FP_Tarif').id);
        t.is_Locked__c 		= false;
        t.Product_only__c 	= false;
        t.categories__c 	= groups[0].name;
        insert t;
        t.Is_Active__c = true;
        update t;
    }
    
    @isTest
    public static void TestAll(){
        Tarif__c tar = TarifSelector.findTarifRecordByTarifName('testTarif1','FP','Hong Kong');
        TarifSelector.findTarifRecordByCountries(new set<Id>{});
        System.assertEquals(true, tar != null);
    }
}