force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Date_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Date_Shipped__c</fullName>
    <description>Date when Shipment Order was shipped</description>
    <label>Date Shipped</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Last_Tracking_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Tracking_Update__c</fullName>
    <description>Timestamp on when delivery tracking status was updated last time.</description>
    <label>Last Tracking Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to display current status of Shipment Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Tracking_Active__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field necessary for Aftership integration to continue tracking returning shipment</description>
    <label>Tracking Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Tracking_Exception__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Exception__c</fullName>
    <description>Field to hold exception message from Aftership</description>
    <label>Tracking Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClsRestShippingOrderUpdAftership.cls
/**
 * Used in Aftership webhook to update the status of shipping order.
 */
@RestResource(urlMapping='/UpdateShippingStatus/*')
global with sharing class ClsRestShippingOrderUpdAftership{
    public static String logName = 'ShipmentStatusUpdate';

    @HttpPost
    global static void  updateShippingStatus() {
        LoggingUtility.createLog(logName,'AFTERSHIP','STATUS_UPDATE',null);
        RestRequest res 	= RestContext.request;
        String resp 		= res.requestBody.tostring();
        LoggingUtility.log(logName,'Request Body => '+ resp);
        JSONParser resJSON 	= JSON.createParser(resp);
        parseAftershipGetResponse(resJSON);
        LoggingUtility.commitLogs();

    }

    public static void parseAftershipGetResponse(JSONParser parser ){
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'msg') {
                system.debug(parser.getCurrentName());
                while (parser.nextToken() != null) {
                    Tracker tc=  (Tracker)parser.readValueAs(Tracker.class);
                    updateInfoOnShipment(tc);
                    break;
                }
            }
        }

    }


    public static void updateInfoOnShipment(Tracker tc){


        if(tc.tracking_number == null || tc.tracking_number == '')
            return;

        List<Shipment_Order__c> shipmentOrders = ShipmentOrderSelector.getShipmentOrderActivebyTracking(tc.tracking_number,tc.id) ;

        if(shipmentOrders.size() == 0)
            return;

        for(Shipment_Order__c so : shipmentOrders){
            if(tc.tag=='Exception'){
                system.debug(tc.checkpoints);
                for(CheckPoint ch:tc.checkpoints){
                    if(ch.tag=='Exception'){
                        so.Tracking_Exception__c=ch.message;
                        so.tracking_active__c=false;

                    }
                }
            }
            so.status__c=tc.tag;
            if(tc.tag=='Delivered')
                so.tracking_active__c=false;

            if(tc.updated_at!=null)
                so.Last_Tracking_Update__c=tc.updated_at;
            if(so.Date_Shipped__c==null && tc.tracking_ship_date!=null)
                so.Date_Shipped__c=tc.tracking_ship_date;
        }
        try{
            update shipmentOrders;
        }catch (Exception e){
            LoggingUtility.logError(logName,'Error => ' + e.getMessage() + '\nLine Number : ' + e.getLineNumber());
        }


    }

    public class Tracker{
        public String id;
        public String tracking_number;
        public String expected_delivery;
        public Date tracking_ship_date;
        public String tag;
        public Datetime updated_at;
        public List<CheckPoint> checkpoints;

    }

    public class CheckPoint{
        public String message;
        public String tag;


    }
}