force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_Item_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Transmission Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Online Payment Fee</fullName>
            </value>
            <value>
                <fullName>White Label Website Fee</fullName>
            </value>
            <value>
                <fullName>Order Now Button Fee</fullName>
            </value>
            <value>
                <fullName>RFV Discount</fullName>
            </value>
            <value>
                <fullName>Branding Discount</fullName>
            </value>
            <value>
                <fullName>White Label Website Discount</fullName>
            </value>
            <value>
                <fullName>Order Now Button Discount</fullName>
            </value>
            <value>
                <fullName>Exclusive Branding Discount</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Terminal Box</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Pizza Cartons</fullName>
            </value>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Monthly Box Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Annual Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Premium Placement</fullName>
            </value>
            <value>
                <fullName>Apron</fullName>
            </value>
            <value>
                <fullName>Caps</fullName>
            </value>
            <value>
                <fullName>Heating Bag</fullName>
            </value>
            <value>
                <fullName>Notepads and Pens</fullName>
            </value>
            <value>
                <fullName>Roofie</fullName>
            </value>
            <value>
                <fullName>T-shirt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppLineItems_Selector.cls
/**
* @author Shravya Rama
* @date 24.09.2019
*
* @description Selector class for retrieving Opportunity Line item records
*/

public class OppLineItems_Selector {

    public static List<Opportunity_Line_Item__c> getLineitemsBasedOnSubtype(String subType, Set<Id> oppIdsToCheckSet) {
        List<Opportunity_Line_Item__c> oppLineItemsList = new List<Opportunity_Line_Item__c>();
        try {
            oppLineItemsList = [SELECT Id,Id_Opportunity__c FROM Opportunity_Line_Item__c WHERE Id_Opportunity__c IN: oppIdsToCheckSet AND Sub_type__c = :subType];
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return oppLineItemsList;

    }
    /*******************************************************************************************************
    * @description Get List of OLi based on oppty Id
    * @param oppIdsToCheckSet Set of Ids of the opportunity
    * @param setofLineItemTypes Set of line item types
    * @return List<Opportunity_Line_Item__c>
    * @jira SSC-1646
    */
    public static List<Opportunity_Line_Item__c> getLineitemsBasedOnItemTypesAndOppty(Set<Id> oppIdsToCheckSet, Set<String> setofLineItemTypes) {
        List<Opportunity_Line_Item__c> oppLineItemsList = new List<Opportunity_Line_Item__c>();
        try {
            oppLineItemsList = [SELECT Id,Id_Opportunity__c,Start_Date__c,Line_Item_Type__c FROM Opportunity_Line_Item__c WHERE Id_Opportunity__c IN: oppIdsToCheckSet AND Line_Item_Type__c IN: setofLineItemTypes order by Start_Date__c ASC];
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return oppLineItemsList;
    }
    /*******************************************************************************************************
    * @description      : Get List of OLi based on oppty Id and sub types
    * @return           : List<Opportunity_Line_Item__c>
    * @jira             : SSC-1929
    * *******************************
    * @param             Set<String> setofLineItemTypes
    * @param             Set<Id> oppIdsToCheckSet
    */
    public static List<Opportunity_Line_Item__c> getLineItemsBasedOnSubtypesAndOppty(Set<String> setofLineItemTypes, Set<Id> oppIdsToCheckSet) {
        List<Opportunity_Line_Item__c> oppLineItemsList = new List<Opportunity_Line_Item__c>();
        try {
            oppLineItemsList = [SELECT Id,Id_Opportunity__c FROM Opportunity_Line_Item__c WHERE Id_Opportunity__c IN: oppIdsToCheckSet AND Sub_type__c IN: setofLineItemTypes];
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return oppLineItemsList;

    }
}