force-app/main/default/objects/Contract/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity_Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity Quote Line Item</label>
    <referenceTo>Opportunity_Quote_Line_Item__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <description>this is commission Type</description>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
                <default>true</default>
                <label>Percentage</label>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <description>This will be copy from List service price when the Oportunity line item is created</description>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <formula>IF(ISPICKVAL(Commission_Type_Picklist__c, &apos;&apos;), 
TEXT(Id_List_Service_Price__r.Commission_Type__c), 
TEXT(Commission_Type_Picklist__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_Type_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type_Picklist__c</fullName>
    <description>In this field it will be copy the info from the list service price to keep the original value on the creation of the line item, the field Commission_Type will have to be delete in the future SP-3440</description>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_List_Service_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Service_Price__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Id List Service Price</label>
    <referenceTo>List_Service_Price__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <description>This will be copy from List service price when the Oportunity line item is created</description>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <formula>IF(ISPICKVAL(Commission_Type_Picklist__c, &apos;&apos;),  
    TEXT(Id_List_Service_Price__r.Commission_Type__c),
    TEXT(Commission_Type_Picklist__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Commission_Type_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type_Picklist__c</fullName>
    <description>In this field it will be copy the info from the list service price to keep the original value on the creation of the line item, the field Commission_Type will have to be delete in the future SP-3440</description>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_List_Service_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Service_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id List Service Price</label>
    <referenceTo>List_Service_Price__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CommissionRemediation_Batch.cls
/**
* @author Mantas Jurkunas
* @date 15.07.2019
*
* @description Batch to perform data remediation on Commission, Opportunity_Line_Item and Opportunity_Quote_Line_Item - Based_On__c, Commission_Type__c fields
*/

public with sharing class CommissionRemediation_Batch implements Database.Batchable<SObject>, Database.Stateful {
    private final Type batchType;
    private List<String> queryFields;
    private String recordType;
    private Boolean allOrNothing;

    public CommissionRemediation_Batch(Type batchType) {
        this(batchType, null, true);
    }

    public CommissionRemediation_Batch(Type batchType, String opportunityRecordType) {
        this(batchType, opportunityRecordType, true);
    }

    public CommissionRemediation_Batch(Type batchType, String opportunityRecordType, Boolean stopOnException) {
        this.batchType = batchType;
        this.recordType = opportunityRecordType;
        allOrNothing = stopOnException;
    }

    public void execute(Database.BatchableContext batchableContext, List<SObject> objectList) {
        for (SObject value: objectList) {
            value.put('Based_On__c', ClsSObjectUtils.getFieldValue(value, queryFields.get(1)));
            value.put(queryFields.get(0), ClsSObjectUtils.getFieldValue(value, queryFields.get(2)));
            value.put('Scaled__c', ClsSObjectUtils.getFieldValue(value, queryFields.get(3)));
        }
        Database.update(objectList, allOrNothing);
    }

    public void finish(Database.BatchableContext batchableContext) {
    }

    public Database.QueryLocator start(Database.BatchableContext batchableContext) {
        String databaseQuery = 'SELECT Id, Based_On__c, Scaled__c, {0}, {1}, {2}, {3} FROM ' + batchType.toString() + ' WHERE ({1} != NULL OR {2} != NULL OR {3} != NULL) AND Based_On__c = NULL AND {0} = NULL';
        if (batchType.equals(Opportunity_Line_Item__c.class) || batchType.equals(Opportunity_Quote_Line_Item__c.class)) {
            queryFields = new List<String>{'Commission_Type_Picklist__c', 'Id_List_Service_Price__r.Based_On__c', 'Id_List_Service_Price__r.Commission_Type__c', 'Id_List_Service_Price__r.Scaled__c'};
        } else if (batchType.equals(Contract.class)) {
            queryFields = new List<String>{'Commission_Type__c', 'Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Based_On__c', 'Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Commission_Type__c', 'Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Scaled__c'};
        } else {
            throw new CommissionRemediationException('Invalid object type');
        }
        if (recordType != null) {
            databaseQuery = databaseQuery + ' AND Id_Opportunity__r.RecordType.DeveloperName = :recordType';
        }
        return Database.getQueryLocator(String.format(databaseQuery, queryFields));
    }

    @TestVisible
    private class CommissionRemediationException extends Exception { }
}