force-app/main/default/objects/Account/recordTypes/CD_Account.recordType-meta.xml
<RecordType>
    <fullName>CD_Account</fullName>
    <active>true</active>
    <description>Account for Click Delivery</description>
    <label>CD Account</label>
</RecordType>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AddressLine__c.field-meta.xml
<CustomField>
    <fullName>AddressLine__c</fullName>
    <label>XAL AddressLine</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AdministrativeAreaCode__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeAreaCode__c</fullName>
    <label>XAL AdministrativeAreaCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AdministrativeAreaDevName__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeAreaDevName__c</fullName>
    <label>XAL AdministrativeAreaDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeAreaName__c</fullName>
    <label>XAL AdministrativeAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AdministrativeAreaType__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeAreaType__c</fullName>
    <label>XAL AdministrativeAreaType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>XAL CountryCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryDevName__c.field-meta.xml
<CustomField>
    <fullName>CountryDevName__c</fullName>
    <label>XAL CountryDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <label>XAL CountryName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/DependentlocalityCode_1__c.field-meta.xml
<CustomField>
    <fullName>DependentlocalityCode_1__c</fullName>
    <label>XAL DependentlocalityCode 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/DependentLocalityDevName_1__c.field-meta.xml
<CustomField>
    <fullName>DependentLocalityDevName_1__c</fullName>
    <label>XAL DependentLocalityDevName 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/DependentLocalityName_1__c.field-meta.xml
<CustomField>
    <fullName>DependentLocalityName_1__c</fullName>
    <label>XAL DependentLocalityName 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/DependentLocalityType_1__c.field-meta.xml
<CustomField>
    <fullName>DependentLocalityType_1__c</fullName>
    <label>XAL DependentLocalityType 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Admin_area_level_1_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Admin_area_level_1_long_name__c</fullName>
    <label>GPA Admin area level 1 long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Country_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Country_long_name__c</fullName>
    <label>GPA Country long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Locality_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Locality_long_name__c</fullName>
    <label>GPA Locality long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Postal_code_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Postal_code_long_name__c</fullName>
    <label>GPA Postal code long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Route_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Route_long_name__c</fullName>
    <label>GPA Route long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Street_number_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Street_number_long_name__c</fullName>
    <label>GPA Street number long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/LocalityCode__c.field-meta.xml
<CustomField>
    <fullName>LocalityCode__c</fullName>
    <label>XAL LocalityCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/LocalityDevName__c.field-meta.xml
<CustomField>
    <fullName>LocalityDevName__c</fullName>
    <label>XAL LocalityDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/LocalityName__c.field-meta.xml
<CustomField>
    <fullName>LocalityName__c</fullName>
    <label>XAL LocalityName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/LocalityType__c.field-meta.xml
<CustomField>
    <fullName>LocalityType__c</fullName>
    <label>XAL LocalityType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/PostalCodeDevName__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeDevName__c</fullName>
    <label>XAL PostalCodeDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/PostalCodeName__c.field-meta.xml
<CustomField>
    <fullName>PostalCodeName__c</fullName>
    <label>XAL PostalCodeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SubAdministrativeAreaCode__c.field-meta.xml
<CustomField>
    <fullName>SubAdministrativeAreaCode__c</fullName>
    <label>XAL SubAdministrativeAreaCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SubAdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>SubAdministrativeAreaName__c</fullName>
    <label>XAL SubAdministrativeAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SubAdministrativeAreaType__c.field-meta.xml
<CustomField>
    <fullName>SubAdministrativeAreaType__c</fullName>
    <label>XAL SubAdministrativeAreaType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SubAdministratriveAreaDevName__c.field-meta.xml
<CustomField>
    <fullName>SubAdministratriveAreaDevName__c</fullName>
    <label>XAL SubAdministratriveAreaDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Restaurant Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/xAL_AdministrativeArea__mdt/xAL_AdministrativeArea__mdt.object-meta.xml
<CustomObject>
    <label>xAL AdministrativeArea</label>
    <pluralLabel>xAL AdministrativeAreas</pluralLabel>
</CustomObject>

force-app/main/default/objects/xAL_AdministrativeArea__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>City</fullName>
                <default>true</default>
                <label>City</label>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Country__mdt/xAL_Country__mdt.object-meta.xml
<CustomObject>
    <label>xAL Country</label>
    <pluralLabel>xAL Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/xAL_Country__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>ISO 3166-1 alpha-2 country code</description>
    <label>Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Locality__mdt/xAL_Locality__mdt.object-meta.xml
<CustomObject>
    <label>xAL Locality</label>
    <pluralLabel>xAL Localities</pluralLabel>
</CustomObject>

force-app/main/default/objects/xAL_Locality__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>City</fullName>
                <default>true</default>
                <label>City</label>
            </value>
            <value>
                <fullName>Suburb</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_PostalCode__mdt/xAL_PostalCode__mdt.object-meta.xml
<CustomObject>
    <label>xAL PostalCode</label>
    <pluralLabel>xAL PostalCodes</pluralLabel>
</CustomObject>

force-app/main/default/objects/xAL_PostalCode__mdt/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_SubAdministrativeAreas__mdt/xAL_SubAdministrativeAreas__mdt.object-meta.xml
<CustomObject>
    <label>xAL SubAdministrativeArea</label>
    <pluralLabel>xAL SubAdministrativeAreas</pluralLabel>
</CustomObject>

force-app/main/default/objects/xAL_SubAdministrativeAreas__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Value to be sent through API integration</description>
    <label>Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_SubAdministrativeAreas__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Province</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnitTestCtrCreateNewAddress.cls
/**
 * Created by marco.zeuli on 25/8/2017.
 */

@IsTest
private class UnitTestCtrCreateNewAddress {
	static final String testPostCode = 'Test_Scenario_PostCode';
	static final String testAdminArea = 'Test_Scenario_AdminArea';
	static final String testAdminAreaLabel = 'Test Scenario AdminArea';
	static final String testLocality = 'Test_Scenario_Locality';
	static final String testSubArea = 'Test_Scenario_SubArea';
	static final String testCountry = 'Test_Scenario_Country';
	static final String testCountryLabel = 'Test Scenario Country';
	static final String testDependentLocality = 'Test_Scenario_DependentLocality';

	static final xAL_Country__mdt country = [
	        SELECT DeveloperName, MasterLabel, Code__c
	        FROM xAL_Country__mdt
	        WHERE DeveloperName = :testCountry
	                                        ];

	static final xAL_AdministrativeArea__mdt area = [
	            SELECT DeveloperName, MasterLabel, Type__c, Code__c
	            FROM xAL_AdministrativeArea__mdt
	            WHERE DeveloperName = :testAdminArea
	        ];

	static final xAL_SubAdministrativeAreas__mdt subArea = [
	            SELECT DeveloperName, MasterLabel, Type__c, Code__c
	            FROM xAL_SubAdministrativeAreas__mdt
	            WHERE DeveloperName = :testSubArea
	        ];

	static final xAL_Locality__mdt locality = [
	            SELECT DeveloperName, MasterLabel, Type__c, Code__c
	            FROM xAL_Locality__mdt
	            WHERE DeveloperName = :testLocality
	        ];

	static final xAL_Locality__mdt dependentLocality = [
	            SELECT DeveloperName, MasterLabel, Type__c, Code__c
	            FROM xAL_Locality__mdt
	            WHERE DeveloperName = :testDependentLocality
	        ];

	static final xAL_PostalCode__mdt zipcode = [
	            SELECT DeveloperName, MasterLabel, Number__c
	            FROM xAL_PostalCode__mdt
	            WHERE DeveloperName = :testPostCode
	        ];

	@TestSetup static void setup() {
		UnitTestDataFactory.getRecordtypeValues();

		Integration_Config__c cs1 = new Integration_Config__c(
		    Name = 'GoogleMapsSignature', Password__c = 'Abvcd-asdfdgfhjklhnO0=');
		insert cs1;

		Country__c c = UnitTestDataFactory.createCountry('EC', testCountryLabel, 'USD');
		insert c;

		Account a = UnitTestDataFactory.createAccount('test xal', c, 'CD_Account');
		Account a2 = UnitTestDataFactory.createAccount('test gpa', c, 'CD_Account');
		insert new List<Account> {a, a2};

		AddressDetail__c addr = new AddressDetail__c(
		    Type__c = 'Restaurant Address;Billing Address',
		    Account__c = a.Id,

		    LatLng__Latitude__s = 10.0,
		    LatLng__Longitude__s = 5.0,

		    AddressLine__c = 'amazing address...',

		    CountryDevName__c = country.DeveloperName,
		    CountryName__c = country.MasterLabel,
		    CountryCode__c = country.Code__c,

		    AdministrativeAreaDevName__c = area.DeveloperName,
		    AdministrativeAreaName__c = area.MasterLabel,
		    AdministrativeAreaCode__c = area.Code__c,
		    AdministrativeAreaType__c = area.Type__c,

		    SubAdministratriveAreaDevName__c = subArea.DeveloperName,
		    SubAdministrativeAreaName__c = subArea.MasterLabel,
		    SubAdministrativeAreaCode__c = subArea.Code__c,
		    SubAdministrativeAreaType__c = subArea.Type__c,

		    LocalityDevName__c = locality.DeveloperName,
		    LocalityName__c = locality.MasterLabel,
		    LocalityType__c = locality.Type__c,
		    LocalityCode__c = locality.Code__c,

		    DependentLocalityDevName_1__c = dependentLocality.DeveloperName,
		    DependentLocalityName_1__c = dependentLocality.MasterLabel,
		    DependentLocalityType_1__c = dependentLocality.Type__c,
		    DependentlocalityCode_1__c = dependentLocality.Code__c,

		    PostalCodeDevName__c = zipcode.DeveloperName,
		    PostalCodeName__c = zipcode.Number__c
		);

		AddressDetail__c addr2 = new AddressDetail__c(
		    Type__c = 'Shipping Address',
		    Account__c = a2.Id,
		    LatLng__Latitude__s = 10.0,
		    LatLng__Longitude__s = 5.0,
		    GPA_Country_long_name__c = testCountryLabel,
		    GPA_Admin_area_level_1_long_name__c = testAdminAreaLabel,
		    GPA_Locality_long_name__c = testLocality,
		    GPA_Route_long_name__c = 'whatever...',
		    GPA_Street_number_long_name__c = '111',
		    GPA_Postal_code_long_name__c = '123'
		);

		insert new List<AddressDetail__c> {
			addr, addr2
		};

		List<GooglePlaceApiFieldMapping__c> confs = new List<GooglePlaceApiFieldMapping__c>();

		confs.add(new GooglePlaceApiFieldMapping__c(
		              Name = 'a1',
		              AddressFieldPrefix__c = 'GPA_Country',
		              CountryIso__c = 'EC',
		              FormLabel__c = 'country',
		              FormPosition__c = '1-1',
		              Required__c = true,
		              TypeToLikelihood__c = '{"country":99}'
		          ));

		confs.add(new GooglePlaceApiFieldMapping__c(
		              Name = 'a2',
		              AddressFieldPrefix__c = 'GPA_Admin_area_level_1',
		              CountryIso__c = 'EC',
		              FormLabel__c = 'admin area',
		              FormPosition__c = '1-2',
		              Required__c = true,
		              TypeToLikelihood__c = '{"admin_Area":99}'
		          ));

		confs.add(new GooglePlaceApiFieldMapping__c(
		              Name = 'a3',
		              AddressFieldPrefix__c = 'GPA_locality',
		              CountryIso__c = 'EC',
		              FormLabel__c = 'locality',
		              FormPosition__c = '1-1',
		              Required__c = true,
		              TypeToLikelihood__c = '{"locality":99}'
		          ));

		confs.add(new GooglePlaceApiFieldMapping__c(
		              Name = 'a4',
		              AddressFieldPrefix__c = 'GPA_route',
		              CountryIso__c = 'EC',
		              FormLabel__c = 'route',
		              FormPosition__c = '1-1',
		              Required__c = true,
		              TypeToLikelihood__c = '{"route":99}'
		          ));

		confs.add(new GooglePlaceApiFieldMapping__c(
		              Name = 'a5',
		              AddressFieldPrefix__c = 'GPA_Street_number',
		              CountryIso__c = 'EC',
		              FormLabel__c = 'street num',
		              FormPosition__c = '1-1',
		              Required__c = true,
		              TypeToLikelihood__c = '{"street num":99}'
		          ));

		confs.add(new GooglePlaceApiFieldMapping__c(
		              Name = 'a6',
		              AddressFieldPrefix__c = 'GPA_Postal_code',
		              CountryIso__c = 'EC',
		              FormLabel__c = 'zipcode',
		              FormPosition__c = '1-1',
		              Required__c = true,
		              TypeToLikelihood__c = '{"zipcode":99}'
		          ));

		insert confs;
	}

	@IsTest static void getAccountTypesReturnsCorrectly() {
		Map<String, String> res;

		Test.startTest();

		res = CtrCreateNewAddress.getAddressTypes();

		Test.stopTest();

		System.assertNotEquals(null, res);
	}

	@IsTest static void getAccountRecordTypeReturnsCorrectly() {
		Account acct;
		Test.startTest();
		acct = CtrCreateNewAddress.getAccountRecordType([SELECT Id FROM Account LIMIT 1].Id);
		Test.stopTest();
		System.assert(acct.RecordType.DeveloperName != null);
	}

	@IsTest static void gpa_getNewAddressDetailsPerAccountReturnsCorrectly() {
		GPAAddressDetails res;
		String accId = [SELECT Id FROM Account WHERE Name = 'test gpa' LIMIT 1].Id;
		Test.startTest();
		res = CtrCreateNewAddress.gpa_getNewAddressDetailsPerAccount(accId);
		Test.stopTest();

		System.assertNotEquals(null, res);
		System.assertEquals(accId, res.account);
	}

	@IsTest static void gpa_getNewAddressPerCountryReturnsCorrectly() {
		GPAAddressDetails res;
		Test.startTest();
		res = CtrCreateNewAddress.gpa_getNewAddressPerCountry(testCountryLabel);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}

	@IsTest static void gpa_getAddressDetailsReturnsCorrectly() {
		AddressDetail__c addr = [
		                            SELECT Id
		                            FROM AddressDetail__c
		                            WHERE GPA_Country_long_name__c != ''
		                            LIMIT 1
		                        ];

		GPAAddressDetails res;

		Test.startTest();
		res = CtrCreateNewAddress.gpa_getAddressDetails(addr.Id);
		Test.stopTest();

		System.assertEquals(addr.Id, res.id);
	}

	@IsTest static void gpa_getAddressDetailsPerAccountReturnsCorrectly() {
		Account acc = [SELECT Id FROM Account WHERE Name = 'test gpa' LIMIT 1];
		List<GPAAddressDetails> res;
		Test.startTest();
		res = CtrCreateNewAddress.gpa_getAddressDetailsPerAccount(acc.Id);
		Test.stopTest();

		System.assertNotEquals(null, res);
		System.assertEquals(1, res.size());
	}

	@IsTest static void gpa_saveAddressReturnsCorrectly() {
		Account a = [SELECT Id FROM Account WHERE Name = 'test gpa' LIMIT 1];
		GPAAddressDetails newAddr = new GPAAddressDetails('EC');

		newAddr.type = new List<String> {'Billing Address'};
		newAddr.longitude = 5.0;
		newAddr.latitude = 10.0;
		newAddr.account = a.Id;
		newAddr.formattedAddress = 'whatever';

		Test.startTest();
		newAddr = CtrCreateNewAddress.gpa_saveAddress(newAddr);
		Test.stopTest();

		System.assert(String.isNotBlank(newAddr.Id));

		List<AddressDetail__c> addresses = [SELECT Id FROM AddressDetail__c WHERE Account__c = :a.Id];
		System.assertEquals(2, addresses.size());
	}

	@IsTest static void gpa_saveAddressesReturnsCorrectly() {
		Account a = [SELECT Id FROM Account WHERE Name = 'test gpa' LIMIT 1];
		GPAAddressDetails addr = new GPAAddressDetails([SELECT Id FROM AddressDetail__c WHERE GPA_Country_long_name__c != '' LIMIT 1].Id);
		GPAAddressDetails newAddr = new GPAAddressDetails('EC');
		newAddr.type = new List<String> {'Billing Address'};
		newAddr.longitude = 5.0;
		newAddr.latitude = 10.0;
		newAddr.account = a.Id;
		newAddr.formattedAddress = 'whatever';

		List<GPAAddressDetails> res;

		Test.startTest();

		res = CtrCreateNewAddress.gpa_saveAddresses(new List<GPAAddressDetails> {
			addr, newAddr
		});

		Test.stopTest();

		System.assertNotEquals(null, res);
		System.assertEquals(2, res.size());
	}

	@IsTest static void CtrCreateNewAddressInstantiateCorrectly() {
		AddressDetail__c addr = [SELECT Id FROM AddressDetail__c WHERE CountryCode__c != '' LIMIT 1];
		PageReference pref = Page.CreateNewAddress;

		Test.startTest();
		Test.setCurrentPage(pref);

		ApexPages.StandardController stdCtr = new ApexPages.StandardController(addr);
		new CtrCreateNewAddress(stdCtr);
		new CtrCreateNewAddress();

		Test.stopTest();
	}

	@IsTest static void getAdminAreaByNameReturnsCorrectly() {
		xALAdministrativeArea res;
		Test.startTest();
		res = CtrCreateNewAddress.getAdminAreaByName(testAdminArea);
		Test.stopTest();
		System.assertNotEquals(null, res);

	}
	@IsTest static void getAdminAreaByLabelReturnsCorrectly() {
		xALAdministrativeArea res;
		Test.startTest();
		res = CtrCreateNewAddress.getAdminAreaByLabel(testAdminAreaLabel);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}
	@IsTest static void getSubAdminAreaByNameReturnsCorrectly() {
		xALSubAdministrativeArea res;
		Test.startTest();
		res = CtrCreateNewAddress.getSubAdminAreaByName(testSubArea);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}
	@IsTest static void getLocalityByNameReturnsCorrectly() {
		xALLocality res;
		Test.startTest();
		res = CtrCreateNewAddress.getLocalityByName(testLocality);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}
	@IsTest static void getCountryByNameReturnsCorrectly() {
		xALCountry res;
		Test.startTest();
		res = CtrCreateNewAddress.getCountryByName(testCountry);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}

	@IsTest static void getCountryByLabelReturnsCorrectly() {
		xALCountry res;
		Test.startTest();
		res = CtrCreateNewAddress.getCountryByLabel(testCountryLabel);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}
	@IsTest static void getCountryByAccountCountryLabelReturnsCorrectly() {
		Account a = [SELECT Id FROM Account WHERE Name = 'test xal' LIMIT 1];
		xALCountry res;
		Test.startTest();
		res = CtrCreateNewAddress.getCountryByAccountCountryLabel(a.Id);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}
	@IsTest static void getAddressDetailsReturnsCorrectly() {
		AddressDetail__c addr = [SELECT Id FROM AddressDetail__c WHERE CountryCode__c != '' LIMIT 1];
		xALAddressDetails res;
		Test.startTest();
		res = CtrCreateNewAddress.getAddressDetails(addr.Id);
		Test.stopTest();
		System.assertNotEquals(null, res);
	}

	@IsTest static void getAddressDetailsPerAccountReturnsCorrectly() {
		AddressDetail__c addr = [SELECT Id FROM AddressDetail__c WHERE CountryCode__c != '' LIMIT 1];
		List<xALAddressDetails> res;

		Test.startTest();

		res = CtrCreateNewAddress.getAddressDetailsPerAccount([SELECT Id FROM Account WHERE Name = 'test xal' LIMIT 1].Id);

		Test.stopTest();

		System.assertEquals(1, res.size());
		System.assertEquals(addr.Id, res[0].id);
	}

	@IsTest static void saveAddressReturnsCorrectly() {
		Account a = [SELECT Id FROM Account WHERE Name = 'test xal' LIMIT 1];
		xALAddressDetails newAddr = new xALAddressDetails();

		newAddr.type = new List<String> {
			'Shipping Address'
		};
		newAddr.addressLine = 'Go to hell!! :D';
		newAddr.account = a.Id;
		newAddr.latitude = 15.0;
		newAddr.longitude = 10.0;

		newAddr.country = xALCountry.byName(testCountry);
		newAddr.country.adminArea = xALAdministrativeArea.byName(testAdminArea);
		newAddr.country.adminArea.postalCode = xALPostalCode.byName(testPostCode);

		Test.startTest();

		CtrCreateNewAddress.saveAddress(newAddr);

		Test.stopTest();

		List<AddressDetail__c> res = [SELECT Id FROM AddressDetail__c WHERE Account__c = :a.Id];

		System.assertEquals(2, res.size());
	}

	@IsTest static void saveAddressesReturnsCorrectly() {
		Account a = [SELECT Id FROM Account WHERE Name = 'test xal' LIMIT 1];

		xALAddressDetails addr = new xALAddressDetails([SELECT Id FROM AddressDetail__c WHERE CountryCode__c != '' LIMIT 1].Id);
		xALAddressDetails newAddr = new xALAddressDetails();

		newAddr.type = new List<String> {
			'Shipping Address'
		};
		newAddr.addressLine = 'Go to hell!! :D';
		newAddr.account = a.Id;
		newAddr.latitude = 15.0;
		newAddr.longitude = 10.0;

		newAddr.country = xALCountry.byName(testCountry);
		newAddr.country.adminArea = xALAdministrativeArea.byName(testAdminArea);
		newAddr.country.adminArea.postalCode = xALPostalCode.byName(testPostCode);

		Test.startTest();

		CtrCreateNewAddress.saveAddresses(new List<xALAddressDetails> {
			addr, newAddr
		});

		Test.stopTest();

		List<AddressDetail__c> res = [SELECT Id FROM AddressDetail__c WHERE Account__c = :a.Id];

		System.assertEquals(2, res.size());
	}
}