force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>this holds the country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/DE_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>DE_List_Product_Group</fullName>
    <active>true</active>
    <label>DE List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this attribute activates the product, so that this product is able to select in the opportunity</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Requires_Add_On__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Asset__c.field-meta.xml
<CustomField>
    <fullName>Requires_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a product requires an asset</description>
    <label>Requires Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Branding__c.field-meta.xml
<CustomField>
    <fullName>Requires_Branding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Branding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/DE_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>DE_List_Product_Price</fullName>
    <active>true</active>
    <label>DE List Product Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Chain_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Chain_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Chain Opportunity Sales Process</businessProcess>
    <label>Chain Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/DE_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>DE_Opportunity</fullName>
    <active>true</active>
    <businessProcess>DE Sales Process</businessProcess>
    <label>DE Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/DE_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>DE_Opportunity_Quote</fullName>
    <active>true</active>
    <label>DE Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Created&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/recordTypes/DE_Opportunity_Quote_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>DE_Opportunity_Quote_Line_Item</fullName>
    <active>true</active>
    <label>DE Opportunity Quote Line Item</label>
</RecordType>

force-app/main/default/classes/UnitTestChainOpportunityController.cls
@isTest
public class UnitTestChainOpportunityController {
    
    @TestSetup
    public static void setupData(){
    	UnitTestDataFactory.getRecordtypeValues();
    	
    	Country__c testCountry = UnitTestDataFactory.createCountry('DE','Germany', 'EUR');
        insert testCountry;
        Company__c com = UnitTestDataFactory.createCompany('Lieferheld', 'DE', testCountry);
        insert com;
        
        List<Account> accList= UnitTestDataFactory.createAccounts(2,testCountry,'DE_Account');
        accList[0].Type = 'Group';
        accList[1].Type = 'Branch';
        insert accList;
        accList[1].ParentId = accList[0].Id;
        update accList;
        
        List<Opportunity> oppList = UnitTestDataFactory.createOpportunities(new List<Account>{accList[0]},1,'Chain_Opportunity',Date.today());
        oppList[0].type = 'Product Only';
        insert oppList;
        
        Opportunity_Quote__c newQuote = new Opportunity_Quote__c(Id_Opportunity__c=oppList[0].id,status__c='Approved',ID_Account__c=acclist[0].id);
        insert newQuote;

        List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com,testCountry,'Apple','DE_List_Product_Group');
        List_Product_Group__c lpg1 = UnitTestDataFactory.createProductGroup(com,testCountry,'Setup Fee','DE_List_Product_Group');
        insert new List<SObject>{lpg,lpg1};

        List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com,testCountry,'Ipad 4 Gen. 16GB',lpg.id,'DE_List_Product_Price',1,true,100,1,false,20);
        List_Product_Price__c lpp1 = UnitTestDataFactory.createProduct(com,testCountry,'Super Hero Setup 1',lpg1.id,'DE_List_Product_Price',1,true,100,1,false,20); 
        List_Product_Price__c lpp2 = UnitTestDataFactory.createProduct(com,testCountry,'Super Hero Setup 2',lpg1.id,'DE_List_Product_Price',1,true,50,1,false,20);
        lpp.Requires_Asset__c=true;  
        lpp.Requires_Branding__c=false;
        lpp.Requires_Add_On__c=false;
        insert new List<sObject>{lpp,lpp1,lpp2};

        List<Opportunity_Quote_Line_Item__c> oppQuoteLine2 =  UnitTestDataFactory.createOpportunityQuoteLineItems(newQuote,1,False,'DE_Opportunity_Quote_Line_Item',12,1,True, 0, date.today(),'Packaging','Product');
        oppQuoteLine2[0].Id_List_Product_Price__c = lpp.Id;
        oppQuoteLine2[0].id_opportunity__c=opplist[0].id;
        oppQuoteLine2[0].Quantity__c = 1;
        insert oppQuoteLine2;
        ClsCaseProcessor.donotValidateOppStage = true;
        newQuote.status__c='Accepted';
        update newQuote;
    	
    	// Create Business Configs
    	Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='childOppStageName',Business_Rule_Value__c='Quality Check Request',
    							Id_Country__c= testCountry.Id,Is_Active__c=true,Parent__c=false,
    							Process_Name__c='HeadquarterDealProcess',
								Record_Type_Id__c='Global_Config',Type__c='Process');
		Business_Config__c b2 = new Business_Config__c(Business_Rule_Name__c='AsynchronousThreshold',Business_Rule_Value__c='2',
    							Id_Country__c= testCountry.Id,Is_Active__c=true,Parent__c=false,
    							Process_Name__c='HeadquarterDealProcess',
								Record_Type_Id__c='Global_Config',Type__c='Process');
		Business_Config__c b3 = new Business_Config__c(Business_Rule_Name__c='SynchronousThreshold',Business_Rule_Value__c='1',
    							Id_Country__c= testCountry.Id,Is_Active__c=true,Parent__c=false,
    							Process_Name__c='HeadquarterDealProcess',
								Record_Type_Id__c='Global_Config',Type__c='Process');		
								
		insert new List<Business_Config__c>{b1,b2,b3};
    }
    
    @isTest
    public static void testFetchBranches(){
    	Opportunity opp = [Select Id,StageName from Opportunity where recordtype.developerName = 'Chain_Opportunity'];
    	ChainOpportunityController.ResultWrapper wrapper;
    	
    	opp.stageName = 'Closed Won';
    	update opp;
    	
    	wrapper = ChainOpportunityController.fetchBranches(opp.Id);
    	System.assertEquals(wrapper.accounts.size(),1);
    }
    
    @isTest
    public static void testApplyDeal(){
    	Opportunity opp = [Select Id,StageName from Opportunity where recordtype.developerName = 'Chain_Opportunity'];
    	opp.stageName = 'Closed Won';
    	update opp;
    	
    	ChainOpportunityController.ResultWrapper wrapper = ChainOpportunityController.fetchBranches(opp.Id);
    	
    	Test.startTest();
    		try{
    			wrapper	= ChainOpportunityController.applyDeals(JSON.Serialize(wrapper.accounts),opp.Id);
    			System.assertEquals(0,1,'Exception was not thrown as expected');
    		}catch(Exception e){
    			System.assertEquals(1,1);
    		}
    		
    		wrapper.accounts[0].isSelected = true;
    		wrapper	= ChainOpportunityController.applyDeals(JSON.Serialize(wrapper.accounts),opp.Id);	
    		System.assertEquals(wrapper.accounts[0].dealAlreadyApplied,true);
    		
    		// Try again by marking deal creation as false
    		wrapper.accounts[0].dealAlreadyApplied = false;
    		try{
    			wrapper	= ChainOpportunityController.applyDeals(JSON.Serialize(wrapper.accounts),opp.Id);
    			System.assertEquals(0,1,'Exception was not thrown as expected on recreation');
    		}catch(Exception e){
    			
    		}
    		
    	Test.stopTest();
    	
    	List<Opportunity> opps = [Select Id from Opportunity Where recordType.developerName = 'DE_Opportunity'];
    	List<Opportunity_Quote__c> quote = [Select Id from Opportunity_Quote__c where recordType.developerName = 'DE_Opportunity_Quote'];
    	
    	System.assertEquals(opps.size(),1);
    	System.assertEquals(quote.size(),1);
    }
    
    @isTest
    public static void testApplyDealAsynchronous(){
    	List<Account> accParent = [Select Id from Account where type = 'Group'];
    	Country__c ger			= [Select Id,Name,CurrencyISOCode from Country__c where name = 'Germany'];
    	List<Account> accList= UnitTestDataFactory.createAccounts(2,ger,'DE_Account');
    	accList[0].parentId = accParent[0].Id;
    	accList[0].type		= 'Branch';
    	insert accList;
    	
    	Opportunity opp = [Select Id,StageName from Opportunity where recordtype.developerName = 'Chain_Opportunity'];
    	opp.stageName = 'Closed Won';
    	update opp;
    	
    	ChainOpportunityController.ResultWrapper wrapper = ChainOpportunityController.fetchBranches(opp.Id);
    	
    	Test.startTest(); 		
    		wrapper.accounts[0].isSelected 	= true;
    		wrapper.accounts[1].isSelected	= true;
    		wrapper	= ChainOpportunityController.applyDeals(JSON.Serialize(wrapper.accounts),opp.Id);	
    		System.assertEquals(wrapper.accounts[0].dealAlreadyApplied,true);
    	Test.stopTest();
    	
    	List<Opportunity> opps = [Select Id from Opportunity Where recordType.developerName = 'DE_Opportunity'];
    	List<Opportunity_Quote__c> quote = [Select Id from Opportunity_Quote__c where recordType.developerName = 'DE_Opportunity_Quote'];
    	
    	System.assertEquals(opps.size(),2);
    	System.assertEquals(quote.size(),2);
    }
}