force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ResultWrapperTest.cls
@isTest
private class ResultWrapperTest {
    @isTest
    static void testParse() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c c = UnitTestDataFactory.createCountry('DE','Germany', 'EUR');
        Company__c com = UnitTestDataFactory.createCompany('testcompany', 'DE', c);
        List<Account> accList = UnitTestDataFactory.createAccounts(1,c,'DE_Account');
        insert accList;

        ResultWrapper res = new ResultWrapper(true);
        res.Id = accList[0].Id;
        res.UserMessage = 'Test Message';

        String resJson = Json.Serialize(res);

        Test.startTest();
            ResultWrapper parsedRes = ResultWrapper.parse(resJson);
        Test.stopTest();

        System.assertEquals('Test Message', parsedRes.UserMessage, 'Parsing failed!');
    }

    @isTest
    static void testParse_Negative() {
        Test.startTest();
            ResultWrapper parsedRes = ResultWrapper.parse('');
        Test.stopTest();

        System.assertEquals(null, parsedRes, 'Parsed result should be null');
    }

    @isTest
    static void testConstructor() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c c = UnitTestDataFactory.createCountry('DE','Germany', 'EUR');
        Company__c com = UnitTestDataFactory.createCompany('testcompany', 'DE', c);
        List<Account> accList = UnitTestDataFactory.createAccounts(1,c,'DE_Account');
        insert accList;
        
        Group g = new Group();
        g.Name = 'test queue';
        insert g;
        
        Test.startTest();
            ResultWrapper res = new ResultWrapper(true);
            res.Id = accList[0].Id;
        	res.OwnerId = g.Id;
        	res.QueueId = g.Id;
            res.UserMessage = 'Test Message';
            res.Error = '';
            res.Success = true;
            res.UserMessage = '';
        Test.stopTest();
    }
}