force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event/recordTypes/DE_Event.recordType-meta.xml
<RecordType>
    <fullName>DE_Event</fullName>
    <active>true</active>
    <label>DE Event</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/DE_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>DE_Opportunity</fullName>
    <active>true</active>
    <businessProcess>DE Sales Process</businessProcess>
    <label>DE Opportunity</label>
</RecordType>

force-app/main/default/classes/UnitTestClsEventTriggerProcessor.cls
@isTest
public class UnitTestClsEventTriggerProcessor {
    
    @testSetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        
        // create business configs
        List<Business_Config__c> configs = new List<Business_Config__c>();
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','requiredProbabilityForCEStage','20', null,'Generic_Activity',True,True));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','oppContactEstablishedStageName','Contact Established', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','requiredProbabilityForOpenStage','5', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','oppOpenStageName','Open', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','CEAcitvitySubject','Call - Decision maker reached', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','openAcitvitySubject','Call - Employee reached,Call - Nobody reached', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','taskTypes','Call', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','taskStatus','Completed', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','eventTypes','Meeting', null,'Generic_Activity',True,false));
        insert configs;
        
    	Country__c testCountry = UnitTestDataFactory.createCountry('DE', 'Germany', 'EUR');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('Lieferheld', 'Lieferheld', testCountry);
        insert testCompany;
        List<Account> accounts 	= UnitTestDataFactory.createAccounts(1, testCountry, 'DE_Account');
        insert accounts;
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accounts, 1, 'DE_Opportunity', Date.today().addMonths(2));
        opportunities[0].stageName = 'New';
        insert opportunities;
    }
    
    @isTest
    public static void testOpportunityStageUpdate(){   
        List<Opportunity> opportunities = [Select Id from Opportunity];
        Test.startTest();
        	Event evt  = new Event(Subject = 'Email', Type = 'Meeting', whatId = opportunities[0].id, 
        				description = 'test it', StartDateTime = DateTime.now(), EndDateTime = Datetime.now(),
        				recordtypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Event'));
        	insert evt;
        Test.stopTest();
        
        List<Opportunity> opps = [Select Id from Opportunity where stageName = 'Contact Established'];
        system.assertEquals(1,opps.size());	
    }
}