force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FP_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Global Sales Process</businessProcess>
    <label>FP Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/FP_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity_Quote</fullName>
    <active>true</active>
    <label>FP Opportunity Quote</label>
</RecordType>

force-app/main/default/classes/UnitTestUniversalSendEmailController.cls
@isTest
public class UnitTestUniversalSendEmailController {
	
    @TestSetup
    static void setup() {
        
        //Country__c testCountry = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'HKD');
        //insert testCountry;	
        Country__c testCountry = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'HKD');
        insert testCountry;
        RecordType testAccountRecordType = UnitTestDataFactory.getRecordType('FP_Account');
        RecordType testOpptyQuoteRecordType = UnitTestDataFactory.getRecordType('FP_Opportunity_Quote');
        List<RecordType__c> customSettings = new List<RecordType__c>();
        customSettings.add(new RecordType__c(Name = testAccountRecordType.Id,
                                                     Value__c = 'FP_Account'));
        customSettings.add(new RecordType__c(Name = testOpptyQuoteRecordType.Id,
                                                     Value__c = 'FP_Opportunity_Quote'));
		insert customSettings;
        RecordType__c additionalSetting = new RecordType__c(Name = 'FP_Account',
                                                     Value__c = customSettings[0].Id); 
        insert additionalSetting;
        Account testAccount = UnitTestDataFactory.createAccount('testacc', testCountry, 'FP_Account');
        testAccount.Phone = '+85265541700';
        insert testAccount;
        Opportunity testOpp = UnitTestDataFactory.createOpportunity('test',testAccount,'FP_Opportunity', Date.today());
        insert testOpp;
        Business_Config__c testConfig = UnitTestDataFactory.createBusinessConfig('UniversalSendSmsButtonProperties', 'Process', 'Opportunity_Quote__c::FP_Opportunity_Quote', 'google.com', String.valueOf(testCountry.Id), 'Global_Config', true, false);                        
       	insert testConfig;
        List<Opportunity_Quote__c> testQuote = UnitTestDataFactory.createOpportunityQuotes(testOpp, 1, 'FP_Opportunity_Quote', 'Draft', 'test description', 100.00, 110.00, '','',10.00);
        insert testQuote;
        
    }
    
    @isTest
    static void positiveScenarioTest(){
        
        Test.startTest();
        Opportunity_Quote__c quote = [SELECT Id FROM Opportunity_Quote__c LIMIT 1];
        String testResult = UniversalSendEmailButton_AuraController.getDestination(quote.Id);
        system.assertEquals('google.com', testResult);
        Test.stopTest();
    }
}