force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <description>SP-168: new Object for storing all the Additional charges and asset during Contract creation.</description>
    <label>Additional Charges</label>
    <nameField>
        <displayFormat>add-{00000}</displayFormat>
        <label>Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_List_Product_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/recordTypes/FP_Additional_Charges.recordType-meta.xml
<RecordType>
    <fullName>FP_Additional_Charges</fullName>
    <active>true</active>
    <label>FP Additional Charges</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stock Item currently assigned to this Asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New from manufacturer, A1 - New used, B - Used few scratches, A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/N</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Yogiyo Stock Item, FI Stock Item, SE Stock Item</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>DH AU Asset</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Ordered, New - In Stock, Assigned, In Shipping, Delivered, Retour in Progress, Lost, Returned - at Manufacturer, Recycled, Damaged, Writeoff, Tested, Returned - In Stock, Awaiting Delivery/In Shipment, In Stock, Technical Issue, Exchange Requested, Takeov</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/No longer usable</value>
        </filterItems>
        <infoMessage>In stock devices</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Asset Assignment</relationshipLabel>
    <relationshipName>Asset_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/FP_Asset.recordType-meta.xml
<RecordType>
    <fullName>FP_Asset</fullName>
    <active>true</active>
    <label>FP Asset</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Consignment__c/Consignment__c.object-meta.xml
<CustomObject>
    <description>A Consignment is the parent of Stock Items, therefore 1 Consignment can have many Stock items eg, Devices</description>
    <label>Consignment</label>
    <nameField>
        <displayFormat>C{00000}</displayFormat>
        <label>Consignment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/FP_Contact.recordType-meta.xml
<RecordType>
    <fullName>FP_Contact</fullName>
    <active>true</active>
    <label>FP Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/FP_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Product_Group</fullName>
    <active>true</active>
    <label>FP List_Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_List_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Group__c</fullName>
    <description>this information gives you to which product group this product belongs</description>
    <label>List Product Group</label>
    <referenceTo>List_Product_Group__c</referenceTo>
    <relationshipName>Id_List_Price_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/FP_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>FP_List_Product_Price</fullName>
    <active>true</active>
    <label>FP List Product Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FP_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Global Sales Process</businessProcess>
    <label>FP Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <description>Determines the quote type to be selected</description>
    <label>Quote Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/FP_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity_Quote</fullName>
    <active>true</active>
    <label>FP Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <description>Items that were or are are held in stock</description>
    <label>Stock Item</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Consignment__c.field-meta.xml
<CustomField>
    <fullName>Consignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A Consignment is the parent of Stock Items, therefore 1 Consignment can have many Stock items eg, Devices</description>
    <label>Consignment</label>
    <referenceTo>Consignment__c</referenceTo>
    <relationshipLabel>Stock Items</relationshipLabel>
    <relationshipName>Stock_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/recordTypes/UK_Stock_Item.recordType-meta.xml
<RecordType>
    <fullName>UK_Stock_Item</fullName>
    <active>true</active>
    <label>UK Stock Item</label>
</RecordType>

force-app/main/default/classes/UnitTestGenericCustomPicklist.cls
/*
@author : Aleksejs Jedamenko
@reviewer : 
@creation : 22.10.2019
*/
/**
 * This class contains unit tests for GenericCustomPicklist_AuraController class
 *
 * GenericCustomPicklist_AuraController contains 2 aura enabled methods which are tested here separately. 
 * for both methods we test positive an negative scenario
 */
@isTest
public class UnitTestGenericCustomPicklist {
	
    @testSetup 
    static void setup() {
    	
    	Country__c testCountry = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'HKD');
        insert testCountry;
        RecordType testAccountRecordType = UnitTestDataFactory.getRecordType('FP_Account');
        RecordType testOpptyQuoteRecordType = UnitTestDataFactory.getRecordType('FP_Opportunity_Quote');
        RecordType testContactRecordType = UnitTestDataFactory.getRecordType('FP_Contact');
        RecordType testOpptyRecordType = UnitTestDataFactory.getRecordType('FP_Opportunity');
        RecordType testStockItemRecordType = UnitTestDataFactory.getRecordType('UK_Stock_Item');
        RecordType testAssetRecordType = UnitTestDataFactory.getRecordType('FP_Asset');
        RecordType testProductGroupRecordType =  UnitTestDataFactory.getRecordType('FP_List_Product_Group');
        RecordType testProductPriceRecordType =  UnitTestDataFactory.getRecordType('FP_List_Product_Price');
        RecordType testAdditionalChargesRecordType =  UnitTestDataFactory.getRecordType('FP_Additional_Charges');
        system.debug('record type id: '+testAdditionalChargesRecordType.Id);
        List<RecordType__c> customSettings = new List<RecordType__c>();
        customSettings.add(new RecordType__c(Name = testAccountRecordType.Id,
                                                     Value__c = 'FP_Account'));
        customSettings.add(new RecordType__c(Name = testOpptyQuoteRecordType.Id,
                                                     Value__c = 'FP_Opportunity_Quote'));
        customSettings.add(new RecordType__c(Name = testContactRecordType.Id,
                                                     Value__c = 'FP_Contact'));
        customSettings.add(new RecordType__c(Name = testOpptyRecordType.Id,
                                                     Value__c = 'FP_Opportunity'));
        customSettings.add(new RecordType__c(Name = testStockItemRecordType.Id,
                                                     Value__c = 'UK_Stock_Item'));
        customSettings.add(new RecordType__c(Name = testAssetRecordType.Id,
                                                     Value__c = 'FP_Asset'));
        customSettings.add(new RecordType__c(Name = testProductGroupRecordType.Id,
                                                     Value__c = 'FP_List_Product_Group'));
        customSettings.add(new RecordType__c(Name = testProductPriceRecordType.Id,
                                                     Value__c = 'FP_List_Product_Price'));
        customSettings.add(new RecordType__c(Name = testAdditionalChargesRecordType.Id,
                                                     Value__c = 'FP_Additional_Charges'));
		insert customSettings;
        List<RecordType__c> additionalSettings = new List<RecordType__c>();
        additionalSettings.add(new RecordType__c(Name = 'FP_Account',
                                                     Value__c = customSettings[0].Id));
        insert additionalSettings;
        List<Account> testAccounts = new List<Account>();
        testAccounts.add(UnitTestDataFactory.createAccount('testacc', testCountry, 'FP_Account'));
        testAccounts[0].Phone = '+85265541700';
        insert testAccounts;
        Opportunity testOpp = UnitTestDataFactory.createOpportunity('test',testAccounts[0],'FP_Opportunity', Date.today()); 
        testOpp.Business_Type__c = 'New Business';
        insert testOpp;
        List<Contact> testContacts1 = UnitTestDataFactory.createContacts(testAccounts, 'TestSoname1','TestName1', 'Mr.','Owner', 1, 'testcontact1', 'FP_Contact'); 
        List<Contact> testContacts2 = UnitTestDataFactory.createContacts(testAccounts, 'TestSoname2','TestName2', 'Mr.','Manager', 1, 'testcontact2', 'FP_Contact');
        testContacts1.addAll(testContacts2);
        insert testContacts1;
        List<Business_Config__c> dcList = new List<Business_Config__c>();
        dcList.add(UnitTestDataFactory.createBusinessConfig('CustomPicklistSettings', 'Process', 'ProductForAdditionalCharges', 
        '{"fieldToDisplay": "Displayed_Name__c","fieldToUpdate": "Product__c","picklistCustomLabel": "Custom_Picklist_Product_Title", "isPleaseSelectOptionDisplayed": true, "isNoneOptionDisplayed": false, "isMessageDisplayed": true, "messageTitleCustomLabel": "Custom_Picklist_Product_Messege_Title", "messageBodyCustomLabel" : "Custom_Picklist_Product_Message","messageSeverity" : "warning","SOQLQuery" : "Select id, Displayed_Name__c,Id_List_Product_Group__r.name from List_Product_Price__c where RecordType.Name = \'FP List Product Price\'"}', String.valueOf(testCountry.Id), 'FP_Additional_Charges', true, true));
        dcList.add(UnitTestDataFactory.createBusinessConfig('populateFieldsAfterProductUpdate','Process','ListProductPriceRecordType','FP_List_Product_Price', String.valueOf(testCountry.Id), 'FP_Additional_Charges', true, true));
        insert dcList; 
        List<Opportunity_Quote__c> testQuote = UnitTestDataFactory.createOpportunityQuotes(testOpp, 1, 'FP_Opportunity_Quote', 'Draft', 'test description', 100.00, 110.00, '','',10.00);
        testQuote[0].Quote_Type__c = 'Contract Amendment'; 
        testQuote[0].RecordType = testOpptyQuoteRecordType; 
        insert testQuote;
        List<Consignment__c> testConsigments = UnitTestDataFactory.createConsignments(1, false, 'Ordered', 'Supplier A', 'google.com');
        insert testConsigments;
        List<Stock_Item__c> testStockItems = UnitTestDataFactory.createStockItems(2, 'UK_Stock_Item',testAccounts[0] , testConsigments[0], 'A - New', date.today().addDays(-2),date.today().addDays(-1), date.today().addDays(-10),
        '2445452', '+852342232333', 'SKT', 'Ordered', 'test');
        insert testStockItems;
        List<Asset__c> testAssets = UnitTestDataFactory.createAssets(1, testAccounts[0], testOpp, date.today().addDays(-1), true, testStockItems[0], testStockItems[1], 'FP_Asset',
        '2242342323', '2', '2',  date.today().addDays(-2), date.today().addDays(-2), 'En Route', true, 'Delivery refused', 'test info', 'test info', 
        'Invalid', date.today().addDays(2), 'DH Staff', '2342234342', 'Arrange Pick up');
        insert testAssets;
        Company__c testCompany = UnitTestDataFactory.createCompany('Tset Company', '1111111', testCountry);
        insert testCompany;
        List<List_Product_Group__c> testProductGroup = UnitTestDataFactory.createProductGroups(testCompany, testCountry, 1, 'FP_List_Product_Group');
        insert testProductGroup; 
        List_Product_Price__c testProductPrice = UnitTestDataFactory.createProduct(testCompany, testCountry, 'LPP-999999', testProductGroup[0].Id, 'FP_List_Product_Price', 6, true, 100.00, 1, false, 25.00);
        testProductPrice.Displayed_Name__c = 'test value';
        insert testProductPrice;
        List<Additional_Charges__c> testCharges = UnitTestDataFactory.createAdditionalChargesWithRecordType(testAccounts[0], testAssets[0], testOpp, testQuote[0], testProductPrice, testProductGroup[0] ,
           '25' , 1, 100.00, 10, 100.00, 1, testAdditionalChargesRecordType.Id, date.today().addDays(3));
        insert testCharges;
       
    }
    
    @isTest
    static void positiveScenarioGetDataTest(){
        
        List<Additional_Charges__c> additionalCharges = [SELECT Id, RecordTypeId, Product__c FROM Additional_Charges__c LIMIT 1];
        Test.startTest();
        String stringifiedResult = GenericCustomPicklist_AuraController.getDataFromBusinessConfig('ProductForAdditionalCharges', additionalCharges[0].Id, 'Additional_Charges__c');
        GenericCustomPicklist_AuraController.BusinessConfigWrapperToSend resultWrapper = (GenericCustomPicklist_AuraController.BusinessConfigWrapperToSend)JSON.deserialize(stringifiedResult, GenericCustomPicklist_AuraController.BusinessConfigWrapperToSend.class);
        Test.stopTest();
        system.assertEquals('Displayed_Name__c',resultWrapper.fieldToDisplay);
        system.assertEquals('Product__c',resultWrapper.fieldToUpdate);
        system.assertEquals('Custom_Picklist_Product_Title',resultWrapper.picklistCustomLabel);
        system.assertEquals('Custom_Picklist_Product_Messege_Title',resultWrapper.messageTitleCustomLabel);
        system.assertEquals('Custom_Picklist_Product_Message',resultWrapper.messageBodyCustomLabel);
        system.assertEquals('warning',resultWrapper.messageSeverity);
        system.assertEquals(additionalCharges[0].Product__c, resultWrapper.currentValue);
        system.assert(resultWrapper.isPleaseSelectOptionDisplayed);
        system.assert(resultWrapper.isMessageDisplayed);
        system.assert(!resultWrapper.isNoneOptionDisplayed);
        system.assert(resultWrapper.picklistData.size()>0);

    }
    
    @isTest
    static void negativeScenarioGetDataTest(){
    	
        List<Business_Config__c> businessConfig = [SELECT Id FROM Business_Config__c LIMIT 1];
        delete businessConfig;
        List<Additional_Charges__c> additionalCharges = [SELECT Id, RecordTypeId, Product__c FROM Additional_Charges__c LIMIT 1];
        Test.startTest();
        String stringifiedResult = GenericCustomPicklist_AuraController.getDataFromBusinessConfig('ProductForAdditionalCharges', additionalCharges[0].Id, 'Additional_Charges__c');
        Test.stopTest();
        JSONParser parser = JSON.createParser(stringifiedResult);
        parser.nextToken();
        parser.nextToken();
       	system.assertEquals('error',parser.getText());
        parser.nextToken();
        system.assertEquals(System.Label.Custom_Picklist_No_Business_Config_Error_Message,parser.getText());
    }
    
    @isTest
    static void positiveScenarioSaveValue(){
     
         List<Additional_Charges__c> additionalCharges = [SELECT Id, RecordTypeId, Product__c FROM Additional_Charges__c LIMIT 1];
         Test.startTest();
         String saveResult = GenericCustomPicklist_AuraController.saveSelectedValue('test value', 'Product__c', additionalCharges[0].Id, 'Additional_Charges__c');
         List<Additional_Charges__c> additionalChargesAfterUpdate = [SELECT Id, RecordTypeId, Product__c, Product_Group__c FROM Additional_Charges__c LIMIT 1];
         Test.stopTest();
         system.assertEquals('OK',saveResult);
         system.assertEquals('Test_Product_Group_0', additionalChargesAfterUpdate[0].Product_Group__c);
    }
    
    @isTest
    static void negativeScenarioSaveValue(){
     
         List<Additional_Charges__c> additionalCharges = [SELECT Id, RecordTypeId, Product__c FROM Additional_Charges__c LIMIT 1];
         String testRecordId = additionalCharges[0].Id;
         delete additionalCharges;
         Test.startTest();
         String saveResult = GenericCustomPicklist_AuraController.saveSelectedValue('test value', 'Product__c', testRecordId, 'Additional_Charges__c');
         Test.stopTest();
         system.assertNotEquals('OK',saveResult);
    }
}