force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stock Item currently assigned to this Asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New from manufacturer, A1 - New used, B - Used few scratches, A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/N</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Yogiyo Stock Item, FI Stock Item, SE Stock Item</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>DH AU Asset</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Ordered, New - In Stock, Assigned, In Shipping, Delivered, Retour in Progress, Lost, Returned - at Manufacturer, Recycled, Damaged, Writeoff, Tested, Returned - In Stock, Awaiting Delivery/In Shipment, In Stock, Technical Issue, Exchange Requested, Takeov</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/No longer usable</value>
        </filterItems>
        <infoMessage>In stock devices</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Asset Assignment</relationshipLabel>
    <relationshipName>Asset_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/FP_Asset.recordType-meta.xml
<RecordType>
    <fullName>FP_Asset</fullName>
    <active>true</active>
    <label>FP Asset</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FP_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Global Sales Process</businessProcess>
    <label>FP Opportunity</label>
</RecordType>

force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <description>Items that were or are are held in stock</description>
    <label>Stock Item</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/recordTypes/FP_Stock_Item.recordType-meta.xml
<RecordType>
    <fullName>FP_Stock_Item</fullName>
    <active>true</active>
    <label>FP Stock Item</label>
</RecordType>

force-app/main/default/classes/ReplacementLightningControllerTest.cls
@isTest
public class ReplacementLightningControllerTest {
	
    @isTest
    private static void test_getCurrentData() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c c = UnitTestDataFactory.createCountry('HK','Hong Kong', 'HKD');
        Company__c com = UnitTestDataFactory.createCompany('testcompany', 'HK', c);

        insert new List<sObject> { c,com };

        List<Account> accList = UnitTestDataFactory.createAccounts(1,c,'FP_Account');
        accList[0].Phone = '+85212345678';
        insert accList;
        
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accList, 1, 'FP_Opportunity', Date.today());
        Database.insert(opportunities);
        
        List<Stock_Item__c> stockItems = UnitTestDataFactory.createStockItems(2,'FP_Stock_Item', accList[0], null, 'A1 - New used', Date.today(), Date.today().addDays(10), Date.today().addDays(-30), '1234567890', '1234567890', 'HK Telekom', 'Ordered', 'Other');
        insert stockItems;
        
        List<Asset__c> assets = UnitTestDataFactory.createAssets(2, accList[0], opportunities[0], Date.today().addDays(-10), true, stockItems[0],null, 'FP_Asset','12345674', '1', '1', Date.today(), Date.today(), 'En Route', true, 'Exchanged', 'Shared Information', 'Take over Information', 'New - Awaiting Shipping', Date.today().addDays(5), 'retourShippingCompany', '552211385', 'Owner sends Terminal');   
        insert assets;
        
        Test.startTest();
        	String json = ReplacementLightningController.getCurrentData(assets[0].Id);
        Test.stopTest();
        
        System.assertEquals(true, !String.isEmpty(json), 'Json string expected');
    }
    
    @isTest
    private static void test_startReplacement() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c c = UnitTestDataFactory.createCountry('HK','Hong Kong', 'HKD');
        Company__c com = UnitTestDataFactory.createCompany('testcompany', 'HK', c);

        insert new List<sObject> { c,com };

        List<Account> accList = UnitTestDataFactory.createAccounts(1,c,'FP_Account');
        accList[0].Phone = '+85212345678';
        insert accList;
        
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accList, 1, 'FP_Opportunity', Date.today());
        Database.insert(opportunities);
        
        List<Stock_Item__c> stockItems = UnitTestDataFactory.createStockItems(2,'FP_Stock_Item', accList[0], null, 'A1 - New used', Date.today(), Date.today().addDays(10), Date.today().addDays(-30), '1234567890', '1234567890', 'HK Telekom', 'Ordered', 'Other');
        insert stockItems;
        
        List<Asset__c> assets = UnitTestDataFactory.createAssets(2, accList[0], opportunities[0], Date.today().addDays(-10), true, stockItems[0],null, 'FP_Asset','12345674', '1', '1', Date.today(), Date.today(), 'En Route', true, 'Exchanged', 'Shared Information', 'Take over Information', 'New - Awaiting Shipping', Date.today().addDays(5), 'retourShippingCompany', '552211385', 'Owner sends Terminal');   
        insert assets;
        
        Test.startTest();
        	String json = ReplacementLightningController.startReplacement(assets[0].Id);
        Test.stopTest();
        
        System.assertEquals(true, !String.isEmpty(json), 'Json string expected');
    }
   
}