force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/Additional_Charges__c/Additional_Charges__c.object-meta.xml
<CustomObject>
    <description>SP-168: new Object for storing all the Additional charges and asset during Contract creation.</description>
    <label>Additional Charges</label>
    <nameField>
        <displayFormat>add-{00000}</displayFormat>
        <label>Additional Charges Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Charges__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_List_Product_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <label>Id Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Additional Charges</relationshipLabel>
    <relationshipName>Additional_Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Charges__c/recordTypes/PY_Additional_Charges.recordType-meta.xml
<RecordType>
    <fullName>PY_Additional_Charges</fullName>
    <active>true</active>
    <description>Record type for Pedidos Ya and in future to be global for all countries</description>
    <label>PY Additional Charges</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity relating to this Asset</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/PY_Restaurant_Operations.recordType-meta.xml
<RecordType>
    <fullName>PY_Restaurant_Operations</fullName>
    <active>true</active>
    <businessProcess>PY General Process</businessProcess>
    <label>PY Restaurant Operations</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/PY_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>PY_List_Product_Group</fullName>
    <active>true</active>
    <description>Record type for Pedidos Ya and in future to be global for all countries</description>
    <label>PY List_Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type to determine the Asset Type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Online Marketing</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Premium placement</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Dish Level Photoshoot</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Car Leasing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Premium placement - 1 Month</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Asset__c.field-meta.xml
<CustomField>
    <fullName>Requires_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a product requires an asset</description>
    <label>Requires Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Branding__c.field-meta.xml
<CustomField>
    <fullName>Requires_Branding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Branding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/UK_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>UK_List_Product_Price</fullName>
    <active>true</active>
    <label>UK List Product Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PY_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>PY_Opportunity</fullName>
    <active>true</active>
    <businessProcess>PY Sales Process</businessProcess>
    <label>PY Opportunity</label>
</RecordType>

force-app/main/default/classes/UnitTestBatchAssetMigration.cls
/**
 * Created by w.novoa on 19.11.2018.
 */

@IsTest
private class UnitTestBatchAssetMigration {

    private static Country__c c;
    private static Account  acc;
    private static Opportunity  opp;
    private static Company__c com;

    @testsetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();

        c = UnitTestDataFactory.createCountry('AR', 'Argentina', 'ARS');
        insert c;

        acc = UnitTestDataFactory.createAccount('TestAccount', c, 'PY_Account');
        insert acc;

        com = UnitTestDataFactory.createCompany('PedidosYA', 'PY', c);
        insert com;

        opp = UnitTestDataFactory.createOpportunity('TestOpp123', acc, 'PY_Opportunity', Date.today());
        insert  opp;

        List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com, c , 'Apple', 'PY_List_Product_Group');
        List_Product_Group__c lpg1 = UnitTestDataFactory.createProductGroup(com, c , 'Menu Printing', 'PY_List_Product_Group');
        insert new List<SObject> {lpg, lpg1};

        List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com, c , 'Menu Printing with website', lpg.id, 'UK_List_Product_Price', 1, true, 100, 1, false, 20);
        lpp.product_type__c = 'Menu Printing';
        lpp.Requires_Branding__c = true;
        lpp.Requires_Asset__c = true;

        insert new List<sobject> {lpp};

        Additional_Charges__c addCharges = new Additional_Charges__c();
        addCharges.Id_Opportunity__c = opp.id;
        addCharges.Id_List_Product_Price__c = lpp.id;
        addCharges.Id_Account__c = acc.id;
        addCharges.RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('PY_Additional_Charges');

        insert addCharges;

        case caso = new case();

        caso.AccountId = acc.id;
        caso.Opportunity__c = opp.id;
        caso.Type = 'Onboarding';
        caso.RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('PY_Restaurant_Operations');

        insert caso;

    }

    @IsTest
    static void testBehavior() {

        Test.startTest();
        Id batchJobId = Database.executeBatch(new BatchAssetMigration(), 200);
        Test.stopTest();

        system.assert([Select id From Asset__c].size()>0);
    }
}