force-app/main/default/objects/Account/recordTypes/SE_Account.recordType-meta.xml
<RecordType>
    <fullName>SE_Account</fullName>
    <active>true</active>
    <description>Sweden Account</description>
    <label>SE Account</label>
</RecordType>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/SE_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>SE_List_Product_Group</fullName>
    <active>true</active>
    <label>SE List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type to determine the Asset Type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Online Marketing</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Premium placement</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Dish Level Photoshoot</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Car Leasing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Premium placement - 1 Month</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/SE_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>SE_List_Product_Price</fullName>
    <active>true</active>
    <label>SE List Product Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/SE_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>SE_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sweden Sales Process</businessProcess>
    <description>Sweden Opportunity</description>
    <label>SE Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/SE_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>SE_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>SE Opportunity Line Item</label>
</RecordType>

force-app/main/default/objects/Trigger_Manager__c/Trigger_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Manager</label>
</CustomObject>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_AddressDetail_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_AddressDetail_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate AddressDetail Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CustomReport_AuraControllerTest.cls
/**
* @author Mantas Jurkunas
* @date 31.07.2019
*
* @description Test class for CustomReport_AuraController
*/
@IsTest
private class CustomReport_AuraControllerTest {

    @TestSetup
    public static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountry = UnitTestDataFactory.createCountry('SE','Sweden', 'SEK');
        insert testCountry;

        Company__c com = UnitTestDataFactory.createCompany('Lieferheld', 'SE', testCountry);
        insert com;

        List<Account> accList= UnitTestDataFactory.createAccounts(5,testCountry,'SE_Account');
        for (Account acc: accList) { acc.Phone = '+461234567'; }
        insert accList;

        List<AddressDetail__c> allAddressDetails = new List<AddressDetail__c>();
        for (Account acc: accList) {
            allAddressDetails.addAll(UnitTestDataFactory.createAddressDetails(new List<String>{'Shipping Address', 'Billing Address', 'Restaurant Address'}, acc.Id));
        }
        Trigger_Manager__c tm = Trigger_Manager__c.getInstance();
        tm.Deactivate_AddressDetail_Trigger__c = true;
        upsert tm;
        insert allAddressDetails;

        List<Opportunity> oppList = UnitTestDataFactory.createOpportunities(accList,5,'SE_Opportunity',Date.today());
        insert oppList;

        List_Product_Group__c lpg1 = UnitTestDataFactory.createProductGroup(com,testCountry,'Setup Fee','SE_List_Product_Group');
        insert lpg1;

        List_Product_Price__c lpp1 = UnitTestDataFactory.createProduct(com,testCountry,'Super Hero Setup 1',lpg1.Id,'SE_List_Product_Price',1,true,100,1,false,null);
        lpp1.Product_Type__c = 'Dish Level Photoshoot';
        insert lpp1;

        List<Opportunity_Line_Item__c> opi = new List<Opportunity_Line_Item__c>();
        for (Opportunity opp: oppList) {
            opi.addAll(UnitTestDataFactory.createOpportunityLineItems(opp, lpg1.Id, lpp1.Id, 5, false, 'SE_Opportunity_Line_Item', 1, '10', 299.0, 1, 1, 'Product'));
        }
        insert opi;
    }

    /**
     * @description  Testing if the correct number of report lines is being generated, it is dependent on the Field sets in the org
     */
    @IsTest
    public static void test_generateReportWIthMultipleChildren() {
        CustomReport_AuraController.ReportRelationDefinition definitionAccount = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionAddress= new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunity = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunityLineItem = new CustomReport_AuraController.ReportRelationDefinition();
        definitionOpportunityLineItem.objectName = Opportunity_Line_Item__c.getSObjectType().getDescribe().getLocalName();
        definitionOpportunityLineItem.parentLookupField = Opportunity_Line_Item__c.Id_Opportunity__c.getDescribe().getLocalName();
        definitionOpportunityLineItem.fieldSetName = 'KR_CustomReport';

        definitionOpportunity.objectName = Opportunity.getSObjectType().getDescribe().getLocalName();
        definitionOpportunity.parentLookupField = Opportunity.AccountId.getDescribe().getLocalName();
        definitionOpportunity.fieldSetName = 'KR_CustomReport';
        definitionOpportunity.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunityLineItem};

        definitionAddress.objectName = AddressDetail__c.getSObjectType().getDescribe().getLocalName();
        definitionAddress.parentLookupField = AddressDetail__c.Account__c.getDescribe().getLocalName();
        definitionAddress.fieldSetName = 'OptTriggerQuery';

        definitionAccount.objectName = Account.getSObjectType().getDescribe().getLocalName();
        definitionAccount.fieldSetName = 'OptTriggerQuery';
        definitionAccount.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunity, definitionAddress};
        CustomReport_AuraController.ReportData reportData = CustomReport_AuraController.loadReportData(JSON.serialize(definitionAccount));
        System.assertEquals(375, reportData.data.size());
    }

    /**
     * @description  Testing if the correct number of report lines is being generated with one row stacked, it is dependent on the Field sets in the org
     */
    @IsTest
    public static void test_generateReportWithStackedRow() {
        CustomReport_AuraController.ReportRelationDefinition definitionAccount = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionAddress= new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunity = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunityLineItem = new CustomReport_AuraController.ReportRelationDefinition();
        definitionOpportunityLineItem.objectName = Opportunity_Line_Item__c.getSObjectType().getDescribe().getLocalName();
        definitionOpportunityLineItem.parentLookupField = Opportunity_Line_Item__c.Id_Opportunity__c.getDescribe().getLocalName();
        definitionOpportunityLineItem.fieldSetName = 'KR_CustomReport';

        definitionOpportunity.objectName = Opportunity.getSObjectType().getDescribe().getLocalName();
        definitionOpportunity.parentLookupField = Opportunity.AccountId.getDescribe().getLocalName();
        definitionOpportunity.fieldSetName = 'KR_CustomReport';
        definitionOpportunity.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunityLineItem};

        definitionAddress.objectName = AddressDetail__c.getSObjectType().getDescribe().getLocalName();
        definitionAddress.parentLookupField = AddressDetail__c.Account__c.getDescribe().getLocalName();
        definitionAddress.fieldSetName = 'OptTriggerQuery';
        definitionAddress.stackValues = true;

        definitionAccount.objectName = Account.getSObjectType().getDescribe().getLocalName();
        definitionAccount.fieldSetName = 'OptTriggerQuery';
        definitionAccount.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunity, definitionAddress};
        CustomReport_AuraController.ReportData reportData = CustomReport_AuraController.loadReportData(JSON.serialize(definitionAccount));
        System.assertEquals(125, reportData.data.size());
    }

    /**
    * @description  Testing if the correct number of report lines is being generated with all rows stacked, it is dependent on the Field sets in the org
    */
    @IsTest
    public static void test_generateReportWIthAllStackedRows() {
        CustomReport_AuraController.ReportRelationDefinition definitionAccount = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionAddress= new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunity = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunityLineItem = new CustomReport_AuraController.ReportRelationDefinition();
        definitionOpportunityLineItem.objectName = Opportunity_Line_Item__c.getSObjectType().getDescribe().getLocalName();
        definitionOpportunityLineItem.parentLookupField = Opportunity_Line_Item__c.Id_Opportunity__c.getDescribe().getLocalName();
        definitionOpportunityLineItem.fieldSetName = 'KR_CustomReport';
        definitionOpportunityLineItem.stackValues = true;

        definitionOpportunity.objectName = Opportunity.getSObjectType().getDescribe().getLocalName();
        definitionOpportunity.parentLookupField = Opportunity.AccountId.getDescribe().getLocalName();
        definitionOpportunity.fieldSetName = 'KR_CustomReport';
        definitionOpportunity.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunityLineItem};
        definitionOpportunity.stackValues = true;

        definitionAddress.objectName = AddressDetail__c.getSObjectType().getDescribe().getLocalName();
        definitionAddress.parentLookupField = AddressDetail__c.Account__c.getDescribe().getLocalName();
        definitionAddress.fieldSetName = 'OptTriggerQuery';
        definitionAddress.stackValues = true;

        definitionAccount.objectName = Account.getSObjectType().getDescribe().getLocalName();
        definitionAccount.fieldSetName = 'OptTriggerQuery';
        definitionAccount.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunity, definitionAddress};
        definitionAccount.stackValues = true;
        CustomReport_AuraController.ReportData reportData = CustomReport_AuraController.loadReportData(JSON.serialize(definitionAccount));
        System.assertEquals(1, reportData.data.size());
    }

    /**
     * @description  Testing if the correct number of report lines is being generated
     */
    @IsTest
    public static void test_generateReport() {
        CustomReport_AuraController.ReportRelationDefinition definitionAccount = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionAddress= new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunity = new CustomReport_AuraController.ReportRelationDefinition();

        definitionOpportunity.objectName = Opportunity.getSObjectType().getDescribe().getLocalName();
        definitionOpportunity.parentLookupField = Opportunity.AccountId.getDescribe().getLocalName();
        definitionOpportunity.fieldSetName = 'KR_CustomReport';

        definitionAddress.objectName = AddressDetail__c.getSObjectType().getDescribe().getLocalName();
        definitionAddress.parentLookupField = AddressDetail__c.Account__c.getDescribe().getLocalName();
        definitionAddress.fieldSetName = 'OptTriggerQuery';

        definitionAccount.objectName = Account.getSObjectType().getDescribe().getLocalName();
        definitionAccount.fieldSetName = 'OptTriggerQuery';
        definitionAccount.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionOpportunity, definitionAddress};
        CustomReport_AuraController.ReportData reportData = CustomReport_AuraController.loadReportData(JSON.serialize(definitionAccount));
        System.assertEquals(75, reportData.data.size());
    }

    /**
     * @description  Testing if the correct number of report lines is being generated
     */
    @IsTest
    public static void test_generateReportWithLinearInheritance() {
        CustomReport_AuraController.ReportRelationDefinition definitionAccount = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionAddress = new CustomReport_AuraController.ReportRelationDefinition();
        CustomReport_AuraController.ReportRelationDefinition definitionOpportunity = new CustomReport_AuraController.ReportRelationDefinition();

        definitionOpportunity.objectName = Opportunity.getSObjectType().getDescribe().getLocalName();
        definitionOpportunity.parentLookupField = Opportunity.AccountId.getDescribe().getLocalName();
        definitionOpportunity.fieldSetName = 'KR_CustomReport';

        definitionAddress.objectName = AddressDetail__c.getSObjectType().getDescribe().getLocalName();
        definitionAddress.parentLookupField = AddressDetail__c.Account__c.getDescribe().getLocalName();
        definitionAddress.fieldSetName = 'OptTriggerQuery';

        definitionAccount.objectName = Account.getSObjectType().getDescribe().getLocalName();
        definitionAccount.fieldSetName = 'OptTriggerQuery';
        definitionAccount.children = new List<CustomReport_AuraController.ReportRelationDefinition>{definitionAddress, definitionOpportunity, definitionAddress};
        CustomReport_AuraController.ReportData reportData = CustomReport_AuraController.loadReportData(JSON.serialize(definitionAccount));
        System.assertEquals(225, reportData.data.size());
    }
}