force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/ActionItem__c/ActionItem__c.object-meta.xml
<CustomObject>
    <label>Action Item</label>
    <nameField>
        <label>Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Commission Upgrade</fullName>
            </value>
            <value>
                <fullName>Delivery Area</fullName>
            </value>
            <value>
                <fullName>Delivery Fee</fullName>
            </value>
            <value>
                <fullName>Delivery Time</fullName>
            </value>
            <value>
                <fullName>Exclusivity</fullName>
            </value>
            <value>
                <fullName>Fail Rate</fullName>
            </value>
            <value>
                <fullName>Joker</fullName>
            </value>
            <value>
                <fullName>Menu</fullName>
            </value>
            <value>
                <fullName>MOV</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Reviews</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Transmission Method</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/Platform_Country__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Platform Country</label>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/UnitTestCtrLinkActionItems.cls
/**
 * @description [ Test class for CtrLinkActionItems Class ]
 * Created by keerthan.tantry on 12/05/2020.
 */

@IsTest
private class UnitTestCtrLinkActionItems {

    @TestSetup static  void setup(){
        User testUser;
        Country__c country;
        List<Account> accounts;
        List<ActionItem__c  > actionItems;
        List<Platform_Country__c> platformCountries;
        Task objTask;
        UnitTestDataFactory.getRecordtypeValues();

        testUser = UnitTestDataFactory.createUser('Talabat Sales Team', 'talabattestuser@talabat.com', 'Talabat', 'AE');
        insert testUser;
        System.runAs(testUser) {
            platformCountries = createPlatformCountries();
            insert platformCountries;

            country = UnitTestDataFactory.createCountry('AE', 'United Arab Emirates', 'AED');
            insert country;

            accounts = UnitTestDataFactory.createAccounts(1, country, 'Talabat_Account');
            insert accounts;

            actionItems  = createActionItems(5,accounts[0]);
            insert actionItems;

            objTask = createTaskForActionItem(actionItems[0]);
            insert objTask;

        }
    }
    /**
    *
    * @description  [Create Action Item data]
    * @param noOfRecords [No of records to create]
    * @param objAccount [Account under which action items are created]
    *
    * @return [List of action items]
    */
    public static List<ActionItem__c> createActionItems(Integer noOfRecords, Account objAccount){
        List<ActionItem__c> actionItems = new List<ActionItem__c>();
        ActionItem__c obj;
        for(Integer i=0;i<noOfRecords;i++){
            obj  = new ActionItem__c();
            obj.Name = 'Action Item' + i;
            obj.Type__c = Constants.ACTION_ITEM_TYPE_COMMISSION_UPGRADE;
            obj.Start_Date__c  = System.today();
            obj.End_Date__c = System.today().addDays(10);
            obj.Account__c = objAccount.Id;
            actionItems.add(obj);
        }
        return actionItems;
    }
    /**
    * @description  [Create Task under Action Items ]
    * @param objActionItem [Action Item record ]
    * @return [Task record]
    */
    public static Task  createTaskForActionItem(ActionItem__c objActionItem){
        Task objTask = new Task();
        objTask.OwnerId = UserInfo.getUserId();
        objTask.WhatId = objActionItem.Id;
        objTask.RecordTypeId = LibRecordTypeHelper.getRecordTypeIdByDeveloperName(Constants.SOBJECT_TASK,Constants.TASK_RT_TALABAT_TASK);
        objTask.Subject = Constants.TASK_SUBJECT_CALL;
        objTask.Status = Constants.TASK_STATUS_NOT_STARTED;
        objTask.Priority = Constants.TASK_PRIORITY_NORMAL;
        return objTask;
    }
    /**
    *
    * @description  [Create Platform_Country__c test records ]
    * @return [List of Platform_Country__c records]
    */
    public static List<Platform_Country__c> createPlatformCountries(){
        List<Platform_Country__c> pcList =new List<Platform_Country__c>();
        pcList.add(new Platform_Country__c(name='TalabatPlatform',country__c='Kuwait,Bahrain,Saudi Arabia,Oman,Qatar,United Arab Emirates'));
        return  pcList;
    }


    @IsTest
    static void testGetActionItems() {
        List<ActionItem__c> actionItems = [SELECT ID,Account__c FROM ActionItem__c];
        List<Task> tasks = [SELECT  Id,WhatId FROM Task];

        Test.startTest();
           List<CtrLinkActionItems.ActionItemsWrapper> resList =   CtrLinkActionItems.getActionItems(tasks[0].Id);
           System.assert(!resList.isEmpty());
        Test.stopTest();
    }

    @IsTest
    static void testLinkActionItems() {
        List<ActionItem__c> actionItems = [SELECT ID,Account__c FROM ActionItem__c];
        List<Task> tasks = [SELECT  Id,Code__c,WhatId FROM Task];

        Test.startTest();
        CtrLinkActionItems.linkActionItems(tasks[0].Id,actionItems[1].Id);
        List<Task> tasks1  = [ SELECT Id,WhatId,Code__c FROM Task WHERE Code__c =:tasks[0].Code__c AND WhatId =:actionItems[1].Id    ];
        System.assert(!tasks1.isEmpty());
        //Cover isTaskAlreadyLinked upsert
        CtrLinkActionItems.linkActionItems(tasks[0].Id,actionItems[1].Id);
        Test.stopTest();
    }

    @IsTest
    static void testDelinkActionItems() {
        List<ActionItem__c> actionItems = [SELECT ID,Account__c FROM ActionItem__c];
        List<Task> tasks = [SELECT  Id,Code__c,WhatId FROM Task];

        Test.startTest();
        CtrLinkActionItems.delinkActionItems(tasks[0].Id,actionItems[0].Id);
        List<Task> tasks1  = [ SELECT Id,WhatId,Code__c FROM Task WHERE Code__c =:tasks[0].Code__c AND WhatId =:actionItems[1].Id    ];
        System.assert(tasks1.isEmpty());
        Test.stopTest();
    }
}