force-app/main/default/objects/Account/recordTypes/UK_Account.recordType-meta.xml
<RecordType>
    <fullName>UK_Account</fullName>
    <active>true</active>
    <label>UK Account</label>
</RecordType>

force-app/main/default/objects/Add_on_Service__c/Add_on_Service__c.object-meta.xml
<CustomObject>
    <description>Add-on Services for Restaurants like : WhiteLable website, Phone Ordering, Pick-up service etc.</description>
    <label>Add-on Service</label>
    <nameField>
        <displayFormat>AOS-{000000}</displayFormat>
        <label>Add-on Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Add-on Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Add_on_Service__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Add-on Services</relationshipLabel>
    <relationshipName>Add_on_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Add_on_Service__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Service End Date</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Add_on_Service__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Final Check</fullName>
            </value>
            <value>
                <fullName>Please Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Add_on_Service__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Cannot Contact</fullName>
            </value>
            <value>
                <fullName>Capacity - Competitors</fullName>
            </value>
            <value>
                <fullName>Capacity - Driver Issue</fullName>
            </value>
            <value>
                <fullName>Capacity - Order Volume</fullName>
            </value>
            <value>
                <fullName>Capacity - Own Website</fullName>
            </value>
            <value>
                <fullName>DH Delivery</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Legal Issue</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
            <value>
                <fullName>New Owner - New Contract</fullName>
            </value>
            <value>
                <fullName>New Owner - No New Contract</fullName>
            </value>
            <value>
                <fullName>No Delivery Service</fullName>
            </value>
            <value>
                <fullName>Not Enough Orders</fullName>
            </value>
            <value>
                <fullName>Not Interested in Product</fullName>
            </value>
            <value>
                <fullName>Onboarding Failure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment Issue</fullName>
            </value>
            <value>
                <fullName>Poor Performance</fullName>
            </value>
            <value>
                <fullName>Pricing - Admin Fee</fullName>
            </value>
            <value>
                <fullName>Pricing - Commission</fullName>
            </value>
            <value>
                <fullName>Pricing - Merchant Fee</fullName>
            </value>
            <value>
                <fullName>Pricing - Premium Placement</fullName>
            </value>
            <value>
                <fullName>Pricing - Setup Fee</fullName>
            </value>
            <value>
                <fullName>Product Change</fullName>
            </value>
            <value>
                <fullName>Product Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Add_on_Service__c/recordTypes/UK_Add_On.recordType-meta.xml
<RecordType>
    <fullName>UK_Add_On</fullName>
    <active>true</active>
    <label>UK Add On</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UnitTestBatchTerminateAddOns.cls
@isTest
public class UnitTestBatchTerminateAddOns {
    
    @testSetup static void setup() {
		Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Add_On_Service__c'});
		UnitTestDataFactory.getRecordtypeValues();

		Country__c uk = UnitTestDataFactory.createCountry('UK', 'United Kingdom', 'GBP');
		insert new List<Country__c> {uk};

		Business_Config__c b1 = UnitTestDataFactory.createBusinessConfig('BatchAddOnTermination', 'Process', 'terminateAddOns', 'true', uk.id, 'UK_Add_On', true, true);
		Business_Config__c b2 = UnitTestDataFactory.createBusinessConfig('BatchAddOnTermination', 'Process', 'expiredStatus', 'Expired', uk.id, 'UK_Add_On', true, false);
		Business_Config__c b3 = UnitTestDataFactory.createBusinessConfig('BatchAddOnTermination', 'Process', 'terminationStatus', 'Terminated', uk.id, 'UK_Add_On', true, false);
		insert new List<sObject> {b1, b2, b3};

		Account acc1 = UnitTestDataFactory.createAccount('BatchTestClassAccount1', uk, 'UK_Account');
		insert new List<Account> {acc1};

		insert new Add_On_Service__c(
		    Account_Name__c = acc1.Id,
		    RecordTypeId 	= mapRecordtypes.get('UK_Add_On').Id,
		    End_Date__c 	= Date.today(),
		    status__c		= 'Active'
		);

	}
	
	@isTest
	public static void testExpiredStatus(){
		Test.startTest();
			Database.executeBatch(new BatchTerminateAddOns());
		Test.stopTest();
		
		Add_On_Service__c addOn = [Select Status__c from Add_On_Service__c];
		
		System.assertEquals('Expired',addOn.status__c);
	}
	
	@isTest
	public static void testTerminatedStatus(){
		Add_On_Service__c addOn 	= [Select Termination_Reason__c from Add_On_Service__c];
		addOn.Termination_Reason__c = 'test';
		update addon;
		
		Test.startTest();
			Database.executeBatch(new BatchTerminateAddOns());
		Test.stopTest();
		
		addOn = [Select Status__c from Add_On_Service__c];
		
		System.assertEquals('Terminated',addOn.status__c);
	}
	
	@isTest static void testScheduleBatchTerminateAddOns() {
		Id jobId;

		Test.startTest();
			jobId = System.schedule('test job', '0 0 0 * * ?', new ScheduleBatchTerminateAddOns());
		Test.stopTest();

		CronTrigger[] jobs = [Select Id from CronTrigger Where Id = : jobId];

		System.assert(!jobs.isEmpty());

	}
	
	@isTest static void testNoBusinessConfig(){
		Delete [Select Id from Business_Config__c];
		Test.startTest();
			Database.executeBatch(new BatchTerminateAddOns());
		Test.stopTest();
		
		Add_On_Service__c addOn = [Select Status__c from Add_On_Service__c];
		
		System.assertNotEquals('Expired',addOn.status__c);
		System.assertNotEquals('Terminated',addOn.status__c); 
	}
	
	@isTest static void testDisabledBusinessConfig(){
		Business_Config__c b = [Select Business_Rule_Value__c From Business_Config__c Where Business_Rule_Name__c = 'terminateAddOns'];
		b.Business_Rule_Value__c = 'false';
		update b;
		
		Test.startTest();
			Database.executeBatch(new BatchTerminateAddOns());
		Test.stopTest();
		
		Add_On_Service__c addOn = [Select Status__c from Add_On_Service__c];
		
		System.assertNotEquals('Expired',addOn.status__c);
		System.assertNotEquals('Terminated',addOn.status__c); 
	}
	
}