force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DummyAssetsCreation_BatchTest.cls
/***
 * @description test class for DummyAssetsCreation_Batch class
 * @date 19.05.2020
 * @author Danish Farooq
 */
@IsTest
private class DummyAssetsCreation_BatchTest {

    @testSetup
    static void setup(){

        UnitTestDataFactory.getRecordtypeValues();
        Country__c country = UnitTestDataFactory.createCountry('TH', 'Thailand', 'THB');
        insert country;

        Company__c company = UnitTestDataFactory.createCompany('FP', 'FP', country);
        insert company;

        List<Account> lstAccounts = UnitTestDataFactory.createAccounts(10, country, 'FP_Account');

        for(Account iAccount : lstAccounts){
            iAccount.phone = '+66123456789';
            iAccount.CurrencyIsoCode = 'THB';
            iAccount.Account_status__c = 'Active';
        }
        insert lstAccounts;
    }
    @IsTest
    static void testAssetRecord() {

        Test.startTest();
        Database.executeBatch(new DummyAssetsCreation_Batch('FP','Thailand','SIM'));
        Test.stopTest();

        List<Account> lstAccount = [SELECT ID FROM Account];
        Map<ID,Account> accountMap = new Map<ID,Account>(lstAccount);
        List<Asset__c> lstAssets = AssetSelector.findActiveByAccountIds(accountMap.keySet());
        system.assertEquals(lstAssets.size(),10);

    }
    @IsTest
    static void testFailAssetRecord() {

        Test.startTest();
        Database.executeBatch(new DummyAssetsCreation_Batch('FPP','Thailand','SIM'));
        Test.stopTest();

        List<Account> lstAccount = [SELECT ID FROM Account];
        Map<ID,Account> accountMap = new Map<ID,Account>(lstAccount);
        List<Asset__c> lstAssets = AssetSelector.findActiveByAccountIds(accountMap.keySet());
        system.assertNotEquals(lstAssets.size(),10);

    }
}