force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Vertical_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>African</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>All Night Alcohol</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Aquariums</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Arepas y Empanadas</fullName>
            </value>
            <value>
                <fullName>Argentine</fullName>
            </value>
            <value>
                <fullName>argentinian</fullName>
                <label>Argentinian</label>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbecue</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Burger and Grill</fullName>
            </value>
            <value>
                <fullName>Burgers</fullName>
            </value>
            <value>
                <fullName>Burmese</fullName>
            </value>
            <value>
                <fullName>Cafe</fullName>
            </value>
            <value>
                <fullName>Cakes &amp; Bakery</fullName>
            </value>
            <value>
                <fullName>Calzones</fullName>
            </value>
            <value>
                <fullName>Cambodian</fullName>
            </value>
            <value>
                <fullName>Cantonese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Record_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Shop</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Vertical__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>B2B/B2C Courier</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Beauty</fullName>
            </value>
            <value>
                <fullName>books &amp; stationary</fullName>
                <label>Books &amp; Stationary</label>
            </value>
            <value>
                <fullName>C2C Courier</fullName>
            </value>
            <value>
                <fullName>charity</fullName>
                <label>Charity</label>
            </value>
            <value>
                <fullName>Coffee</fullName>
            </value>
            <value>
                <fullName>confectionery</fullName>
                <label>Confectionery</label>
            </value>
            <value>
                <fullName>convenience</fullName>
                <label>Convenience</label>
            </value>
            <value>
                <fullName>cosmetics</fullName>
                <label>Cosmetics</label>
            </value>
            <value>
                <fullName>Darkstores</fullName>
            </value>
            <value>
                <fullName>delicatessen</fullName>
                <label>Delicatessen</label>
            </value>
            <value>
                <fullName>Desert</fullName>
            </value>
            <value>
                <fullName>Drinks</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>fashion</fullName>
                <label>Fashion</label>
            </value>
            <value>
                <fullName>Flowers</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>games</fullName>
                <label>Games</label>
            </value>
            <value>
                <fullName>Groceries</fullName>
            </value>
            <value>
                <fullName>health_and_wellness</fullName>
                <label>Health &amp; Wellness</label>
            </value>
            <value>
                <fullName>Healthcare &amp; Beauty</fullName>
            </value>
            <value>
                <fullName>Home &amp; Gifts</fullName>
            </value>
            <value>
                <fullName>Home Based Kitchen</fullName>
            </value>
            <value>
                <fullName>Ice cream</fullName>
            </value>
            <value>
                <fullName>just_for_adults</fullName>
                <label>Just For Adults</label>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>mother_and_baby</fullName>
                <label>Mother &amp; Baby</label>
            </value>
            <value>
                <fullName>Party Supplies</fullName>
            </value>
            <value>
                <fullName>Regular Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MultiSelectLookUp_AuraControllerTest.cls
/***
* @description test class for MultiSelectLookUp_AuraController class
* @date 24.06.2020
* @author Danish Farooq
   */

@IsTest
private class MultiSelectLookUp_AuraControllerTest {
    @testSetup
    static void setup(){

        UnitTestDataFactory.getRecordtypeValues();
        Country__c country = UnitTestDataFactory.createCountry('MY', 'Malaysia', 'MYR');
        insert country;

        Company__c company = UnitTestDataFactory.createCompany('FP', 'FP', country);
        insert company;

        List<Account> lstAccounts = UnitTestDataFactory.createAccounts(1, country, 'FP_Account');

        for(Account iAccount : lstAccounts){
            iAccount.phone = '+6023456789';
            iAccount.CurrencyIsoCode = 'MYR';
            iAccount.Account_status__c = 'Active';
            iAccount.Vertical__c = 'Restaurant';
            iAccount.Vertical_Segment__c = 'Regular Restaurant';
            iAccount.Category__c = 'Asian';
            iAccount.Name = 'testAccount_Test';
        }
        insert lstAccounts;

        List<Contact> lstContact = UnitTestDataFactory.createContacts(lstAccounts,'FirstName','Last Name','MR','owner',1,'test',Constants.FP_CONTACT_DEVELOPERNAME);
        insert lstContact;

    }

    @IsTest
    static void testSearchLookUp() {

        MultiSelectLookUp_AuraController.ParametersWrapper paramObj = new MultiSelectLookUp_AuraController.ParametersWrapper();
        MultiSelectLookUp_AuraController multiSelectCtrlObj = new MultiSelectLookUp_AuraController();
        multiSelectCtrlObj.searchKeyWord = 'last Name';
        multiSelectCtrlObj.objectName = 'Contact';
        multiSelectCtrlObj.fieldToQuery = 'Email';
        multiSelectCtrlObj.excludedItemLst = new List<sObject>();

        paramObj.searchKeyWord = multiSelectCtrlObj.searchKeyWord;
        paramObj.objectName =  multiSelectCtrlObj.objectName;
        paramObj.fieldToQuery =multiSelectCtrlObj.fieldToQuery ;

        MultiSelectLookUp_AuraController.ExcludedItemWrapper excludedItemWrapperObj = new MultiSelectLookUp_AuraController.ExcludedItemWrapper();
        excludedItemWrapperObj.id = '000';
        excludedItemWrapperObj.name = 'test Name';
        excludedItemWrapperObj.email = 'test Email';
        paramObj.excludedItemLst = new List<MultiSelectLookUp_AuraController.ExcludedItemWrapper> { excludedItemWrapperObj };

        string jsonString = JSON.serialize(paramObj);

        test.startTest();
        List<sObject> lstReturnedObjects = MultiSelectLookUp_AuraController.fetchLookUpValues(jsonString);
        test.stopTest();

        system.assertNotEquals(lstReturnedObjects.size(),0);
    }
}