force-app/main/default/objects/Account/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <description>Account Email - Will come from the lead during lead conversion</description>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Apex__c.field-meta.xml
<CustomField>
    <fullName>Is_Apex__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is controlled from the Apex class and used in the validation rules.</description>
    <label>Is Apex</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_VIP_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_VIP_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>true --&gt; this means this a important account, is defined by each country</description>
    <label>Key / VIP Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mark_up__c.field-meta.xml
<CustomField>
    <fullName>Mark_up__c</fullName>
    <label>Mark-up</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No mark-up</fullName>
            </value>
            <value>
                <fullName>In percentage</fullName>
            </value>
            <value>
                <fullName>In flat amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mark_up_Value__c.field-meta.xml
<CustomField>
    <fullName>Mark_up_Value__c</fullName>
    <label>Mark-up Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Shared_Menu__c.field-meta.xml
<CustomField>
    <fullName>Shared_Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shared Menu</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Shared_Menu__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Branch - Main, Branch - Kitchen Restaurant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Shared Menu)</relationshipLabel>
    <relationshipName>Shared_Menu_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Record_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Shop</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <formula>Account__r.GRID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountSelector.cls
public inherited sharing class AccountSelector {

    public static Account getAccountDetailsforId(Id accountId) {
        return [SELECT Id, Name, Account_Email__c, RecordTypeId, RecordType.DeveloperName, Record_Country__c, Account_Status__c,Mark_up_Value__c,Mark_up__c,Vertical__c
                FROM Account
                WHERE Id =: accountId
                LIMIT 1];
    }

    public static Account getAccountByName(String name) {
        return [SELECT Id, GRID__c, Phone, Name, RecordTypeId, Record_Country__c
                FROM Account
                WHERE Name =: name
                LIMIT 1];
    }

    public static Account getByCountry(String countryName) {
        List<Account> accList = new List<Account>([SELECT RecordTypeId FROM Account WHERE Record_Country__c = :countryName LIMIT 1]);
        return !accList.isEmpty() ? accList[0] : new Account();
    }

    /**
	 * Retrieves Account related to specified country and RecordTypeId
	 * @param  country name
	 * @return recordTypeId
	 */
    public static Account getByPlatformAndRecordType(String recordType,String countryName) {
        List<Account> accList = new List<Account>([SELECT Id from Account where RecordTypeId =:recordType AND Record_Country__c =:countryName Limit 1]);
        return !accList.isEmpty() ? accList[0] : new Account();
    }

    /**
	 * Retrieves record type related to specified country and Account
	 * @param  country name
	 * @return reordTypeId
	 */
    public static String getAccountRecordTypeByCountry(String countryName) {
        Account acc = AccountSelector.getByCountry(countryName);
        return null != acc && String.isNotBlank(acc.RecordTypeId) ? String.valueOf(acc.RecordTypeId) : '';

    }
    
    /**
     * @description get accounts by their ids
     *
     * @param accountIds
     *
     * @return
     */
    public static List<Account> getByIds(Set<Id> accountIds) {
        List<Account> accounts = new List<Account>();
        try {
            accounts = [SELECT
                    Id, Parent.GRID__c, Parent.Type, Shared_Menu__c, Shared_Menu__r.GRID__c, Record_Country__c, Vertical__c,
                    (SELECT Id, Name FROM Contacts WHERE Contact_Role__c = 'Owner')
                FROM Account
                WHERE Id IN :accountIds];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return accounts;
    }

    @TestVisible
    private static List<Account> getAll() {
        List<Account> accounts = new List<Account>();
        try {
            accounts = [SELECT
                    Id, Parent.GRID__c, Parent.Type, Shared_Menu__c, Shared_Menu__r.GRID__c, Record_Country__c
            FROM Account];
          } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return accounts;
    }

    /**
     * @description get accounts with active platform by account Ids, opportunity Ids and opportunity business type.
     *
     * @param accountIds
     * @param opportunityIds
     * @param businessType
     *
     * @return
     */
    public static List<Account> getByIdsOpportunityIdsBusinessType(final Set<Id> accountIds, final Set<Id> opportunityIds, final String businessType) {
        List<Account> accounts = new List<Account>();
        try {
            accounts = [SELECT Id, Type, (SELECT Account__c FROM Platforms_Performance__r WHERE Account__c IN :accountIds AND Backend_ID__c != NULL)
                    FROM Account WHERE Id IN :accountIds AND Id IN
                        (SELECT AccountId FROM Opportunity WHERE Id IN :opportunityIds AND Business_Type__c = :businessType)];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return accounts;
    }

    
    /*******************************************************************************************************
    * @description (SSC-2547)Account Map Queried based on Account Id set to update status
    * @param accIdsSet
    * @return Map<Id,Account> holds Id and Account record
    */
    public static Map<Id,Account> getAccountMapFromAccIdSet(Set<Id> accIdsSet) {
    	Map<Id,Account> accMap = new Map<Id,Account>();
        try {
             accMap = new Map<Id,Account>([SELECT Id,Account_Status__c
                                            FROM Account 
                                            WHERE Id IN :accIdsSet ]);
         }catch (QueryException e) {
            Loggingutility.createLog('AccountSelector','getAccountMapFromAccIdSet','','');
            LoggingUtility.log('AccountSelector',e.getMessage());
            LoggingUtility.commitLogs();

         }
         return accMap;
     }


    /**
    *
    * @description -  get all accounts along with child accounts
    * @param accountIdSet - Set of ids of Accounts
    * @return - List of Accounts
    */
    public static List<Account> selectByIdWithChildAccounts(Set<Id> accountIdSet) {
        String queryStr = ' SELECT Id,Key_VIP_Account__c,Name,Parent.Key_VIP_Account__c,ParentId,Is_Apex__c,(SELECT Id,Key_VIP_Account__c,ParentId,Is_Apex__c FROM ChildAccounts) FROM ACCOUNT WHERE Id IN:accountIdSet ';
        return (List<Account>) Database.query(queryStr);
    }

}