force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of account company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Delivery_Service__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Service__c</fullName>
    <description>Information of delivery type used by partner</description>
    <inlineHelpText>Information of delivery type used by partner</inlineHelpText>
    <label>Delivery Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Facility Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Record_Country__c</field>
            <operation>equals</operation>
            <valueField>$Source.Record_Country__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stalls</relationshipLabel>
    <relationshipName>Stalls</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Franchise_Connection__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only use to establish a connection between TWO hierarchies, used mostly for billing transfers on Opportunity level.</description>
    <inlineHelpText>Only use to establish a connection between TWO hierarchies, used mostly for billing transfers on Opportunity level</inlineHelpText>
    <label>Franchise Connection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Franchise, DH Concept</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Franchise Connection)</relationshipLabel>
    <relationshipName>AccountsFranchise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Revenue_Model__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Model__c</fullName>
    <label>Revenue Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordering Platform</fullName>
            </value>
            <value>
                <fullName>Deal Subscription Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Shared_Menu__c.field-meta.xml
<CustomField>
    <fullName>Shared_Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shared Menu</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Shared_Menu__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Branch - Main, Branch - Kitchen Restaurant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Shared Menu)</relationshipLabel>
    <relationshipName>Shared_Menu_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stalls_Occupied__c.field-meta.xml
<CustomField>
    <fullName>Stalls_Occupied__c</fullName>
    <label>Stalls Occupied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>Service type of contract. Says whether a contract is a main service or an additional service (surcharge)</description>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of opportunity company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <formula>Account__r.GRID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DH Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Take away</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Delivery Service</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClsAccountSelector.cls
/**
* @author Mantas Jurkunas
* @date 09.01.2019
*
* @description Selector class for retrieving account records
*/
public class ClsAccountSelector {

    /*******************************************************************************************************
    * @description Queries for account records by provided GRID numbers.
    * @param keys List<String> GRID numbers.
    * @return List<Account>
    */
    public static List<Account> findAccountsByGrid(final Set<String> keys) {
        List<Account> accounts = new List<Account>();
        try {
            accounts = [
                    SELECT
                        Id,
                        Name,
                        GRID__c,
                        Company_code__c,
                        Record_country__c,
                        CurrencyIsoCode
                    FROM
                        Account
                    WHERE
                        GRID__c IN :keys
            ];
        } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return accounts;
    }

    /**
     * @description get accounts that have shared menu
     *
     * @param accountIds
     *
     * @return
     */
    public static List<Account> getSharedMenuAccountsWOBackendIdFromIds(Set<Id> accountIds) {
        List<Account> lstAccounts = new List<Account>();
        try {
            List<Account> accountsWOBackendId = [SELECT Id, Shared_Menu__r.Backend_ID__c, GRID__c, Shared_Menu__r.GRID__c, Shared_Menu__c FROM Account WHERE Shared_Menu__c != NULL AND Shared_Menu__r.Backend_ID__c = NULL AND Id IN :accountIds];
            Set<Id> sharedMenuIds = ClsSObjectUtils.extractSetIds(accountsWOBackendId, Account.Shared_Menu__c.getDescribe().getLocalName());
            List<Platform_Performance__c> platformPerformances = [SELECT Id FROM Platform_Performance__c WHERE Backend_ID__c != NULL AND Account__c IN :sharedMenuIds];
            if (platformPerformances == null || platformPerformances.isEmpty()) {
                return accountsWOBackendId;
            }
            sharedMenuIds = ClsSObjectUtils.extractSetIds(platformPerformances, Platform_Performance__c.Account__c.getDescribe().getLocalName());
            for (Account acc: accountsWOBackendId) {
                if (!sharedMenuIds.contains(acc.Shared_Menu__c)) {
                    lstAccounts.add(acc);
                }
            }
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return lstAccounts;
    }

    /*******************************************************************************************************
    * @description Queries for account record by provided Id.
    * @param Id accountId.
    * @return Account
    */
    public static Account findAccountById(final Id accountId) {
        Account theAccount = new Account();
        try {
            theAccount = [
                    SELECT
                        Id,
                        ParentId,
                        Franchise_Connection__c,
                        RecordType.DeveloperName,
                        Name,
                        GRID__c,
                        Delivery_Service__c
                    FROM
                        Account
                    WHERE
                        Id = :accountId
                    LIMIT 1
            ];
        } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
            return null;
        }
        return theAccount;
    }

    /*******************************************************************************************************
    * @description Queries account parent and grandparent type
    * @param accountId
    * @return Account
    */
    public static Account getAccountParentsTypes(Id accountId) {
        return [SELECT Parent.Type, Parent.Parent.Type 
                FROM Account
                WHERE Id = :accountId];
    }

    /*******************************************************************************************************
   * @description Queries accounts and related contracts that are terminated expired or ative
   * @param ids account ids
   * @param serviceTypes contract service types
   * @return List<Account> accounts that have contracts that are active expired or terminated
   */
    public static List<Account> findByIdsAndContractServiceType(final Set<Id> ids, final Set<String> serviceTypes) {
        List<Account> accounts = new List<Account>();
        try {
            accounts = [
                    SELECT
                            Id,
                            Delivery_Service__c,
                            (SELECT RecordTypeId, Status, Service_Type__c
                                FROM Contracts WHERE Service_Type__c IN :serviceTypes AND Status IN ('Activated', 'Expired', 'Terminated') ORDER BY Service_Type__c)
                    FROM
                            Account
                    WHERE
                            Id IN (SELECT AccountId FROM Contract WHERE Service_Type__c IN :serviceTypes AND Status IN ('Activated', 'Expired', 'Terminated') AND AccountId IN :ids)
            ];
        } catch (QueryException e) {
            System.debug('Error: '+e.getMessage());
        }
        return accounts;
    }
    
      /**
     * @Description: This method returns Account against opportunity
       @Input Params       : Set of Account id
       @Return             : List of Account
       @TriggerContext     : Before Update, Before Insert
       @Ticket #           : SSC-1533
    */
    public static List<Account> getAccountByOppty(Set<Id> setOfAccountId){

        List<Account> lstOfAccount = new List<Account>();
        try{
            lstOfAccount = [Select Id, Record_Country__c,Revenue_Model__c from Account WHERE Id IN  : setOfAccountId
                            AND Record_Country__c != NULL LIMIT : Limits.getLimitDMLRows()];
        }
        catch(Exception ex){
            System.debug('Error: '+ex.getMessage());
        }
        return lstOfAccount;
    }
    /*******************************************************************************************************
    * @description Queries facility accounts and related stalls
    * @param ids account facility ids
    * @return List<Account> facility accounts that have associated stalls
    */
    public static List<Account> getStallsByFacilityIds(final Set<Id> ids) {
        List<Account> accounts = new List<Account>();
        accounts = [
                SELECT Id,Stalls_Occupied__c, (SELECT Id,Account_Status__c FROM Stalls__r)
                FROM Account
                WHERE Id IN :ids
        ];
        return accounts;
    }

    /**
    * @date     : [18/06/2020]
    * @method name  : getAccountRecord
    * @description  : method to return the the account
    * @return List<Account>
    */
    public static List<Account> getAccountRecord() {

        List<Account> accountDetails = [SELECT Id, Name, GRID__c  FROM Account limit 1];
        return accountDetails;
    }
}