force-app/main/default/objects/Account/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <description>Account Email - Will come from the lead during lead conversion</description>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>Restaurant Backend Id</description>
    <formula>Account.Backend_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Backend ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Partial_Refund_Type__c.field-meta.xml
<CustomField>
    <fullName>Partial_Refund_Type__c</fullName>
    <label>Partial Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank transfer</fullName>
            </value>
            <value>
                <fullName>Online payment</fullName>
            </value>
            <value>
                <fullName>COD</fullName>
            </value>
            <value>
                <fullName>Paypal</fullName>
            </value>
            <value>
                <fullName>MOLpay</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Apple Pay</fullName>
            </value>
            <value>
                <fullName>PayLah</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <formula>Account.Restaurant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Restaurant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DataFridgeEntityIdMapping__mdt/DataFridgeEntityIdMapping__mdt.object-meta.xml
<CustomObject>
    <label>DataFridgeEntityIdMapping</label>
    <pluralLabel>DataFridgeEntityIdMapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/DataFridgeEntityIdMapping__mdt/fields/Account_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Record_Type__c</fullName>
    <label>Account Record Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <formula>Account__r.GRID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <description>SP-1592</description>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CtrGlobalChatBot.cls
global without sharing class CtrGlobalChatBot {
	global static String requestLabel;
	global static ResponseWrapper responseWrap = new ResponseWrapper();
	private static Map<String, Map<String,Map<String,Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;

	/**
    * @description: This method fetches the case details from the chat record
    * @param: String objrecId: CaseId/ChatId to get case info.
    * @return: String key value pair of field values for case
	*/
	@AuraEnabled
	global static String getCaseFromChat(String objrecId) {
		return CaseControllerLightning.getCaseFromChat(objrecId);
	}
	/**
    * @description: This method fetches the order details based on the order id and the entity id
    * @param: order number, platform, country
    * @return: Continuation Object
	*/
	@AuraEnabled(continuation=true)
    global static Object fetchOrder(String orderId,String platform,String country){
		HttpRequest req=DataFridgeUtility.fetchOrderDetails(orderId,country,platform);
		Continuation con = new Continuation(40);
		con.continuationMethod='processResponse';
		requestLabel=con.addHttpRequest(req);
		con.state='DF Response';
		return con;
    }

    /**
    * @description: This method fetches the order history based on the customer id and the entity id
    * @param: customer id (from datafridge), platform, country
    * @return: Continuation Object
	*/
	@AuraEnabled(continuation=true)
    global static Object fetchOrderHistory(String customerId,String platform,String country){
		HttpRequest req=DataFridgeUtility.fetchOrderAggregateDetails(customerId,country,platform);
		Continuation con = new Continuation(40);
		con.continuationMethod='processResponse';
		con.state='DF Response';
		requestLabel=con.addHttpRequest(req);
		con.addHttpRequest(req);
		return con;
    }

    /**
    * @description: This method fetches the restaurant data based on the vendor id (backendId) and the entity id
    * @param: vendorId from datafridge, platform
    * @return: ResponseWrapper
    */
	@AuraEnabled
    global static ResponseWrapper fetchRestaurantDetails(String vendorId,String platform){

	        List<Platform_Performance__c> platforms = [SELECT id,Account__c
														FROM Platform_Performance__c
														WHERE Backend_Id__c =: vendorId
															AND Platform__c =: platform];

			platform = platform.replaceAll('[^a-zA-Z0-9]', '_');
			DataFridgeEntityIdMapping__mdt metaData = [SELECT Account_Record_Type__c
														FROM DataFridgeEntityIdMapping__mdt
														WHERE QualifiedApiName =: platform];

			String accountId;
			if(platforms.size() > 0){
				accountId = platforms[0].account__c;
			}

			if(accountId != null){
				Account acc = [SELECT Id,Name,Restaurant_Name__c,Account_Email__c,phone,backend_id__c,GRID__c
								FROM Account
								WHERE id =: accountId];
				return new ResponseWrapper(acc);
			}


			List<Account> accounts = [SELECT Id,Name,Restaurant_Name__c,Account_Email__c,phone,backend_id__c,GRID__c
										FROM Account
										WHERE backend_id__c =: vendorId
										 AND recordType.developerName =: metaData.Account_Record_type__c];

			if(accounts.size() > 0){
				return new ResponseWrapper(accounts[0]);
			}

    	return new ResponseWrapper(true,System.Label.No_Account_found_for_the_backend_id + ' ' + vendorId);
    }

	/**
    * @description: Wrapper class for capturing data fridge response
    */
    global class ResponseWrapper{
		@AuraEnabled public Boolean isError;
		@AuraEnabled public String errorMessage;
		@AuraEnabled public String result;
		@AuraEnabled public Account account;
		@AuraEnabled public String voucherToolLink;
		@AuraEnabled public String voucherCountryName;

    	public ResponseWrapper(String result){
    		this.result			= result;
    		this.isError		= false;
    		this.errorMessage	= '';
    	}

    	public ResponseWrapper(Account account){
    		this.account		= account;
    		this.isError		= false;
    		this.errorMessage	= '';
    	}

    	public ResponseWrapper(Boolean isError,String errorMessage){
    		this.isError		= isError;
    		this.errorMessage	= errorMessage;
    	}

		public ResponseWrapper(){
			this.isError        = false;
			this.errorMessage   = '';
		}
    }

	/**
    * @description: Callback method for the continuation process to make the callout and return the response to the lightning components.
    * @param: continuation request labels, continuation state
    * @return: ResponseWrapper
    */
	@AuraEnabled(cacheable=true)
	global static Object processResponse(List<String> labels, Object state) {
		HttpResponse dFResponse = new HttpResponse();
		dFResponse=Continuation.getResponse(labels[0]);
		if(dFResponse.getStatusCode()==200) {
			responseWrap = new ResponseWrapper(dFResponse.getBody());
		}
		else{
			responseWrap = new ResponseWrapper(true,dFResponse.getBody());
		}
		return responseWrap;
	}

	/**
    * @description: Callback method for the continuation process to make the callout and return the response to the visualforce page.
    * This is used primarily for covering the test cases due to the limitations in the apex testing methods for Continuation class.
    * @return: ResponseWrapper
    */
	@AuraEnabled(cacheable=true)
	global static Object processResponse() {
		HttpResponse dFResponse = new HttpResponse();
		dFResponse=Continuation.getResponse(requestLabel);
		if(dFResponse.getStatusCode()==200) {
			responseWrap = new ResponseWrapper(dFResponse.getBody());
		}
		else{
			responseWrap = new ResponseWrapper(true,dFResponse.getBody());
		}
		return responseWrap;
	}

	/**
    * @description: Fetch Hurrier Links, Order Details & Customer Details for the order details section.
    * @param platform, country, deliveryType(platform delivery/vendor delivery)(from datafridge)
    * @return: Map of links with type of link
    */
	@AuraEnabled
	global static Map<String,String> getLinks(String platform,String country,String deliveryType){
		Map<String,String> linksMap=new Map<String,String>();
		linksMap.put('HurrierDetails','Not Found');
		linksMap.put('OrderDetails','Not Found');
		linksMap.put('CustomerDetails','Not Found');
		Map<String, Map<String, Business_Config__c>> mapBusinessLogic = moam.get('ChatBotConfigs');
		Map<String, Business_Config__c> mapBusinessRules = mapBusinessLogic.get('Global_Config');
		if (mapBusinessRules == null) {
			return linksMap;
		}
		try {
			if (deliveryType == 'platform delivery') {
				if (mapBusinessRules.containsKey('hurrierDetails')) {
					linksMap.put('HurrierDetails', CaseControllerLightning.getUrlString('hurrierDetails', mapBusinessRules.get('hurrierDetails').Business_Rule_Value__c, platform, country));
				}
			}
			if (mapBusinessRules.containsKey('orderDetailsLink')) {
				linksMap.put('OrderDetails', CaseControllerLightning.getUrlString('orderDetailsLink', mapBusinessRules.get('orderDetailsLink').Business_Rule_Value__c, platform, country));
			}
			if (mapBusinessRules.containsKey('customerDetailsLink')) {
				linksMap.put('CustomerDetails', CaseControllerLightning.getUrlString('customerDetailsLink', mapBusinessRules.get('customerDetailsLink').Business_Rule_Value__c, platform, country));
			}
		} catch (Exception e) {
			system.debug(e);
		}
		return linksMap;
	}

	/**
     * @description : SCC-40/SCC-376 Moving logic from CaseControllerLightning to CtrGlobalChatBot
     * @param: case recordId and paymentMethod from DF
     * @return - if payment method gets updated successfully, then payment method else 'Failed'
     */
	@AuraEnabled
	global static String updatePaymentMethod(String caseIdString, String paymentMethod) {
		IF(!String.isEmpty(caseIdString)){
			Case cas = new Case(Id=caseIdString,Partial_Refund_Type__c=paymentMethod);
			try {
				Database.SaveResult saveResult = Database.update(cas, true);
				if(saveResult.isSuccess()){
					return paymentMethod;
				} else {
					return 'Failed';
				}
			} catch (Exception ex) {
				system.debug('Exception occurred: '+ex.getMessage());

			}
		}
		return '';
	}

    global class chatBotException extends Exception{}
}