force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Key_VIP_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_VIP_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>true --&gt; this means this a important account, is defined by each country</description>
    <label>Key / VIP Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <description>Talabat Backend Field that indicates why a branch is on a certain status</description>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Shortage of Delivery Drivers</fullName>
            </value>
            <value>
                <fullName>Shortage of Production Capacity</fullName>
            </value>
            <value>
                <fullName>Electricity Failure</fullName>
            </value>
            <value>
                <fullName>Issue in punching order in system</fullName>
            </value>
            <value>
                <fullName>Overload of orders</fullName>
            </value>
            <value>
                <fullName>Municipality issue</fullName>
            </value>
            <value>
                <fullName>Renovation of Restaurant</fullName>
            </value>
            <value>
                <fullName>Maintenance issue</fullName>
            </value>
            <value>
                <fullName>Telephone Line not working</fullName>
            </value>
            <value>
                <fullName>Bad weather outside</fullName>
            </value>
            <value>
                <fullName>Internet failure/cut off</fullName>
            </value>
            <value>
                <fullName>Fax problems</fullName>
            </value>
            <value>
                <fullName>Updates in Menu</fullName>
            </value>
            <value>
                <fullName>Party In Restaurant</fullName>
            </value>
            <value>
                <fullName>Coordination Issues</fullName>
            </value>
            <value>
                <fullName>Due to traffic issues</fullName>
            </value>
            <value>
                <fullName>Physically closed due to poor dine in business</fullName>
            </value>
            <value>
                <fullName>Set Busy by Operations</fullName>
            </value>
            <value>
                <fullName>Auto busy on GPRS Last Activity more than 15 minutes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Key_VIP_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_VIP_Account__c</fullName>
    <description>SP-4241</description>
    <formula>AND(Account.Key_VIP_Account__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Key / VIP Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>this hold the end date because the other end date is not writable</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>Service type of contract. Says whether a contract is a main service or an additional service (surcharge)</description>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform_Online_Status__c.field-meta.xml
<CustomField>
    <fullName>Platform_Online_Status__c</fullName>
    <label>Platform Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Online_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Online_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <customValue>
        <fullName>On Holiday</fullName>
    </customValue>
    <customValue>
        <fullName>In Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Quality Check</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Initiated</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Final Check</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Changes Requested</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Approval Pending</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Take Online</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Backend ID Creation</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Menu Typing</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Delivery Area</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Offline</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Take Online</fullName>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <customValue>
        <fullName>true</fullName>
        <isActive>false</isActive>
        <label>true</label>
    </customValue>
    <customValue>
        <fullName>false</fullName>
        <isActive>false</isActive>
        <label>false</label>
    </customValue>
    <customValue>
        <fullName>Offline - current day</fullName>
        <isActive>false</isActive>
        <label>Offline - current day</label>
    </customValue>
    <masterLabel>Online Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BatchWinbackOpportunities.cls
/**
 * Created by w.novoa on 27.08.2018.
 */

global with sharing class BatchWinbackOpportunities  implements Database.Batchable<sObject>, Database.Stateful{


    private static Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
    private String strRecordType;
    private String StrOppRecordType;
    Private Map<String, Business_Config__c> mapBusinessRule;


    global BatchWinbackOpportunities(String RecordType){
        strRecordType  = RecordType;

        Map<String, Map<String, Business_Config__c>> mapBusinessLogic = moam.get('WinbackOpportunities');
        System.debug(mapBusinessLogic);
        mapBusinessRule =  mapBusinessLogic.get(strRecordType);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {

        set<String> stStatusReason = new set<String>();
        set<String> stAccountType = new set<String>();

        System.debug('mapBusinessRule-->'+mapBusinessRule);

        if(mapBusinessRule!= null &&
                mapBusinessRule.get('InvalidStatusReason')!= null &&
                mapBusinessRule.get('AccountType')!= null){
            stStatusReason.addAll(mapBusinessRule.get('InvalidStatusReason').Business_Rule_Value__c.split(','));
            stAccountType.addAll(mapBusinessRule.get('AccountType').Business_Rule_Value__c.split(','));
            StrOppRecordType = LibRecordTypeHelper.getRecordTypeValue(mapBusinessRule.get('OpportunityRecordType').Business_Rule_Value__c);
        }


        System.debug([select id
        from Account
        where Account_Status__c  = 'Terminated'
        AND Key_VIP_Account__c = false
        AND RecordType.DeveloperName = :strRecordType
        AND Type IN : stAccountType
        AND Status_Reason__c NOT IN : stStatusReason]);

        return Database.getQueryLocator([select id
                                            from Account
                                            where Account_Status__c  = 'Terminated'
                                                AND Key_VIP_Account__c = false
                                                AND RecordType.DeveloperName = :strRecordType
                                                AND Type IN : stAccountType
                                                AND Status_Reason__c NOT IN : stStatusReason]);
    }

    global void execute(Database.BatchableContext BC, List<Account> scope) {

        set<String> stAccountId = new set<String>();
        List<Opportunity> lstOpp = new List<Opportunity>();

        for(Account accTemp: scope){
            stAccountId.add(accTemp.id);
        }

        for(Account accTemp: [Select id,
                                    (Select id from Opportunities where Business_Type__c = 'Win Back' limit 1),
                                    (select id from Platforms_Performance__r where Platform_Online_Status__c = 'Online' limit 1),
                                     (select id,End_Date__c  from Contracts where Service_Type__c = 'Commission Fee' AND End_Date__c < LAST_90_DAYS Order by End_Date__c DESC Limit 1)
                                from Account
                                where id In  :stAccountId]){
            if(accTemp.Opportunities != null &&  accTemp.Opportunities.size() > 0)// check that doesn't have any win back opportunity before
                continue;

            if(accTemp.Platforms_Performance__r != null &&  accTemp.Platforms_Performance__r.size() > 0)// check that there is not platform online
                continue;

            if(accTemp.Contracts != null &&  accTemp.Contracts.size() > 0)// check if there is any contract before that the last 3 months.
                lstOpp.add(new Opportunity(RecordTypeId = StrOppRecordType, AccountId = accTemp.id, Business_Type__c = 'Win Back',OwnerId =  mapBusinessRule.get('OwnerId').Business_Rule_Value__c , StageName = 'New',Name = 'Win Back', CloseDate = Date.Today() ));
        }

        List<Database.saveResult> lstSr =  Database.insert(lstOpp);

        LoggingUtility.createLog('BatchWinbackOpportunities','BATCH','CASE CLOSURE',null);
        Boolean isError = false;
        for(Database.saveResult result : lstSr){
            if(!result.isSuccess()){
                LoggingUtility.logError('BatchWinbackOpportunities','BatchWinbackOpportunities: Update failed for case ' + result.getId() +
                        ' Errors '  + result.getErrors() + '\n');
                isError = true;
            }
        }

        // Do Logging in case of error.
        if(isError){
            LoggingUtility.commitLogs();
        }


    }
    global void finish(Database.BatchableContext BC) {

    }

}