force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/Platform_Country__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Platform Country</label>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UnitTestClsPlatformPerfomanceHandler.cls
/**
 * Created by w.novoa on 27.06.2018.
 */

@IsTest
private class UnitTestClsPlatformPerfomanceHandler {

    @testSetup
    static void setup() {
        UnitTestDataFactory.getRecordtypeValues();

        Country__c bh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        company__c com = UnitTestDataFactory.createCompany('Talabat', 'Talabat', bh);
        insert com;

        Business_Config__c b1 = UnitTestDataFactory.createBusinessConfig('UpdateAccountStatusParent', 'Process', 'ParentTypes', 'Brand,Group', bh.id, 'Talabat_Account', true, true);

        insert b1;

        Platform_Country__c pt2 = new Platform_Country__c(name = 'TalabatPlatform', Country__c = 'Kuwait,Bahrain,Saudi Arabia,Oman,Qatar,United Arab Emirates');
        Account accParent = UnitTestDataFactory.createAccount('BatchTestClassAccount1', bh, 'Talabat_Account');
        accParent.ParentId = accParent.id;
        accParent.Type = 'Brand';
        insert accParent;
        System.debug('accParent-->'+accParent);
        Account accParent1 = UnitTestDataFactory.createAccount('BatchTestClassAccount2', bh, 'Talabat_Account');
        accParent1.ParentId = accParent.id;
        accParent1.Type = 'Brand';
        insert accParent1;
        Account accParent2 = UnitTestDataFactory.createAccount('BatchTestClassAccount3', bh, 'Talabat_Account');
        accParent2.ParentId = accParent1.id;
        accParent2.Type = 'Brand';
        insert accParent2;
        Account accParent3 = UnitTestDataFactory.createAccount('BatchTestClassAccount4', bh, 'Talabat_Account');
        accParent3.ParentId = accParent2.id;
        accParent3.Type = 'Brand';
        insert accParent3;
        Account accParent4 = UnitTestDataFactory.createAccount('BatchTestClassAccount5', bh, 'Talabat_Account');
        accParent4.ParentId = accParent3.id;
        accParent4.Type = 'Brand';
        insert accParent4;
        Account accChild = UnitTestDataFactory.createAccount('TestChild', bh, 'Talabat_Account');
        accChild.ParentId = accParent4.id;
        insert accChild;

    }

    @IsTest
    static void testUpdateOnlineStatusOnParentsAccount() {
        Account accChild = [select id from Account where ParentId != null and Name = 'TestChild'];
        Platform_Performance__c platPer = new Platform_Performance__c();

        List<Account> lstAccParent = new List<Account>();
        lstAccParent = [select id, Account_Status__c from Account where Account_Status__c = 'Online'];
        system.assertEquals(lstAccParent.size(),0);

        platPer.Account__c = accChild.id;
        platPer.Backend_ID__c = '';

        insert platPer;

        test.startTest();
        platPer.Backend_ID__c = '1234';
           update platPer;
        test.stopTest();

        lstAccParent = [select id,Name, Account_Status__c from Account where Account_Status__c = 'Online'];
        System.debug('lstAccParent-->'+lstAccParent);
        system.assertEquals(lstAccParent.size(),4);



    }
}