force-app/main/default/objects/Account/fields/Account_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Country_Code__c</fullName>
    <label>Account Country Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Restaurant</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stock Item currently assigned to this Asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New from manufacturer, A1 - New used, B - Used few scratches, A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/N</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Yogiyo Stock Item, FI Stock Item, SE Stock Item</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>DH AU Asset</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Ordered, New - In Stock, Assigned, In Shipping, Delivered, Retour in Progress, Lost, Returned - at Manufacturer, Recycled, Damaged, Writeoff, Tested, Returned - In Stock, Awaiting Delivery/In Shipment, In Stock, Technical Issue, Exchange Requested, Takeov</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/No longer usable</value>
        </filterItems>
        <infoMessage>In stock devices</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Asset Assignment</relationshipLabel>
    <relationshipName>Asset_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <description>Items that were or are are held in stock</description>
    <label>Stock Item</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Account Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stock Items</relationshipLabel>
    <relationshipName>Stock_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>New - In Stock</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Shipping</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Retour in Progress</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Returned - at Manufacturer</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Writeoff</fullName>
            </value>
            <value>
                <fullName>Tested</fullName>
            </value>
            <value>
                <fullName>Returned - In Stock</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery/In Shipment</fullName>
            </value>
            <value>
                <fullName>In Stock</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Pick-up Needed</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Stock_Item_Ownership__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item_Ownership__c</fullName>
    <description>Used to indicate Inventory Ownership</description>
    <label>Stock Item Ownership</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Field Agent</fullName>
            </value>
            <value>
                <fullName>HQ / office</fullName>
            </value>
            <value>
                <fullName>Manufacturer</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Warehouse ext.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DummyAssetsCreation_Batch.cls
/***
 * @description Batch class for creation of dummy asset for all migrated active accounts
 *              that don't have any SIM Card or Tablet
 * @date 19.05.2020
 * @author Danish Farooq
 * #ticket : SSC-2928
 * @param {name} {description}
 */
global class  DummyAssetsCreation_Batch implements Database.Batchable<SObject>, Database.Stateful {

    global Integer sequenceNumberStock = 1;
    String assetType;
    List<String> lstCountries;
    String companyCode;
    /**
   * @description Batch class constructor
   * @param companyCode concatenate with recordtype dev Name to generate ID (e.g. FP,Talabat)
   * @param countries countries for which Dummy Assets will be created
   * @param assetType Type of Assets (e.g Sim , Tablet)
   */
    global DummyAssetsCreation_Batch(String companyCode, String countries, String assetType) {

        this.assetType = assetType;
        this.lstCountries = (String.isNotBlank(countries) ? countries.split(',') : new List<string>());
        this.companyCode = companyCode;
    }
    /**
  * @description Batch class Start
  * @param bc BatchableContext
  * @return list of records from query locator
  */
    global Database.QueryLocator start(Database.BatchableContext bc) {

        String assetQueryClause = '%' + assetType + '%';
        return Database.getQueryLocator([
                SELECT id, record_country__c, currencyisocode, Account_Country_Code__c, GRID__c
                FROM account
                WHERE Account_status__c = 'Active' AND
                record_country__c IN :lstCountries AND ID NOT IN (
                SELECT account__c
                FROM asset__c
                WHERE name LIKE :assetQueryClause
                AND account__r.record_country__c IN :lstCountries
                )
        ]);
    }
    /**
    * @description Batch class Execute
    * @param bc BatchableContext
    * @param scope list of sobject
    */
    global void execute(Database.BatchableContext bc, List<SObject> scope) {

        Savepoint sp = Database.setSavepoint();
       try {
            LoggingUtility.createLog('DummyAssetsCreation_Batch', 'BATCH', 'Validate Email Flag', null);
            Map<ID, Account> mapOfAccountsByIds = new Map<ID, Account>((List<Account>) scope);
            List <Stock_item__c> lstStockItems = createStocks(mapOfAccountsByIds);
            insert lstStockItems;
            List <Asset__c> lstAssets = createAssets(lstStockItems, mapOfAccountsByIds);
            insert lstAssets;
       }
        catch(Exception ex){
            Database.rollback(sp);
            LoggingUtility.logError('DummyAssetsCreation_Batch','Error :' + ex.getMessage() + ';Line No : ' + ex.getLineNumber()
                                        + ';Stack Trace : ' + ex.getStackTraceString());
            LoggingUtility.commitLogs();
        }
    }
    /**
   * @description Batch class Finish
   * @param bc BatchableContext
   */
    global void finish(Database.BatchableContext bc) {
    }
    /**
    * @description create stock items
    * @param accountMap Map of Account
    * @return list of stock item to be insert
    */
    private List <Stock_item__c> createStocks(Map<ID, Account> accountMap) {

        List <Stock_item__c> lstStockItems = new List <Stock_item__c>();
        String stockItemRecordTypeId = LibRecordTypeHelper.getRecordTypeIdByDeveloperName('Stock_Item__c', companyCode + '_Stock_Item');
        String stockName = '';
        for (Account iAcc : accountMap.values()) {
            stockName = iAcc.Account_Country_Code__c + ' - Unknown ' + assetType + ' ' + sequenceNumberStock;
            lstStockItems.add(new Stock_item__c(
                    name = stockName,
                    Currencyisocode = iAcc.currencyisocode,
                    Account_Country__c = iAcc.record_country__c,
                    Status__c = 'In Stock',
                    Stock_Item_Ownership__c = 'Restaurant',
                    ID_Account__c = iAcc.Id,
                    Type__c = 'Original',
                    recordtypeid = stockItemRecordTypeId));
            sequenceNumberStock++;
        }

        return lstStockItems;
    }
    /**
   * @description create asset
    * @param lstStockItems list of stock item
    * @param accountMap Map of Account
    * @return list of asset to be insert
   */
    private List <Asset__c> createAssets(List <Stock_item__c> lstStockItems, Map<ID, Account> accountMap) {

        List <Asset__c> lstAssets = new List <Asset__c>();
        String assetRecordTypeId = LibRecordTypeHelper.getRecordTypeIdByDeveloperName('Asset__c', companyCode + '_Asset');
        for (Stock_item__c iStockItem : lstStockItems) {
            lstAssets.add(new Asset__c(
                    name = iStockItem.Name,
                    Currencyisocode = iStockItem.currencyisocode,
                    Account_Country__c = iStockItem.Account_country__c,
                    recordtypeid = assetRecordTypeId,
                    Account__c = iStockItem.ID_Account__c,
                    Stock_item__c = iStockItem.ID,
                    type__c = 'Original',
                    Status__c = 'Activated Successfuly',
                    GRID__c = (accountMap.containsKey(iStockItem.ID_Account__c) ? accountMap.get(iStockItem.ID_Account__c).GRID__c : '')));
        }
        return lstAssets;
    }
}