force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>SP-1725 - It represents the life cycle of an account</description>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Quality Check</fullName>
            </value>
            <value>
                <fullName>Menu processing</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Partially Online</fullName>
            </value>
            <value>
                <fullName>Win Back failed</fullName>
            </value>
            <value>
                <fullName>Active - Temp. Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>this hold the end date because the other end date is not writable</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>Service type of contract. Says whether a contract is a main service or an additional service (surcharge)</description>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/DE_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>DE_Opportunity</fullName>
    <active>true</active>
    <businessProcess>DE Sales Process</businessProcess>
    <label>DE Opportunity</label>
</RecordType>

force-app/main/default/classes/UnitTestBatchWinbackOpportunities.cls
/**
 * Created by w.novoa on 29.08.2018.
 */

@IsTest
private class UnitTestBatchWinbackOpportunities {
    private static Account acc_de;
    private static country__c c_de;
    private static Opportunity opp;
    private static Company__c com_de;
    private static case cs_de;
    static Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Case'});

    @testSetup static void setup() {

        UnitTestDataFactory.getRecordtypeValues();

        c_de = UnitTestDataFactory.createCountry('DE', 'Germany', 'EUR');
        insert c_de;
        com_de = UnitTestDataFactory.createCompany('Hungryhouse', 'DE', c_de);
        insert com_de;
        acc_de = UnitTestDataFactory.createAccount('TestAccount', c_de, 'DE_Account');
        acc_de.Account_Status__c = 'Terminated';
        acc_de.Type = 'Branch - Main';

        insert acc_de;


        List<Business_Config__c> listConfigs = new List<Business_Config__c>();
        listConfigs.add(UnitTestDataFactory.createBusinessConfig('WinbackOpportunities', 'Process', 'InvalidStatusReason', 'Business Closed,Duplicate,Fraud,Invalid,Legal Form Change,New Owner - New contract,New Owner - No new contract, Poor Performance,Cannot Contact,Obsolete,Downgrade,Upgrade', c_de.Id, 'DE_Account', true, true));
        listConfigs.add(UnitTestDataFactory.createBusinessConfig('WinbackOpportunities', 'Process', 'AccountType', 'Branch - Main,Brand,Group,Holding', c_de.Id, 'DE_Account', true, false));
        listConfigs.add(UnitTestDataFactory.createBusinessConfig('WinbackOpportunities', 'Process', 'OwnerId', String.valueof(System.userInfo.getUserId()), c_de.Id, 'DE_Account', true, false));
        listConfigs.add(UnitTestDataFactory.createBusinessConfig('WinbackOpportunities', 'Process', 'OpportunityRecordType', 'DE_Opportunity', c_de.Id, 'DE_Account', true, false));

        insert listConfigs;

        Contract con = new Contract();

        con.AccountId = acc_de.id;
        con.Service_Type__c = 'Commission Fee';
        con.End_Date__c = Date.TODAY().addDays(-180);

        insert con;
    }

    @IsTest
    static void testBehavior() {
        ScheduleBatchWinbackDE sch =new ScheduleBatchWinbackDE();

        Test.startTest();
        sch.execute(null);
        Test.stopTest();

        List<Opportunity> lstOptRes= [Select id from Opportunity where Business_Type__c = 'Win Back'];

        System.assert(lstOptRes.size()>0);
    }

}