force-app/main/default/objects/Account/fields/Avg_Commission_of_Cont_Franchise_Branch__c.field-meta.xml
<CustomField>
    <fullName>Avg_Commission_of_Cont_Franchise_Branch__c</fullName>
    <description>Average Commission of Cont. Franchise Branch</description>
    <label>Avg Commission of Cont. Franchise Branch</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Box_Available__c.field-meta.xml
<CustomField>
    <fullName>Box_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Box Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branches_In_Franchise_HQ__c.field-meta.xml
<CustomField>
    <fullName>Branches_In_Franchise_HQ__c</fullName>
    <description>Branches in Franchise HQ</description>
    <label>Branches in Franchise HQ</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <description>First Payment Date</description>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Shared_Menu__c.field-meta.xml
<CustomField>
    <fullName>Shared_Menu__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shared Menu</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Shared_Menu__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Branch - Main, Branch - Kitchen Restaurant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Shared Menu)</relationshipLabel>
    <relationshipName>Shared_Menu_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Total_Revenue__c</fullName>
    <description>Total Revenue from Orders with the Restaurant</description>
    <label>Total Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PY_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>PY_Opportunity</fullName>
    <active>true</active>
    <businessProcess>PY Sales Process</businessProcess>
    <label>PY Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Talabat_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Talabat Sales Process</businessProcess>
    <description>Talabat Opportunity</description>
    <label>Talabat Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/PY_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>PY_Opportunity_Quote</fullName>
    <active>true</active>
    <label>PY Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/Talabat_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Quote</fullName>
    <active>true</active>
    <label>Talabat Opportunity Quote</label>
</RecordType>

force-app/main/default/classes/ClsSObjectUtilsTest.cls
/**
* @author Mantas Jurkunas
* @date 25.01.2019
*
* @description Test class for testing ClsObjectUtils methods
* @see ClsSObjectUtils
*/

@IsTest
public with sharing class ClsSObjectUtilsTest {

    @TestSetup
    private static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c bh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        Database.insert(bh);
        Company__c com = UnitTestDataFactory.createCompany('Talabat', 'Talabat', bh);
        insert com;

        List<Business_Config__c> rules = new List<Business_Config__c>();

        rules.add(
                new Business_Config__c(
                        Record_Type_Id__c = 'Talabat_Account',
                        Id_Country__c = bh.Id,
                        Is_Active__c = true,
                        Parent__c = true,
                        Type__c = 'Process',
                        Process_Name__c = 'DelayedActivationOfContractsAndAddCharges',
                        Business_Rule_Name__c = 'parentAccountType',
                        Business_Rule_Value__c = 'Brand'
                )
        );

        rules.add(
                new Business_Config__c(
                        Record_Type_Id__c = 'Talabat_Account',
                        Id_Country__c = bh.Id,
                        Is_Active__c = true,
                        Parent__c = true,
                        Type__c = 'Process',
                        Process_Name__c = 'DelayedActivationOfContractsAndAddCharges',
                        Business_Rule_Name__c = 'childAccountType',
                        Business_Rule_Value__c = 'Branch'
                )
        );

        rules.add(
                new Business_Config__c(
                        Record_Type_Id__c = 'Talabat_Account',
                        Id_Country__c = bh.Id,
                        Is_Active__c = true,
                        Parent__c = false,
                        Type__c = 'Process',
                        Process_Name__c = 'DelayedActivationOfContractsAndAddCharges',
                        Business_Rule_Name__c = 'validContractStatuses',
                        Business_Rule_Value__c = 'Draft'
                )
        );

        rules.add(
                new Business_Config__c(
                        Record_Type_Id__c = 'Talabat_Account',
                        Id_Country__c = bh.Id,
                        Is_Active__c = true,
                        Parent__c = false,
                        Type__c = 'Process',
                        Process_Name__c = 'DelayedActivationOfContractsAndAddCharges',
                        Business_Rule_Name__c = 'contractActivationStatus',
                        Business_Rule_Value__c = 'Activated'
                )
        );
        Database.insert(rules);
        List<Account> accounts = UnitTestDataFactory.createAccounts(1, bh, 'Talabat_Account');
        Database.insert(accounts);
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accounts, 1, 'Talabat_Opportunity', Date.today());
        Database.insert(opportunities);
        List<Opportunity_Quote__c> oppQuotes = UnitTestDataFactory.createOpportunityQuotes(opportunities.get(0), 3, 'Talabat_Opportunity_Quote', 'Accepted', 'test', 100, 100, 'Test', 'Test', 10);
        Database.insert(oppQuotes);

    }

    /*******************************************************************************************************
    * @description test if approval process is being updated;
    */
    @IsTest
    public static void test_updateApprovalProcesses() {

        //change from talabat opportunity to PY as this approval process is not longer used by Talabat.

        Country__c bo = UnitTestDataFactory.createCountry('BO', 'Bolivia', 'BOB');
        Database.insert(bo);
        Company__c com = UnitTestDataFactory.createCompany('PedidosYa Bolivia', 'PY', bo);
        insert com;

        List<Account> accounts = UnitTestDataFactory.createAccounts(1, bo, 'PY_Account');
        Database.insert(accounts);
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accounts, 1, 'PY_Opportunity', Date.today());
        Database.insert(opportunities);
        List<Opportunity_Quote__c> oppQuotes = UnitTestDataFactory.createOpportunityQuotes(opportunities.get(0), 3, 'PY_Opportunity_Quote', 'Accepted', 'test', 100, 100, 'Test', 'Test', 10);
        Database.insert(oppQuotes);
        List<Approval.ProcessSubmitRequest> approvalRequests = new List<Approval.ProcessSubmitRequest>();


        ProcessDefinition currentApproval= ClsProcessDefinitionSelector.getApprovalProcessDefinition('Global - Approval Process');

        for(Opportunity_Quote__c oppQuote: oppQuotes) {
            Approval.ProcessSubmitRequest req1 =
                    new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval.');
            req1.setObjectId(oppQuote.Id);

            // Submit on behalf of a specific submitter
            req1.setSubmitterId(UserInfo.getUserId());

            req1.setProcessDefinitionNameOrId(currentApproval.DeveloperName);
            req1.setSkipEntryCriteria(true);

            approvalRequests.add(req1);
        }

        List<Approval.ProcessResult> results = Approval.process(approvalRequests);

        for(Approval.ProcessResult result: results) {
            System.assert(result.isSuccess());
        }

        Test.startTest();
            ClsSObjectUtils.updateApprovalProcesses(new Map<Id, Opportunity_Quote__c>(oppQuotes).keySet(), 'Removed');
        Test.stopTest();

        List<ProcessInstanceWorkitem> workItems = ProcessInstanceWorkItemSelector.findActiveWorkItemsByTargetIds(new Map<Id, Opportunity_Quote__c>(oppQuotes).keySet());

        System.assert(workItems == null || workItems.isEmpty());
    }

    /**
     * @description Test if changed values are filtered correctly
     */
    @IsTest
    public static void filterChangedValues_test() {

        Country__c kr = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        Database.insert(kr);

        List<Account> accounts = UnitTestDataFactory.createAccounts(4, kr, 'Talabat_Account');
        insert accounts;
        Map<Id, Account> accountMap = new Map<Id, Account>(accounts);
        List<Account> accountCopies = accounts.deepClone(true);
        for (Account accountCopy: accountCopies) {
            accountCopy.Name = 'CopyOfAccount';
            accountCopy.Backend_ID__c = '1234';
            accountCopy.First_Payment_Date__c = Date.newInstance(1992, 05, 14);
            accountCopy.Total_Revenue__c = 200;
            accountCopy.Avg_Commission_of_Cont_Franchise_Branch__c = 20;
            accountCopy.Box_Available__c = true;
            accountCopy.Branches_In_Franchise_HQ__c = 25;
        }

        List<Account> filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{'CopyOfAccount'},
                'First_Payment_Date__c' => new Set<Object> { Date.newInstance(1992, 05, 14), Date.newInstance(1992, 05, 15) }
        }, true);
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{'CopyOfAcc'},
                'First_Payment_Date__c' => new Set<Object> { Date.newInstance(1992, 05, 15) }
        });
        System.assertEquals(0, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Name' => new Set<Object>()
        });
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Name' => new Set<Object>(),
                'First_Payment_Date__c' => new Set<Object>(),
                'Total_Revenue__c' => new Set<Object>()
        }, true);
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Id' => new Set<Object>()
        });
        System.assertEquals(0, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{'CopyOfAccount'}, 'Backend_Id__c' => new Set<Object>{ '1234'}
        });
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accountCopies, accountMap, new Map<String, Set<Object>>{
                'Total_Revenue__c' => new Set<Object>{ Decimal.valueOf(25), Decimal.valueOf(200), Decimal.valueOf(10) },
                'Backend_Id__c' => new Set<Object>{ '1234'},
                'Avg_Commission_of_Cont_Franchise_Branch__c' => new Set<Object>{ Decimal.valueOf(20), Decimal.valueOf(200), Decimal.valueOf(10)},
                'Box_Available__c' => new Set<Object>{ true },
                'Branches_In_Franchise_HQ__c' => new Set<Object>{ Decimal.valueOf(28), Decimal.valueOf(25), Decimal.valueOf(10) }
        }, true);
        System.assertEquals(4, filteredAccounts.size());

    }

    /**
     * @description Test if changed values are filtered correctly
     */
    @IsTest
    public static void filterFieldValues_test() {

        Country__c kr = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        Database.insert(kr);

        List<Account> accounts = UnitTestDataFactory.createAccounts(4, kr, 'Talabat_Account');
        for (Account accountCopy: accounts) {
            accountCopy.Name = 'CopyOfAccount';
            accountCopy.Backend_ID__c = '1234';
        }

        insert accounts;

        accounts[0].Shared_Menu__r = accounts[1];

        List<Account> filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }
        });
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAcc' }
        });
        System.assertEquals(0, filteredAccounts.size());

        try {
            filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                    'Name' => null
            });
        } catch(ClsSObjectUtils.SObjectUtilsException e ) {}
        System.assertNotEquals(4, filteredAccounts.size());

        try {
            filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                    'Name' => null, 'Backend_Id__c' => null
            });
        } catch(ClsSObjectUtils.SObjectUtilsException e ) {}
        System.assertNotEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Backend_Id__c' => new Set<Object>{ '1234' }
        });
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Backend_Id__c' => new Set<Object>{ '12345' }
        }, true);
        System.assertEquals(0, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Backend_Id__c' => new Set<Object>{ '12345', '1234' }
        }, true);
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Shared_Menu__r.Backend_ID__c' => new Set<Object>{ '1234' }
        }, true);
        System.assertEquals(1, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
        'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Shared_Menu__r.Backend_ID__c' => new Set<Object>{ null }
        }, true);
        System.assertEquals(3, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Backend_ID__c' => new Set<Object>()
        }, true);
        System.assertEquals(4, filteredAccounts.size());

        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Name' => new Set<Object>{ 'CopyOfAccount' }, 'Shared_Menu__r.Backend_ID__c' => new Set<Object>()
        }, true);
        System.assertEquals(1, filteredAccounts.size());
        filteredAccounts = ClsSObjectUtils.filterFieldValues(accounts, new Map<String, Set<Object>>{
                'Shared_Menu__r.Backend_ID__c' => new Set<Object>()
        });
        System.assertEquals(1, filteredAccounts.size());

    }
}