force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Vertical_Segment__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accessories</fullName>
            </value>
            <value>
                <fullName>African</fullName>
            </value>
            <value>
                <fullName>Alcohol</fullName>
            </value>
            <value>
                <fullName>All Night Alcohol</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Aquariums</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Arepas y Empanadas</fullName>
            </value>
            <value>
                <fullName>Argentine</fullName>
            </value>
            <value>
                <fullName>argentinian</fullName>
                <label>Argentinian</label>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bakery</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbecue</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Beverages</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Burger and Grill</fullName>
            </value>
            <value>
                <fullName>Burgers</fullName>
            </value>
            <value>
                <fullName>Burmese</fullName>
            </value>
            <value>
                <fullName>Cafe</fullName>
            </value>
            <value>
                <fullName>Cakes &amp; Bakery</fullName>
            </value>
            <value>
                <fullName>Calzones</fullName>
            </value>
            <value>
                <fullName>Cambodian</fullName>
            </value>
            <value>
                <fullName>Cantonese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/MIDASApiException__c.field-meta.xml
<CustomField>
    <fullName>MIDASApiException__c</fullName>
    <label>MIDASApiException</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CountryCompanyBrand__c/CountryCompanyBrand__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryCompanyBrand</label>
</CustomObject>

force-app/main/default/objects/CountryCompanyBrand__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MidasIntegration__c/MidasIntegration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MidasIntegration</label>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <description>SP-1592</description>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClsAccountHelper.cls
public class ClsAccountHelper {
	
	/**
	* @Description: This method updates the owners of the restaunrats in MIDAS whenever the owner is change
	* @Params:  List<String> List of account Ids whose owners are changed
	*/
	@future(callout = true)
	public static void changeOwnershipOfTheAccount(List<String> accountIds){
		Map<Id,Account> accountmap = new Map<Id,Account>([Select Name,OwnerId,Owner.email,record_country__c,backend_id__c,recordType.developerName,
															 (Select Name,Backend_Id__c,Platform__c from Platforms_Performance__r)
														FROM Account
														where Id in: accountIds ]);
									
		makeCalloutToMidasForOwnershipChange(accountmap);
	}
	
	/**
	* @Description: This method makes callout to MIDAS for updating the ownerships
	* @Params: Map<Id,Account> Map of all the accounts
	*/
	public static void makeCalloutToMidasForOwnershipChange(Map<Id,Account> accountMap){
	    List<Account> accounts				= accountMap.values();
	    List<Account> failedAccounts		= new List<Account>();
	    List<Account> successfullAccounts 	= new List<Account>();
	    Set<Id> failedAccountIds			= new Set<Id>();
	    Set<Id> successfullAccountIds		= new Set<Id>();
	    String api							= '/ownerships';
	    String errorMessage 				= 'Error: There was a failure in updating owners of the account in MIDAS for some accounts\n';
        
        // Populate all the maps required
        Map<String,List<Account>> codeVsAccountsMap 		= populateCodeVsAccountsMap(accounts);
        
        DataWrapper wrapper		= new DataWrapper();
        wrapper.populateMetaData();
        for(String code : codeVsAccountsMap.keySet()){
        	List<Account> accountsToBeProcessed = codeVsAccountsMap.get(code);
        	HttpResponse res = new HttpResponse();      
        	Http http = new Http();
        	String uri = '/v2/sites/'+code+api;
        	
        	wrapper.populateData(accountsToBeProcessed);
        	String body 			= JSON.serialize(wrapper,true);
        	System.debug('Body => ' + body);
        	HttpRequest req 		= LibWebserviceHelper.constructMidasHttpRequest('PP',uri,'POST',body);
        	// Log
        	String logName = code+'OwnershipChange';
        	LoggingUtility.createLog(logName,'MIDAS','OWNERSHIP CHANGE',null);
        	LoggingUtility.log(logName,'code : ' + code + '\nBody => ' + body);
        	if(req!=null){
        		try{
	                LoggingUtility.captureTimeStamp(logName,'Begin');
                    res = http.send(req);
                    LoggingUtility.captureTimeStamp(logName,'End');
                    LoggingUtility.log(logName,'\nResponse Body : ' + res.getBody() + 'Response status code : ' + res.getStatusCode());
	                if(res.getStatusCode()==200) {
	                    ResultWrapper resWrapper = (ResultWrapper)JSON.Deserialize(res.getBody(),ResultWrapper.class);
	                    for(Result result : resWrapper.data.results){                	
	                    	if(result.status != 'OK'){
	                    		errorMessage += 'SF Restaurant Id: ' + result.ownership.sf_restaurant_id + 
	                    						' Error: ' + result.status_code+ ': ' +result.description + '\n';
        						LoggingUtility.logError(logName,errorMessage);
	                    		accountMap.get(result.ownership.sf_restaurant_id).MIDASApiException__c = 'Error: ' + result.description;
	                    		if(!failedAccountIds.contains(accountMap.get(result.ownership.sf_restaurant_id).Id)){
	                    			failedAccounts.add(accountMap.get(result.ownership.sf_restaurant_id));
	                    			failedAccountIds.add(accountMap.get(result.ownership.sf_restaurant_id).Id);
	                    		}
	                    	}else{
	                    		// Clear the MIDASApiException__c
	                    		Account acc = accountMap.get(result.ownership.sf_restaurant_id);
	                    		acc.MIDASApiException__c = null;
	                    		if(!successfullAccountIds.contains(acc.Id)){
	                    			successfullAccounts.add(acc);
	                    			successfullAccountIds.add(acc.Id);
	                    		}
	                    	}
	                    } 
	                }else{
	            		errorMessage = 'Error: The MIDAS Ownership change callout failed for some accounts';
	            		LoggingUtility.logError(logName,errorMessage);
	                    for(Account acc : accountsToBeProcessed){
	                    	acc.MIDASApiException__c = 'Error: ' + res.getBody();
	                    	if(!failedAccountIds.contains(acc.Id)){
	                    		failedAccounts.add(acc);
	                    		failedAccountIds.add(acc.Id);
	                    	}
	                    }
	                }
        		}catch(CalloutException e){
        			LoggingUtility.captureTimeStamp(logName,'End');
                	LoggingUtility.logError(logName,e.getMessage());
        		}
            }else{
               	throw new AccountHelperException('Error: MidasIntegration__c is not configured');
            } 
        }    
        
        if(successfullAccounts.size() > 0){
        	update successfullAccounts;
        }
        if(failedAccounts.size() > 0 ){
        	update failedAccounts;
        }   	
        
        LoggingUtility.commitLogs();
	}
	
	/**
	* @Description: This method populates a map of (Code => Accounts)
	*/
	@TestVisible
	private static Map<String,List<Account>> populateCodeVsAccountsMap(List<Account> accounts){
		Map<String,List<Account>> codeVsAccountsMap =  new Map<String,List<Account>>();
		for(Account acc : accounts){
			if(acc.Platforms_performance__r.size() > 0){
				for(Platform_Performance__c plat : acc.Platforms_performance__r){
					String platformName;
					if(acc.recordType.developerName == 'Talabat_Account'){
	 					platformName 	= plat.Name;
	 				}else{
	 					platformName	= plat.Platform__c;
	 				}
					if(CountryCompanyBrand__c.getInstance(platformName) == null){
						// Not throwing the error as configuration cannot be present for few platforms
						//throw new AccountHelperException('Error: CountryCompanyBrand__c configuration not present for ' + plat.platform__c);
						continue;
					}
					String code = CountryCompanyBrand__c.getInstance(platformName).code__c;
					if(!codeVsAccountsMap.containsKey(code)){
		        		codeVsAccountsMap.put(code,new List<Account>());
		        	}
		        	codeVsAccountsMap.get(code).add(acc);
				}
			}else{
				if(CountryCompanyBrand__c.getInstance(acc.record_country__c) == null){
					// Nor throwing the error as few platforms cannot have platforms and owner is changed
					//throw new AccountHelperException('Error: CountryCompanyBrand__c configuration not present for '+ acc.record_Country__c);
					continue;
				}
				String code = CountryCompanyBrand__c.getInstance(acc.record_country__c).code__c;
				if(!codeVsAccountsMap.containsKey(code)){
	        		codeVsAccountsMap.put(code,new List<Account>());
	        	}
	        	codeVsAccountsMap.get(code).add(acc);
			}
		}
		return codeVsAccountsMap;          
	}
	
	/**
    * Called from verifyFPCategory method. Add error for accounts where number of categories chosen is greater then 1
    * @param list of accounts
    */
    public static void verifyCategory(List<Account> accs){
		/*All the recordtype set of Account Object */
		Map<Id, RecordType> accRTMap = LibRecordTypeHelper.getRecordTypeForIds(new Set<String>{'Account'});
		/*Getting data from process name */
		Map<String, Map<String, Business_Config__c>> mapBusinessLogic = LibBusinessConfig.getGenericProcessData('oneCategoryRecordtypes');
		/*Getting all the business rules from process  */
		Map<String, Business_Config__c> mapBusinessRules = mapBusinessLogic.get('ALL');
		if(mapBusinessRules == null || mapBusinessRules.get('AccountRecordTypes') == null) {return;}
		/*Getting business rules related to Account recordtype  */
		Set<String> oneCatAccRTSet = new Set<String>(mapBusinessRules.get('AccountRecordTypes').Business_Rule_Value__c.split(','));

        List<String> lstCat = new List<String>();
        for(Account acc : accs){  
			if((accRTMap.get(acc.RecordTypeId) != null && !oneCatAccRTSet.contains(accRTMap.get(acc.RecordTypeId).developerName)) 
			|| String.isEmpty(acc.Category__c)) {continue;}
            lstCat = acc.Category__c.split(';');
            if(lstCat.size() > 1) acc.addError(Label.Error_message_for_Account_and_Lead_Category_Validation);
            lstCat.clear();
        }
    }
	
	/**
	* @Description: This class is a wrapper of the request generated
	*/
	public class DataWrapper{
		public Meta meta;
		public List<Data> data;
		
		public void populateMetaData(){
			String userEmail 	= UserInfo.getUserEmail();
			String userRole 	= [Select Name from UserRole where Id =: UserInfo.getUserRoleId()].Name;
			meta = new Meta(userEmail,userRole);
		}
		
		public void populateData(List<Account> accounts){
			data	= new List<Data>();
			for(Account acc : accounts){
				data.add(new Data(acc.owner.email,acc.Id));
			}
		}
	}
	
	/**
	* @Description: This class is a wrapper of the result
	*/
	public class ResultWrapper{
		public Data data;
	}
	
	public class Meta{
		public String username;
		public String sf_role;
		
		public Meta(String username,String sf_role){
			this.username 	= username;
			this.sf_role	= sf_role;
		}
	}
	
	public class Data{
		public String username;
		public Integer restaurant_id;
		public String sf_restaurant_id;
		public List<Result> results;
		
		public Data(String username,String sf_restaurant_id){
			this.username 			= username;
			this.sf_restaurant_id	= sf_restaurant_id;
		}
	}
	
	public class result{
		public String status;
		public String status_code;
		public String description;
		public Ownership ownership;
	}
	
	public class Ownership{
		public String username;
		public Integer restaurant_id;
		public String sf_restaurant_id;
	}
	
	public class AccountHelperException extends Exception{}
}