force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logging__c/Logging__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>use this custom setting to disable or enable Logging
1. Disable a particular type to disable the logging for that particular type
2. Enable ONLY_ERROR_LOGGING to log only errors

NOTE: If you can enable only error logging and still you have not disbaled logging for particular type, it will log for both errors and that particular type. If you just want to log error disbale all the other types and enable logging.</description>
    <label>Logging</label>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Contract_Number_SAP__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number_SAP__c</fullName>
    <description>Contract Number in SAP group by &quot;Razon Social&quot;</description>
    <externalId>true</externalId>
    <label>Contract number SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Debt_Value__c.field-meta.xml
<CustomField>
    <fullName>Debt_Value__c</fullName>
    <description>the debt value ( from SAP)</description>
    <label>Debt value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Number_Pending_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Number_Pending_Invoices__c</fullName>
    <description>The number of pending invoices( from SAP)</description>
    <label>Number of pending invoices</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DebtStatusTest.cls
/**
 * Created by w.novoa on 30.04.20.
 */
@IsTest
public with sharing class DebtStatusTest {
    @testSetup
    static void testSetup() {

        UnitTestDataFactory.getRecordtypeValues();
        country__c country  = UnitTestDataFactory.createCountry('AR', 'Argentina', 'ARS');
        insert country;
        Company__c company = UnitTestDataFactory.createCompany('PedidosYA', 'PY', country);
        insert company;
        Business_Config__c business = new Business_Config__c(Business_Rule_Name__c = 'AssetStatus', Business_Rule_Value__c = 'Canceled', Id_Country__c = country.id, Is_Active__c = true, Parent__c = true, Process_Name__c = 'AssetStockProcess', Record_Type_Id__c = 'PY_Account', Type__c = 'Process');
        insert business;
        Account account = UnitTestDataFactory.createAccount('TestAccount', country, 'PY_Account');
        insert account;

        Platform_Performance__c platformPerformance = new Platform_Performance__c();
        platformPerformance.Account__c = account.id;
        platformPerformance.Backend_ID__c = '12';
        platformPerformance.Contract_Number_SAP__c = '10';

        insert platformPerformance;
    }
    @IsTest
    static void updateplatformdebtPositive() {
        insert new Logging__c(SetupOwnerId=UserInfo.getOrganizationId());
        String jsonUpdate= '{"countryName":"Argentina","recordTypeName":"PY_Account","debtInformation":[{"numberPendingInvoices":1,"debtValue":1111111,"contractSAP":"10"},{"numberPendingInvoices":123,"debtValue":null,"contractSAP":11}]}';
        RestRequest request = new RestRequest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        request.requestUri =baseUrl +'/services/apexrest/DebtStatusRestService/';

        request.httpMethod = 'POST';
        request.requestBody = Blob.valueof(jsonUpdate);
        RestContext.request = request;
        test.startTest();
        DebtStatusRestHelper.ResponseWrapper response= DebtStatusRestService.doPost();
        test.stopTest();
        System.assertEquals('SUCCESS',response.status);
        Platform_Performance__c platform = [select id,Debt_Value__c,Number_Pending_Invoices__c
                                            from Platform_Performance__c limit 1 ];

        System.assertEquals(1111111,platform.Debt_Value__c);
        System.assertEquals(1,platform.Number_Pending_Invoices__c);

    }

    @IsTest
    static void updateplatformdebtNegatiive() {
        insert new Logging__c(SetupOwnerId=UserInfo.getOrganizationId());
        String jsonUpdate= '{"countryName":"Argentina","recordTypeName":"PY_Account","debtInformation":[{"numberPendingInvoices":1234,"debtValue":1111111,"contractSAP":"10"},{"numberPendingInvoices":123,"debtValue":null,"contractSAP":11}]}';
        RestRequest request = new RestRequest();
        String baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        request.requestUri =baseUrl +'/services/apexrest/DebtStatusRestService/';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueof(jsonUpdate);
        RestContext.request = request;
        test.startTest();
        DebtStatusRestHelper.ResponseWrapper response= DebtStatusRestService.doPost();
        test.stopTest();
        System.assertEquals('FAIL',response.status);

    }
}