force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>Restaurant Backend Id</description>
    <formula>Account.Backend_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Backend ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/fields/ClientId__c.field-meta.xml
<CustomField>
    <fullName>ClientId__c</fullName>
    <label>ClientId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>ClientSecret__c</fullName>
    <label>ClientSecret</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <label>Timeout</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>Object used to store the invoice information coming from Juston Connector.</description>
    <label>Invoice</label>
    <nameField>
        <label>Invoices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Master Detail relationship to Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>The invoice date that is printed on the invoice.</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>The invoice number of the invoice in the billing org. (previously called &quot;No&quot; in old org)</description>
    <externalId>true</externalId>
    <label>Invoice Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <formula>Account__r.GRID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GRID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <description>SP-1592</description>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CtrViewInvoicePDF.cls
/**
 * Created by marco.zeuli on 17/5/2018.
 */

public with sharing class CtrViewInvoicePDF {
    private static final String PLATFORM_PIZZADE = 'PizzaDE';
    private static final String PLATFORM_LIEFEHELDDE = 'LieferheldDE';

    static final Map<String, String> platformToApiSettings = new Map<String, String>{
            PLATFORM_PIZZADE => 'AWS_S3_PDE_Invoices',
            PLATFORM_LIEFEHELDDE => 'AWS_S3_LIH_Invoices'
    };

    public CtrViewInvoicePDF(ApexPages.StandardController stdCtr) {
    }

    /**
     * Given an Invoice's id, retrieves from S3 bucket the PDF file
     *
     * @param invoiceId Invoice's id
     *
     * @return An instance of ResponseWrapper
     */
    @RemoteAction
    public static ResponseWrapper getInvoicePDF(String invoiceId) {
        ResponseWrapper res;

        System.debug('CtrViewInvoicePDF.getInvoicePDF: start, invoice id is: ' + invoiceId);

        try {

            // retrieves invoice record
            Invoice__c invoice = [
                    SELECT
                            Date__c,
                            Invoice_Number__c,
                            Account__c,
                            Account__r.GRID__c,
                            Platform__c
                    FROM Invoice__c
                    WHERE Id = :invoiceId
            ];

            // retrieve api settings based on the platform name
            Integration_Config__c apiSettings = Integration_Config__c.getValues(
                    platformToApiSettings.get(invoice.Platform__c)
            );

            System.debug('CtrViewInvoicePDF.getInvoicePDF: invoice is: ' + invoice);

            // retrieves platform
            Platform_Performance__c plat = useAccountGRID(invoice) ? null :
                    [
                        SELECT
                                Backend_ID__c, GRID__c
                        FROM Platform_Performance__c
                        WHERE Account__c = :invoice.Account__c
                        AND Platform__c = :invoice.Platform__c
                    ];

            System.debug('CtrViewInvoicePDF.getInvoicePDF: platform is: ' + plat);

            Datetime tmp = Datetime.newInstance(
                    invoice.Date__c.year(),
                    invoice.Date__c.month(),
                    invoice.Date__c.day()
            );

            // creates invoice's url
            String pdfUrl = String.format(
                    apiSettings.Endpoint__c + '/{0}/{1}/{2}/{3}_{4}.pdf',
                    new List<String>{
                            useAccountGRID(invoice) ? invoice.Account__r.GRID__c : plat.GRID__c,
                            tmp.format('yyyy'),
                            tmp.format('MM'),
                            tmp.format('yyyyMMdd'),
                            invoice.Invoice_Number__c
                    }
            );

            System.debug('CtrViewInvoicePDF.getInvoicePDF: url is: ' + pdfUrl);

            // create AWS signed request
            HttpRequest request = new AWSConnector(
                    apiSettings.ClientId__c,
                    apiSettings.ClientSecret__c,
                    's3',
                    'eu-central-1'
            ).signedRequest(
                    'GET',
                    new Url(pdfUrl),
                    null,
                    null,
                    false
            );

            request.setTimeout(apiSettings.Timeout__c.intValue());

            System.debug('CtrViewInvoicePDF.getInvoicePDF: request is: ' + request);

            // send request
            HttpResponse response = new Http().send(request);

            System.debug('CtrViewInvoicePDF.getInvoicePDF: response is: ' + response);

            if (response.getStatusCode() == 200) {
                res = new ResponseWrapper(true, EncodingUtil.base64Encode(response.getBodyAsBlob()));
            } else {
                res = new ResponseWrapper(false, Label.AWS_S3_Bucket_download_error + response.getBody());
            }

        } catch (Exception e) {
            System.debug('CtrViewInvoicePDF.getInvoicePDF: exception occurred. Message is: ' + e.getMessage() + ' - Stacktrace is: ' + e.getStackTraceString());
            res = new ResponseWrapper(false, Label.AWS_S3_Bucket_download_error + e.getMessage());
        }

        System.debug('CtrViewInvoicePDF.getInvoicePDF: done');
        return res;
    }

    /**
     * @description Checks whether the invoice is platform dependant or not.
     *
     * @param invoice Invoice__c
     *
     * @return Boolean
     */
    private static Boolean useAccountGRID(final Invoice__c invoice) {
        return invoice.Platform__c.equalsIgnoreCase(PLATFORM_LIEFEHELDDE) ||
                invoice.Platform__c.equalsIgnoreCase(PLATFORM_PIZZADE);
    }

    /**
     * Response wrapper. If no error occurred success flag will be set to true otherwise to false.
     * Data will hold the base64 pdf string or an error message in case success is set to false
     */
    public class ResponseWrapper {
        public Boolean success {
            get;
            set;
        }
        public String data { get; set; }
        public ResponseWrapper(Boolean success, String data) {
            this.success = success;
            this.data = data;
        }
    }
}