force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>SP-1592</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Contract_Number_SAP__c.field-meta.xml
<CustomField>
    <fullName>Contract_Number_SAP__c</fullName>
    <description>Contract Number in SAP group by &quot;Razon Social&quot;</description>
    <externalId>true</externalId>
    <label>Contract number SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Debt_Value__c.field-meta.xml
<CustomField>
    <fullName>Debt_Value__c</fullName>
    <description>the debt value ( from SAP)</description>
    <label>Debt value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/GMVClass__c.field-meta.xml
<CustomField>
    <fullName>GMVClass__c</fullName>
    <description>created for SP-3704</description>
    <label>GMV Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Number_Pending_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Number_Pending_Invoices__c</fullName>
    <description>The number of pending invoices( from SAP)</description>
    <label>Number of pending invoices</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <description>SP-1592</description>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform_Online_Status__c.field-meta.xml
<CustomField>
    <fullName>Platform_Online_Status__c</fullName>
    <label>Platform Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Online_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <description>Represents if the Account is active or not for the platform based on the contracts&apos; status</description>
    <label>Vendor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Online_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <customValue>
        <fullName>On Holiday</fullName>
    </customValue>
    <customValue>
        <fullName>In Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Quality Check</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Initiated</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Final Check</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Changes Requested</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Approval Pending</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Take Online</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Backend ID Creation</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Menu Typing</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Delivery Area</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Offline</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Take Online</fullName>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <customValue>
        <fullName>true</fullName>
        <isActive>false</isActive>
        <label>true</label>
    </customValue>
    <customValue>
        <fullName>false</fullName>
        <isActive>false</isActive>
        <label>false</label>
    </customValue>
    <customValue>
        <fullName>Offline - current day</fullName>
        <isActive>false</isActive>
        <label>Offline - current day</label>
    </customValue>
    <masterLabel>Online Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlatformPerformanceSelector.cls
/**
* @author g.singh
* @date 2019-05-03.
*
* @description Selector class for retrieving platformPerformance records
*/

public inherited sharing class PlatformPerformanceSelector {
    /*******************************************************************************************************
    * @description Returns Platfrom Performances for a set of Accounts
    * @param accountIds - Set<Id> - Ids of related Accounts
    * @return List<Platform_Performance__c>
    */
    public static List<Platform_Performance__c> getPlatformPerformancesForAccounts(Set<Id> accountIds) {
        return [SELECT Id, Account__c, Platform__c, Platform_Online_Status__c, Vendor_Status__c, GMVClass__c
            FROM Platform_Performance__c
            WHERE Account__c IN :accountIds];
    }

  

    /**
    * @author Tarun Jain
    * @date 25-Feb-20
    * @description This method returns the platform performance records based on backend ids
    * SCC-124
    * @return List<Platform_Performance__c>
    * @param  List<String> backendIds
    */
    public static List<Platform_Performance__c> getPlatformPerformancesByBackendIds(Set<String> backendIds) {
        List<Platform_Performance__c> platformPerformances = new List<Platform_Performance__c>();
        platformPerformances = [SELECT Id,Account__c,Backend_ID__c,Platform__c FROM Platform_Performance__c WHERE Backend_ID__c IN:backendIds];
        return platformPerformances;
    }

    /**
     * @author William Castillo.
     * @date 30-Apr-20
     * @description This method return the platform performance by contract number from sap
     * SCC-14
     * @return List<Platform_Performance__c>
     * @param  set<String> contractsNumbers
     */
    public static List<Platform_Performance__c> getPlatformPerformancesByContracts(Set<String> contractsNumbers, String country, string recordType) {
        List<Platform_Performance__c> platformPerformances = new List<Platform_Performance__c>();
        platformPerformances = [select id,Debt_Value__c,Number_Pending_Invoices__c,Contract_Number_SAP__c,Account__r.Record_Country__c, Account__r.RecordType.DeveloperName
                                    from Platform_Performance__c
                                    where Contract_Number_SAP__c IN:contractsNumbers
                                      AND Account__r.Record_Country__c =: country
                                      AND Account__r.RecordType.DeveloperName =: recordType];
        return platformPerformances;
    }
}