force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CD Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>$Source.RecordTypeId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <filterItems>
            <field>Account.Backend_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Brand)</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Chain__c.field-meta.xml
<CustomField>
    <fullName>Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CD Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>$Source.RecordTypeId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Chain</value>
        </filterItems>
        <filterItems>
            <field>Account.Backend_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Company_Number__c.field-meta.xml
<CustomField>
    <fullName>Company_Number__c</fullName>
    <description>this field is used to store the company id</description>
    <label>Company Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Minimum_order_value_Cash__c.field-meta.xml
<CustomField>
    <fullName>Minimum_order_value_Cash__c</fullName>
    <label>Minimum order value - Cash</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BEIntegration_CountriesToCities__c/BEIntegration_CountriesToCities__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Each entry in this custom setting represents a city. City&apos;s name is in Name field of the record.</description>
    <label>BEIntegration_CountryToCities</label>
</CustomObject>

force-app/main/default/objects/BEIntegration_CountriesToCities__c/fields/City_Backend_Id__c.field-meta.xml
<CustomField>
    <fullName>City_Backend_Id__c</fullName>
    <label>City Backend Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BEIntegration_CountriesToCities__c/fields/Country_Backend_Id__c.field-meta.xml
<CustomField>
    <fullName>Country_Backend_Id__c</fullName>
    <label>Country Backend Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country on related Account</description>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <inlineHelpText>Country on related Account</inlineHelpText>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MidasIntegration__c/MidasIntegration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MidasIntegration</label>
</CustomObject>

force-app/main/default/classes/ClsGetBackendIdAccount.cls
global class ClsGetBackendIdAccount {

    webservice static String getBackendIdAccount(String accId, String accType) {
        try {
            String label = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().get('Backend_ID__c').getDescribe().getLabel();
            //get account details
            Account acc = [Select Id, Name, Restaurant_Name__c, Backend_ID__c, BillingStreet, BillingCity, Phone, Delivery_Fee__c, Minimum_order_value_Cash__c,
                           parent.Backend_ID__c, parent.parent.Backend_ID__c, Company_Number__c, Brand__c, parent.Chain__c, Record_Country__c, parent.brand__c
                           from account where Id = : accId];

            // get the contacts:
            List<Contact> conlst = [Select Id, email, Phone from contact where id in (select contactid from AccountContactRelation  where accountid = : accId)];



            //Construct Body
            String body;
            String backEndId;
            String path;
            BEIntegration_CountriesToCities__c cntCit;
            if (accType == 'Client' || accType == 'Branch') {
                cntCit = BEIntegration_CountriesToCities__c.getValues(acc.BillingCity);
                //check if cntCit != null
                if (cntCit == null) {return 'warning';}
            }
            if (accType == 'Client') {
                // set the path
                path = '/clients/create';
                //Construct body
                // Billing Street can contain new line characters.  we need to escape it
                String street =  acc.BillingStreet;
                street = street.replace('\r\n', ' ');
                street = street.replace('\n', ' ');
                street = street.replace('\r', ' ');


                String bodySt = '{"salesforce-id":'     + '"' + String.valueOf(acc.Id)  + '"' + ',' +
                                '"legal-number":'       + '"' + acc.Company_Number__c   + '"'   + ',' +
                                '"address":'                + '"' + street                  + '"'   +  ',' +
                                '"city-id":'                + '"' + cntCit.City_Backend_Id__c + '"' +  ',' +
                                '"country-id":'         + '"' + cntCit.Country_Backend_Id__c + '"'  + ',' +
                                '"legal-name":'         + '"' + acc.Name        + '"' + ',' +
                                '"commercial-name":'    + '"' + acc.Restaurant_Name__c  + '"' + ',' +
                                '"salesperson-email":'    + '"' + UserInfo.getUserEmail() + '"'   + ',';
                String bodyParEmail = '';
                String bodyParPhone = '';
                for (contact con : conlst) {
                    bodyParEmail += con.email + ',';
                    bodyParPhone += con.Phone + ',';
                }

                //body
                body = bodySt + '"contact-emails":' + '"' + bodyParEmail.removeEnd(',') + '"' + ',' + '"contact-phones":' + '"' + bodyParPhone.removeEnd(',') + '"' + '}';
                system.debug(body);
            }
            // Brand
            if (accType == 'Brand') {
                path = '/brands/create';
                String bodySt = '{"salesforce-id":' + '"' + String.valueOf(acc.Id)  + '"' + ',' + '"name":' + '"' + acc.Name + '"' + '}';

                body = bodySt;
                system.debug(body);
            }

            if (accType == 'Franchise') {
                path = '/franchises/create';
                String bodySt = '{"salesforce-id":'     + '"' + String.valueOf(acc.Id)    + '"' + ',' +
                                '"name":'           + '"' + acc.Name            + '"'   + ',' +
                                '"client-id":'        + '"' + acc.parent.Id   + '"'   + ',' +
                                '"brand-id":'         + '"' + acc.Brand__c        + '"';

                //body
                body = bodySt + '}';
            }

            if (accType == 'Branch') {

                String street =  acc.BillingStreet;
                street = street.replace('\r\n', ' ');
                street = street.replace('\n', ' ');
                street = street.replace('\r', ' ');

                path = '/branches/create';
                String bodySt = '{"salesforce-id":'     + '"' + String.valueOf(acc.Id)        + '"' + ',' +
                                '"brand-id":'           + '"' + acc.parent.brand__c             + '"'   + ',' +
                                '"client-id":'          + '"' + acc.parent.parent.Id            + '"' + ',' +
                                '"address":'          + '"' + street                              + '"' + ',' +
                                '"name":'           + '"' + acc.Name              + '"' + ',';

                //min-order-amount and delivery-cost are optional fields
                //in the request message. only include them if populated.

                if (acc.phone != null) {bodySt += '"manager-phone":' + '"' + acc.Phone + '"' + ',';}
                if (acc.Delivery_Fee__c != null) {bodySt += '"min-order-amount":' + acc.Delivery_Fee__c + ',';}
                if (acc.Minimum_order_value_Cash__c != null) {bodySt += '"delivery-cost":' + acc.Minimum_order_value_Cash__c + ',';}

                bodySt += '"city-id":' + '"' + cntCit.City_Backend_Id__c + '"' + ',';
                bodySt += '"country-id":' + '"'  + cntCit.Country_Backend_Id__c + '"';

                body = bodySt + '}';
                system.debug('body' + body);
            }

            HttpResponse res = new HttpResponse();
            Http http = new Http();

            //system.debug('countrycode' + acc.Record_Country__c);
            HttpRequest req = LibWebserviceHelper.constructMidasHttpRequest(acc.Record_Country__c, path, 'POST', body);

            if (req != null) {
                res = http.send(req);
                if (res.getStatusCode() == 201 || res.getStatusCode() == 200) {
                    JSONParser parser = JSON.createParser(res.getBody());

                    while (parser.nextToken() != null) {
                        if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getCurrentName() == 'Id') {
                            parser.nextToken();
                            backEndId = parser.getText();
                            break;
                        }
                    }
                } else {
                    return 'Error:' + res.getStatus();
                }

            } else {
                return 'MidasIntegration__c is not configured';
            }


            acc.Backend_ID__c = backEndId;

            update acc;
            return 'SUCCESS:' + label + ':' + acc.Backend_ID__c;
        } catch (Exception e) {
            return 'Error: ' + e.getMessage();
        }


    }


}