force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CD Account</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <valueField>$Source.RecordTypeId</valueField>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Brand</value>
        </filterItems>
        <filterItems>
            <field>Account.Backend_ID__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Brand)</relationshipLabel>
    <relationshipName>Brand</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Franchise_Connection__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Only use to establish a connection between TWO hierarchies, used mostly for billing transfers on Opportunity level.</description>
    <inlineHelpText>Only use to establish a connection between TWO hierarchies, used mostly for billing transfers on Opportunity level</inlineHelpText>
    <label>Franchise Connection</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Franchise, DH Concept</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Franchise Connection)</relationshipLabel>
    <relationshipName>AccountsFranchise</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Franchise_Type__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Type__c</fullName>
    <description>Only use to indicate if a Restaurant is managed via Headquarter or individually in a hierarchy</description>
    <inlineHelpText>Only use to indicate if a Restaurant is managed via Headquarter or individually in a hierarchy</inlineHelpText>
    <label>Franchise Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Directly managed</fullName>
            </value>
            <value>
                <fullName>Indirectly managed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CD_Account.recordType-meta.xml
<RecordType>
    <fullName>CD_Account</fullName>
    <active>true</active>
    <description>Account for Click Delivery</description>
    <label>CD Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UnitTestCtrAccountHierarchy.cls
@isTest
private class UnitTestCtrAccountHierarchy {

    @testSetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();

        Country__c c = UnitTestDataFactory.createCountry('EC', 'Ecuador', 'USD');
        insert c;

        insert new Business_Config__c(
            Record_Type_Id__c = 'CD_Account',
            Id_Country__c = c.Id,
            Is_Active__c = true,
            Parent__c = true,
            Type__c = 'Process',
            Process_Name__c = 'Account Hierarchy',
            Business_Rule_Name__c = 'FieldsToQuery',
            Business_Rule_Value__c = '[{"apiName": "Name", "isHeaderField":true, "relationshipField": "", "isLookup": false, "isPicklist": false }, {"apiName": "Type", "relationshipField": "", "isLookup": false, "isPicklist": true }, {"apiName": "Brand__c", "relationshipField": "Brand__r.Name", "isLookup": true, "isPicklist": false }, {"apiName": "Backend_ID__c", "relationshipField": "", "isLookup": false, "isPicklist": false }]'
        );

        Account client = UnitTestDataFactory.createAccount('client', c, 'CD_Account');
        client.Type = 'Client';
        insert client;

        Account franchise1 = UnitTestDataFactory.createAccount('franchise1', c, 'CD_Account');
        franchise1.ParentId = client.Id;
        franchise1.Type = 'Franchise';

        Account franchise2 = UnitTestDataFactory.createAccount('franchise2', c, 'CD_Account');
        franchise2.ParentId = client.Id;
        franchise2.Type = 'Franchise';

        List<Account> accountList = new List<Account>{franchise1, franchise2};

        insert accountList;

        List<Account> branches = new List<Account>();

        Account aBranch = UnitTestDataFactory.createAccount('aBranch', c, 'CD_Account');
        aBranch.ParentId = client.Id;
        aBranch.Franchise_Connection__c = accountList[0].Id;
        aBranch.Type = 'relFranchise';
        aBranch.Franchise_Type__c = 'Indirectly managed';

        branches.add(aBranch);

        Account aBranch2 = UnitTestDataFactory.createAccount('aBranch2', c, 'CD_Account');
        aBranch.Franchise_Connection__c = client.Id;
        aBranch.Type = 'relFranchise2';
        aBranch.Franchise_Type__c = 'Indirectly managed';

        branches.add(aBranch2);

        for (Integer i = 0; i < 10; i++) {
            Account branch = UnitTestDataFactory.createAccount('branch ' + i, c, 'CD_Account');
            branch.ParentId = Math.mod(i, 2) == 0 ? franchise1.Id : franchise2.Id;
            branch.Type = 'Branch';
            branches.add(branch);
        }

        insert branches;
    }

    @isTest static void constructorsInstantiateCorrectly() {

        Account a = [select id from account limit 1];

        Test.startTest();

        Test.setCurrentPage(Page.AccountHierarchy);

        ApexPages.StandardController stdCtr = new ApexPages.StandardController(a);

        CtrAccountHierarchy ctr1 = new CtrAccountHierarchy();
        CtrAccountHierarchy ctr2 = new CtrAccountHierarchy(stdCtr);

        Test.stopTest();
    }

    @isTest static void getHeadersReturnsEmptyListIfNoBCForRecordType() {

        List<String> res;

        Test.startTest();

        res = CtrAccountHierarchy.getHeaders('RecordType that do not exist');

        Test.stopTest();

        System.assertNotEquals(null, res);
        System.assert(res.isEmpty());
    }

    @isTest static void getHeadersReturnsCorrectly() {
        List<String> res;

        Test.startTest();

        res = CtrAccountHierarchy.getHeaders('CD_Account');

        Test.stopTest();

        System.assert(!res.isEmpty());
    }

    @isTest static void getTreeReturnsCorrectlyWithRootAccount() {

        Account root = [Select Id from Account Where Type = 'Client' limit 1];

        List<CtrAccountHierarchy.TreeNode> res;

        Test.startTest();

        res = CtrAccountHierarchy.getTree(root.Id);

        Test.stopTest();

        System.assertNotEquals(null, res);
        System.assertEquals(1, res.size());
        System.assertEquals(root.Id, res[0].Id);
    }

    @isTest static void getTreeReturnsCorrectlyWithFranchiseAccount() {

        Account root = [Select Id from Account Where Type = 'Client' limit 1];
        Account franc = [Select Id from Account Where Type = 'Franchise' limit 1];

        List<CtrAccountHierarchy.TreeNode> res;

        Test.startTest();

        res = CtrAccountHierarchy.getTree(franc.Id);

        Test.stopTest();

        System.assertNotEquals(null, res);
        System.assertEquals(1, res.size());
        System.assertEquals(root.Id, res[0].Id);
    }

    @isTest static void getTreeReturnsCorrectlyWithBranchAccount() {

        Account root = [Select Id from Account Where Type = 'Client' limit 1];
        Account branch = [Select Id from Account Where Type = 'Branch' limit 1];

        List<CtrAccountHierarchy.TreeNode> res;

        Test.startTest();

        res = CtrAccountHierarchy.getTree(branch.Id);

        Test.stopTest();

        System.assertNotEquals(null, res);
        System.assertEquals(1, res.size());
        System.assertEquals(root.Id, res[0].Id);
    }


    @isTest static void getFranchiseHierarchyReturnsCorrectlyWithNoFranchise() {

        Account root = [Select Id from Account Where Type = 'Client' limit 1];

        List<CtrAccountHierarchy.TreeNode> res;

        Test.startTest();

        res = CtrAccountHierarchy.getFranchiseHierarchy(root.Id);

        Test.stopTest();

        System.assertEquals(null, res);
    }

    @isTest static void getFranchiseHierarchyReturnsCorrectlyWithFranchise() {

        Account root = [Select Id from Account Where Type = 'Client' limit 1];
        Account franc = [Select Id from Account Where Name = 'aBranch' limit 1];

        List<CtrAccountHierarchy.TreeNode> res;

        Test.startTest();

        res = CtrAccountHierarchy.getFranchiseHierarchy(franc.Id);

        Test.stopTest();

        System.assertNotEquals(null, res);
        System.assertEquals(1, res.size());
        System.assertEquals(root.Id, res[0].Id);
    }

    @isTest static void test_getFranchiseChildRelations() {

        Account root = [Select Id from Account Where Type = 'Client' limit 1];
        Account franc = [Select Id from Account Where Name = 'aBranch2' limit 1];

        List<CtrAccountHierarchy.TreeNode> res;

        Test.startTest();

        res = CtrAccountHierarchy.getFranchiseChildRelations(root.Id);

        Test.stopTest();

        System.assertNotEquals(null, res);
        System.assertEquals(1, res.size());
        System.assertEquals(root.Id, res[0].Id);
    }
}