force-app/main/default/objects/Account/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>this field is used to store the backend id of the restaurant</description>
    <externalId>true</externalId>
    <label>Backend ID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/UK_Account.recordType-meta.xml
<RecordType>
    <fullName>UK_Account</fullName>
    <active>true</active>
    <label>UK Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Yogiyo_Account.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Account</fullName>
    <active>true</active>
    <description>KR Account Recordtype</description>
    <label>Yogiyo Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/Backend_ID__c.field-meta.xml
<CustomField>
    <fullName>Backend_ID__c</fullName>
    <description>Restaurant Backend Id</description>
    <formula>Account.Backend_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Backend ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryCompanyBrand__c/CountryCompanyBrand__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryCompanyBrand</label>
</CustomObject>

force-app/main/default/objects/CountryCompanyBrand__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/UK_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>UK_List_Product_Group</fullName>
    <active>true</active>
    <label>UK List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/UK_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>UK_List_Product_Price</fullName>
    <active>true</active>
    <label>UK List Product Price</label>
</RecordType>

force-app/main/default/objects/MidasIntegration__c/MidasIntegration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>MidasIntegration</label>
</CustomObject>

force-app/main/default/objects/MidasIntegration__c/fields/AuthenticationToken__c.field-meta.xml
<CustomField>
    <fullName>AuthenticationToken__c</fullName>
    <label>AuthenticationToken</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MidasIntegration__c/fields/CountryBrand__c.field-meta.xml
<CustomField>
    <fullName>CountryBrand__c</fullName>
    <label>CountryBrand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MidasIntegration__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/UK_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>UK_Opportunity</fullName>
    <active>true</active>
    <businessProcess>UK Sales Process</businessProcess>
    <label>UK Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Booking_Api_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Api_Id__c</fullName>
    <externalId>true</externalId>
    <label>Booking Api Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/UK_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>UK_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>UK Opportunity Line Item</label>
</RecordType>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/UK_Tarif.recordType-meta.xml
<RecordType>
    <fullName>UK_Tarif</fullName>
    <active>true</active>
    <label>UK Tarif</label>
</RecordType>

force-app/main/default/classes/UnitTestCtrAccountList.cls
@isTest
private class UnitTestCtrAccountList {

    private static User runningUser = UnitTestDataFactory.createUser('System Administrator', 'testUser@deliveryhero.com', 'UK', 'UK');

    static Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Case'});
    private static Account acc_uk;
    private static Country__c c_uk;
    private static USerRole ur;
    private static Company__c com_uk;


    @testSetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        List<MidasIntegration__c> midasIntg = new List<MidasIntegration__c>();
        midasIntg.add(new MidasIntegration__c(name = 'PP', EndPoint__c = 'http://midas.medusa-hero.com/backend/', AuthenticationToken__c = 'WyI0IiwiYzUwNjRkMmQ2MWUwNTE3YjVhNjRmMTk4Yjc2NmFiODgiXQ.CgtJbA.kFY4BLsKd3XXiXg7QtVxmLqZ7i0', countrybrand__c='{"United Kingdom":"UKHH", "Kuwait":"KWTB"}'));
        insert midasIntg;
        
        List<CountryCompanyBrand__c> countryBrandSettings = new List<CountryCompanyBrand__c>();

        CountryCompanyBrand__c config2 = new CountryCompanyBrand__c();
        config2.name = 'United Kingdom';
        config2.code__c = 'UKHH';
        countryBrandSettings.add(config2);
        
        CountryCompanyBrand__c config3 = new CountryCompanyBrand__c();
        config3.name = 'Kuwait';
        config3.code__c = 'KWTB';
        countryBrandSettings.add(config3);
        
        insert countryBrandSettings;
    }

    static void setupUserData() {
        c_uk = UnitTestDataFactory.createCountry('UK', 'United Kingdom', 'GBP');
        com_uk = UnitTestDataFactory.createCompany('hungryhouse', 'UK', c_uk);
        insert new List<sObject> {c_uk, com_uk};
        acc_uk = UnitTestDataFactory.createAccount('TestAccount', c_uk, 'UK_Account');
        acc_uk.Backend_ID__c = '2266';
        acc_uk.record_country__c='United Kingdom';
        insert new List<sObject> {acc_uk};
        
        CountryCompanyBrand__c config = new CountryCompanyBrand__c();
        config.name = 'hungryhouse';
        config.code__c = 'UKHH';
        insert config;
    }

    @isTest static void test_AccountList() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());
        System.runAs(runningUser) {
            setupUserData();

            CtrAccountList.DataWrapper result = CtrAccountList.loadAccountList(true, 'UK Sales Management','United Kingdom',null,null);

            System.debug('result: ' + result);
            //System.assertEquals(result.contains('restaurant_id'));
        }
        Test.stopTest();
    }
	
	 @isTest static void test_AccountListContinuation() {
        Test.startTest();
        System.runAs(runningUser) {
            setupUserData();
            CtrAccountList controller = new CtrAccountList();
	        Continuation conti = (Continuation)CtrAccountList.loadAccountListContinuation(true, 'UK Sales Management','United Kingdom');

	        // Perform mock callout
	        // (i.e. skip the callout and call the callback method)
	        HttpResponse response = new HttpResponse();
	        response.setBody('{"data":{"restaurants":[{"status":"Open","sf_restaurant_id":"001w000001TvGJyAAN","name":"Delhi On The Go","ownership_reason":"manual_assignment","rating":0,"postcode":"SW184NJ","owner":"taha.holawala@deliveryhero.com","id":29401},{"status":"Not eligible","sf_restaurant_id":"001w000001gjhn9AAA","name":"Papa Johns","ownership_reason":"manual_assignment","rating":0,"postcode":"CF146PD","owner":"taha.holawala@deliveryhero.com","id":38780}]}}');
	        // Set the fake response for the continuation
        	Test.setContinuationResponse('test', response);
	        // Invoke callback method
	        //Object result = Test.invokeContinuationMethod(controller, conti);
	        List<String> state = new List<String>{'test'};
			CtrAccountList.processContinuationResponse(state);
        }
        Test.stopTest();
    }
	
    @isTest static void test_createOpp() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());
        System.runAs(runningUser) {
            setupUserData();
            Tarif__c t = UnitTestDataFactory.createTarif(com_uk, c_uk, 'Premium Placement', 'UK_Tarif', false);
            insert t;


            String result = CtrAccountList.createOpportunity(acc_uk.Id);

            Opportunity Opp = [select id, Record_Country__c from Opportunity where id = :result];
            //System.assertNotEquals(Opp,null);
        }
        Test.stopTest();
    }


    @isTest static void test_getOppLines() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());
        System.runAs(runningUser) {
            setupUserData();
            Tarif__c t = UnitTestDataFactory.createTarif(com_uk, c_uk, 'Premium Placement', 'UK_Tarif', false);
            List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com_uk, c_uk, 'Premium Placement', 'UK_List_Product_Group');
            insert new List<sObject> {lpg, t};
            List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com_uk, c_uk, 'Premium Placement', lpg.id, 'UK_List_Product_Price', 1, true, 100, 1, false, 20);
            insert lpp;
            Opportunity opp = UnitTestDataFactory.createOpportunity('TestOppUK', acc_uk, 'UK_Opportunity', Date.today());
            //opp.Record_Country__c='United Kingdom';
            insert opp;
            Opportunity_Line_Item__c oppProduct = UnitTestDataFactory.createOpportunityLineItemProduct('Premium Placement', opp, lpg.id, lpp.id, true, 'UK_Opportunity_Line_Item', 1, '', 50, 1, 50, 'Premium Placement');
            oppProduct.Booking_Api_Id__c = '58983';
            insert oppProduct;


            String result1 = CtrAccountList.getOppLineItems(null, '58983','United Kingdom');
            //List<Opportunity_Line_Item__c> opplines1 = (List<Opportunity_Line_Item__c>) JSON.deserialize(result1, List<Opportunity_Line_Item__c>.class);
            String result2 = CtrAccountList.getOppLineItems('2266', null,'United Kingdom');
            //List<Opportunity_Line_Item__c> opplines2 = (List<Opportunity_Line_Item__c>) JSON.deserialize(result2, List<Opportunity_Line_Item__c>.class);
            String result3 = CtrAccountList.getOppLineItems('2266,2266', null,'United Kingdom');
            //List<Opportunity_Line_Item__c> opplines3 = (List<Opportunity_Line_Item__c>) JSON.deserialize(result2, List<Opportunity_Line_Item__c>.class);
            String result4 = CtrAccountList.getOppLineItems(null, '58983,58984','United Kingdom');
            //List<Opportunity_Line_Item__c> opplines4 = (List<Opportunity_Line_Item__c>) JSON.deserialize(result2, List<Opportunity_Line_Item__c>.class);

            //System.assertEquals(opplines1.size(),1);
            //System.assertEquals(opplines2.size(),1);
        }
        Test.stopTest();
    }


    @isTest static void test_cancelBookings() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());
        System.runAs(runningUser) {
            setupUserData();
            Tarif__c t = UnitTestDataFactory.createTarif(com_uk, c_uk, 'Premium Placement', 'UK_Tarif', false);
            List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com_uk, c_uk, 'Premium Placement', 'UK_List_Product_Group');
            insert new List<sObject> {lpg, t};
            List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com_uk, c_uk, 'Premium Placement', lpg.id, 'UK_List_Product_Price', 1, true, 100, 1, false, 20);
            insert lpp;
            Opportunity opp = UnitTestDataFactory.createOpportunity('TestOppUK', acc_uk, 'UK_Opportunity', Date.today());
            insert opp;
            Opportunity_Line_Item__c oppProduct = UnitTestDataFactory.createOpportunityLineItemProduct('Premium Placement', opp, lpg.id, lpp.id, true, 'UK_Opportunity_Line_Item', 1, '', 50, 1, 50, 'Premium Placement');
            oppProduct.Booking_Api_Id__c = '58983';
            insert oppProduct;


            String result = CtrAccountList.cancelBookings(new List<CtrAccountList.Bookings> {new CtrAccountList.Bookings('58983', oppProduct.id,'hungryhouse')}, 'UK Sales Management', 'test@deliveryhero.com','United Kingdom',false);

            //System.assertEquals(result,'success');
        }
        Test.stopTest();
    }


    @isTest static void test_loadPPSlots() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());
        System.runAs(runningUser) {
            setupUserData();


            String result = CtrAccountList.loadPPSlots('CM18', 'UK Sales Management', '2016', '8','United Kingdom');
            String result2 = CtrAccountList.loadPPSlots(null, 'UK Sales Management', '2016', '8','United Kingdom');

            System.debug('result: ' + result);
            //System.assert(result.contains('status'));
        }
        Test.stopTest();
    }

    @isTest static void test_loadPPAccounts() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());
        System.runAs(runningUser) {
            setupUserData();


            String result = CtrAccountList.loadPPAccounts('N1', 'UK Sales Management', false, '2016-08-08','United Kingdom');
            String result2 = CtrAccountList.loadPPAccounts('N1', 'UK Sales Management', true, '2016-08-10','United Kingdom');
            String result3 = CtrAccountList.loadPPAccounts(null, 'UK Sales Management', true, '2016-08-09','United Kingdom');


            System.debug('result: ' + result);
            //System.assert(result.contains('sf_restaurant_id'));
        }
        Test.stopTest();
    }
    
    @isTest static void test_loadPPAccountsContinuation() {
        Test.startTest();
        System.runAs(runningUser) {
            setupUserData();

            CtrAccountList controller = new CtrAccountList();
	        Continuation conti = (Continuation)CtrAccountList.loadPPAccountsConitnuation('N1', 'UK Sales Management', false, '2016-08-08','United Kingdom');

	        // Perform mock callout
	        // (i.e. skip the callout and call the callback method)
	        HttpResponse response = new HttpResponse();
	        response.setBody('{"data":{"restaurants":[{"status":"Open","sf_restaurant_id":"001w000001TvGJyAAN","name":"Delhi On The Go","ownership_reason":"manual_assignment","rating":0,"postcode":"SW184NJ","owner":"taha.holawala@deliveryhero.com","id":29401},{"status":"Not eligible","sf_restaurant_id":"001w000001gjhn9AAA","name":"Papa Johns","ownership_reason":"manual_assignment","rating":0,"postcode":"CF146PD","owner":"taha.holawala@deliveryhero.com","id":38780}]}}');
	        // Set the fake response for the continuation
        	Test.setContinuationResponse('test', response);
	        // Invoke callback method
	        //Object result = Test.invokeContinuationMethod(controller, conti);
	        List<String> state = new List<String>{'test'};
			CtrAccountList.processContinuationResponse(state);
        }
        Test.stopTest();
    }
    
    @isTest static void testGetCountryPerCurrentUser(){
        List<String> countries;
        Test.startTest();
            System.runAs(runningUser){
                setupUserData();
                countries = CtrAccountList.getCountryPerCurrentUser();
            }
        Test.stoptest();
        
        System.assertEquals(countries.size(), 1);
    }

    /*******************************************************************************************************
   * @description Tests restaurant data population on Data object when passing GRID__c in restaurant data as sf_id. Grid__c
   * value should be replaced by actual sObject id.
   */
    @isTest
    static void testDataRestaurantPopulation() {
        List<CtrAccountList.Restaurant> restaurants = new List<CtrAccountList.restaurant>();
        CtrAccountList.Data data = new CtrAccountList.Data();
        Country__c country = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        insert country;
        List<Account> accounts = UnitTestDataFactory.createAccounts(5, country, 'Yogiyo_Account');
        insert accounts;
        Map<Id, Account> accountIdMap = new Map<Id, Account>(accounts);
        for(Account account: accounts) {
            CtrAccountList.Restaurant restaurant = new CtrAccountList.Restaurant();
            restaurant.sf_restaurant_id = account.GRID__c;
            restaurants.add(restaurant);
        }
        data.populateRestaurants(restaurants);
        for(CtrAccountList.Restaurant restaurant: data.restaurants) {
            System.assert(accountIdMap.containsKey(restaurant.sf_restaurant_id), 'Error converting restaurant Ids');
        }

    }

}