force-app/main/default/objects/Account/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of account company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Key_VIP_Account__c.field-meta.xml
<CustomField>
    <fullName>Key_VIP_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>true --&gt; this means this a important account, is defined by each country</description>
    <label>Key / VIP Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Admin_area_level_1_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Admin_area_level_1_long_name__c</fullName>
    <label>GPA Admin area level 1 long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Admin_area_level_1_short_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Admin_area_level_1_short_name__c</fullName>
    <label>GPA Admin area level 1 short name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Country_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Country_long_name__c</fullName>
    <label>GPA Country long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Country_short_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Country_short_name__c</fullName>
    <label>GPA Country short name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Restaurant Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>The role the contact plays in the restaurant</description>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-owner</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Franchise Contact</fullName>
            </value>
            <value>
                <fullName>Former Owner</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Previous Owner</fullName>
            </value>
            <value>
                <fullName>Ex-employee</fullName>
            </value>
            <value>
                <fullName>Billing Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
                <label>duplicate</label>
            </value>
            <value>
                <fullName>Additional Contact</fullName>
                <label>additional contact</label>
            </value>
            <value>
                <fullName>Restaurant Operations</fullName>
            </value>
            <value>
                <fullName>Customer Contact</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of opportunity company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Email_Path__c.field-meta.xml
<CustomField>
    <fullName>Email_Path__c</fullName>
    <label>Email Path</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PY_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>PY_Opportunity</fullName>
    <active>true</active>
    <businessProcess>PY Sales Process</businessProcess>
    <label>PY Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/PY_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>PY_Opportunity_Quote</fullName>
    <active>true</active>
    <label>PY Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Platform_Country__c/Platform_Country__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Platform Country</label>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DocuSignUtilityController_Test.cls
@isTest
public class DocuSignUtilityController_Test {

    private static User testUser;
    private static Country__c PYCoutry;
    private static List<Account> accounts;
    private static List<Opportunity> opportunities;
    private static List<Opportunity_Quote__c> quotes;

    private static testMethod void testMethod1(){

        testUser = UnitTestDataFactory.createUser('PY Sales Management', 'pyuser@deliveryhero.com', 'PedidosYa', 'UY');
        insert testUser;
        Test.startTest();
        setupUserData(testUser);
        System.runAs(testUser) {

            Opportunity_Quote__c oq = [Select Id,Name,Id_Account__r.Key_VIP_Account__c,Id_Opportunity__r.Probability,RecordTypeId,Id_opportunity__c,Status__c FROM Opportunity_Quote__c LIMIT 1];
            ApexPages.currentPage().getParameters().put('Id',String.valueOf(oq.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(oq);
            DocuSignUtilityController dsController = new DocuSignUtilityController(sc);
            dsController.createEnvelope();
            DocuSignUtilityController.checkDocuSignEnvelopeCount(oq.Id);
            DocuSignUtilityController.getUIThemeDescription();

        }
        Test.stopTest();

    }

    @testSetup static void setup() {
        List<Platform_Country__c> platformCountry = new List<Platform_Country__c>();
        platformCountry.add(new Platform_Country__c(name = 'PYPlatform', country__c = 'Argentina,Bolivia,Uruguay,Paraguay,Panama,Chile,Dominican Republic'));
        insert platformCountry;
        UnitTestDataFactory.getRecordtypeValues();
    }

    static void setupUserData(User u) {
        System.runAs(u) {

            //Inserting country
            PYCoutry = UnitTestDataFactory.createCountry('UY','Uruguay', 'UYU');
            insert PYCoutry;

            //Inserting Business configs
            Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='Uruguay',Business_Rule_Value__c='PY_DocuSign_Email_Body_Non_Argentina,ABC',Id_Country__c=PYCoutry.id,Is_Active__c=true,Parent__c=false,Process_Name__c='docuSignEmailTemplate',Record_Type_Id__c='PY_Opportunity_Quote',Type__c='Process');
            Business_Config__c b2 = new Business_Config__c(Business_Rule_Name__c='enableButton',Business_Rule_Value__c='2',Id_Country__c=PYCoutry.id,Is_Active__c=true,Parent__c=false,Process_Name__c='docuSignFilters',Record_Type_Id__c='PY_Opportunity_Quote',Type__c='Process');
            Business_Config__c b3 = new Business_Config__c(Business_Rule_Name__c='maxEnvelopeCount',Business_Rule_Value__c='2',Id_Country__c=PYCoutry.id,Is_Active__c=true,Parent__c=false,Process_Name__c='docuSignFilters',Record_Type_Id__c='PY_Opportunity_Quote',Type__c='Process');
            //Business_Config__c b3 = new Business_Config__c(Business_Rule_Name__c='Uruguay',Business_Rule_Value__c='2',Id_Country__c=PYCoutry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='docuSignFilters',Record_Type_Id__c='PY_Opportunity_Quote',Type__c='Process');
            insert new List<sObject>{b1,b2,b3};

            //INserting account
            Account fpAcc = UnitTestDataFactory.createAccount('test',PYCoutry,'PY_Account');
            fpAcc.phone = '+85278273613';
            insert fpAcc;

            Contact con = new Contact();
            con.FirstName = 'Test';
            con.LastName = 'Test';
            con.Contact_Role__c = 'Owner';
            con.AccountId = fpAcc.Id;
            insert con;

            //Inserting Opp
            Opportunity opp = UnitTestDataFactory.createOpportunity('test',fpAcc,'PY_Opportunity', Date.today());
            opp.Company_Code__c = 'UY';
            opp.Business_Type__c = 'Upgrade/Upsell';
            opp.Email_Path__c = 'DocuSign';
            opp.Type = 'Product Only';
            insert opp;

            //Inserting address
            Integration_Config__c cs1 = new Integration_Config__c(
                    Name = 'GoogleMapsSignature', Password__c = 'Abvcd-asdfdgfhjklhnO0=');
            insert cs1;

            AddressDetail__c addr = new AddressDetail__c(
                    Type__c = 'Billing Address;Restaurant Address',
                    LatLng__Longitude__s = 10.0,
                    LatLng__Latitude__s = 5.0,
                    Account__c = fpAcc.Id,

                    GPA_Country_long_name__c = 'Ecuador',
                    GPA_Country_short_name__c = 'EC',

                    GPA_Admin_area_level_1_long_name__c = 'admin area 1 test',
                    GPA_Admin_area_level_1_short_name__c = 'aat1',

                    GPA_Locality_long_name__c = 'locality',
                    GPA_Locality_short_name__c = 'lco',

                    GPA_Route_long_name__c = 'street name',
                    GPA_Route_short_name__c = 'str',

                    GPA_Street_number_long_name__c = '10',
                    GPA_Street_number_short_name__c = '10',

                    GPA_Postal_code_long_name__c = '1010',
                    GPA_Postal_code_short_name__c = '1010',

                    GPA_Place_id__c = '12344',
                    GPA_formatted_address__c = 'whatever bla bla',
                    GPA_Was_modified_manually__c = false
            );

            insert addr;

            EmailTemplate etemp = new EmailTemplate();
            etemp.Name = 'PY_DocuSign_Email_Body_Non_Argentina';
            etemp.Subject = 'Test';
            etemp.Body = 'Test';
            etemp.FolderId = UserInfo.getUserId();
            etemp.TemplateType = 'text';
            etemp.DeveloperName = 'PY_DocuSign_Email_Body_Non_Argentina';
            insert etemp;

            //Inserting Opp quote
            Opportunity_Quote__c  oq = new Opportunity_Quote__c();
            oq.Id_Opportunity__c = opp.Id;
            oq.Id_Account__c = fpAcc.Id;
            oq.Status__c = 'Approved';
            insert oq;

            //Inserting DocuSign Status
            dsfs__DocuSign_Status__c ds = new dsfs__DocuSign_Status__c();
            ds.Opportunity_Quote__c = oq.Id;
            ds.dsfs__Envelope_Status__c = 'Sent';
            insert ds;

            dsfs__DocuSign_Status__c ds1 = new dsfs__DocuSign_Status__c();
            ds1.Opportunity_Quote__c = oq.Id;
            ds1.dsfs__Envelope_Status__c = 'Sent';
            insert ds1;

            oq.Status__c = 'Declined';
            update oq;

            ds.dsfs__Envelope_Status__c = 'Declined';
            ds.dsfs__Declined_Reason__c = 'Declined';
            update ds;

            ds.dsfs__Envelope_Status__c = 'Voided';
            ds.dsfs__Voided_Reason__c = 'Voided';
            update ds;

        }
    }

}