force-app/main/default/objects/Account/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of account company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AddressLine__c.field-meta.xml
<CustomField>
    <fullName>AddressLine__c</fullName>
    <label>XAL AddressLine</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AdministrativeAreaDevName__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeAreaDevName__c</fullName>
    <label>XAL AdministrativeAreaDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>AdministrativeAreaName__c</fullName>
    <label>XAL AdministrativeAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>XAL CountryCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryDevName__c.field-meta.xml
<CustomField>
    <fullName>CountryDevName__c</fullName>
    <label>XAL CountryDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <label>XAL CountryName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/LocalityDevName__c.field-meta.xml
<CustomField>
    <fullName>LocalityDevName__c</fullName>
    <label>XAL LocalityDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/LocalityName__c.field-meta.xml
<CustomField>
    <fullName>LocalityName__c</fullName>
    <label>XAL LocalityName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SubAdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>SubAdministrativeAreaName__c</fullName>
    <label>XAL SubAdministrativeAreaName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SubAdministratriveAreaDevName__c.field-meta.xml
<CustomField>
    <fullName>SubAdministratriveAreaDevName__c</fullName>
    <label>XAL SubAdministratriveAreaDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Restaurant Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryCompanyMapping__c/CountryCompanyMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryCompanyMapping</label>
</CustomObject>

force-app/main/default/objects/CountryCompanyMapping__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Area for middle east</description>
    <label>Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company Code e.g Yogiyo, DH_AU etc.</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country of Lead</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
                <default>true</default>
                <label>Branch</label>
            </value>
            <value>
                <fullName>Branch - Main</fullName>
            </value>
            <value>
                <fullName>Branch - Kitchen Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/FP_Lead.recordType-meta.xml
<RecordType>
    <fullName>FP_Lead</fullName>
    <active>true</active>
    <businessProcess>Global Lead Process</businessProcess>
    <description>Used for APAC Foodpanda countries.</description>
    <label>FP Lead</label>
</RecordType>

force-app/main/default/objects/Trigger_Manager__c/Trigger_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Manager</label>
</CustomObject>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_AddressDetail_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_AddressDetail_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate AddressDetail Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/xAL_Address__c.object-meta.xml
<CustomObject>
    <label>xAL Address</label>
    <nameField>
        <displayFormat>XAL-ADD-{0000}</displayFormat>
        <label>xAL Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>xAL Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xAL_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Province</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Suburb</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_AdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>xAL_AdministrativeAreaName__c</fullName>
    <label>Administrative Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_Country__c.field-meta.xml
<CustomField>
    <fullName>xAL_Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_SubAdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>xAL_SubAdministrativeAreaName__c</fullName>
    <label>SubAdministrative Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Uruguay</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Laos</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Myanmar</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <description>Countries for xAL model</description>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/xALAddress_Test.cls
/**
* @author Mantas Jurkunas
* @date 09.09.2019
*
* @description Test class for xAL_Address related methods
*/

@IsTest
public with sharing class xALAddress_Test {

    @TestSetup
    private static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c country = UnitTestDataFactory.createCountry('CL', 'Chile', 'USD');
        insert country;
        CountryCompanyMapping__c countryCompanyMapping = new CountryCompanyMapping__c(Name = 'Chile', Company_Code__c='PY');
        insert countryCompanyMapping;
        Business_Config__c addressConfig = UnitTestDataFactory.createBusinessConfig('xALAddressObject', 'Process', 'TextFieldVisibility',
                '{"Chile":{"postCode":false, "translatedStreetName":true}}', country.Id, 'PY_Account', true, true);
        insert addressConfig;
    }

    @IsTest
    private static void testGetNextAddressLineText() {
        Map<String, Boolean> textVisibilityMap = xALAddress_Utils.getNextAddresslineText('Chile');
        System.assert(textVisibilityMap.containsKey('postCode'));
        System.assert(!textVisibilityMap.get('postCode'));
        System.assert(textVisibilityMap.containsKey('translatedStreetName'));
        System.assert(textVisibilityMap.get('translatedStreetName'));
    }

    @IsTest
    public static void test_getCountry() {
        Country__c country = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'USD');
        insert country;
        Account account = UnitTestDataFactory.createAccount('FP account', country, 'FP_Account');
        account.Phone = '+85227367722';
        insert account;

        AddressDetail__c addressDetail = new AddressDetail__c(
                AddressLine__c = 'Oranienburger Str. 70, Berlin, Germany',
                CountryCode__c = 'DE',
                CountryName__c = 'Germany',
                CountryDevName__c = 'Germany',
                AdministrativeAreaName__c ='admArea',
                AdministrativeAreaDevName__c = 'admArea',
                SubAdministrativeAreaName__c = 'subAdminArea',
                SubAdministratriveAreaDevName__c = 'subAdminArea',
                LocalityName__c = 'locality',
                LocalityDevName__c = 'locality',
                Account__c = account.Id,
                Type__c = 'Billing Address;Shipping Address'
        );
        Trigger_Manager__c tm = Trigger_Manager__c.getInstance();
        tm.Deactivate_AddressDetail_Trigger__c = true;
        upsert tm;
        insert addressDetail;

        xALCountry xcountry = CtrCreateNewAddress.getCountryByCountryName('Hong Kong');
        System.assertEquals('Hong Kong', xcountry.label);
        System.assertEquals('HK', xcountry.code);

        xALCountry xcountry2 = CtrCreateNewAddress.getAccountCountry(account.Id);
        System.assertEquals('Hong Kong', xcountry2.label);
        System.assertEquals('HK', xcountry2.code);

        List<xALAddressDetails> alAddressDetails = CtrCreateNewAddress.getXALAddressDetailsPerAccount(account.Id);
        System.assertEquals(1, alAddressDetails.size());

        alAddressDetails = CtrCreateNewAddress.saveXALAddresses(alAddressDetails);
        System.assertEquals(1, alAddressDetails.size());

        xALAddressDetails alAddressDetail = CtrCreateNewAddress.saveXALAddress(alAddressDetails.get(0));
        System.assertEquals('admArea', alAddressDetail.country.adminArea.label);
        System.assertEquals('subAdminArea', alAddressDetail.country.adminArea.subAdministrativeArea.label);
        System.assertEquals('locality', alAddressDetail.country.adminArea.subAdministrativeArea.locality.label);
    }

    @IsTest
    public static void test_insertAddress() {
        xAL_Address__c address1 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area1',
                xAL_SubAdministrativeAreaName__c='area2',
                Type__c = 'City'
        );

        xAL_Address__c address2 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area1',
                xAL_SubAdministrativeAreaName__c='area2',
                Type__c = 'State'
        );

        Country__c country = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'HKD');
        insert country;
        List<Lead> lstLeads = UnitTestDataFactory.createLeads(1, country, 'FP Test Lead', 'HK', 'HKD', 'FP Restaurant Test Lead', 'FP_Lead');
        lstLeads[0].Area__c = 'test area';
        insert lstLeads;

        Account account = UnitTestDataFactory.createAccount('FP account', country, 'FP_Account');
        account.Phone = '+85227367722';
        insert account;

        Business_Config__c b1x = new Business_Config__c(Business_Rule_Name__c='Hong KongAddressMappingJSON',
                Business_Rule_Value__c='{"Country":"City","City":"District","District": "Area"}',
                Id_Country__c=country.id,Is_Active__c=true,Parent__c=true,Process_Name__c='xALAddressObject',
                Record_Type_Id__c='FP_Account',Type__c='Process');
        insert b1x;

        Map<String, Business_Config__c> bconfMap_1 = new Map<String, Business_Config__c>{b1x.Business_Rule_Name__c => b1x};
        Map<String, Map<String, Business_Config__c>> bconfMap_1f = new Map<String, Map<String, Business_Config__c>>{'FP_Account' => bconfMap_1};
        Map<String, Map<String, Map<String, Business_Config__c>>> testMap = new Map<String, Map<String, Map<String, Business_Config__c>>>{b1x.Process_Name__c => bconfMap_1f};
        LibBusinessConfig.setMotherOfAllBusinessMaps(testMap);

        try {
            insert address1;
            insert address2;
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        xAL_Address__c addresses = xALAddress_Selector.getById(address1.Id);
        System.assertEquals('City', addresses.Type__c);
        System.assert(address2.Id == null);
    }

    /**
     * @description Test if next address lines are retrieved properly with similar city names
     */
    @IsTest
    public static void testAddressRetrieval() {
        CountryCompanyMapping__c countryCompanyMapping = new CountryCompanyMapping__c(Name = 'Hong Kong', Company_Code__c='FP');
        insert countryCompanyMapping;
        Country__c country = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'USD');
        insert country;
        Business_Config__c addressConfig = new Business_Config__c(Id_Country__c=country.Id, Process_Name__c='xALAddressObject', Business_Rule_Name__c='AddressMappingJSON', Business_Rule_Value__c='{"Country":"City","City":"Area"}', Record_Type_Id__c='FP_Account', Is_Active__c=true, Type__c='Process');
        insert addressConfig;
        Account account = UnitTestDataFactory.createAccount('FP account', country, 'FP_Account');
        account.Phone = '+85227367722';
        insert account;

        xAL_Address__c address0 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                Type__c = 'Country'
        );
        xAL_Address__c address0_1 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area1',
                Type__c = 'City'
        );
        xAL_Address__c address0_2 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area 1',
                Type__c = 'City'
        );
        xAL_Address__c address0_3 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area  1',
                Type__c = 'City'
        );
        xAL_Address__c address0_4 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area   1',
                Type__c = 'City'
        );

        xAL_Address__c address1 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area1',
                xAL_SubAdministrativeAreaName__c='area2',
                Type__c = 'Area'
        );

        xAL_Address__c address2 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area 1',
                xAL_SubAdministrativeAreaName__c='area2',
                Type__c = 'Area'
        );

        xAL_Address__c address3 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area  1',
                xAL_SubAdministrativeAreaName__c='area2',
                Type__c = 'Area'
        );

        xAL_Address__c address4 = new xAL_Address__c(
                xAL_Country__c = 'Hong Kong',
                xAL_AdministrativeAreaName__c='area   1',
                xAL_SubAdministrativeAreaName__c='area2',
                Type__c = 'Area'
        );

        try {
            insert new List<xAL_Address__c> { address0, address0_1, address0_2, address0_3, address0_4, address1, address2, address3, address4 };
        } catch (DmlException e) {
            System.debug(e.getMessage());
        }
        Test.startTest();
        List<xAL_Address__c> addresses = xALAddress_Utils.getNextAddressLineValues(xALAddress_Selector.getById(address0_1.Id));
        System.assertEquals(1, addresses.size());
        addresses = xALAddress_Utils.getNextAddressLineValues(xALAddress_Selector.getById(address0_2.Id));
        System.assertEquals(1, addresses.size());
        addresses = xALAddress_Utils.getNextAddressLineValues(xALAddress_Selector.getById(address0_3.Id));
        System.assertEquals(1, addresses.size());
        addresses = xALAddress_Utils.getNextAddressLineValues(xALAddress_Selector.getById(address0_4.Id));
        System.assertEquals(1, addresses.size());
        Test.stopTest();
    }

}