force-app/main/default/objects/Account/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of account company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Reason__c</fullName>
    <label>Closed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Take Online</fullName>
            </value>
            <value>
                <fullName>Take Online is not possible</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Not Successful</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Create Retention Task</fullName>
            </value>
            <value>
                <fullName>Create Take Offline Task for Non Contracted</fullName>
            </value>
            <value>
                <fullName>Take Offline</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Not Successful - Data Missing</fullName>
            </value>
            <value>
                <fullName>Not Successful - Commission is not correct</fullName>
            </value>
            <value>
                <fullName>Back Online</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Duplicated</fullName>
            </value>
            <value>
                <fullName>Auto Closed</fullName>
            </value>
            <value>
                <fullName>Escalated to AM</fullName>
            </value>
            <value>
                <fullName>Successful Call</fullName>
            </value>
            <value>
                <fullName>Call Scheduled</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (Agent)</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (AM)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (1 st Incident)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (Permanent)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code. Comes from the record type provided naming conventions are respected e.g DH_AU for Delivery Hero Australia</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code</description>
    <label>Company Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yogiyo</fullName>
            </value>
            <value>
                <fullName>DH_AU</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>TL_QT</fullName>
            </value>
            <value>
                <fullName>TL_SA</fullName>
            </value>
            <value>
                <fullName>TL_LB</fullName>
            </value>
            <value>
                <fullName>TL_OM</fullName>
            </value>
            <value>
                <fullName>TL_AE</fullName>
            </value>
            <value>
                <fullName>TL_BH</fullName>
            </value>
            <value>
                <fullName>TL_KW</fullName>
            </value>
            <value>
                <fullName>Talabat</fullName>
            </value>
            <value>
                <fullName>TL_JO</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>PY</fullName>
            </value>
            <value>
                <fullName>FP</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Logging__c/Logging__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>use this custom setting to disable or enable Logging
1. Disable a particular type to disable the logging for that particular type
2. Enable ONLY_ERROR_LOGGING to log only errors

NOTE: If you can enable only error logging and still you have not disbaled logging for particular type, it will log for both errors and that particular type. If you just want to log error disbale all the other types and enable logging.</description>
    <label>Logging</label>
</CustomObject>

force-app/main/default/objects/Logging__c/fields/DISABLE_LOGGING__c.field-meta.xml
<CustomField>
    <fullName>DISABLE_LOGGING__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DISABLE_LOGGING</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of opportunity company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FP_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Global Sales Process</businessProcess>
    <label>FP Opportunity</label>
</RecordType>

force-app/main/default/classes/CloseOpportunities_Test.cls
/**
* @author Mantas Jurkunas
* @date 14.04.2020
*
* @description Test class containing test methods related to closing opportunities with failed onboarding
*/
@IsTest
private class CloseOpportunities_Test {

    @TestSetup
    private static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        Logging__c logConfig =new Logging__c(SetupOwnerId=UserInfo.getUserId());
        logConfig.DISABLE_LOGGING__c = false;
        insert logConfig;

        Country__c country = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'GBP');
        insert country;

        Business_Config__c businessConfig0 = UnitTestDataFactory.createBusinessConfig('OpportunityAutoClose', 'Process', 'OnboardingFailedCaseLimit', '3', country.Id, 'FP_Opportunity', true, true);
        Business_Config__c businessConfig1 = UnitTestDataFactory.createBusinessConfig('OpportunityAutoClose', 'Process', 'FailedOpportunitiesFollowupLimit', '7', country.Id, 'FP_Opportunity', true, false);

        insert new List<Business_Config__c> {businessConfig0, businessConfig1};

        Company__c com = UnitTestDataFactory.createCompany('FoodPanda', 'FP', country);
        insert com;

        Account acc = UnitTestDataFactory.createAccount('Test Account#1',country,'FP_Account');
        Account acc2 = UnitTestDataFactory.createAccount('Test Account#2',country,'FP_Account');
        insert new List<Account> {acc, acc2};

        Opportunity opp = UnitTestDataFactory.createOpportunity('Test #1',acc,'FP_Opportunity', Date.today().addDays(20));
        opp.Company_Code__c = 'FP';
        opp.Business_Type__c = 'New Business';
        opp.StageName = 'New';

        Opportunity opp2 = UnitTestDataFactory.createOpportunity('Test #2',acc2,'FP_Opportunity', Date.today().addDays(20));
        opp2.Company_Code__c = 'FP';
        opp2.Business_Type__c = 'New Business';
        opp2.StageName = 'Onboarding';
        insert new List<Opportunity> {opp, opp2};
        opp.StageName = 'Onboarding Failed';
        update opp;

        Case onboardingCase0 = UnitTestDataFactory.createCase(acc2, 'Closed', 'Onboarding', '', '', country, 'FP_Entry_Case', '');
        Case onboardingCase1 = UnitTestDataFactory.createCase(acc2, 'Closed', 'Onboarding', '', '', country, 'FP_Entry_Case', '');
        Case onboardingCase2 = UnitTestDataFactory.createCase(acc2, 'New', 'Onboarding', '', '', country, 'FP_Entry_Case', '');
        onboardingCase0.Opportunity__c = opp2.Id;
        onboardingCase1.Opportunity__c = opp2.Id;
        onboardingCase2.Opportunity__c = opp2.Id;
        onboardingCase0.Closed_Reason__c = CaseSelector.CR_NOT_SUCCESSFUL;
        onboardingCase1.Closed_Reason__c = CaseSelector.CR_NOT_SUCCESSFUL;
        onboardingCase0.Root_Cause__c = 'Duplicated';
        onboardingCase1.Root_Cause__c = 'Duplicated';

        insert new List<Case> {onboardingCase0, onboardingCase1, onboardingCase2};
    }

    @IsTest
    private static void testTripleOnboardingCaseFailure() {
        List<Case> onboardingCases = CaseSelector.getAll();
        Opportunity opp = Opportunity_Selector.getOpportunityById(onboardingCases.get(0).Opportunity__c);
        System.assertNotEquals('Closed Lost', opp.StageName);
        System.assertNotEquals('Onboarding Failed', opp.Lost_Reason__c);
        for (Case cs: onboardingCases) {
            if (cs.Status.equals('Closed')) {
                continue;
            }
            cs.Status = 'Closed';
            cs.Closed_Reason__c = CaseSelector.CR_NOT_SUCCESSFUL;
            cs.Root_Cause__c = 'Duplicated';
        }
        update onboardingCases;
        opp = Opportunity_Selector.getOpportunityById(onboardingCases.get(0).Opportunity__c);
        System.assertEquals('Closed Lost', opp.StageName);
        System.assertEquals('Onboarding Failed', opp.Lost_Reason__c);
    }

    @IsTest
    private static void testOnboardingFailedOpportunities() {
        List<Opportunity> opportunities = Opportunity_Selector.getAll();
        Opportunity onboardingOpportunity;
        for (Opportunity opp: opportunities) {
            if (opp.StageName.equals('Onboarding Failed')) {
                onboardingOpportunity = opp;
                break;
            }
        }
        System.assertNotEquals(null, onboardingOpportunity);
        Test.startTest();
            Database.executeBatch(new CloseOpportunities_Batch());
        Test.stopTest();

        onboardingOpportunity = Opportunity_Selector.getOpportunityById(onboardingOpportunity.Id);
        System.assertEquals('Closed Lost', onboardingOpportunity.StageName);
        System.assertEquals('Onboarding Failed', onboardingOpportunity.Lost_Reason__c);
    }

    @IsTest
    private static void testTripleOnboardingCaseFailureNoBC() {
        delete [SELECT Id FROM Business_Config__c];
        List<Case> onboardingCases = CaseSelector.getAll();
        Opportunity opp = Opportunity_Selector.getOpportunityById(onboardingCases.get(0).Opportunity__c);
        System.assertNotEquals('Closed Lost', opp.StageName);
        System.assertNotEquals('Onboarding Failed', opp.Lost_Reason__c);
        for (Case cs: onboardingCases) {
            if (cs.Status.equals('Closed')) {
                continue;
            }
            cs.Status = 'Closed';
            cs.Closed_Reason__c = CaseSelector.CR_NOT_SUCCESSFUL;
            cs.Root_Cause__c = 'Duplicated';
        }
        update onboardingCases;
        opp = Opportunity_Selector.getOpportunityById(onboardingCases.get(0).Opportunity__c);
        System.assertNotEquals('Closed Lost', opp.StageName);
        System.assertNotEquals('Onboarding Failed', opp.Lost_Reason__c);
    }

    @IsTest
    private static void testOnboardingFailedOpportunitiesNoBC() {
        delete [SELECT Id FROM Business_Config__c];
        List<Opportunity> opportunities = Opportunity_Selector.getAll();
        Opportunity onboardingOpportunity;
        for (Opportunity opp: opportunities) {
            if (opp.StageName.equals('Onboarding Failed')) {
                onboardingOpportunity = opp;
                break;
            }
        }
        System.assertNotEquals(null, onboardingOpportunity);
        Test.startTest();
        Database.executeBatch(new CloseOpportunities_Batch());
        Test.stopTest();

        onboardingOpportunity = Opportunity_Selector.getOpportunityById(onboardingOpportunity.Id);
        System.assertNotEquals('Closed Lost', onboardingOpportunity.StageName);
        System.assertNotEquals('Onboarding Failed', onboardingOpportunity.Lost_Reason__c);
        //Coverage-only execution. The functionality is tested in other method
        CloseOpportunities_Batch.schedule(CloseOpportunities_Batch.CRON_DAILY);
    }
}