force-app/main/default/objects/Account/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of account company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <description>Company code of opportunity company</description>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FP_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FP_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Global Sales Process</businessProcess>
    <label>FP Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Platform_Country__c/Platform_Country__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Platform Country</label>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GetAccountDataForNintexTest.cls
/**
* @author Sudhakar Ch
* @date 09/01/2020
* @description Class is the test class for 'GetAccountDataForNintex.cls'
* This class is build as for recomendations of Nintex documentation can be find here : https://help.nintex.com/en-us/docgen/docservices/#docgen-sfdc/Services/manageDDP/RelationshipApexData.htm%3FTocPath%3DUse%2520advanced%2520techniques%7CRelationships%7C_____5
*/
@istest
public with sharing class GetAccountDataForNintexTest {
    
    private static testMethod void testApexData() {
        User testUser = UnitTestDataFactory.createUser('FP Sales Team', 'unittestUser@deliveryhero.com', 'Foodpanda', 'HK');
        // Create apex data class instance
        GetAccountDataForNintex apexData = new GetAccountDataForNintex();
        
        Test.startTest();
        System.runAs(testUser) {
            setupUserData(testUser);
            
            Set<string> gd = apexData.getGlobalDescribe();
            system.assertEquals(1, gd.size());
            
            system.assert(apexData.getChildRelationships('Account').isEmpty());
            
            List<Loop.ExternalData.DataObject> dataObjects = apexData.describeObjects(new List<string>(gd));
            system.assertEquals(1, dataObjects.size());
            for (Loop.ExternalData.DataObject dataObject : dataObjects) {
                system.assert(!dataObject.fields.isEmpty());
            }
            
            Loop.ExternalData.QueryRequestInfo requestInfo = new Loop.ExternalData.QueryRequestInfo();
            requestInfo.RecordId = [Select Id FROM Opportunity_Quote__c LIMIT 1].Id;
            
            Loop.ExternalData.Relationship opps = new Loop.ExternalData.Relationship();
            opps.Name = 'Account';            
            requestInfo.Relationships = new List<Loop.ExternalData.Relationship>{opps};
            Loop.ExternalData.QueryResultSet qrs = apexData.query(requestInfo);            
            system.assertEquals(1, qrs.results.size());
            
            for (Loop.ExternalData.QueryResult queryResult : qrs.results) {
                system.assertEquals(1, queryResult.rows.size());
            }
        }
        Test.stopTest();
    }
    
    @testSetup static void setup() {
        List<Platform_Country__c> platformCountry = new List<Platform_Country__c>();
        platformCountry.add(new Platform_Country__c(name = 'TalabatPlatform', country__c = 'Kuwait,Bahrain,Saudi Arabia,Oman,Qatar,United Arab Emirates'));
        platformCountry.add(new Platform_Country__c(name = 'FOCPlatform', country__c = 'Lebanon,Qatar,United Arab Emirates'));
        insert platformCountry;
        UnitTestDataFactory.getRecordtypeValues();
    }
    
    static void setupUserData(User u) {
        System.runAs(u) {
            //Inserting country
            Country__c HKCoutry = UnitTestDataFactory.createCountry('HK','Hong Kong', 'HKD');
            insert HKCoutry;
            
            //INserting account
            Account fpAcc = UnitTestDataFactory.createAccount('test',HKCoutry,'FP_Account');
            fpAcc.phone = '+85278273613';
            insert fpAcc;
            
            //Inserting Opp
            Opportunity opp = UnitTestDataFactory.createOpportunity('test',fpAcc,'FP_Opportunity', Date.today());
            opp.Company_Code__c = 'HK';
            opp.Business_Type__c = 'Upgrade/Upsell';
            opp.Type = 'Product Only';
            insert opp;
            
            //Inserting address
            Integration_Config__c cs1 = new Integration_Config__c(
                Name = 'GoogleMapsSignature', Password__c = 'Abvcd-asdfdgfhjklhnO0=');
            insert cs1;
            
            
            //Inserting Opp quote
            Opportunity_Quote__c  oq = new Opportunity_Quote__c();
            oq.Id_Opportunity__c = opp.Id;
            oq.Id_Account__c = fpAcc.Id;
            insert oq;   
        }
    }
}