force-app/main/default/objects/Account/fields/Delivery_Service__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Service__c</fullName>
    <description>Information of delivery type used by partner</description>
    <inlineHelpText>Information of delivery type used by partner</inlineHelpText>
    <label>Delivery Service</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Yogiyo_Account.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Account</fullName>
    <active>true</active>
    <description>KR Account Recordtype</description>
    <label>Yogiyo Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>this hold the end date because the other end date is not writable</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>Service type of contract. Says whether a contract is a main service or an additional service (surcharge)</description>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/Yogiyo_Contract.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Contract</fullName>
    <active>true</active>
    <label>Yogiyo Contract</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso__c.field-meta.xml
<CustomField>
    <fullName>Iso__c</fullName>
    <label>Iso</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Yogiyo_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Sales Proccess</businessProcess>
    <description>KR Opportunity Recordtype</description>
    <label>Yogiyo Opportunity</label>
</RecordType>

force-app/main/default/objects/Platform_Country__c/Platform_Country__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Platform Country</label>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/Platform_Performance__c.object-meta.xml
<CustomObject>
    <description>SP-1592 - Platform_Performance objects holds all information around country specific Websites, Backends in countries with multiple platforms (like pizza.de, lieferheld.de) AND/OR Account performance in general</description>
    <label>Platform Performance</label>
    <nameField>
        <label>Platform Performance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Platforms Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Performance__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>SP-1592</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Platforms Performance</relationshipLabel>
    <relationshipName>Platforms_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <description>SP-1592</description>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Platform_Online_Status__c.field-meta.xml
<CustomField>
    <fullName>Platform_Online_Status__c</fullName>
    <label>Platform Online Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Online_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Platform_Performance__c/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <description>Represents if the Account is active or not for the platform based on the contracts&apos; status</description>
    <label>Vendor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending Activation</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>A company that a user belongs to. A user can belong to more than one company</description>
    <label>Company Name</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yogiyo</fullName>
            </value>
            <value>
                <fullName>Talabat</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>PY</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>FP</fullName>
            </value>
            <value>
                <fullName>YE</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>HS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Delivery_Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DH Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Hybrid</fullName>
    </customValue>
    <customValue>
        <fullName>None</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Take away</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>Delivery Service</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Online_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Online</fullName>
    </customValue>
    <customValue>
        <fullName>Offline</fullName>
    </customValue>
    <customValue>
        <fullName>On Holiday</fullName>
    </customValue>
    <customValue>
        <fullName>In Acquisition</fullName>
    </customValue>
    <customValue>
        <fullName>Quality Check</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Initiated</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Final Check</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Changes Requested</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Approval Pending</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Take Online</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Backend ID Creation</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Menu Typing</fullName>
    </customValue>
    <customValue>
        <fullName>MP - Delivery Area</fullName>
    </customValue>
    <customValue>
        <fullName>Temporary Offline</fullName>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Take Online</fullName>
    </customValue>
    <customValue>
        <fullName>0</fullName>
        <isActive>false</isActive>
        <label>0</label>
    </customValue>
    <customValue>
        <fullName>true</fullName>
        <isActive>false</isActive>
        <label>true</label>
    </customValue>
    <customValue>
        <fullName>false</fullName>
        <isActive>false</isActive>
        <label>false</label>
    </customValue>
    <customValue>
        <fullName>Offline - current day</fullName>
        <isActive>false</isActive>
        <label>Offline - current day</label>
    </customValue>
    <masterLabel>Online Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UnitTestClsContractProcessor.cls
@IsTest
private class UnitTestClsContractProcessor {

    private static List<Contract> newContracts = new List<Contract>();
    private static List<Contract> oldContracts = new List<Contract>();
    private static List<Account> accounts;
    private static Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Contract'});


    @TestSetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        List<Platform_Country__c> platformCountry = new List<Platform_Country__c>();
        platformCountry.add(new Platform_Country__c(Name = 'TalabatPlatform', Country__c = 'Kuwait,Bahrain,Saudi Arabia,Oman,Qatar,United Arab Emirates'));
        platformCountry.add(new Platform_Country__c(Name = 'FOCPlatform', Country__c = 'Lebanon,Qatar,United Arab Emirates'));
        insert platformCountry;

        Country__c testCountry = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        insert testCountry;

        Business_Config__c config1 = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'GroupBeforeSorting', 'false', testCountry.Id, 'Yogiyo_Contract', true, true);
        Business_Config__c config2 = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'validServiceTypesForPlatformStatusChange', 'Commission Fee, Logistics Fee', testCountry.Id, 'Yogiyo_Contract', true, false);
        Business_Config__c config3 = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'additionalSwitchBusinessTypes', 'Upgrade/Upsell,Winback,Downgrade', testCountry.Id, 'Yogiyo_Contract', true, false);
        Business_Config__c config4 = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'deliveryServiceTypes', 'Commission Fee, Logistics Fee', testCountry.Id, 'Yogiyo_Contract', true, false);
        Business_Config__c config5 = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'deliveryServiceTypesMap', '{"Logistics Fee" : "DH Delivery", "Commission Fee" : "Partner Delivery", "Logistics Fee, Commission Fee" : "Hybrid"}', testCountry.Id, 'Yogiyo_Contract', true, false);
        List<Business_Config__c> bConfigs = new List<Business_Config__c> {config1, config2, config3, config4, config5};
        insert bConfigs;
    }

    static void setupUserData(User u) {
        System.runAs(u) {
            //Country__c testCountry = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
            //insert testCountry;
            Country__c testCountry = [SELECT Iso__c,
                                      Name,
                                      CurrencyIsoCode
                                      FROM Country__c
                                      WHERE Iso__c = 'KR' ];

            accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
            insert accounts;

            Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                                                                                    Platform__c = 'Yogiyo',
                                                                                    Vendor_Status__c = '');
            insert platPerformance;
            
			List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
            testOpportunities.get(0).Business_Type__c = 'Switch';
            insert testOpportunities;
            
            for (Integer i = 1; i < 11; i++) {
                oldContracts.add(new Contract(
                                    AccountId = accounts[0].Id,
                                    Id_Opportunity__c = testOpportunities.get(0).Id,
                                    StartDate = Date.today().addDays(i + 1),
                                    End_Date__c = Date.today().addDays(i + 2),
                                    Status = 'Draft',
                                    Service_Type__c = 'Commission Fee',
                                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                                    Company_Name__c = 'Yogiyo'
                                    )
                                );
            }
            oldContracts.add(new Contract(AccountId = accounts[0].Id, StartDate = Date.today(), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

            for (Integer i = 12; i < 212; i++) {
                newContracts.add(new Contract(
                                    AccountId = accounts[0].Id,
                                    Id_Opportunity__c = testOpportunities.get(0).Id,
                                    StartDate = Date.today().addDays(i + 1),
                                    End_Date__c = Date.today().addDays(i + 2),
                                    Status = 'Draft',
                                    Service_Type__c = 'Logistics Fee',
                                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                                    Company_Name__c = 'Yogiyo'
                                    )
                                );
            }
            newContracts.add(new Contract(AccountId = accounts[0].Id, StartDate = Date.today().addDays(1), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

            //Business_Config__c config = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'GroupBeforeSorting', 'false', testCountry.Id, 'Yogiyo_Contract', true, true);

            //insert config;
        }
    }


    @isTest static void test_noContractsAvailableOnAccountYet() {
        User testUser = UnitTestDataFactory.createUser('Yogiyo Sales Management', 'testUser@deliveryhero.com', 'Yogiyo', 'KR');
        insert testUser;
        PermissionSet ps = [SELECT Id From PermissionSet WHERE Name = 'Exclude_from_Validation'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id );


        Test.startTest();
        System.runAs(testUser) {
            setupUserData(testUser);
            insert newContracts;
            ClsContractProcessor.preventDuplicateContracts(newContracts);
        }
        Test.stopTest();

        // Nothing happens
        System.assertEquals(null, newContracts[newContracts.size() - 1].End_Date__c);

        Platform_Performance__c pp = [SELECT Id, Account__c, Platform__c, Platform_Online_Status__c, Vendor_Status__c
                FROM Platform_Performance__c WHERE Platform__c = 'Yogiyo' LIMIT 1];

        System.assertEquals(ContractSelector.ONLINE_STATUS_PENDINGACTIVATION, pp.Vendor_Status__c);
    }


    @isTest static void test_contractsOnAccountPreventDuplicates() {
        User testUser = UnitTestDataFactory.createUser('Yogiyo Sales Management', 'testUser@deliveryhero.com', 'Yogiyo', 'KR');
        insert testUser;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Exclude_from_Validation'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id );
        Test.startTest();
        System.runAs(testUser) {
            setupUserData(testUser);
            insert oldContracts;
            insert newContracts;
            ClsContractProcessor.preventDuplicateContracts(newContracts);
        }
        Test.stopTest();

        Set<Id> conIds = new Set<Id>();
        for (Contract cont : oldContracts) {
            conIds.add(cont.Id);
        }

        Boolean allTerminated = true;
        List<Contract> contracts = [SELECT Id, Status, StartDate, End_Date__c FROM Contract WHERE Id IN :conIds];
        Contract con = [SELECT Id, Status, End_Date__c FROM Contract WHERE Id = : oldContracts[oldContracts.size() - 1].Id];

        // Check to make sure that all previous contacts with a start date greated than the start date of the earliest new contract are terminated.
        /*for(Contract cont : contracts){
            if((cont.Id != con.Id) && (cont.Status != 'Terminated')){
                allTerminated = false;
            }
        }*/

        // System.assertEquals(Date.today(), con.End_Date__c);
        System.assertEquals('Draft', con.Status);
        //System.assertEquals(true, allTerminated);
    }


    @IsTest static void test_PlatformStatusForActiveContract() {

        User testUser = UnitTestDataFactory.createUser('Yogiyo Sales Management', 'testUser@deliveryhero.com', 'Yogiyo', 'KR');
        insert testUser;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Exclude_from_Validation'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id );


        Test.startTest();
        System.runAs(testUser) {
            setupUserData(testUser);
            newContracts[0].StartDate = Date.today().addDays(-1);
            insert newContracts;
            ClsContractProcessor.preventDuplicateContracts(newContracts);
        }
        Test.stopTest();

        Platform_Performance__c pp = [SELECT Id, Account__c, Platform__c, Platform_Online_Status__c, Vendor_Status__c
        FROM Platform_Performance__c WHERE Platform__c = 'Yogiyo' LIMIT 1];

        System.assertEquals(ContractSelector.ONLINE_STATUS_ACTIVE, pp.Vendor_Status__c);
    }

    /**
     * @description Test scenario when one contract is ending today and another one is starting the next day. Contract should remain active in this case.
    */
    @IsTest
    public static void test_PlatformStatusForActiveContractToday() {

        User testUser = UnitTestDataFactory.createUser('Yogiyo Sales Management', 'testUser@deliveryhero.com', 'Yogiyo', 'KR');
        insert testUser;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Exclude_from_Validation'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id );

        Test.startTest();
        Contract currentContract;
        System.runAs(testUser) {
            setupUserData(testUser);
            currentContract = newContracts[0];
            Contract futureContract = newContracts[1];
            currentContract.StartDate = Date.today().addDays(-1);
            currentContract.End_Date__c = Date.today();
            insert currentContract;
            Platform_Performance__c pp = PlatformPerformanceSelector.getPlatformPerformancesForAccounts(new Set<Id>{currentContract.AccountId})[0];
            System.assertEquals(ContractSelector.ONLINE_STATUS_ACTIVE, pp.Vendor_Status__c);
            futureContract.StartDate = Date.today().addDays(1);
            insert futureContract;
        }
        Test.stopTest();
        Platform_Performance__c pp = PlatformPerformanceSelector.getPlatformPerformancesForAccounts(new Set<Id>{currentContract.AccountId})[0];
        System.assertEquals(ContractSelector.ONLINE_STATUS_ACTIVE, pp.Vendor_Status__c);
    }

    @IsTest static void test_PlatformStatusForTerminatedContract() {
        User testUser = UnitTestDataFactory.createUser('Yogiyo Sales Management', 'testUser@deliveryhero.com', 'Yogiyo', 'KR');
        insert testUser;
        PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'Exclude_from_Validation'];
        insert new PermissionSetAssignment(AssigneeId = testUser.Id, PermissionSetId = ps.Id );


        Test.startTest();
        System.runAs(testUser) {
            setupUserData(testUser);
            newContracts[0].StartDate = Date.today().addDays(-10);
            newContracts[0].End_Date__c = Date.today().addDays(-1);
            insert newContracts[0];
            ClsContractProcessor.preventDuplicateContracts(newContracts);
        }
        Test.stopTest();

        Platform_Performance__c pp = [SELECT Id, Account__c, Platform__c, Platform_Online_Status__c, Vendor_Status__c
        FROM Platform_Performance__c WHERE Platform__c = 'Yogiyo' LIMIT 1];

        System.assertEquals(ContractSelector.ONLINE_STATUS_TERMINATED, pp.Vendor_Status__c);
    }

    /**
     * @description Test switch process with  one switch contract
     */
    @IsTest
    public static void test_switchFunctionality() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'Switch';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(10), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert switchContract;

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assert(cont.End_Date__c <= switchContract.StartDate || cont.StartDate > switchContract.StartDate || cont.Id == switchContract.Id);
            if (cont.Id == switchContract.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertEquals(null, cont.End_Date__c);
            } else if (cont.StartDate < switchContract.StartDate) {
                System.assertEquals('Draft', cont.Status);
            } else {
                System.assertEquals('Terminated', cont.Status);
            }
        }

    }

    /**
     * @description Test switch process with Business Config
     */
    @IsTest
    public static void test_switchFunctionalityBC() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];
        Business_Config__c config3 = UnitTestDataFactory.createBusinessConfig('ContractCreation', 'Process', 'validServiceTypesForSwitch', 'Commission Fee,Logistics Fee', testCountry.Id, 'Yogiyo_Contract', true, false);
        insert config3;
        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'Switch';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(10), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert switchContract;

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assert(cont.End_Date__c <= switchContract.StartDate || cont.StartDate > switchContract.StartDate || cont.Id == switchContract.Id);
            if (cont.Id == switchContract.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertEquals(null, cont.End_Date__c);
            } else if (cont.StartDate < switchContract.StartDate) {
                System.assertEquals('Draft', cont.Status);
            } else {
                System.assertEquals('Terminated', cont.Status);
            }
        }

    }

    /**
     * @description Test switch functionality with tiered switch commissions
     */
    @IsTest
    public static void test_switchFunctionalityTieredSwitch() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'Switch';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(5), End_Date__c = Date.today().addDays(7), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);
        Contract switchContract2 = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(8), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert new List<Contract> {switchContract, switchContract2};

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assert(cont.End_Date__c <= switchContract2.StartDate || cont.StartDate > switchContract2.StartDate || cont.Id == switchContract2.Id);
            if (cont.Id == switchContract2.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertEquals(null, cont.End_Date__c);
            } else if (cont.Id == switchContract.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertNotEquals(null, cont.End_Date__c);
            } else if (cont.StartDate < switchContract.StartDate) {
                System.assertEquals('Draft', cont.Status);
            } else {
                System.assertEquals('Terminated', cont.Status);
            }
        }

    }

    /**
    * @description Test switch functionality with tiered switch commissions of different service type
    */
    @IsTest
    public static void test_switchFunctionalityServiceType() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'Switch';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Logistics Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(5), End_Date__c = Date.today().addDays(7), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);
        Contract switchContract2 = new Contract(Service_Type__c = 'Logistics Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(8), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert new List<Contract> {switchContract, switchContract2};

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assert(cont.End_Date__c <= switchContract2.StartDate || cont.StartDate > switchContract2.StartDate || cont.Id == switchContract2.Id);
            if (cont.Id == switchContract2.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertEquals(null, cont.End_Date__c);
            } else if (cont.Id == switchContract.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertNotEquals(null, cont.End_Date__c);
            } else if (cont.StartDate < switchContract.StartDate) {
                System.assertEquals('Draft', cont.Status);
            } else {
                System.assertEquals('Terminated', cont.Status);
            }
        }

    }

    /**
    * @description Test switch functionality with tiered switch commissions of different service type
    */
    @IsTest
    public static void test_switchFunctionalityInvalidServiceType() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'Switch';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Service Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(5), End_Date__c = Date.today().addDays(7), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);
        Contract switchContract2 = new Contract(Service_Type__c = 'Service Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(8), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert new List<Contract> {switchContract, switchContract2};

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assertEquals('Draft', cont.Status);
        }

    }

    /**
    * @description Test additional switch types functionality with tiered switch commissions
    */
    @IsTest
    public static void testAdditionalSwitchFunctionalityTieredSwitch() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'Upgrade/Upsell';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(5), End_Date__c = Date.today().addDays(7), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);
        Contract switchContract2 = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(8), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert new List<Contract> {switchContract, switchContract2};

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assert(cont.End_Date__c <= switchContract2.StartDate || cont.StartDate > switchContract2.StartDate || cont.Id == switchContract2.Id);
            if (cont.Id == switchContract2.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertEquals(null, cont.End_Date__c);
            } else if (cont.Id == switchContract.Id) {
                System.assertEquals('Draft', cont.Status);
                System.assertNotEquals(null, cont.End_Date__c);
            } else if (cont.StartDate < switchContract.StartDate) {
                System.assertEquals('Draft', cont.Status);
            } else {
                System.assertEquals('Terminated', cont.Status);
            }
        }
    }

    /**
    * @description Test switch functionality with tiered switch commissions of invalit opportunity business type
    */
    @IsTest
    public static void testSwitchFunctionalityInvalidBusinessType() {
        List<Contract> allContracts = new List<Contract>();
        List<Contract> oldContracts = new List<Contract>();
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;

        Platform_Performance__c platPerformance = new Platform_Performance__c (Account__c = accounts.get(0).Id,
                Platform__c = 'Yogiyo',
                Vendor_Status__c = '');
        insert platPerformance;

        List<Opportunity> testOpportunities = UnitTestDataFactory.createOpportunities(accounts, 2, 'Yogiyo_Opportunity', System.today());
        testOpportunities.get(0).Business_Type__c = 'New Business';
        testOpportunities.get(1).Business_Type__c = 'New Business';
        insert testOpportunities;

        for (Integer i = 1; i < 11; i++) {
            oldContracts.add(new Contract(
                    AccountId = accounts[0].Id,
                    Id_Opportunity__c = testOpportunities.get(1).Id,
                    StartDate = Date.today().addDays(i + 1),
                    End_Date__c = Date.today().addDays(i + 2),
                    Status = 'Draft',
                    Service_Type__c = 'Commission Fee',
                    RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id,
                    Company_Name__c = 'Yogiyo'
            )
            );
        }
        oldContracts.add(new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(1).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(12), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id));

        insert oldContracts;

        Contract switchContract = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(5), End_Date__c = Date.today().addDays(7), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);
        Contract switchContract2 = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunities.get(0).Id, AccountId = accounts[0].Id, StartDate = Date.today().addDays(8), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert new List<Contract> {switchContract, switchContract2};

        allContracts = ContractSelector.getAll();
        for (Contract cont: allContracts) {
            System.assertEquals('Draft', cont.Status);
        }

    }

   /**
    * @description Test if account is updated based on active/expired commissions
    */
    @IsTest
    public static void testAccountDeliveryTypeUpdate() {
        Country__c testCountry = [SELECT Iso__c,
                Name,
                CurrencyIsoCode
        FROM Country__c
        WHERE Iso__c = 'KR' ];

        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        insert accounts;
  
        Opportunity testOpportunity = UnitTestDataFactory.createOpportunities(accounts, 1, 'Yogiyo_Opportunity', System.today()).get(0);
        testOpportunity.Business_Type__c = 'New Business';
        insert testOpportunity;

        Contract commissionContract = new Contract(Service_Type__c = 'Commission Fee', Id_Opportunity__c = testOpportunity.Id, AccountId = accounts[0].Id, StartDate = Date.today(), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);
        Contract serviceContract = new Contract(Service_Type__c = 'Logistics Fee', Id_Opportunity__c = testOpportunity.Id, AccountId = accounts[0].Id, StartDate = Date.today(), End_Date__c = Date.today().addDays(7), Status = 'Draft', RecordTypeId = mapRecordtypes.get('Yogiyo_Contract').Id);

        insert new List<Contract> {commissionContract, serviceContract};
        commissionContract.Status = 'Activated';
        serviceContract.Status = 'Activated';
        update new List<Contract> {commissionContract, serviceContract};

        Test.startTest();
            Account deliveryAccount = ClsAccountSelector.findAccountById(accounts[0].Id);
            System.assertEquals('Hybrid', deliveryAccount.Delivery_Service__c);

            commissionContract.Status = 'Terminated';
            update commissionContract;

            deliveryAccount = ClsAccountSelector.findAccountById(accounts[0].Id);
            System.assertEquals('DH Delivery', deliveryAccount.Delivery_Service__c);

            serviceContract.Status = 'Terminated';
            update serviceContract;

            deliveryAccount = ClsAccountSelector.findAccountById(accounts[0].Id);
            System.assertEquals(null, deliveryAccount.Delivery_Service__c);

            commissionContract.Status = 'Activated';
            update commissionContract;

            deliveryAccount = ClsAccountSelector.findAccountById(accounts[0].Id);
            System.assertEquals('Partner Delivery', deliveryAccount.Delivery_Service__c);
        Test.stopTest();
    }
}