force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>The role the contact plays in the restaurant</description>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-owner</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Franchise Contact</fullName>
            </value>
            <value>
                <fullName>Former Owner</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Previous Owner</fullName>
            </value>
            <value>
                <fullName>Ex-employee</fullName>
            </value>
            <value>
                <fullName>Billing Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
                <label>duplicate</label>
            </value>
            <value>
                <fullName>Additional Contact</fullName>
                <label>additional contact</label>
            </value>
            <value>
                <fullName>Restaurant Operations</fullName>
            </value>
            <value>
                <fullName>Customer Contact</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_ID_Number__c</fullName>
    <description>#JIRA:SSC-795</description>
    <label>Passport / ID Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactSelectorTest.cls
/**
 * @description [Test class for ContactSelector]
 * Created by Sarfaraz.Ahmed on 06/07/2020.
 */
@isTest
public class ContactSelectorTest {

    @testSetup static void setup() {

        UnitTestDataFactory.getRecordtypeValues();

        Country__c uaeCountry = UnitTestDataFactory.createCountry('AE','United Arab Emirates', 'AED');
        insert uaeCountry;
        Company__c comUAE = UnitTestDataFactory.createCompany('Talabat UAE', 'Talabat', uaeCountry);
        insert comUAE;

        Account uaeAccount = UnitTestDataFactory.createAccount('test',uaeCountry,Constants.ACCOUNT_RT_TALABAT_ACCOUNT);
        uaeAccount.phone = '+85278273613';
        insert uaeAccount;

        Account uaeAccount1 = UnitTestDataFactory.createAccount('test1',uaeCountry,Constants.ACCOUNT_RT_TALABAT_ACCOUNT);
        uaeAccount1.phone = '+85278273613';
        insert uaeAccount1;

        List<Contact> listContact;
        listContact = UnitTestDataFactory.CreateContacts(new List<Account>{uaeAccount}, 'Best', 'Burger', 'Mr', 'Employee', 2, 'test', Constants.CONTACT_RT_TALABAT_DEVELOPERNAME);
        listContact[0].Contact_Role__c='Owner';
        listContact[0].Passport_ID_Number__c='111';
        listContact[0].Email='test@test.com';
        listContact[1].Contact_Role__c='Manager';
        listContact[1].AccountId=uaeAccount1.id;
        insert listContact;

    }
    /**
    * @method name  : testOwnerQueries
    * @description  : Test method of the getAccountOwnerInformation, getNonPrimaryContactListForAccount,getByEmailAndAccountGrid and fetchContactsWithOwnerRole
    */
    private static testMethod void testOwnerQueries() {

        Contact contactObj =[select id,AccountId,Email,Account.GRID__c,Contact_Role__c from Contact where Contact_Role__c=:Constants.CONTACT_CONTACTROLE_OWNER limit 1];
        if(contactObj!=null){
            Test.startTest();
            List<Contact> contList = new List<Contact>();
            ContactSelector.getAccountOwnerInformation(contactObj.AccountId);
            ContactSelector.getNonPrimaryContactListForAccount(contactObj.AccountId,contactObj.Email);
            contList = ContactSelector.fetchContactsWithOwnerRole(new Set<Id>{contactObj.AccountId});
            ContactSelector.getByEmailAndAccountGrid(contactObj.Email,contactObj.Account.GRID__c);
            Test.stopTest();
            System.assert(!contList.isEmpty());
        }
    }
    /**
    * @method name  : testNonOwnerQueries
    * @description  : Test method of the getAccountOwnerInformation
    */
    private static testMethod void testNonOwnerQueries() {
        Contact contactObj =[select id,AccountId,Email,Account.GRID__c,Contact_Role__c from Contact where Contact_Role__c!=:Constants.CONTACT_CONTACTROLE_OWNER limit 1];
        if(contactObj!=null){
            Test.startTest();
            ContactSelector.getAccountOwnerInformation(contactObj.AccountId);
            Test.stopTest();
            System.assert(contactObj.Contact_Role__c!=null);
        }

    }
}