force-app/main/default/objects/Account/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID</description>
    <externalId>true</externalId>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CD_Account.recordType-meta.xml
<RecordType>
    <fullName>CD_Account</fullName>
    <active>true</active>
    <description>Account for Click Delivery</description>
    <label>CD Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Yogiyo_Account.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Account</fullName>
    <active>true</active>
    <description>KR Account Recordtype</description>
    <label>Yogiyo Account</label>
</RecordType>

force-app/main/default/objects/ActionItem__c/ActionItem__c.object-meta.xml
<CustomObject>
    <label>Action Item</label>
    <nameField>
        <label>Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionItem__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sales_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionItem__c/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <formula>Account__r.GRID__c</formula>
    <label>GRID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionItem__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Commission Upgrade</fullName>
            </value>
            <value>
                <fullName>Delivery Area</fullName>
            </value>
            <value>
                <fullName>Delivery Fee</fullName>
            </value>
            <value>
                <fullName>Delivery Time</fullName>
            </value>
            <value>
                <fullName>Exclusivity</fullName>
            </value>
            <value>
                <fullName>Fail Rate</fullName>
            </value>
            <value>
                <fullName>Joker</fullName>
            </value>
            <value>
                <fullName>Menu</fullName>
            </value>
            <value>
                <fullName>MOV</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Reviews</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
            <value>
                <fullName>Transmission Method</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Date__c</fullName>
    <inlineHelpText>this field is populated when case has a task of type call.</inlineHelpText>
    <label>Last Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Opportunity__r.Start_Date_uk__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If emply, this means ASAP.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CD_Inbound_Case.recordType-meta.xml
<RecordType>
    <fullName>CD_Inbound_Case</fullName>
    <active>true</active>
    <businessProcess>Global Inbound</businessProcess>
    <label>CD Inbound Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Yogiyo_Inbound.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Inbound</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Inbound</businessProcess>
    <description>Case for every external communucation in Korea</description>
    <label>Yogiyo Inbound</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country of Lead</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID to be transferred to account when lead record is converted</description>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Date__c</fullName>
    <label>Last Call Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
                <default>true</default>
                <label>Branch</label>
            </value>
            <value>
                <fullName>Branch - Main</fullName>
            </value>
            <value>
                <fullName>Branch - Kitchen Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/CD_Lead.recordType-meta.xml
<RecordType>
    <fullName>CD_Lead</fullName>
    <active>true</active>
    <businessProcess>CD Lead Process</businessProcess>
    <description>Click Delivery Lead Process</description>
    <label>CD Lead</label>
</RecordType>

force-app/main/default/objects/Lead/recordTypes/Yogiyo_Lead.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Lead</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Lead Process</businessProcess>
    <description>Korea Lead Record Type</description>
    <label>Yogiyo Lead</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/DE_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>DE_Opportunity</fullName>
    <active>true</active>
    <businessProcess>DE Sales Process</businessProcess>
    <label>DE Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Yogiyo_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Sales Proccess</businessProcess>
    <description>KR Opportunity Recordtype</description>
    <label>Yogiyo Opportunity</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/CD_Task.recordType-meta.xml
<RecordType>
    <fullName>CD_Task</fullName>
    <active>true</active>
    <label>CD Task</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/DE_Task.recordType-meta.xml
<RecordType>
    <fullName>DE_Task</fullName>
    <active>true</active>
    <label>DE Task</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Talabat_Task.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Task</fullName>
    <active>true</active>
    <label>Talabat Task</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Yogiyo_Task.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Task</fullName>
    <active>true</active>
    <description>Yogiyo_Task</description>
    <label>Yogiyo Task</label>
</RecordType>

force-app/main/default/classes/UnitTestClsTaskProcessor.cls
@isTest
private class UnitTestClsTaskProcessor {

    @testSetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();

        Country__c c = UnitTestDataFactory.createCountry('EC', 'Ecuador', 'USD');
        insert c;

        Account a = UnitTestDataFactory.createAccount('test acc', c, 'CD_Account');
        insert a;

        Case cs = UnitTestDataFactory.createCase(a, 'New', 'CD Inbound', 'issue whatever', 'Phone', c, 'CD_Inbound_Case', 'test');
        insert cs;

        Lead l = UnitTestDataFactory.createLeads(1, c, 'test', 'test', 'USD', 'test', 'CD_Lead')[0];
        insert l;

        Country__c talabatCountry = UnitTestDataFactory.createCountry('AE', 'United Arab Emirates', 'AED');
        insert talabatCountry;

        Account talabatAccount = UnitTestDataFactory.createAccount('test acc', talabatCountry, 'Talabat_Account');
        insert talabatAccount;

        List<ActionItem__c> actionItems = createActionItems(2,talabatAccount);
        insert actionItems;

        List<Task> taskInstance = createTaskForActionItem(1, actionItems[0]);
        insert taskInstance;

        List<Task> taskWithAnotherActionItem = createTaskForActionItem(1, actionItems[1]);
        insert taskWithAnotherActionItem;
        
        // create business configs
        List<Business_Config__c> configs = new List<Business_Config__c>();
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','requiredProbabilityForCEStage','20', null,'Generic_Activity',True,True));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','oppContactEstablishedStageName','Contact Established', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','requiredProbabilityForOpenStage','5', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','oppOpenStageName','Open', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','CEAcitvitySubject','Call - Decision maker reached', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','openAcitvitySubject','Call - Employee reached,Call - Nobody reached', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','taskTypes','Call', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','taskStatus','Completed', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('opportunityUpdateFromTaskProcess','process','eventTypes','Meeting', null,'Generic_Activity',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig(Constants.BUSINESSCONFIG_PROCESSNAME_SYNCTASKS,'process', Constants.BUSINESSCONIFG_RULENAME_TASKFIELDTOMAP,'Subject,Type', null,'Talabat_Task',True,True));
        insert configs;
    }

    @isTest static void updateCaseLastCallDateWorksCorrectly() {
        Case c = [Select Id From Case Limit 1];

        Datetime res;

        Test.startTest();

        Task call = new Task(
            Type = 'Call',
            Subject = 'Test',
            WhatId = c.Id,
            Status = 'Completed',
            recordtypeId = LibRecordTypeHelper.getRecordTypeValue('CD_Task')
        );

        insert call;

        res = [select CreatedDate from Task where id =: call.Id].CreatedDate;

        Test.stopTest();

        c = [Select Last_Call_Date__c From Case where id =: c.Id];

        System.assertEquals(res, c.Last_Call_Date__c);
    }

    @isTest static void updateCaseLastCallDateDoesNothingIfTaskIsNotACallOrIsNotCompleted() {
        Case c = [Select Id From Case Limit 1];

        Test.startTest();

        // call not completed
        Task t1 = new Task(
            Type = 'Call',
            Subject = 'Test',
            WhatId = c.Id,
            Status = 'New',
            recordtypeId = LibRecordTypeHelper.getRecordTypeValue('CD_Task')
        );

        // not a call
        Task t2 = new Task(
            Type = 'Task',
            Subject = 'Test',
            WhatId = c.Id,
            Status = 'Completed',
            recordtypeId = LibRecordTypeHelper.getRecordTypeValue('CD_Task')
        );

        insert new List<Task>{t1, t2};

        Test.stopTest();

        c = [Select Last_Call_Date__c From Case where id =: c.Id];

        System.assertEquals(null, c.Last_Call_Date__c);
    }

    @isTest static void updateLeadLastCallDateWorksCorrectly() {
        Lead l = [select id from Lead limit 1];

        Datetime res;

        Test.startTest();

        Task call = new Task(
            Type = 'Call',
            Subject = 'Test',
            WhoId = l.Id,
            Status = 'Completed',
            recordtypeId = LibRecordTypeHelper.getRecordTypeValue('CD_Task')
        );

        insert call;

        res = [select CreatedDate from Task where id =: call.Id].CreatedDate;

        Test.stopTest();

        l = [Select Last_Call_Date__c From Lead Where Id =: l.Id];

        System.assertEquals(res, l.Last_Call_Date__c);
    }

    @isTest static void updateLeadLastCallDateDoesNothingIfTaskIsNotACallOrIsNotCompleted() {
        Lead l = [Select Id From Lead Limit 1];

        Test.startTest();

        // call not completed
        Task t1 = new Task(
            Type = 'Call',
            Subject = 'Test',
            WhoId = l.Id,
            Status = 'New',
            recordtypeId = LibRecordTypeHelper.getRecordTypeValue('CD_Task')
        );

        // not a call
        Task t2 = new Task(
            Type = 'Task',
            Subject = 'Test',
            WhoId = l.Id,
            Status = 'Completed',
            recordtypeId = LibRecordTypeHelper.getRecordTypeValue('CD_Task')
        );

        insert new List<Task>{t1, t2};

        Test.stopTest();

        l = [Select Last_Call_Date__c From Lead where id =: l.Id];

        System.assertEquals(null, l.Last_Call_Date__c);
    }



    @isTest static void legacyTestJustForCoverage() {
        List<Account> accounts;
        List<Account> accounts2;
        List<Opportunity> opportunities;
        List<Lead> ls;
        Case cs;


        Country__c testCountry = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        Country__c testCountry2 = UnitTestDataFactory.createCountry('UK', 'United Kingdom', 'GBP');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('Yogiyo', 'Yogiyo', testCountry);
        insert testCompany;
        accounts = UnitTestDataFactory.createAccounts(1, testCountry, 'Yogiyo_Account');
        accounts2 = UnitTestDataFactory.createAccounts(1, testCountry2, 'FP_Account');
        accounts2[0].Phone = '+85227367722';
        insert accounts;
        opportunities = UnitTestDataFactory.createOpportunities(accounts, 1, 'Yogiyo_Opportunity', Date.today().addMonths(2));
        insert opportunities;
        ls = UnitTestDataFactory.createLeads(2, testCountry, 'test', 'Yogiyo', 'KRW', 'test', 'Yogiyo_Lead');
        ls[0].Status = 'decision maker reached';
        ls[0].GRID__c = 'BCD1';
        ls[1].Status = 'employee reached';
        ls[1].GRID__c = 'BCD2';

        insert ls;
        cs = UnitTestDataFactory.createCase(accounts2[0], 'New', 'Partner', 'Transmission Issues', 'phone', testCountry2, 'Yogiyo_Inbound', 'Tablink Callback: Eve Richens');
        insert cs;

        ClsTaskProcessor ct = new ClsTaskProcessor();
        Task t1  = new Task(Subject = 'Email', Type = 'Call', status = 'Completed', whatId = opportunities[0].id, description = 'test it', ActivityDate = Date.today(), recordtypeId = LibRecordTypeHelper.getRecordTypeValue('Yogiyo_Task'));
        Task t2  = new Task(Subject = 'Email', Type = 'Call', status = 'New', whoid = ls[0].id, description = 'test it', ActivityDate = Date.today(), Activity_Subject__c = 'decision maker reached');
        Task t3  = new Task(Subject = 'Email', Type = 'Call', status = 'Completed', whoid = ls[0].id, description = 'test it', ActivityDate = Date.today(), Activity_Subject__c = 'employee reached');
        Task t4  = new Task(Subject = 'Email', Type = 'Call', status = 'Completed', whatId = cs.Id, description = 'test it', ActivityDate = Date.today(), Activity_Subject__c = 'employee reached');
        insert new List<Task> {t1, t2, t3, t4};
    }
    
    @isTest
    public static void testOpportunityStageUpdateForOpenStage(){
    	Country__c testCountry = UnitTestDataFactory.createCountry('DE', 'Germany', 'EUR');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('Lieferheld', 'Lieferheld', testCountry);
        insert testCompany;
        List<Account> accounts 	= UnitTestDataFactory.createAccounts(1, testCountry, 'DE_Account');
        insert accounts;
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accounts, 1, 'DE_Opportunity', Date.today().addMonths(2));
        opportunities[0].stageName = 'New';
        insert opportunities;
        
        Test.startTest();
        	Task t1  = new Task(Subject = 'Email', Type = 'Call', status = 'Completed', whatId = opportunities[0].id, 
        				description = 'test it', ActivityDate = Date.today(), 
        				recordtypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Task'),
        				Activity_Subject__c = 'Call - Employee reached');
        	insert t1;
        Test.stopTest();
        
        List<Opportunity> opps = [Select Id from Opportunity where stageName = 'Open'];
        system.assertEquals(1,opps.size());
    }
    
    @isTest
    public static void testOpportunityStageUpdateForCEStage(){
    	Country__c testCountry = UnitTestDataFactory.createCountry('DE', 'Germany', 'EUR');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('Lieferheld', 'Lieferheld', testCountry);
        insert testCompany;
        List<Account> accounts 	= UnitTestDataFactory.createAccounts(1, testCountry, 'DE_Account');
        insert accounts;
        List<Opportunity> opportunities = UnitTestDataFactory.createOpportunities(accounts, 1, 'DE_Opportunity', Date.today().addMonths(2));
        opportunities[0].stageName = 'New';
        insert opportunities;
        
        Test.startTest();
        	Task t1  = new Task(Subject = 'Email', Type = 'Call', status = 'Completed', whatId = opportunities[0].id, 
        				description = 'test it', ActivityDate = Date.today(), 
        				recordtypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Task'),
        				Activity_Subject__c = 'Call - Decision maker reached');
        	insert t1;
        Test.stopTest();
        
        List<Opportunity> opps = [Select Id from Opportunity where stageName = 'Contact Established'];
        system.assertEquals(1,opps.size());
    }

    /**
    * @date     : [06/05/2020]
    * @method name  : testSyncTaskObject
    * @description  : Test method of the syncTaskObject
    * @retun : None
    */
    @IsTest
    public static void testSyncTaskObject() {

        List<Task> taskInstance = [SELECT ID,Code__c,WhatId,Subject FROM Task limit 2];
        taskInstance[0].Code__c = taskInstance[1].Code__c;
        taskInstance[0].Subject = 'Other';

        Test.startTest();
        update taskInstance[0];
        System.assert(!taskInstance.isEmpty());
        Test.stopTest();
    }

    /**
    *
    * @description [Create Action Item data]
    * @param noOfRecords [No of records to create]
    * @param objAccount [Account under which action items are created]
    *
    * @return [List of action items]
    */
    public static List<ActionItem__c> createActionItems(Integer noOfRecords, Account objAccount){
        List<ActionItem__c> actionItems = new List<ActionItem__c>();
        ActionItem__c obj = new ActionItem__c();
        for(Integer i=0;i<noOfRecords;i++){
            obj  = new ActionItem__c();
            obj.Name = 'Action Item' + i;
            obj.Type__c = Constants.ACTION_ITEM_TYPE_COMMISSION_UPGRADE;
            obj.Start_Date__c  = System.today();
            obj.End_Date__c = System.today().addDays(10);
            obj.Account__c = objAccount.Id;
            actionItems.add(obj);
        }
        return actionItems;
    }

    /**
    * @description  [Create Task under Action Items ]
    * @param noOfRecords [No of records to create]
    * @param objActionItem [Action Item record ]
    * @return [Task record]
    */
    public static List<Task>  createTaskForActionItem(Integer noOfRecords, ActionItem__c objActionItem){
        List<Task> taskList = new List<Task>();
        Task objTask = new Task();
        for(Integer i=0;i<noOfRecords;i++){
            objTask.OwnerId = UserInfo.getUserId();
            objTask.WhatId = objActionItem.Id;
            objTask.RecordTypeId = LibRecordTypeHelper.getRecordTypeIdByDeveloperName(Constants.SOBJECT_TASK,Constants.TASK_RT_TALABAT_TASK);
            objTask.Subject = Constants.TASK_SUBJECT_CALL;
            objTask.Status = Constants.TASK_STATUS_NOT_STARTED;
            objTask.Priority = Constants.TASK_PRIORITY_NORMAL;
            taskList.add(objTask);
        }
        return taskList;
    }
}