force-app/main/default/objects/Account/fields/Halal_Certificate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Halal_Certificate_Expiry_Date__c</fullName>
    <label>Halal Certificate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Yogiyo_Account.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Account</fullName>
    <active>true</active>
    <description>KR Account Recordtype</description>
    <label>Yogiyo Account</label>
</RecordType>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Yogiyo_Internal_Case.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Internal_Case</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Inbound</businessProcess>
    <label>Yogiyo Internal Case</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Cheque Copy</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Contract Termination</fullName>
            </value>
            <value>
                <fullName>Deal Confirmation</fullName>
            </value>
            <value>
                <fullName>Exclusivity Agreement</fullName>
            </value>
            <value>
                <fullName>Delivery Area</fullName>
            </value>
            <value>
                <fullName>Menu Item Level Photos</fullName>
            </value>
            <value>
                <fullName>Halal Certification</fullName>
            </value>
            <value>
                <fullName>Logo</fullName>
            </value>
            <value>
                <fullName>Menu</fullName>
            </value>
            <value>
                <fullName>Tax Registration Form</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Opening Hours</fullName>
            </value>
            <value>
                <fullName>Photo Store Front</fullName>
            </value>
            <value>
                <fullName>Food Licence Number</fullName>
            </value>
            <value>
                <fullName>Account Set Up Form</fullName>
            </value>
            <value>
                <fullName>ID Card/Passport</fullName>
            </value>
            <value>
                <fullName>Cover Photo/Listing Hero Photo</fullName>
            </value>
            <value>
                <fullName>Food Photos</fullName>
                <isActive>false</isActive>
                <label>Food Photos</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>d</fullName>
                <isActive>false</isActive>
                <label>d</label>
            </value>
            <value>
                <fullName>sa</fullName>
                <isActive>false</isActive>
                <label>sa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Halal_Certificate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Halal_Certificate_Expiry_Date__c</fullName>
    <label>Halal Certificate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country of Lead</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Yogiyo_Lead.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Lead</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Lead Process</businessProcess>
    <description>Korea Lead Record Type</description>
    <label>Yogiyo Lead</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Yogiyo_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Sales Proccess</businessProcess>
    <description>KR Opportunity Recordtype</description>
    <label>Yogiyo Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/Yogiyo_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity_Quote</fullName>
    <active>true</active>
    <label>Yogiyo Opportunity Quote</label>
</RecordType>

force-app/main/default/classes/ContentVersion_Selector_Test.cls
@isTest
public with sharing class ContentVersion_Selector_Test {
    private static Opportunity opp;
    private static Account acc;
    private static Case testCase;
    private static List<Lead> lstLd;
    private static List<Opportunity_Quote__c> lstOppQ;
    private static Country__c c;
    private static Company__c com;
    private static String attType;
    private static String docId;
    private static ContentDocumentLink cdl;
    private static List<String> lstAttTypes = new List<String>();
   
    static {
        UnitTestDataFactory.getRecordtypeValues();
        c = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
        insert c;
        com = UnitTestDataFactory.createCompany('Yogiyo', 'Yogiyo', c);
        insert com;
        acc = UnitTestDataFactory.createAccount('TestAccount', c, 'Yogiyo_Account');
        acc.Halal_Certificate_Expiry_Date__c = Date.today();
        insert acc;
        opp = UnitTestDataFactory.createOpportunity('TestOpp123', acc, 'Yogiyo_Opportunity', Date.today());
        insert opp;
        lstLd = UnitTestDataFactory.createLeads(1, c, 'Test Last Name', 'Yogiyo', 'KRW', 'Test Res Name', 'Yogiyo_Lead');
        insert lstLd;
        lstOppQ = UnitTestDataFactory.createOpportunityQuotes(opp, 1, 'Yogiyo_Opportunity_Quote', 'Accepted', 'Test description', 10.00, 10.00, 'urlKey', 'key', 23.00);
        insert lstOppQ;

        Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Case'});
        testCase = new Case(Opportunity__c = opp.id, type = 'Quality Check', AccountId = opp.AccountId, RecordTypeId = mapRecordtypes.get('Yogiyo_Internal_Case').id);
        insert testCase;

        
        Schema.DescribeFieldResult fieldResult = ContentVersion.Attachment_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for(Schema.PicklistEntry plVal : ple){
            lstAttTypes.add(plVal.getLabel());
        }
        attType = lstAttTypes[0];
        ContentVersion cv = new ContentVersion(Title = 'TestTitle',
                                                Attachment_Type__c = attType,
                                                VersionData = Blob.valueOf('Content Test'),
                                                PathOnClient = 'testpath',
                                                IsMajorVersion = true
        );
        insert cv;

        List<ContentVersion> contentVersion = [SELECT Id, ContentDocumentId FROM ContentVersion LIMIT 1];
        docId = contentVersion[0].ContentDocumentId;
        cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = testCase.Id;
        cdl.ContentDocumentId = docId;
        cdl.ShareType = 'V';
        insert cdl;
    }
    
    @isTest 
    static void testAllMethods(){
        Set<Id> recIdSet = new Set<Id>();
        List<Case> allCasesList = CaseSelector.getAll();
        List<Account> allAccsList = AccountSelector.getAll();
        List<Opportunity> allOppList = Opportunity_Selector.getAll();
        
        for(Case cs : allCasesList){
            recIdSet.add(cs.Id);
        }
        
        List<ContentDocumentLink> cdLinkList = COntentVersion_Selector.getContentDocumnetLink(allCasesList[0].Id, 'TestTitle');
        List<String> cdIdList = new List<String>();
        List<String> titlesList = new List<String>();
        Set<Id> cdIdSet = new Set<Id>();
        for(ContentDocumentLink cdl : cdLinkList){
            cdIdList.add(cdl.ContentDocumentId);
            cdIdSet.add(cdl.ContentDocumentId);
            titlesList.add(cdl.ContentDocument.Title);
        }        
        
        COntentVersion_Selector.getContentDocumnetLink(allCasesList[0].Id);
        COntentVersion_Selector.getContentVersion(cdIdList);
        COntentVersion_Selector.getContentDocumnetLinksWithLatestVersionBody(recIdSet);
        COntentVersion_Selector.getObjects(allCasesList[0].Id);
        COntentVersion_Selector.getObjects(allAccsList[0].Id);
        COntentVersion_Selector.getObjects(allOppList[0].Id);
        COntentVersion_Selector.getObjects(lstLd[0].Id);
        COntentVersion_Selector.getObjects(lstOppQ[0].Id);
        COntentVersion_Selector.getAccounts(allAccsList[0].Id);
        COntentVersion_Selector.getContentDocumentLinks(cdIdSet);
        COntentVersion_Selector.getContentDocumentsFromTitles(titlesList);
        System.assertEquals(false, cdLinkList.isEmpty());
    }
}