force-app/main/default/objects/Account/fields/Halal_Certificate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Halal_Certificate_Expiry_Date__c</fullName>
    <label>Halal Certificate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Attachment_Type__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Type__c</fullName>
    <label>Attachment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bank Details</fullName>
            </value>
            <value>
                <fullName>Cheque Copy</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Contract Termination</fullName>
            </value>
            <value>
                <fullName>Deal Confirmation</fullName>
            </value>
            <value>
                <fullName>Exclusivity Agreement</fullName>
            </value>
            <value>
                <fullName>Delivery Area</fullName>
            </value>
            <value>
                <fullName>Menu Item Level Photos</fullName>
            </value>
            <value>
                <fullName>Halal Certification</fullName>
            </value>
            <value>
                <fullName>Logo</fullName>
            </value>
            <value>
                <fullName>Menu</fullName>
            </value>
            <value>
                <fullName>Tax Registration Form</fullName>
            </value>
            <value>
                <fullName>Business License</fullName>
            </value>
            <value>
                <fullName>Opening Hours</fullName>
            </value>
            <value>
                <fullName>Photo Store Front</fullName>
            </value>
            <value>
                <fullName>Food Licence Number</fullName>
            </value>
            <value>
                <fullName>Account Set Up Form</fullName>
            </value>
            <value>
                <fullName>ID Card/Passport</fullName>
            </value>
            <value>
                <fullName>Cover Photo/Listing Hero Photo</fullName>
            </value>
            <value>
                <fullName>Food Photos</fullName>
                <isActive>false</isActive>
                <label>Food Photos</label>
            </value>
            <value>
                <fullName>a</fullName>
                <isActive>false</isActive>
                <label>a</label>
            </value>
            <value>
                <fullName>b</fullName>
                <isActive>false</isActive>
                <label>b</label>
            </value>
            <value>
                <fullName>d</fullName>
                <isActive>false</isActive>
                <label>d</label>
            </value>
            <value>
                <fullName>sa</fullName>
                <isActive>false</isActive>
                <label>sa</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Halal_Certificate_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Halal_Certificate_Expiry_Date__c</fullName>
    <label>Halal Certificate Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContentVersion_Selector.cls
/**
* @author Konrad Czykin
* @date 14.08.2019
*
* @description Selector class for retrieving contentversions, object's records for Attachments_AuraController.cls
*/
public class ContentVersion_Selector {
	
    /*Constants used in Contentversion trigger */
    public static final String FILE_TYPE_PDF = '.pdf';
    public static final String QUOTE_FILENAME_PREFIX = 'Contract - '; // THis prefix should always match with the delivery option File name mentioned in the Docgen package
     public static final String FILE_TYPE_SNOTE = 'snote';

    /*****************************************************************************
    * @description Query for ContendDocument by title and file extension 
    * @param title of the document
    * @param file extension of the document
    * @return List of ContentDocument records
    *******************************************************************************/
	/*
    public static List<ContentDocument> getContentDocumentByTitleAndExtension(String title, String fileExtension){
        List<ContentDocument> lstContentDocuments = new List<ContentDocument>();
        try {
              lstContentDocuments = [SELECT Id, Title, FileExtension FROM ContentDocument WHERE Title =:title AND FileExtension = :fileExtension LIMIT 1]; 
        } catch (QueryException e) {
            system.debug('Error: '+ e.getMessage());
        }
        return lstContentDocuments;
    } */

     /*****************************************************************************
    * @description Query for ContendDocument by id
    * @param set of ids
    * @return List of ContentDocument records
    *******************************************************************************/
	/*
    public static List<ContentDocument> getContentDocumentByIds(Set<Id> ids){
        List<ContentDocument> lstContentDocuments = new List<ContentDocument>();
        try {
              lstContentDocuments = [SELECT Id, Title, FileExtension FROM ContentDocument WHERE Id in :ids]; 
        } catch (QueryException e) {
            system.debug('Error: '+ e.getMessage());
        }
        return lstContentDocuments;
    }*/

     /*****************************************************************************
    * @description Query for ContendVersion including Body
    * @param set of ids
    * @return List of ContentVersions records
    *******************************************************************************/
	/*
    public static List<ContentVersion> getContentVersionWithBody(Set<Id> contentDocumentIds){
        List<ContentVersion> lstContentVersion = new List<ContentVersion>();
        try {
              lstContentVersion = [SELECT Id, IsLatest, ContentDocumentId, VersionData FROM ContentVersion WHERE ContentDocumentId in :contentDocumentIds AND IsLatest = true]; 
        } catch (QueryException e) {
            system.debug('Error: '+ e.getMessage());
        }
        return lstContentVersion;
    }*/
    /*****************************************************************************
    * @description Query for ContentDocumentLink object Id.
    * @param objectId
    * @return List of ContentDocumentLink
    *******************************************************************************/
    public static List<ContentDocumentLink> getContentDocumnetLink(String recordId){
        return [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :recordId];
    }
	
     /*****************************************************************************
    * @description Query for ContentDocumentLink obect by id and file name
    * @param objectId
    * @return List of ContentDocumentLink
    *******************************************************************************/
    public static List<ContentDocumentLink> getContentDocumnetLink(String recordId, String fileName){
        return [SELECT ContentDocumentId, ShareType, Visibility, ContentDocument.LatestPublishedVersionId, ContentDocument.Title FROM ContentDocumentLink WHERE LinkedEntityId = :recordId AND ContentDocument.Title = :fileName];
    }
     /*****************************************************************************
    * @description Query for ContentDocumentLink obect by content document 
    * @param objectId
    * @return List of ContentDocumentLink
    *******************************************************************************/
    public static List<ContentDocumentLink> getContentDocumnetLinksWithLatestVersionBody(Set<Id> recordIds){
       
        return [SELECT ContentDocumentId, ContentDocument.Title, ContentDocument.LatestPublishedVersionId, ContentDocument.LatestPublishedVersion.VersionData FROM ContentDocumentLink WHERE ContentDocumentId IN :recordIds];

    }

    /*****************************************************************************
    * @description Query for ContentVersion Ids
    * @param list of contentDocumentIds
    * @return List of ContentVersions records
    *******************************************************************************/
    public static List<ContentVersion> getContentVersion(List<String> lstFilesId){
   
        return [SELECT Id, ContentDocumentId, Title, FileExtension, Attachment_Type__c, 
                                    ContentModifiedDate, CreatedBy.Name, ContentSize, Halal_Certificate_Expiry_Date__c
                                FROM ContentVersion 
                                WHERE IsLatest = true AND FileType != :FILE_TYPE_SNOTE AND ContentDocumentId IN :lstFilesId ORDER BY LastModifiedDate DESC];
    }

    /*****************************************************************************
    * @description Query for sObject
    * @param queryString
    * @return List of sObjects
    *******************************************************************************/
    public static List<sObject> getObjects(Id objectId){

        String sObjectName = objectId.getSObjectType().getDescribe().getName();
        String queryString = '';
        if(sObjectName =='Account'){
            queryString = 'SELECT Id, Name, (SELECT Id, Name, LastModifiedDate, ContentType, BodyLength, CreatedBy.Name FROM Attachments) FROM ' + sObjectName + ' WHERE Id =: objectId';
        }else if(sObjectName == 'Case'){
            queryString = 'SELECT CaseNumber, AccountId, (SELECT Id, Name, LastModifiedDate, ContentType, BodyLength, CreatedBy.Name FROM Attachments) FROM ' + sObjectName + ' WHERE Id =: objectId';
        }else if(sObjectName == 'Lead'){
            queryString = 'SELECT Name, (SELECT Id, Name, LastModifiedDate, ContentType, BodyLength, CreatedBy.Name FROM Attachments) FROM ' + sObjectName + ' WHERE Id =: objectId';
        }else if(sObjectName == 'Opportunity_Quote__c'){
            queryString = 'SELECT Name, Id_Account__c, (SELECT Id, Name, LastModifiedDate, ContentType, BodyLength, CreatedBy.Name FROM Attachments) FROM ' + sObjectName + ' WHERE Id =: objectId';
        }else{
            queryString = 'SELECT Name, AccountId, (SELECT Id, Name, LastModifiedDate, ContentType, BodyLength, CreatedBy.Name FROM Attachments) FROM ' + sObjectName + ' WHERE Id =: objectId';
        }

    
        return Database.query(queryString);
    }

    /*****************************************************************************
    * @description Query for Accounts
    * @param account Id
    * @return List of Accounts
    *******************************************************************************/
    public static List<Account> getAccounts(String parentId){
       
        return [SELECT Id, Halal_Certificate_Expiry_Date__c FROM Account WHERE Id = :parentId];
    }

    /*****************************************************************************
    * @description Query for ContentDocumentLinks
    * @param set of contentdocumentIds
    * @return List of ContentDocumentLink
    *******************************************************************************/
    public static List<ContentDocumentLink> getContentDocumentLinks(Set<Id> contentDocumentIds){
        List<ContentDocumentLink> lstCdL = new List<ContentDocumentLink>();
        lstCdL = [SELECT id, ContentDocumentID, LinkedEntity.type, LinkedEntityId 
                                    FROM ContentDocumentLink 
                                    WHERE ContentDocumentID IN :contentDocumentIds];
        return lstCdL;
    }
	
    /*****************************************************************************
    * @description Query to return documents based on file names
    * @param titleList list of all the filenames 
    * @return List of ContentDocuments
    *******************************************************************************/
    public static List<ContentDocument> getContentDocumentsFromTitles(List<String> titleList){
        List<ContentDocument> cdList = new List<ContentDocument>();
        cdList = [SELECT Id, Title FROM ContentDocument WHERE Title IN:titleList];
        return cdList;
    }
    
}