force-app/main/default/objects/Account/fields/Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Frequency__c</fullName>
    <description>Invoice schedule  for Australia customers</description>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Quint-Monthly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Transmission_method__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Transmission_method__c</fullName>
    <description>Invoice Transmission method for AU</description>
    <inlineHelpText>For e.x. Invoices would send to the customer by email, post, Fax</inlineHelpText>
    <label>Invoice Transmission method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity_Quote__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity Quote</label>
    <referenceTo>Opportunity_Quote__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Transmission_method__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Transmission_method__c</fullName>
    <description>Invoice Transmission method</description>
    <formula>TEXT( Account.Invoice_Transmission_method__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Invoice Transmission method copied into this field from account</inlineHelpText>
    <label>Invoice Transmission method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Commission_Fee__c.field-meta.xml
<CustomField>
    <fullName>Main_Commission_Fee__c</fullName>
    <description>Holds the value of the main commission in case there are more than one opportunity line items of type commission on the opportunity. Use case for this is when a user has a trial commission and a normal commission. Used on the Australian quote template</description>
    <label>Main Commission Fee</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Main_Online_Payment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Main_Online_Payment_Fee__c</fullName>
    <description>Holds the value of the &quot;Online Payment Fee&quot; in case there are more than one opportunity line items of type &quot;Online Payment Fee&quot; on the opportunity. Used in the Australian quote template</description>
    <label>Main Online Payment Fee</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quote_Comment_Menu_Printing__c.field-meta.xml
<CustomField>
    <fullName>Quote_Comment_Menu_Printing__c</fullName>
    <description>Quote Comment Menu Printing</description>
    <label>Quote Comment Menu Printing</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SubTotalRF__c.field-meta.xml
<CustomField>
    <fullName>SubTotalRF__c</fullName>
    <label>SubTotal</label>
    <summarizedField>Opportunity_Line_Item__c.Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity_Line_Item__c.Line_Item_Type__c</field>
        <operation>equals</operation>
        <value>Product</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity_Line_Item__c.Id_Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VAT_fm__c.field-meta.xml
<CustomField>
    <fullName>VAT_fm__c</fullName>
    <formula>CASE( RecordType.DeveloperName , &quot;DH_AU_Opportunity&quot;, (SubTotalRF__c * 0.1), &quot;UK_Opportunity&quot;,(SubTotalRF__c * 0.2),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/SubTotalRF__c.field-meta.xml
<CustomField>
    <fullName>SubTotalRF__c</fullName>
    <label>SubTotal</label>
    <summarizedField>Opportunity_Quote_Line_Item__c.Total_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Opportunity_Quote_Line_Item__c.Line_Item_Type__c</field>
        <operation>equals</operation>
        <value>Product</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity_Quote_Line_Item__c.Id_Opportunity_Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Total_fm__c.field-meta.xml
<CustomField>
    <fullName>Total_fm__c</fullName>
    <formula>SubTotalRF__c + VAT_fm__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/VAT_fm__c.field-meta.xml
<CustomField>
    <fullName>VAT_fm__c</fullName>
    <formula>CASE(Id_Opportunity__r.RecordType.DeveloperName, &quot;DH_AU_Opportunity&quot;, (SubTotalRF__c * 0.1), &quot;UK_Opportunity&quot;,(SubTotalRF__c * 0.2),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity_Quote__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote__c</fullName>
    <label>Opportunity Quote</label>
    <referenceTo>Opportunity_Quote__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Listed_Price__c.field-meta.xml
<CustomField>
    <fullName>Listed_Price__c</fullName>
    <label>Listed Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_Item_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Transmission Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Online Payment Fee</fullName>
            </value>
            <value>
                <fullName>White Label Website Fee</fullName>
            </value>
            <value>
                <fullName>Order Now Button Fee</fullName>
            </value>
            <value>
                <fullName>RFV Discount</fullName>
            </value>
            <value>
                <fullName>Branding Discount</fullName>
            </value>
            <value>
                <fullName>White Label Website Discount</fullName>
            </value>
            <value>
                <fullName>Order Now Button Discount</fullName>
            </value>
            <value>
                <fullName>Exclusive Branding Discount</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Terminal Box</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Pizza Cartons</fullName>
            </value>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Monthly Box Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Annual Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Premium Placement</fullName>
            </value>
            <value>
                <fullName>Apron</fullName>
            </value>
            <value>
                <fullName>Caps</fullName>
            </value>
            <value>
                <fullName>Heating Bag</fullName>
            </value>
            <value>
                <fullName>Notepads and Pens</fullName>
            </value>
            <value>
                <fullName>Roofie</fullName>
            </value>
            <value>
                <fullName>T-shirt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ctrDH_AU_QuoteVFTemplate.cls
public with sharing class ctrDH_AU_QuoteVFTemplate {
    public List<Opportunity_Quote_Line_Item__c> oppProdItems {get; set;}
    public List<Opportunity_Quote_Line_Item__c> oppQLItems {get; set;}

    public Opportunity_Quote__c theOppQ {get; set;}
    public Boolean premiumPlacement { get; set; }
    public Boolean ukQuote { get; set; }
    public Boolean menuPrinting {get; set;}
    public Boolean colombia { get; set; }
    public Boolean peru { get; set; }
    public Boolean ecuador { get; set; }
    public Boolean prodOnly {get; set;}
    public Boolean foodora {get; set;}
    public Boolean foodoraColombia {get; set;}
    public Boolean foodoraPeru {get; set;}
    public Boolean foodoraEcuador {get; set;}
    public Boolean addContract {get; set;}
    public Boolean isNewBusiness {get;set;}
    public Boolean isARLogisticFee {get;set;}
    public Boolean isARMarketPlace {get;set;}
    public Boolean isNonARLogisticFee {get;set;}
    public Boolean isNonARMarketPlace {get;set;}
    public Boolean isARUpgradeUpsell {get;set;}
    public Boolean isNonARUpgradeUpsell {get;set;}
    public Boolean isQuoteProductOnly {get;set;}
    public Boolean isDRLogisticFee {get;set;}
    public Boolean isDRMarketPlace {get;set;}
    public Boolean isDRUpgradeUpsell {get;set;}
    /**
     * @description Is set based on Tarif names defined in Business Config "CPC Products" whether cpc quote should be loaded.
     */
    public Boolean isCpcQuote {get;set;}

    public ctrDH_AU_QuoteVFTemplate() {
        Id objId = ApexPages.currentPage().getParameters().get('id');
        this.premiumPlacement = false;
        this.ukQuote = true;
        this.menuPrinting = false;
        this.colombia = false;
        this.peru = false;
        this.ecuador = false;
        this.foodora = false;
        this.addContract = false;
        this.foodoraColombia = false;
        this.foodoraPeru = false;
        this.foodoraEcuador = false;
        this.isARLogisticFee = false;
        this.isARMarketPlace = false;
        this.isNonARLogisticFee = false;
        this.isNonARMarketPlace = false;
        this.isARUpgradeUpsell = false;
        this.isNonARUpgradeUpsell = false;
        this.isQuoteProductOnly =false;
        theOppQ = [SELECT Id_Account__c,
                Id_Account__r.Name,
                Id_Account__r.Invoice_Frequency__c,
                Id_Opportunity__c,
                SubTotalRF__c,
                VAT_fm__c,
                Total_fm__c,
                RecordTypeId,
                Id_Opportunity__r.Main_Commission_Fee__c ,
                Id_Opportunity__r.Invoice_Transmission_method__c,
                Id_Opportunity__r.Main_Online_Payment_Fee__c ,
                Id_Opportunity__r.Quote_Comment_Menu_Printing__c,
                Id_Opportunity__r.Type
        FROM Opportunity_Quote__c
        WHERE Id = : objId];

        oppProdItems = [SELECT
                    Name,
                    Listed_Price__c,
                    Quantity__c,
                    Total_Amount__c,
                    Sub_type__c
                FROM Opportunity_Quote_Line_Item__c
                WHERE Id_Opportunity_Quote__c = :theOppQ.Id and Line_Item_Type__c = 'Product'];

        oppQLItems = [SELECT
                    Id_Opportunity_Quote__c,
                    Sub_type__c,Id_Opportunity__r.Record_Country__c,
                    Id_Opportunity__r.Business_Type__c
                FROM Opportunity_Quote_Line_Item__c
                WHERE Id_Opportunity_Quote__c = :theOppQ.Id and Line_Item_Type__c = 'Service'];

        Opportunity opt = [
                SELECT
                    Record_Country__c,
                    Id_Tarif__r.Name,
                    Type,
                    Business_Type__c,
                    Name
                FROM Opportunity
                WHERE Id = :theOppQ.Id_Opportunity__c];

        Set<String> logisticFees = new Set<String>(Label.logistics_fee.split(','));
        this.isCpcQuote = isCPCQuote(theOppQ, oppProdItems);

        if ((opt.Name != null && opt.Name == 'Premium Placement') || (opt.Id_Tarif__r.Name != null && opt.Id_Tarif__r.Name.contains('Premium Placement'))) {
            this.premiumPlacement = true;
            this.ukQuote = false;
        } else if (opt.Type == 'Additional Contract') {
            this.addContract = true;
            this.ukQuote = false;
        } else if (opt.Id_Tarif__r.Name == 'Menu Printing') {
            this.menuPrinting = true;
            this.ukQuote = false;
        }

        if (logisticFees.contains(opt.Id_Tarif__r.Name)) {
            if (opt.Record_Country__c == 'Colombia')
                this.foodoraColombia = true;
            if (opt.Record_Country__c == 'Peru')
                this.foodoraPeru = true;
            if (opt.Record_Country__c == 'Ecuador')
                this.foodoraEcuador = true;
            this.foodora = true;
        }

        if (!this.foodora) {
            if (opt.Record_Country__c == 'Colombia')
                this.colombia = true;
            else if (opt.Record_Country__c == 'Peru')
                this.peru = true;
            else if (opt.Record_Country__c == 'Ecuador')
                this.ecuador = true;

            if (opt.Type != null && opt.Type.indexOf('Contract') == -1) {
                this.prodOnly = true;
                this.colombia = false;
                this.peru = false;
                this.ecuador = false;
            }
        }

        if(opt.Business_Type__c == 'New Business' || opt.Business_Type__c == 'Win Back'
                || opt.Business_Type__c == 'Owner Change'){
            this.isNewBusiness = true;
        }
        else {
            this.isNewBusiness = false;
        }

        if(opt.Type == 'Product Only'){
            this.isQuoteProductOnly = true;
        }

        /*Peya quote changes SP-2777
        Peya Prod only quotes SP-2832*/
        if(!oppQLItems.isEmpty()) {
            for (Opportunity_Quote_Line_Item__c oppQLI : oppQLItems) {
                if (oppQLI.Sub_type__c == 'Logistics Fee') {
                    if (oppQLI.Id_Opportunity__r.Record_Country__c == 'Argentina') {
                        this.isARLogisticFee = true;
                    } 
                    else if(oppQLI.Id_Opportunity__r.Record_Country__c == 'Dominican Republic'){
                    	this.isDRLogisticFee = true;
                    }
                    else {
                        this.isNonARLogisticFee = true;
                    }
                } else {
                    if (oppQLI.Id_Opportunity__r.Record_Country__c == 'Argentina') {
                        this.isARMarketPlace = true;
                    } 
                    else if(oppQLI.Id_Opportunity__r.Record_Country__c == 'Dominican Republic'){
                    	this.isDRMarketPlace = true;
                    }
                    else {
                        this.isNonARMarketPlace = true;
                    }
                }
            }
        }else{
            if (opt.Record_Country__c == 'Argentina') {
                this.isARUpgradeUpsell = true;
            }
            else if(opt.Record_Country__c == 'Dominican Republic'){
            	this.isDRUpgradeUpsell = true;
			}
            else {
                this.isNonARUpgradeUpsell = true;
            }
        }

    }

    private Boolean isCPCQuote(Opportunity_Quote__c oppQuote, List<Opportunity_Quote_Line_Item__c> lineItems) {
        Business_Config__c config = LibBusinessConfig.getBusinessConfigFromRuleMap('QuoteScreenProcess', oppQuote.RecordTypeId, 'CPC Products');
        if (config == null || String.isBlank(config.Business_Rule_Value__c)) {
            return false;
        }
        Set<String> productNames = new Set<String>(config.Business_Rule_Value__c.replaceAll(' ,|, ', ',').split(','));
        for (Opportunity_Quote_Line_Item__c lineItem: lineItems) {
            if (productNames.contains(lineItem.Name)) {
                return true;
            }
        }
        return false;
    }
}