force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Elastix_Agent_Extension__c.field-meta.xml
<CustomField>
    <fullName>Elastix_Agent_Extension__c</fullName>
    <label>Elastix Agent Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Vendor_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Phone_Number__c</fullName>
    <description>Field to capture vendor phone number so that the agents can click to dial the number from the case page.
Created for SCC-26 (Elastix).</description>
    <label>Vendor Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Elastix_Agent_Id__c.field-meta.xml
<CustomField>
    <fullName>Elastix_Agent_Id__c</fullName>
    <externalId>true</externalId>
    <label>Elastix Agent Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Elastix_Password__c.field-meta.xml
<CustomField>
    <fullName>Elastix_Password__c</fullName>
    <label>Elastix Password</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DH_ElastixSoftphoneControllerTest.cls
@IsTest
private class DH_ElastixSoftphoneControllerTest {

    @testSetup
    static void testSetup() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c bh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        Database.insert(bh);
        Company__c com = UnitTestDataFactory.createCompany('Talabat', 'Talabat', bh);
        insert com;
        Account acco = UnitTestDataFactory.createAccount('TEST', bh, 'Talabat_Account');
        insert acco;
        Group q = new Group();
        q.Name = 'Talabat_BH_Sales_Admin';
        q.Type = 'Queue';
        insert q;
        User u = [SELECT Id FROM User WHERE Id = :userinfo.getUserId()];
        User elastixUser = new User();
        system.runAs(u) {
            QueueSObject qSObj = new QueueSObject(SobjectType = 'Case', QueueId = q.Id);
            insert qSObj;

            Profile talabatProfile = [SELECT Id FROM Profile WHERE Name = 'Talabat Customer Care'];
            elastixUser.Elastix_Agent_Id__c = '9876';
            elastixUser.Elastix_Password__c = 'test1234';
            elastixUser.alias = 'elastUsr';
            elastixUser.email = 'testclassuser@talabat.com';
            elastixUser.emailencodingkey = 'UTF-8';
            elastixUser.lastname = 'Test Class User';
            elastixUser.languagelocalekey = 'en_US';
            elastixUser.localesidkey = 'en_US';
            elastixUser.profileid = talabatProfile.Id;
            elastixUser.timezonesidkey = 'America/Los_Angeles';
            elastixUser.username = 'testclassuser@talabat.com.test';
            elastixUser.FederationIdentifier = 'testclassuser@talabat.com.test';
            insert elastixUser;
        }

        List<Business_Config__c> configs = new List<Business_Config__c>();

        configs.add(
                new Business_Config__c(
                        Process_Name__c = 'ElastixQueuePrefixes',
                        Business_Rule_Name__c = 'Bahrain',
                        Business_Rule_Value__c = '{"Country Code":"+973","Prefix":"30"}',
                        Id_Country__c = bh.id,
                        Is_Active__c = true,
                        Record_Type_Id__c = 'Global_Config',
                        Type__c = 'Process',
                        Parent__c = true
                ));
        insert configs;
        Case testCase = UnitTestDataFactory.createCase(acco, 'New', 'Customer', '', '', bh, 'Talabat_Inbound_Case', 'Testing Escalation');
        testCase.Platform__c = 'Talabat';
        testCase.OwnerId = elastixUser.id;
        testCase.Elastix_Agent_Extension__c = '9876';
        testCase.Vendor_Phone_Number__c = '+973123456789';
        testCase.Status = 'In Progress';
        insert testCase;
    }

    @IsTest
    static void testFetchRecordId() {
        User agent = [SELECT Id FROM User WHERE Elastix_Agent_Id__c = '9876' LIMIT 1];
        String recordId;
        system.runAs(agent) {
            String todayDateTime = System.today().year() + ',' + System.today().month() + ',' + System.today().day() + ',0,0,0';
            recordId = DH_ElastixSoftphoneController.getRecordId('+973123456789', todayDateTime);
        }
        List<Case> cases = [SELECT Id FROM Case Limit 1];
        system.assertEquals(recordId, cases[0].id);
    }

    @IsTest
    static void testFetchUserDetails() {
        User agent = [SELECT Id,Elastix_Agent_Id__c,Elastix_Password__c FROM User WHERE Elastix_Agent_Id__c = '9876' LIMIT 1];
        system.runAs(agent) {
            DH_ElastixSoftphoneController.getUserDetails();
        }
        system.assertEquals(DH_ElastixSoftphoneController.username, agent.Elastix_Agent_Id__c);
        system.assertEquals(DH_ElastixSoftphoneController.password, agent.Elastix_Password__c);
    }

    @IsTest
    static void testCreateTaskRecord() {
        User agent = [SELECT Id,Elastix_Agent_Id__c,Elastix_Password__c FROM User WHERE Elastix_Agent_Id__c = '9876' LIMIT 1];
        Case phoneCase = [SELECT Id,Vendor_Phone_Number__c FROM Case WHERE Elastix_Agent_Extension__c = '9876' LIMIT 1];
        String taskId;
        system.runAs(agent) {
            taskId = DH_ElastixSoftphoneController.createRecord(phoneCase.Vendor_Phone_Number__c,phoneCase.Id);
        }
        system.assertNotEquals(null,taskId);
    }

    @IsTest
    static void testPhoneNumberWithCountryCodeWithPrefix() {
        User agent = [SELECT Id,Elastix_Agent_Id__c,Elastix_Password__c FROM User WHERE Elastix_Agent_Id__c = '9876' LIMIT 1];
        Case phoneCase = [SELECT Id,Vendor_Phone_Number__c FROM Case WHERE Elastix_Agent_Extension__c = '9876' LIMIT 1];
        String phoneNumber;
        system.runAs(agent) {
            phoneNumber = DH_ElastixSoftphoneController.getPhoneNumberWithPrefix(phoneCase.Vendor_Phone_Number__c,phoneCase.Id);
        }
        system.assertEquals('30123456789',phoneNumber);
    }

    @IsTest
    static void testPhoneNumberWithCountryCodeZeroWithPrefix() {
        User agent = [SELECT Id,Elastix_Agent_Id__c,Elastix_Password__c FROM User WHERE Elastix_Agent_Id__c = '9876' LIMIT 1];
        Case phoneCase = [SELECT Id,Vendor_Phone_Number__c FROM Case WHERE Elastix_Agent_Extension__c = '9876' LIMIT 1];
        String phoneNumber;
        system.runAs(agent) {
            phoneNumber = DH_ElastixSoftphoneController.getPhoneNumberWithPrefix('00973123456789',phoneCase.Id);
        }
        system.assertEquals('30123456789',phoneNumber);
    }
}