force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Migration_ID__c.field-meta.xml
<CustomField>
    <fullName>Migration_ID__c</fullName>
    <externalId>true</externalId>
    <label>Migration ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/DE_Entry_Case.recordType-meta.xml
<RecordType>
    <fullName>DE_Entry_Case</fullName>
    <active>true</active>
    <businessProcess>DE Entry Process</businessProcess>
    <label>DE Entry Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/DE_Finance_Case.recordType-meta.xml
<RecordType>
    <fullName>DE_Finance_Case</fullName>
    <active>true</active>
    <businessProcess>DE Finance Process</businessProcess>
    <label>DE Finance Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/DE_Inbound_Case.recordType-meta.xml
<RecordType>
    <fullName>DE_Inbound_Case</fullName>
    <active>true</active>
    <businessProcess>DE Inbound Process</businessProcess>
    <label>DE Inbound Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/DE_Internal_Case.recordType-meta.xml
<RecordType>
    <fullName>DE_Internal_Case</fullName>
    <active>true</active>
    <businessProcess>DE Internal</businessProcess>
    <label>DE Internal Case</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/DE_Restaurant_Operations.recordType-meta.xml
<RecordType>
    <fullName>DE_Restaurant_Operations</fullName>
    <active>true</active>
    <businessProcess>DE Restaurant Operations</businessProcess>
    <label>DE Restaurant Operations</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LiveChatTranscript/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Myanmar</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Migration_ID__c.field-meta.xml
<CustomField>
    <fullName>Migration_ID__c</fullName>
    <externalId>true</externalId>
    <label>Migration ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UnitTestClsDeleteCustomerDetails.cls
/**
 * Created by marco.zeuli on 14/2/2018.
 */
@isTest
private class UnitTestClsDeleteCustomerDetails {

    static final String EMAIL_TO_SEARCH_FOR = 'aaaaaa@aaaaaaa.it';

    @TestSetup
    static void setup() {
        UnitTestDataFactory.getRecordtypeValues();

        Country__c de = UnitTestDataFactory.createCountry('DE', 'Germany', 'EUR');
        insert de;

        Account acc = UnitTestDataFactory.createAccount('test', de, 'DE_Account');
        insert acc;

        Case inbound = new Case(
            RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Inbound_Case'),
                Customer_Email__c = EMAIL_TO_SEARCH_FOR,
                Subject = 'test',
                Description = 'test',
                Platform__c = 'PizzaDE',
                Order_Number__c = '0'
        );

        Case internal = new Case(
                RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Internal_Case'),
                Customer_Email__c = EMAIL_TO_SEARCH_FOR,
                Subject = 'test',
                Description = 'test',
                Platform__c = 'PizzaDE'
        );

        Case finance = new Case(
                RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Finance_Case'),
                Customer_Email__c = EMAIL_TO_SEARCH_FOR,
                Subject = 'test',
                Description = 'test',
                Platform__c = 'PizzaDE'
        );

        Case entry = new Case(
                RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Entry_Case'),
                Customer_Email__c = EMAIL_TO_SEARCH_FOR,
                Subject = 'test',
                Description = 'test',
                Platform__c = 'PizzaDE'
        );

        insert new List<Case> {inbound, internal, finance, entry};

        LiveChatVisitor visitor = new LiveChatVisitor();
        insert visitor;

        LiveChatTranscript chat1 = new LiveChatTranscript(
                Email__c = EMAIL_TO_SEARCH_FOR,
                LiveChatVisitorId = visitor.Id,
                Migration_ID__c = 'avoid flow to run'
        );

        insert chat1;
        
        // Create business configs
		Business_Config__c bc1 = UnitTestDataFactory.createBusinessConfig('customerDataDeletionProcess', 'Process','recordTypes','DE_Internal_Case,DE_Inbound_Case,DE_Finance_Case,DE_Entry_Case,DE_Restaurant_Operations', null, 'Global_Config', true, true);
    	Business_Config__c bc2 = UnitTestDataFactory.createBusinessConfig('customerDataDeletionProcess', 'Process','isSuspiciousCheckEnabled','True', null, 'Global_Config', true, false);
    	Business_Config__c bc3 = UnitTestDataFactory.createBusinessConfig('customerDataDeletionProcess', 'Process','suspiciousCheckTreshhold','15', null, 'Global_Config', true, false);
    	insert new List<sObject>{bc1,bc2,bc3};
    }

    @IsTest
    static void deleteDataDeleteAllRecords() {

        Test.startTest();

        ClsDeleteCustomerDetails.deleteData(EMAIL_TO_SEARCH_FOR);

        Test.stopTest();

        List<Case> cc = [SELECT Id FROM Case];
        List<LiveChatTranscript> chats = [SELECT Id FROM LiveChatTranscript];

        System.assert(cc.isEmpty());
        System.assert(chats.isEmpty());
    }
    
    @isTest
    static void testCustomerDataDeletionWebService(){
    	
    	Test.startTest();
        	CustomerDataDeletionService.DeletionResponse res  = CustomerDataDeletionService.deleteCustomerData(123,EMAIL_TO_SEARCH_FOR);
			CustomerDataDeletionService.DeletionResponse res2 = CustomerDataDeletionService.deleteCustomerData(124,'test@test.com');
        Test.stopTest();
        
        List<Case> cc = [SELECT Id FROM Case];
        List<LiveChatTranscript> chats = [SELECT Id FROM LiveChatTranscript];

        System.assert(cc.isEmpty());
        System.assert(chats.isEmpty());
        
        System.assertEquals(res.status,CustomerDataDeletionService.FULLFILLED);
        System.assertEquals(res2.status,CustomerDataDeletionService.ALREADY_FULLFILLED);
    }
    
    @isTest
    static void testSuspiciousDeletion(){
    	// create bulk cases
    	List<Case> cases = new List<Case>();
    	for(Integer i=0;i<=15;i++){
    		Case inbound = new Case(
	            RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('DE_Inbound_Case'),
	                Customer_Email__c = EMAIL_TO_SEARCH_FOR,
	                Subject = 'test',
	                Description = 'test',
	                Platform__c = 'PizzaDE',
	                Order_Number__c = '0'
	        );
	        cases.add(inbound);
    	}
    	insert cases;
    	
    	Test.startTest();
        	ClsDeleteCustomerDetails.Result result = ClsDeleteCustomerDetails.deleteData(EMAIL_TO_SEARCH_FOR);
        Test.stopTest();
        
        // check no cases are deleted
        cases = [Select Id from Case];
        System.assertEquals(cases.size(),20);
        System.assertEquals(result.isError,True);
    }

}