force-app/main/default/objects/Account/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/DE_Account.recordType-meta.xml
<RecordType>
    <fullName>DE_Account</fullName>
    <active>true</active>
    <label>DE Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason__c</fullName>
    <label>Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>0% Commission</fullName>
            </value>
            <value>
                <fullName>0% Commission Cancel / Decrease</fullName>
            </value>
            <value>
                <fullName>1st Warning</fullName>
            </value>
            <value>
                <fullName>2nd Warning</fullName>
            </value>
            <value>
                <fullName>ABN</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Acct related Call Back</fullName>
            </value>
            <value>
                <fullName>Add / Deactivate User</fullName>
            </value>
            <value>
                <fullName>Add child account</fullName>
            </value>
            <value>
                <fullName>Additional Order Time</fullName>
            </value>
            <value>
                <fullName>Agreement Issue</fullName>
            </value>
            <value>
                <fullName>Alcohol Listing Request</fullName>
            </value>
            <value>
                <fullName>All Inclusive</fullName>
            </value>
            <value>
                <fullName>Assignment Rules</fullName>
            </value>
            <value>
                <fullName>Automation</fullName>
            </value>
            <value>
                <fullName>Bad Debt Check</fullName>
            </value>
            <value>
                <fullName>Bad Restaurant Service</fullName>
            </value>
            <value>
                <fullName>Bank/Police request</fullName>
            </value>
            <value>
                <fullName>Bank Account Change</fullName>
            </value>
            <value>
                <fullName>Bank Account Details</fullName>
            </value>
            <value>
                <fullName>Bank Account Details Collected</fullName>
            </value>
            <value>
                <fullName>BE Restaurant Name Change</fullName>
            </value>
            <value>
                <fullName>Best Price Guarantee</fullName>
            </value>
            <value>
                <fullName>Bill Request</fullName>
            </value>
            <value>
                <fullName>Blacklist removal request</fullName>
            </value>
            <value>
                <fullName>Block Payout</fullName>
            </value>
            <value>
                <fullName>Bonus / Bonus Problems</fullName>
            </value>
            <value>
                <fullName>BPG Violation Report</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Restaurant Operations</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Reason__c</fullName>
    <label>Closed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Take Online</fullName>
            </value>
            <value>
                <fullName>Take Online is not possible</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Not Successful</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Create Retention Task</fullName>
            </value>
            <value>
                <fullName>Create Take Offline Task for Non Contracted</fullName>
            </value>
            <value>
                <fullName>Take Offline</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Not Successful - Data Missing</fullName>
            </value>
            <value>
                <fullName>Not Successful - Commission is not correct</fullName>
            </value>
            <value>
                <fullName>Back Online</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Duplicated</fullName>
            </value>
            <value>
                <fullName>Auto Closed</fullName>
            </value>
            <value>
                <fullName>Escalated to AM</fullName>
            </value>
            <value>
                <fullName>Successful Call</fullName>
            </value>
            <value>
                <fullName>Call Scheduled</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (Agent)</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (AM)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (1 st Incident)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (Permanent)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Send_Survey__c.field-meta.xml
<CustomField>
    <fullName>Send_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Helper field. When checked by Batch will trigger workflow/outbound message to Qualtrics</description>
    <label>Send Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/DE_Restaurant_Operations.recordType-meta.xml
<RecordType>
    <fullName>DE_Restaurant_Operations</fullName>
    <active>true</active>
    <businessProcess>DE Restaurant Operations</businessProcess>
    <label>DE Restaurant Operations</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UnitTestBatchOnboardingSendSurvey.cls
/**
 * Created by c.kumari on 17.12.2018.
 */

@isTest
public class UnitTestBatchOnboardingSendSurvey {

    @testSetup
    public static void setupData() {
        UnitTestDataFactory.getRecordtypeValues();

        Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String>{
                'Case'
        });
        Country__c coun = UnitTestDataFactory.createCountry('DE', 'Germany', 'EUR');
        insert coun;
        Account acc = UnitTestDataFactory.createAccount('BatchSendSurvey', coun, 'DE_Account');
        insert acc;

        Case cs1 = new Case();
        cs1.accountId = acc.Id;
        cs1.type = 'Restaurant Operations';
        cs1.origin = 'Chat';
        cs1.subject = 'Test';
        cs1.recordtypeid = mapRecordtypes.get('DE_Restaurant_Operations').Id;
        cs1.order_number__c = '90123456789012';
        cs1.customer_email__c = 'test@test.com';
        cs1.Case_Reason__c='Bad Restaurant Service';
        cs1.Platform__c = 'PizzaDE';
        cs1.Description = 'test';
        cs1.Status = 'Closed';
        cs1.Closed_Reason__c = 'Successful';
        cs1.Send_Survey__c = false;
        insert cs1;

        // create configs
        Business_Config__c config = UnitTestDataFactory.createBusinessConfig('BatchOnboardingSurvey', 'Process', 'recordTypes', 'DE_Restaurant_Operations', null, 'Global_Config', true, true);
        Business_Config__c config1 = UnitTestDataFactory.createBusinessConfig('BatchOnboardingSurvey', 'Process', 'numberOfDays', '-1', null, 'Global_Config', true, false);
        Business_Config__c config2 = UnitTestDataFactory.createBusinessConfig('BatchOnboardingSurvey', 'Process', 'closedReason', 'Successful', null, 'Global_Config', true, false);
        Business_Config__c config3 = UnitTestDataFactory.createBusinessConfig('BatchOnboardingSurvey', 'Process', 'Status', 'Closed', null, 'Global_Config', true, false);

        insert new List<sObject>{config, config1, config2, config3};

    }

    @isTest
    public static void testBatchOnboardingSendSurvey(){
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        Case casse = [SELECT Id,Status,ClosedDate,RecordType.Id,Closed_Reason__c,Send_Survey__c from Case limit 1];
        system.debug('idd..'+casse.id+'status...'+casse.Status+'RecordTypeId...'+casse.RecordType.Id+'ClosedDate...'+casse.ClosedDate+'Closed_Reason__c....'+casse.Closed_Reason__c+'Send_Survey__c...'+casse.Send_Survey__c);

        Test.startTest();
        BatchOnboardingSendSurvey batch = new BatchOnboardingSendSurvey();
        Database.executebatch(batch);
        Test.stopTest();
        List<Case> cases = [Select Id from Case where Send_Survey__c = true];
        system.assertEquals(1,cases.size());
    }

}