force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CD_Account.recordType-meta.xml
<RecordType>
    <fullName>CD_Account</fullName>
    <active>true</active>
    <description>Account for Click Delivery</description>
    <label>CD Account</label>
</RecordType>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>This field is to check which level this restaurant is to reflect to Sales reps&apos; performance</description>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Service A</fullName>
            </value>
            <value>
                <fullName>Service AAA</fullName>
            </value>
            <value>
                <fullName>Service B</fullName>
            </value>
            <value>
                <fullName>Service C</fullName>
            </value>
            <value>
                <fullName>Service D</fullName>
            </value>
            <value>
                <fullName>Service R</fullName>
            </value>
            <value>
                <fullName>Terminal</fullName>
            </value>
            <value>
                <fullName>Terminal A</fullName>
            </value>
            <value>
                <fullName>Terminal B</fullName>
            </value>
            <value>
                <fullName>Terminal T</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date_uk__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_uk__c</fullName>
    <description>For Migration Only</description>
    <inlineHelpText>Use field it the Start Date is NOT ASAP. Automatically populated via tariffs.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CD_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>CD_Opportunity</fullName>
    <active>true</active>
    <businessProcess>CD Sales Process</businessProcess>
    <description>Opportunity for Click Delivery</description>
    <label>CD Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_Item_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Transmission Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Online Payment Fee</fullName>
            </value>
            <value>
                <fullName>White Label Website Fee</fullName>
            </value>
            <value>
                <fullName>Order Now Button Fee</fullName>
            </value>
            <value>
                <fullName>RFV Discount</fullName>
            </value>
            <value>
                <fullName>Branding Discount</fullName>
            </value>
            <value>
                <fullName>White Label Website Discount</fullName>
            </value>
            <value>
                <fullName>Order Now Button Discount</fullName>
            </value>
            <value>
                <fullName>Exclusive Branding Discount</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Terminal Box</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Pizza Cartons</fullName>
            </value>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Monthly Box Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Annual Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Premium Placement</fullName>
            </value>
            <value>
                <fullName>Apron</fullName>
            </value>
            <value>
                <fullName>Caps</fullName>
            </value>
            <value>
                <fullName>Heating Bag</fullName>
            </value>
            <value>
                <fullName>Notepads and Pens</fullName>
            </value>
            <value>
                <fullName>Roofie</fullName>
            </value>
            <value>
                <fullName>T-shirt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/CD_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>CD_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>CD Opportunity Line Item</label>
</RecordType>

force-app/main/default/classes/OppLineItemProcessor_Test.cls
/**
* @author Peter Kalina
* @date 14.05.2019
*
* @description Test class for Apex Class (ClsOppLineItemProcessor, ClsOppLineItemHandler)
*/
@IsTest
private class OppLineItemProcessor_Test {
	
    /*******************************************************************************************************
    * @description test if Start Date was going to be changed in Opportunity;
    */
    @IsTest
    public static void updateOpportunityStartDate_Test(){
        UnitTestDataFactory.getRecordtypeValues();
        Map<String, String> mapCountryCurrency = LibBusinessConfig.recordCurrencyMap();
        
        Country__c cd = UnitTestDataFactory.createCountry('CD', 'Colombia', 'COP');
        insert cd;
        
        Account acco = UnitTestDataFactory.createAccount('TEST', cd, 'CD_Account');
        acco.Type = 'Branch - main';
        insert acco;
        
        Opportunity oppt = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'CD_Opportunity', (Date.today() + 4));
        oppt.Business_Type__c = 'New Business';
        insert oppt;
        
        List<Opportunity_Line_Item__c> listOppLI = new List<Opportunity_Line_Item__c>();
        for(Integer i = 0; i < 3; i++){
            listOppLI.add(new Opportunity_Line_Item__c(
                    Name = 'Test_Opportunity_Line_Item_' + i,
                    Id_Opportunity__c = oppt.Id,
                	Line_Item_Type__c = 'Service',
                    Start_Date__c = Date.Today() + i + 1,
                    RecordtypeId = UnitTestDataFactory.mapRecordtypes.get('CD_Opportunity_Line_Item').Id,
                    CurrencyIsoCode = mapCountryCurrency.get(oppt.Record_Country__c)
                )
            );
        }
		
        Test.startTest();
        insert listOppLI;
        listOppLI[0].Start_Date__c = Date.Today() - 1;
		update listOppLI;
        List<Opportunity> oppt2 = new List<Opportunity>([Select ID, Start_Date_uk__c, Name, Level__c From Opportunity where ID =: oppt.ID]);
        Test.stopTest();
        
        System.assertEquals(oppt2[0].Start_Date_uk__c, (Date.Today() - 1));
    }

    /*******************************************************************************************************
    * @description Test class for the mutliple commission then populate the earliest commission on Oppty Start date
    */
    @IsTest
    public static void updateOpptyStartDateWithEarliestCommissionDate(){
        UnitTestDataFactory.getRecordtypeValues();
        Map<String, String> mapCountryCurrency = LibBusinessConfig.recordCurrencyMap();

        Country__c cd = UnitTestDataFactory.createCountry('CD', 'Colombia', 'COP');
        insert cd;

        Account acco = UnitTestDataFactory.createAccount('TEST', cd, 'CD_Account');
        acco.Type = 'Branch - main';
        insert acco;

        Opportunity oppt = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'CD_Opportunity', (Date.today() + 4));
        oppt.Business_Type__c = 'New Business';
        insert oppt;

        List<Opportunity_Line_Item__c> listOppLI = new List<Opportunity_Line_Item__c>();
        for(Integer i = 0; i < 1; i++){
            listOppLI.add(new Opportunity_Line_Item__c(
                    Name = 'Test_Opportunity_Line_Item_' + i,
                    Id_Opportunity__c = oppt.Id,
                    Line_Item_Type__c = 'Service',
                    Sub_type__c = 'Commission Fee',
                    Start_Date__c = Date.Today() + i + 1,
                    RecordtypeId = UnitTestDataFactory.mapRecordtypes.get('CD_Opportunity_Line_Item').Id,
                    CurrencyIsoCode = mapCountryCurrency.get(oppt.Record_Country__c)
            )
            );
        }
        List<Opportunity_Line_Item__c> listOppLINew = new List<Opportunity_Line_Item__c>();
        for(Integer i = 0; i < 1; i++){
            listOppLI.add(new Opportunity_Line_Item__c(
                    Name = 'Test_Opportunity_Line_Item_' + i,
                    Id_Opportunity__c = oppt.Id,
                    Line_Item_Type__c = 'Service',
                    Sub_type__c = 'Commission Fee',
                    Start_Date__c = Date.Today() - 5,
                    RecordtypeId = UnitTestDataFactory.mapRecordtypes.get('CD_Opportunity_Line_Item').Id,
                    CurrencyIsoCode = mapCountryCurrency.get(oppt.Record_Country__c)
            )
            );
        }
        insert listOppLI;
        Test.startTest();
        insert listOppLINew;
        listOppLI[0].Start_Date__c = Date.Today() - 5;
        update listOppLI;
        List<Opportunity> oppt2 = new List<Opportunity>([Select ID, Start_Date_uk__c, Name, Level__c From Opportunity where ID =: oppt.ID]);
        Test.stopTest();

        System.assertEquals(oppt2[0].Start_Date_uk__c, (Date.Today() - 5));
    }
}