force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Do_not_auto_renew__c.field-meta.xml
<CustomField>
    <fullName>Do_not_auto_renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Auto-renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>this hold the end date because the other end date is not writable</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Last_renewal_date__c.field-meta.xml
<CustomField>
    <fullName>Last_renewal_date__c</fullName>
    <label>Last renewal date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewal_version__c.field-meta.xml
<CustomField>
    <fullName>Renewal_version__c</fullName>
    <label>Renewal version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Renewed_by__c.field-meta.xml
<CustomField>
    <fullName>Renewed_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <description>Service type of contract. Says whether a contract is a main service or an additional service (surcharge)</description>
    <label>Service Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>0% Commission Upselling</fullName>
            </value>
            <value>
                <fullName>Bad debtor</fullName>
            </value>
            <value>
                <fullName>Best Price Guarantee</fullName>
            </value>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Business Temporarily out of service</fullName>
            </value>
            <value>
                <fullName>Cannot Contact</fullName>
            </value>
            <value>
                <fullName>Capacity - Competitors</fullName>
            </value>
            <value>
                <fullName>Capacity - Driver Issue</fullName>
            </value>
            <value>
                <fullName>Capacity - Order Volume</fullName>
            </value>
            <value>
                <fullName>Capacity - Own Website</fullName>
            </value>
            <value>
                <fullName>Change of Business Name</fullName>
            </value>
            <value>
                <fullName>Comission too high</fullName>
            </value>
            <value>
                <fullName>Commission Upselling</fullName>
            </value>
            <value>
                <fullName>Contract never received</fullName>
            </value>
            <value>
                <fullName>DH Delivery</fullName>
            </value>
            <value>
                <fullName>Does not accept Online Payment</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Exclusive with competitor</fullName>
            </value>
            <value>
                <fullName>Franchise Contract - Commission Change</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>High Failure Rate</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Issues with payments to restaurant</fullName>
            </value>
            <value>
                <fullName>Language issues</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Legal Issue</fullName>
            </value>
            <value>
                <fullName>Logistics Issue</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
            <value>
                <fullName>Low rating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchContractRenewal.cls
/**
 * Updates expired Contract, based on Business Config terminates the Contract
 * or renews it
 */
global class BatchContractRenewal implements Database.Batchable<SObject>, Database.Stateful {

   // business rules
   Map<String, Map<String, Business_Config__c>> mapBusinessLogic = LibBusinessConfig.motherOfAllBusinessMaps.get('BatchContractRenewal');
   Map<String, Map<String, Business_Config__c>> mapBusinessLogicTLife = LibBusinessConfig.motherOfAllBusinessMaps.get('TlifeRevenueModel'); //SSC-1982

   global Database.QueryLocator start(Database.BatchableContext BC) {
      Set<String> statusSet = new Set<String>{'Activated','Draft','To be Sent'};
      return Database.getQueryLocator([
                                         SELECT
                                             StartDate,
	                                         End_Date__c,
	                                         Status,
	                                         RecordType.DeveloperName,
	                                         Account.Record_Country__c,
	                                         Renewal_version__c,
	                                         Renewed_by__c,
	                                         Last_renewal_date__c,
                                             Service_Type__c,
                                             AccountId,
	                                         Do_not_auto_renew__c,
	                                         Termination_Reason__c
                                         FROM Contract
                                         WHERE (End_Date__c < TODAY
                                            OR StartDate = TODAY)
                                            AND Status IN : statusSet
                                      ]);
   }

   global void execute(Database.BatchableContext BC, List<SObject> scope) {
      System.debug('BatchContractRenewal.execute: start');

      List<Contract> toUpdate = new List<Contract>();
      Map<String,List<Contract>> mapOfAccountIdContract = new Map<String,List<Contract>>(); //SSC-1982
      Map<String, Business_Config__c> mapOfContractBusinessConfig =  new Map<String, Business_Config__c>(); //SSC-1982

      if (mapBusinessLogic == null || mapBusinessLogic.isEmpty()) {
         return; // nothing to do
      }

      for (Contract cont : (List<Contract>) scope) {
          if (cont.StartDate != Date.today()) {
              Map<String, Business_Config__c> businessData = mapBusinessLogic.get(cont.RecordType.DeveloperName);

              if (businessData == null || businessData.isEmpty()) {
                  continue; // nothing to do for this contract
              }

              String countriesEnabledForAutoRenewal = businessData.get('CountriesEnabledForAutoRenewal') != null ? businessData.get('CountriesEnabledForAutoRenewal').Business_Rule_Value__c : '';

              // checks if has to renew the contract
              if (
                      countriesEnabledForAutoRenewal.containsIgnoreCase(cont.Account.Record_Country__c)
                              && businessData.get('RenewForNumberOfMonths') != null
                              && cont.End_Date__c != null
                              && !cont.Do_not_auto_renew__c
                      ) {

                  cont.End_Date__c = cont.End_Date__c.addMonths(Integer.valueOf(businessData.get('RenewForNumberOfMonths').Business_Rule_Value__c)).addDays(-1);
                  cont.Renewal_version__c = cont.Renewal_version__c != null ? cont.Renewal_version__c + 1 : 1;
                  cont.Last_renewal_date__c = Date.today();
                  cont.Renewed_by__c = UserInfo.getUserId();
                  cont.Status = businessData.get('renewalContractStatus').Business_Rule_Value__c;

                  toUpdate.add(cont);
              }
              // checks if has to terminate expired contracts
              else if (businessData.get('updateExpiredContracts') != null && Boolean.valueOf(businessData.get('updateExpiredContracts').Business_Rule_Value__c)) {


                  if (String.isBlank(cont.Termination_Reason__c)) {
                      cont.Status = businessData.get('expiredContractStatus').Business_Rule_Value__c;
                  } else {
                      cont.Status = businessData.get('terminatedContractStatus').Business_Rule_Value__c;

                      //The below logic is added for SSC-1982 : Tlife Commission
                      String contractRecordType = String.isNotBlank(cont.RecordType.DeveloperName) ? cont.RecordType.DeveloperName : '';
                      if(mapBusinessLogicTLife != null && null != mapBusinessLogicTLife.get(contractRecordType)){
                          List<Contract> listOfContract = !mapOfAccountIdContract.isEmpty() && mapOfAccountIdContract.get(cont.AccountId) != null ?
                                  mapOfAccountIdContract.get(cont.AccountId) : new List<Contract>();
                          listOfContract.add(cont);
                          mapOfContractBusinessConfig = mapBusinessLogicTLife.get(contractRecordType);
                          mapOfAccountIdContract.put(cont.AccountId,listOfContract);
                      }
                      //SSC-1982 : Tlife Commission ends here
                  }
                  toUpdate.add(cont);

              }
          } else if (cont.StartDate == Date.today() && cont.End_Date__c != Date.today()) {

             cont.Status = 'Activated';
             toUpdate.add(cont);
         }
      }

      if (!toUpdate.isEmpty()) {
          List<Database.SaveResult> results = Database.update(toUpdate,false);
          LoggingUtility.createLog('BatchContractRenewal','BATCH','Contract Renewal Terminated',null);
          Boolean isError = false;

          for(Integer i=0;i<results.size();i++){
              if(!results[i].isSuccess()){
                  LoggingUtility.logError('BatchContractRenewal','BatchContractRenewal: Update failed for Contract ' + toUpdate[i].Id +
                          ' Errors '  + results[i].getErrors() + '\n');
                  System.debug(LoggingLevel.ERROR,'BatchContractRenewal: Update failed for Contract ' + toUpdate[i].Id +
                          ' Errors '  + results[i].getErrors());
                  isError = true;
              }
          }


          // Do Logging in case of error.
          if(isError){
              LoggingUtility.commitLogs();
          }

          //The below logic is added for SSC-1982 : Tlife Commission
          if(!mapOfAccountIdContract.isEmpty() && !mapOfContractBusinessConfig.isEmpty()) {
              CtrTerminationRestaurantVue.fetchAllContractsWithServiceType(mapOfAccountIdContract,mapOfContractBusinessConfig);
          }
          //logic ends here for SSC-1982 : Tlife Commission


      }

      System.debug('BatchContractRenewal.execute: done');
   }

   global void finish(Database.BatchableContext BC) {}
}