force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <description>Lease End date</description>
    <label>End-date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Installation</fullName>
                <default>true</default>
                <label>New - Awaiting Installation</label>
            </value>
            <value>
                <fullName>Installed successfully</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Uninstalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Design rejected</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Pending design approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Cannot Contact</fullName>
            </value>
            <value>
                <fullName>Capacity - Competitors</fullName>
            </value>
            <value>
                <fullName>Capacity - Driver Issue</fullName>
            </value>
            <value>
                <fullName>Capacity - Order Volume</fullName>
            </value>
            <value>
                <fullName>Capacity - Own Website</fullName>
            </value>
            <value>
                <fullName>DH Delivery</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Legal Issue</fullName>
            </value>
            <value>
                <fullName>Logistics Issue</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
            <value>
                <fullName>New Owner - New Contract</fullName>
            </value>
            <value>
                <fullName>New Owner - No New Contract</fullName>
            </value>
            <value>
                <fullName>No Delivery Service</fullName>
            </value>
            <value>
                <fullName>Not Enough Orders</fullName>
            </value>
            <value>
                <fullName>Not Interested in Product</fullName>
            </value>
            <value>
                <fullName>Onboarding Failure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment Issue</fullName>
            </value>
            <value>
                <fullName>Poor Performance</fullName>
            </value>
            <value>
                <fullName>Pricing - Admin Fee</fullName>
                <label>Pricing - Admin fee</label>
            </value>
            <value>
                <fullName>Pricing - Commission</fullName>
            </value>
            <value>
                <fullName>Pricing - Merchant Fee</fullName>
                <label>Pricing - Merchant fee</label>
            </value>
            <value>
                <fullName>Pricing - Premium Placement</fullName>
            </value>
            <value>
                <fullName>Pricing - Setup Fee</fullName>
            </value>
            <value>
                <fullName>Product Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/BatchTerminateBrandingContent.cls
global class BatchTerminateBrandingContent implements Database.Batchable<sObject>, Database.Stateful{
   
   // business rules
   Map<String, Map<String, Business_Config__c>> mapBusinessLogic = LibBusinessConfig.motherOfAllBusinessMaps.get('BatchBrandingContentTermination');
   
   global Database.QueryLocator start(Database.BatchableContext BC) {
      Set<String> statusSet = new Set<String>{'Terminated','Canceled','Expired'};
      return Database.getQueryLocator([SELECT Id,End_Date__c,Status__c,recordtype.developername,
      											Restaurant_Name__r.record_country__c,Termination_Reason__c
  											FROM Branding_Content__c
  											WHERE end_date__c <= TODAY
  												AND Status__c NOT IN :statusSet]);
   }		
   
   global void execute(Database.BatchableContext BC, List<sObject> scope) {
      System.debug('BatchTerminateBrandingContent.execute: scope list size is: ' + scope.size());
	  List<Branding_Content__c> toUpdate = new List<Branding_Content__c>();

      if (mapBusinessLogic == null || mapBusinessLogic.isEmpty()) {
         System.debug('BatchTerminateBrandingContent.execute: empty business rules');
         return; // nothing to do
      }


      for (Branding_Content__c content : (List<Branding_Content__c>) scope) {

         System.debug('BatchTerminateBrandingContent.execute: processing branding content: ' + content.Id);

         Map<String, Business_Config__c> businessData = mapBusinessLogic.get(content.RecordType.developername);

	     if (businessData == null || businessData.isEmpty()) {
	        System.debug('BatchTerminateBrandingContent.execute: nothing to do for this one');
	        continue; // nothing to do for this Add On
	     }

		// checks whether to mark as expired or terminated
		if (businessData.containsKey('terminateBradningContent')
	        && Boolean.valueOf(businessData.get('terminateBradningContent').Business_Rule_Value__c)){

			System.debug('BatchTerminateBrandingContent.execute: terminating: ' + content.id);
				
			if(String.isBlank(content.Termination_Reason__c)){
				content.Status__c = businessData.get('expiredStatus').Business_Rule_Value__c;
			}else{
				content.Status__c = businessData.get('terminationStatus').Business_Rule_Value__c;
			}

			toUpdate.add(content);
		}
         
      }

      System.debug('BatchTerminateBrandingContent.execute: toUpdate size is: ' + toUpdate.size());

      if (!toUpdate.isEmpty()) {
         update toUpdate;
      }

      System.debug('BatchTerminateBrandingContent.execute: done');
   }

   global void finish(Database.BatchableContext BC) {}
   
   
}