force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Uses in Booking Rest Service. To store the information about external system name through which the booking was done.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIDAS</fullName>
            </value>
            <value>
                <fullName>Restaurant Portal Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Booking_Api_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Api_Id__c</fullName>
    <externalId>true</externalId>
    <label>Booking Api Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ClsTerminationRestaurantHelper.cls
/**
 * Created by w.novoa on 16.03.2018.
 */

public inherited sharing class ClsTerminationRestaurantHelper {


    public Map<String, Business_Config__c> mapBusinessData { get; set; }
    public Set<String> doNotOverwriteStatusSet;

    public String assetStatus {get; set;}
    public Boolean showButtons {get; set;}

    public Boolean contractTerminationReasonMandatory {get; private set;}
    public Boolean addChargesTerminationReasonMandatory {get; private set;}
    public Boolean brandingTerminationReasonMandatory {get; private set;}

    public Boolean addOnTerminationReasonMandatory {get; private set;}

    public Boolean contractTerminationDateMandatory {get; private set;}
    public Boolean addChargesTerminationDateMandatory {get; private set;}
    public Boolean brandingTerminationDateMandatory {get; private set;}
    public Boolean addOnTerminationDateMandatory {get; private set;}

    public ClsTerminationRestaurantHelper(String RecordTypeid) {
        System.debug('CtrTerminationRestaurantVue');
        this.contractTerminationReasonMandatory = false;
        this.addChargesTerminationReasonMandatory = false;
        this.brandingTerminationReasonMandatory = false;
        this.addOnTerminationReasonMandatory = false;

        this.contractTerminationDateMandatory = false;
        this.addChargesTerminationDateMandatory = false;
        this.brandingTerminationDateMandatory = false;
        this.addOnTerminationDateMandatory = false;

        this.doNotOverwriteStatusSet = new Set<String>();

        Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;

        Map<String, Map<String, Business_Config__c>> mapProcessData = moam.get('TerminateRestaurant');

        this.mapBusinessData = mapProcessData.get(LibRecordTypeHelper.getRecordTypeForIds(new Set<String> {'Account'}).get(RecordTypeid).DeveloperName);

        System.debug('CtrTerminationRestaurantVue-->'+mapBusinessData);


        if (this.mapBusinessData != null && !this.mapBusinessData.isEmpty()) {

            System.debug('CtrTerminationRestaurantVue-->'+mapBusinessData.get('AssetTerminateStatus'));
            if (mapBusinessData.get('AssetTerminateStatus') != null) {
                this.assetStatus = mapBusinessData.get('AssetTerminateStatus').Business_Rule_Value__c;
                this.showButtons = true;
            } else {
                this.showButtons = false;
                ClsUtilsApexPages.addErrorMessage('Business rule AssetTerminateStatus is required');
                return;
            }

            if (mapBusinessData.containsKey('contractTerminationReasonMandatory')) {
                this.contractTerminationReasonMandatory = Boolean.valueOf(mapBusinessData.get('contractTerminationReasonMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('addChargesTerminationReasonMandatory')) {
                this.addChargesTerminationReasonMandatory = Boolean.valueOf(mapBusinessData.get('addChargesTerminationReasonMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('brandingTerminationReasonMandatory')) {
                this.brandingTerminationReasonMandatory = Boolean.valueOf(mapBusinessData.get('brandingTerminationReasonMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('addonTerminationReasonMandatory')) {
                this.addOnTerminationReasonMandatory = Boolean.valueOf(mapBusinessData.get('addonTerminationReasonMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('contractTerminationDateMandatory')) {
                this.contractTerminationDateMandatory = Boolean.valueOf(mapBusinessData.get('contractTerminationDateMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('addChargesTerminationDateMandatory')) {
                this.addChargesTerminationDateMandatory = Boolean.valueOf(mapBusinessData.get('addChargesTerminationDateMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('brandingTerminationDateMandatory')) {
                this.brandingTerminationDateMandatory = Boolean.valueOf(mapBusinessData.get('brandingTerminationDateMandatory').Business_Rule_Value__c);
            }

            if (mapBusinessData.containsKey('addonTerminationDateMandatory')) {
                this.addOnTerminationDateMandatory = Boolean.valueOf(mapBusinessData.get('addonTerminationDateMandatory').Business_Rule_Value__c);
            }

            system.debug('mapBusinessData.get(DoNotOverwriteStatus)--->'+mapBusinessData.get('DoNotOverwriteStatus'));
            if (mapBusinessData.get('DoNotOverwriteStatus') != null) {
                if (mapBusinessData.get('DoNotOverwriteStatus').Business_Rule_Value__c.indexOf(',') > -1) {
                    this.doNotOverwriteStatusSet.addAll(mapBusinessData.get('DoNotOverwriteStatus').Business_Rule_Value__c.split(','));
                } else {
                    this.doNotOverwriteStatusSet.add(mapBusinessData.get('DoNotOverwriteStatus').Business_Rule_Value__c);
                }
            }

        } else {
            this.showButtons = false;
            ClsUtilsApexPages.addErrorMessage(Label.Terminate_process_required);
        }
    }

    public String terminateMidasPP(List<String> bookingIds) {

        String result = '';
        string logName = 'BookingOrAddCharge_Termination';
        Id currentUserId = UserInfo.getUserId();
        List<LibWebserviceHelper.oppLineItemBookingData> listBookData;
        HttpResponse response;
        try {
            List<User> userData = UserSelector.getAllByUserId(new set<ID>{currentUserId});
            List<Opportunity_line_item__c> oppLines = OpportunityLineItem_Selector.getOLIByBookingId(bookingIds);
            if (oppLines.isEmpty()) {
                return result;
            }
            LoggingUtility.createLog(logName, 'MIDAS_SELFBOOKING', ' OPP ID- ' + oppLines[0].Id_Opportunity__c, null);
            if (!mapBusinessData.containsKey('EnableCancelBookingInMidas')  || oppLines[0].Id_Opportunity__r.Source_System__c != 'MIDAS') {
                return ClsOpportunityProcessor.cancelBookings(userData[0], oppLines, oppLines[0].Id_Opportunity__r.record_country__c);
            }
            listBookData = prepareDataForMidasCancelCallout(oppLines);
            LoggingUtility.log(logName, 'Request Body: ' + listBookData);
            LoggingUtility.captureTimeStamp(logName, 'Begin');
            response = LibWebserviceHelper.constructMidasRequestForBookingCancellation(oppLines[0].Id_Opportunity__r.record_country__c, listBookData, logName);
            if (response != null && (response.getStatusCode() == 204 || response.getStatusCode() == 208)) {
                result = Label.Midas_Terminate_Page_Success_Message;
            } else if (response == null) {
                result = Label.Midas_Terminate_Page_Error_Message ;
                LoggingUtility.logError(logName, 'No Token or response for Premium Placement');
                ClsOpportunityProcessor.updateExceptionInOpp(listBookData);
            }else {
                result = Label.Midas_Terminate_Page_Error_Message + ' ' + response.getStatus();
                LoggingUtility.logError(logName, ' Failed to terminate PremPlacements ' + response.getStatus() + ' Status Code ' + response.getStatusCode());
                ClsOpportunityProcessor.updateExceptionInOpp(listBookData);
            }
            LoggingUtility.captureTimeStamp(logName, 'End');
            LoggingUtility.commitLogs();
            return result;
        } catch (Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.logError(logName, e.getStackTraceString());
            if ((response == null || response.getStatusCode() != 204 && response.getStatusCode() != 208) && listBookData != null) {
                ClsOpportunityProcessor.updateExceptionInOpp(listBookData);
            }
            return e.getMessage();
        }
    }

    /**
   * @description To prepare data to send as body to Midas cancellations
   * @Param        ID oppLineId
   * @return       Wrapper oppLineItemBookingData
   */
    public static List<LibWebserviceHelper.oppLineItemBookingData> prepareDataForMidasCancelCallout(List<Opportunity_line_item__c> premPlacementLineItems ){

        List<LibWebserviceHelper.oppLineItemBookingData> wrapper = new List<LibWebserviceHelper.oppLineItemBookingData>();
        try {
            for (Opportunity_Line_item__c lineItem : premPlacementLineItems) {
                LibWebserviceHelper.oppLineItemBookingData bookData = new LibWebserviceHelper.oppLineItemBookingData(Integer.valueOf(lineItem.Booking_Api_Id__c), UserInfo.getUserEmail());
                wrapper.add(bookData);
            }
        }catch(exception e){
            system.debug('Error: '+e.getMessage());
        }
        return wrapper;
    }


}