force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tax_Number__c.field-meta.xml
<CustomField>
    <fullName>Tax_Number__c</fullName>
    <label>Tax Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trade_Register_Number__c.field-meta.xml
<CustomField>
    <fullName>Trade_Register_Number__c</fullName>
    <label>Business Licence Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country on related Account</description>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <inlineHelpText>Country on related Account</inlineHelpText>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Non_Standard_Contract_Components__c.field-meta.xml
<CustomField>
    <fullName>Non_Standard_Contract_Components__c</fullName>
    <label>Non Standard Contract Components</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Platform exclusivity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Online Payment Doc</fullName>
            </value>
            <value>
                <fullName>Registration fee</fullName>
            </value>
            <value>
                <fullName>Renewal fee</fullName>
            </value>
            <value>
                <fullName>Pizza</fullName>
            </value>
            <value>
                <fullName>Sushi</fullName>
            </value>
            <value>
                <fullName>New Restaurant Info</fullName>
            </value>
            <value>
                <fullName>Ownership Change</fullName>
            </value>
            <value>
                <fullName>Premium Show Discount</fullName>
            </value>
            <value>
                <fullName>BladeT&amp;C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Non_Standard_Contract_Components__c.field-meta.xml
<CustomField>
    <fullName>Non_Standard_Contract_Components__c</fullName>
    <label>Non Standard Contract Components</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Platform exclusivity</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Online Payment Doc</fullName>
            </value>
            <value>
                <fullName>Registration fee</fullName>
            </value>
            <value>
                <fullName>Renewal fee</fullName>
            </value>
            <value>
                <fullName>Pizza</fullName>
            </value>
            <value>
                <fullName>Sushi</fullName>
            </value>
            <value>
                <fullName>New Restaurant Info</fullName>
            </value>
            <value>
                <fullName>Ownership Change</fullName>
            </value>
            <value>
                <fullName>Premium Show Discount</fullName>
            </value>
            <value>
                <fullName>Cash before delivery</fullName>
            </value>
            <value>
                <fullName>Partial prepayment</fullName>
            </value>
            <value>
                <fullName>Settlement</fullName>
            </value>
            <value>
                <fullName>BladeT&amp;C</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Mjam Web</fullName>
            </value>
            <value>
                <fullName>Exclusivity: KSP Lite</fullName>
            </value>
            <value>
                <fullName>Exclusivity: KSP Classic</fullName>
            </value>
            <value>
                <fullName>Exclusivity: KSP+</fullName>
            </value>
            <value>
                <fullName>Exclusivity: KSP PGA</fullName>
            </value>
            <value>
                <fullName>Cancellation Reimbursement</fullName>
            </value>
            <value>
                <fullName>Cash Only</fullName>
            </value>
            <value>
                <fullName>Menu Flyer Terms</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Created&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CtrQuoteScreen.cls
public without sharing class CtrQuoteScreen {
    private static Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;

    public Opportunity_Quote__c theQuote {get; set;}
    public List<Schema.FieldSetMember> fields_Quote {get; set;}
    public boolean viewMode {get; set;}
    public boolean editMode {get; set;}
    public boolean showAcceptQuote {get; set;}
    public boolean showCreatePDF {get; set;}
    public boolean showSendEmail {get; set;}
    public boolean showEditButton {get; set;}
    public boolean readOnly {get; set;}
    public boolean showRefresh {get; set;}
    public Boolean displayQuoteInIframe {get; set;}
    public Boolean checkForRequiredFields { get; set; }
    public String allowAcceptQuote { get; set; }
    public Boolean allowVIPAcceptQuote {get;set; }
    public Boolean isNintexQuote {get; set;}
    private Boolean templateNameIsSet {get; set;}
    private static final Set<String> nintexClassicCountries = Constants.NINTEX_CONFIG_CLASSICUI_COUNTRIES;

    /*
    * SP-581 Approval for ME
    */
    public boolean showApprovalButtons {get; set;} //show Approve and Reject button

    public CtrQuoteScreen(ApexPages.StandardController controller) {
        this.viewMode = true;
        this.editMode = false;
        this.showAcceptQuote = true;
        this.showCreatePDF = true;
        this.showSendEmail = true;
        this.showEditButton = true;
        this.showApprovalButtons = false;
        this.readOnly = false;
        this.showRefresh = true;
        this.templateNameIsSet = false;
        this.displayQuoteInIframe = false;

        Map<String, Map<String, Business_Config__c>> mapProcessData = moam.get('QuoteScreenProcess');
        Map<String, Business_Config__c> mapBusinessData;

        if (!Test.isRunningTest()) {
            controller.addFields(new List<String> {
                'Template_Name__c',
                'Id_opportunity__r.RecordTypeId',
                'Id_opportunity__r.Business_Type__c',
                'Id_Account__r.recordType.developerName',
                'Non_Standard_Contract_Components__c',
                'Recordtype.Developername',
                'Id_Opportunity__r.Record_Country__c',
                'Id_Account__r',
                'Id_Account__r.Trade_Register_Number__c',
                'Id_Account__r.Tax_Number__c',
                'Id_Account__c',
                'CreatedDate'
            });
        }

        this.theQuote = (Opportunity_Quote__c) controller.getRecord();
        this.isNintexQuote = nintexClassicCountries.contains(theQuote.Id_Opportunity__r.Record_Country__c);
        // checks for null values
        if (mapProcessData == null) {
            ClsUtilsApexPages.addInfoMessage(Label.BusinessProcessNotActive);
            return;
        }

        mapBusinessData = mapProcessData.get(this.theQuote.Recordtype.Developername);

        Map<String, Map<String, Business_Config__c>> mapProcessDataApproval = moam.get('QuoteApprovalProcess');

        // checks if quote can be approved by current user
        if (mapProcessDataApproval != null) {
            Map<String, Map<String, OpportunityTeamMember>>mapOppTeam = LibBusinessConfig.determineApproverMap(this.theQuote.id_opportunity__c);
            Map<String, OpportunityTeamMember> mapApprovalLevel1 = mapOppTeam.get('HOS');
            Map<String, OpportunityTeamMember> mapApprovalLevel2 = mapOppTeam.get('Legal');
            Map<String, OpportunityTeamMember> mapApprovalLevel3 = mapOppTeam.get('Regional HOS');
            Map<String, Business_Config__c> mapBusinessDataApproval = mapProcessDataApproval.get(this.theQuote.Recordtype.Developername);


            // checks if to show or not approval buttons
            if (mapBusinessDataApproval != null && mapOppTeam != null) {

                this.showApprovalButtons = (
                                               // level 3 approvers
                                               (
                                                   mapApprovalLevel3 != null &&
                                                   mapApprovalLevel3.keySet().contains(UserInfo.getUserId()) && mapBusinessDataApproval.get('initialStatusLevel3') != null &&
                                                   this.theQuote.Status__c == mapBusinessDataApproval.get('initialStatusLevel3').Business_Rule_Value__c
                                               )
                                               ||
                                               // level 1 approvers
                                               (
                                                   mapApprovalLevel1 != null &&
                                                   mapApprovalLevel1.keySet().contains(UserInfo.getUserId()) && mapBusinessDataApproval.get('initialStatusLevel1') != null &&
                                                   this.theQuote.Status__c == mapBusinessDataApproval.get('initialStatusLevel1').Business_Rule_Value__c
                                               )
                                               ||
                                               // level 2 approvers
                                               (
                                                   mapApprovalLevel2 != null &&
                                                   mapApprovalLevel2.keySet().contains(Userinfo.getUserId()) && mapBusinessDataApproval.get('level1ApprovedStatus') != null &&
                                                   this.theQuote.Status__c == mapBusinessDataApproval.get('level1ApprovedStatus').Business_Rule_Value__c
                                               )
                                           );
            }
        }

        if (mapBusinessData != null) {

            // checks if has to display the quote pdf in an iframe instead of injecting it into the page
            if (mapBusinessData.containsKey('displayQuoteInIframe')) {
                this.displayQuoteInIframe = Boolean.valueOf(mapBusinessData.get('displayQuoteInIframe').Business_Rule_Value__c);
            }

            // add fields
            if (mapBusinessData.containsKey('FieldSet')) {
                this.fields_Quote = readFieldSet(mapBusinessData.get('FieldSet').Business_Rule_Value__c, 'Opportunity_Quote__c');
                this.checkForRequiredFields = Boolean.valueOf(mapBusinessData.get('CheckForRequiredFields').Business_Rule_Value__c);
                if (mapBusinessData.containsKey('AllowAcceptQuoteButton') && (!mapBusinessData.containsKey('SkipEmailForTypes')
                        || this.theQuote.Id_Opportunity__r.Business_Type__c == null
                        || !mapBusinessData.get('SkipEmailForTypes').Business_Rule_Value__c.contains(this.theQuote.Id_Opportunity__r.Business_Type__c))) {
                    this.allowAcceptQuote = mapBusinessData.get('AllowAcceptQuoteButton').Business_Rule_Value__c;

                }
            }

            if (mapBusinessData.containsKey('AllowVIPAcceptQuote')){
            	allowVIPAcceptQuote = boolean.valueOf(mapBusinessData.get('AllowVIPAcceptQuote').Business_Rule_Value__c);
            }else{
            	allowVIPAcceptQuote = false;
            }
            

            // gets the quote
            retriveQuoteDetails();

            // enable/disable buttons according to quote status
            String statusRuleName = 'DisableButton_' + this.theQuote.status__c;
            if (mapBusinessData.containsKey(statusRuleName)) {
                for (String str : (mapBusinessData.get(statusRuleName).Business_Rule_Value__c.split(','))) {
                    if (str.equalsIgnoreCase('acceptQuote')) {
                        this.showAcceptQuote = false;
                    } else if (str.equalsIgnoreCase('createPDF')) {
                        this.showCreatePDF = false;
                    } else if (str.equalsIgnoreCase('sendEmail')) {
                        this.showSendEmail = false;
                    } else if (str.equalsIgnoreCase('approval')) {
                        this.showApprovalButtons = false;
                    } else if (str.equalsIgnoreCase('edit')) {
                        this.showEditButton = false;
                    } else if (str.equalsIgnoreCase('readOnly')) {
                        this.readOnly = true;
                    } else if (str.equalsIgnoreCase('refresh')) {
                        this.showRefresh = false;
                    }
                }
            }
        }

        if (this.theQuote.Template_Name__c != null && !this.isNintexQuote) { // Defect Fix: #SSC:1319) {
            this.templateName = this.theQuote.Template_Name__c;
        }
    }

    private void retriveQuoteDetails() {
        String queryString = 'select id,Name, CreatedDate, Template_Name__c,Id_opportunity__r.RecordTypeId, Id_Opportunity__r.Account.ParentId, Non_Standard_Contract_Components__c,Id_Account__r.recordType.developerName';
        if (this.fields_Quote != null) {
            for (Schema.FieldSetMember fsm : this.fields_Quote) {
                String filedName = fsm.getFieldPath();
                if (!queryString.containsIgnoreCase(filedName)) {
                    queryString += ', ' + filedName;
                }
            }
        }
        queryString += ' from Opportunity_Quote__c where id=\'' + this.theQuote.id + '\'';
        this.theQuote = Database.query(queryString);
    }

    public String templateName {
        get{
            System.debug('templateName1: ' + templateName);
            this.templateNameIsSet = false;
            if (templateName == null) {
                List<Opportunity_Quote_Line_Item__c> existingLineItems = [select id, Line_Item_Type__c, sub_type__c from Opportunity_Quote_Line_Item__c where Id_Opportunity_Quote__c = :this.theQuote.Id];
                ClsQuoteProcessor cqp1 = new ClsQuoteProcessor(null, this.theQuote,this.theQuote.Id_Account__r.recordType.developerName, existingLineItems);
                this.templateName = cqp1.vfTemplateName;
                System.debug('templateName2: ' + templateName);
                this.theQuote.Template_Name__c = this.templateName;
                this.templateNameIsSet = true;
                //update this.theQuote;
                System.debug('this.theQuote.Template_Name__c: ' + this.theQuote.Template_Name__c);
            }
            return templateName;
        }
        private set;
    }

    public void generateTemplateName() {
        if (this.templateNameIsSet) {
            System.debug('templateNameIsSet: ' + templateNameIsSet);
            update this.theQuote;
        }
    }

    public PageReference saveDetails() {
        try {
            update this.theQuote;
            retriveQuoteDetails();
        } catch (Exception e) {
            System.debug('Error at Save Detail: ' + e.getMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Error occured contact Admins.'));
        }
        return new PageReference('/' + this.theQuote.Id);
    }

    private List<Schema.FieldSetMember> readFieldSet(String fieldSetName, String ObjectName) {
        Map<String, Schema.SObjectType> GlobalDescribeMap = Schema.getGlobalDescribe();
        Schema.SObjectType SObjectTypeObj = GlobalDescribeMap.get(ObjectName);
        Schema.DescribeSObjectResult DescribeSObjectResultObj = SObjectTypeObj.getDescribe();

        Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
        return fieldSetObj.getFields();
    }

    public void switchToEditMode() {
        this.viewMode = false;
        this.showEditButton = false;
        this.editMode = true;
    }

    public void switchToLockMode() {
        //this.lockMode = true;
        this.viewMode = true;
        this.showEditButton = true;
        this.editMode = false;
    }

    public void switchToViewMode() {
        this.viewMode = true;
        this.showEditButton = true;
        this.editMode = false;
        retriveQuoteDetails();
    }
}