force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Restaurant Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Iso__c.field-meta.xml
<CustomField>
    <fullName>Iso__c</fullName>
    <label>Iso</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/classes/CtrCreateNewAddress.cls
public with sharing class CtrCreateNewAddress {

	public CtrCreateNewAddress() {
	}

	public CtrCreateNewAddress(ApexPages.StandardController ctr) {
	}
	public static String DaumApiKey {
		get {
			return Integration_Config__c.getValues('DaumMapsAPI').Password__c;
		}
	}
	/* ********** UTILS ACTIONS ********* */

	@RemoteAction
	public static Map<String, String> getAddressTypes() {
		Map<String, String> res = new Map<String, String>();
		for (Schema.PicklistEntry pe : AddressDetail__c.Type__c.getDescribe().getPicklistValues()) {
			res.put(pe.getValue(), pe.getLabel());
		}
		return  res;
	}

	@RemoteAction
	public static Account getAccountRecordType(String accountId) {
        Account accountCountryRecType = [SELECT RecordType.DeveloperName,Record_Country__c FROM Account WHERE Id = :accountId];
        return accountCountryRecType;
	}

	/* ********** GPA MODEL ACTIONS ********* */

	@RemoteAction
	public static GPAAddressDetails gpa_getNewAddressDetailsPerAccount(String accountId) {
		// get country iso code
		String countryName = [
				SELECT Record_Country__c
				FROM Account
				WHERE Id = :accountId
		].Record_Country__c;

		// creates empty address
		GPAAddressDetails res = new GPAAddressDetails([
				SELECT Iso__c
				FROM Country__c
				WHERE Name = :countryName
				LIMIT 1
		].Iso__c);

		// set account id
		res.account = accountId;
		return res;
	}

	@RemoteAction
	public static GPAAddressDetails gpa_getNewAddressPerCountry(String countryName) {
		return new GPAAddressDetails([
				SELECT Iso__c
				FROM Country__c
				WHERE Name = :countryName
		].Iso__c);
	}

	@RemoteAction
	public static GPAAddressDetails gpa_getAddressDetails(String addressId) {
		return new GPAAddressDetails(Id.valueOf(addressId));
	}

	@RemoteAction
	public static GPAAddressDetails daum_getAddressDetails(String addressId, String accountId) {
		return new GPAAddressDetails(Id.valueOf(addressId), Id.valueOf(accountId));
	}

	@RemoteAction
	public static List<GPAAddressDetails> daum_getAddressDetailsPerAccount(String accountId) {
		List<GPAAddressDetails> res = new List<GPAAddressDetails>();
		for (AddressDetail__c address : AddressDetail_Selector.getByAccountIdsAndDaumModel(new Set<Id> {accountId}, Label.KR_Old_Address)) {
			res.add(new GPAAddressDetails(address.Id, accountId));
		}
		return res;
	}

	@RemoteAction
	public static List<GPAAddressDetails> gpa_getAddressDetailsPerAccount(String accountId) {
		List<GPAAddressDetails> res = new List<GPAAddressDetails>();
		for (AddressDetail__c address : AddressDetail_Selector.getByAccountIds(new Set<Id> {accountId})) {
			res.add(new GPAAddressDetails(address.Id));
		}
		return res;
	}

	@RemoteAction
	public static GPAAddressDetails gpa_saveAddress(GPAAddressDetails address) {
		return new GPAAddressDetails(address.save());
	}

	@RemoteAction
	public static List<GPAAddressDetails> gpa_saveAddresses(List<GPAAddressDetails> addresses) {
		List<GPAAddressDetails> res = new List<GPAAddressDetails>();
		for (GPAAddressDetails address : addresses) {
			res.add(new GPAAddressDetails(address.save()));
		}
		return res;
	}

	/* ********** XAL MODEL ACTIONS ********* */

	@RemoteAction
	public static xALAdministrativeArea getAdminAreaByName(String name) {
		return xALAdministrativeArea.byName(name);
	}

	@RemoteAction
	public static xALAdministrativeArea getAdminAreaByLabel(String label) {
		return xALAdministrativeArea.byLabel(label);
	}

	@RemoteAction
	public static xALSubAdministrativeArea getSubAdminAreaByName(String name) {
		return xALSubAdministrativeArea.byName(name);
	}

	@RemoteAction
	public static xALLocality getLocalityByName(String name) {
		return xALLocality.byName(name);
	}

	@RemoteAction
	public static xALCountry getCountryByName(String name) {
		return xALCountry.byName(name);
	}

	@RemoteAction
	public static xALCountry getCountryByLabel(String label) {
		xALCountry res = null;
		try {
			res = xALCountry.byLabel(label);
		} catch (Exception e) {
			System.debug('CtrCreateNewAddress.getCountryByLabel: exception occurred. Message is: ' + e.getMessage());
		}
		return res;
	}

	@RemoteAction
	public static xALCountry getCountryByAccountCountryLabel(String accountId) {
		return getCountryByLabel([SELECT Record_Country__c FROM Account WHERE Id = :accountId].Record_Country__c);
	}

	@RemoteAction
	public static xALAddressDetails getAddressDetails(String id) {
		return new xALAddressDetails(id);
	}

	@RemoteAction
	public static List<xALAddressDetails> getAddressDetailsPerAccount(String accountId) {
		List<xALAddressDetails> res = new List<xALAddressDetails>();
		for (AddressDetail__c addr : [SELECT Id FROM AddressDetail__c WHERE Account__c = :accountId]) {
			res.add(new xALAddressDetails(addr.Id));
		}
		return res;
	}

	@RemoteAction
	public static xALAddressDetails saveAddress(xALAddressDetails address) {
		return new xALAddressDetails(address.save());
	}

	@RemoteAction
	public static List<xALAddressDetails> saveAddresses(List<xALAddressDetails> addresses) {
		List<xALAddressDetails> res = new List<xALAddressDetails>();
		for (xALAddressDetails addr : addresses) {
			res.add(new xALAddressDetails(addr.save()));
		}
		return res;
	}

	/*---------------------New xAL Methods--------------------*/

	@RemoteAction
	public static xALCountry getCountryByCountryName(String countryName) {
		Country__c country = Country_Selector.getByName(countryName);
		return new xALCountry(country);
	}

	@RemoteAction
	public static xALCountry getAccountCountry(String accountId) {
		String countryName =  AccountSelector.getAccountDetailsforId(accountId).Record_Country__c;
		return getCountryByCountryName(countryName);
	}

	@RemoteAction
	public static xALAddressDetails getXALAddressDetails(String id) {
		return xALAddressDetails.getXALAddressDetailsById(id);
	}

	@RemoteAction
	public static List<xALAddressDetails> getXALAddressDetailsPerAccount(String accountId) {
		List<xALAddressDetails> res = new List<xALAddressDetails>();
		for (AddressDetail__c addr : AddressDetail_Selector.getByAccountId(accountId)) {
			res.add(xALAddressDetails.getXALAddressDetailsById(addr.Id));
		}
		return res;
	}

	@RemoteAction
	public static xALAddressDetails saveXALAddress(xALAddressDetails address) {
		return xALAddressDetails.getXALAddressDetailsById(address.save());
	}

	@RemoteAction
	public static List<xALAddressDetails> saveXALAddresses(List<xALAddressDetails> addresses) {
		List<xALAddressDetails> res = new List<xALAddressDetails>();
		for (xALAddressDetails address : addresses) {
			res.add(xALAddressDetails.getXALAddressDetailsById(address.save()));
		}
		return res;
	}

	/* ********** Mixed (GPA/XAL) MODEL ACTIONS - Used by Argentina,Chile,Uruguay **********/

	@RemoteAction
	public static List<xALLocality> getLocalityBySubAdminArea(String name) {
		return xALLocality.bySubAdministrativeAreaLabel(name);
	}
}