force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Country_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Country_long_name__c</fullName>
    <label>GPA Country long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/GPA_Postal_code_long_name__c.field-meta.xml
<CustomField>
    <fullName>GPA_Postal_code_long_name__c</fullName>
    <label>GPA Postal code long name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Restaurant Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>The role the contact plays in the restaurant</description>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-owner</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Franchise Contact</fullName>
            </value>
            <value>
                <fullName>Former Owner</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Previous Owner</fullName>
            </value>
            <value>
                <fullName>Ex-employee</fullName>
            </value>
            <value>
                <fullName>Billing Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
                <label>duplicate</label>
            </value>
            <value>
                <fullName>Additional Contact</fullName>
                <label>additional contact</label>
            </value>
            <value>
                <fullName>Restaurant Operations</fullName>
            </value>
            <value>
                <fullName>Customer Contact</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country on related Account</description>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <inlineHelpText>Country on related Account</inlineHelpText>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <description>SSC-1617</description>
    <label>Countries</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Config__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Aftership_ID__c.field-meta.xml
<CustomField>
    <fullName>Aftership_ID__c</fullName>
    <description>Filed holds ID for Aftership tracking system</description>
    <label>Aftership ID</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Last_Tracking_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Tracking_Update__c</fullName>
    <description>Timestamp on when delivery tracking status was updated last time.</description>
    <label>Last Tracking Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Shipping_Company__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Company__c</fullName>
    <label>Shipping Company</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Account_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>fonsen</fullName>
                <label>Fonsen Logistics</label>
            </value>
            <value>
                <fullName>hct-logistics</fullName>
                <label>HCT logistics</label>
            </value>
            <value>
                <fullName>ninjavan-my</fullName>
                <label>Ninjavan</label>
            </value>
            <value>
                <fullName>sf-express</fullName>
                <label>SF Express</label>
            </value>
            <value>
                <fullName>lbcexpress</fullName>
                <label>LBC express</label>
            </value>
            <value>
                <fullName>kerry-logistics</fullName>
                <label>Kerry Logistics</label>
            </value>
            <value>
                <fullName>ecoutier</fullName>
                <label>Ecourier</label>
            </value>
            <value>
                <fullName>paperfly</fullName>
                <label>Paperfly</label>
            </value>
            <value>
                <fullName>alphafast</fullName>
                <label>Alpha</label>
            </value>
            <value>
                <fullName>grab</fullName>
                <label>Grab</label>
            </value>
            <value>
                <fullName>xpost</fullName>
                <label>Xpost</label>
            </value>
            <value>
                <fullName>malaysia-post</fullName>
                <label>Pos Laju</label>
            </value>
            <value>
                <fullName>sagawa</fullName>
                <label>Sagawa</label>
            </value>
            <value>
                <fullName>DHL</fullName>
                <isActive>false</isActive>
                <label>DHL</label>
            </value>
            <value>
                <fullName>FLS</fullName>
                <isActive>false</isActive>
                <label>FLS</label>
            </value>
            <value>
                <fullName>UPS</fullName>
                <isActive>false</isActive>
                <label>UPS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to display current status of Shipment Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Tracking_Active__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field necessary for Aftership integration to continue tracking returning shipment</description>
    <label>Tracking Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Tracking_Exception__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Exception__c</fullName>
    <description>Field to hold exception message from Aftership</description>
    <label>Tracking Exception</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Determines shipment source and destination</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DH to Vendor</fullName>
                <default>true</default>
                <label>DH to Vendor</label>
            </value>
            <value>
                <fullName>Vendor to DH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchCreateTrackingIdOnAfterShip.cls
global class BatchCreateTrackingIdOnAfterShip implements Database.Batchable<sObject>, Database.AllowsCallouts{
    Integration_Config__c intConfig;
     Integer v;
    static List<string> acc;
    Set<string> setOfCountries;

    global BatchCreateTrackingIdOnAfterShip(){
        intConfig = Integration_Config__c.getValues('AfterShip');
        setOfCountries = new Set<string>();
        if(!string.isEmpty(intConfig.Countries__c)){
            setOfCountries.addAll(intConfig.Countries__c.split(','));

        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){           
        return Database.getQueryLocator([select id,Tracking_Number__c,account__c,Shipping_Company__c
                                            from Shipment_Order__c
                                            where Tracking_Number__c!=null
                                                and Shipping_Company__c !=null
                                            	and Aftership_ID__c=null
                                            	and  status__c='Shipped'
                                            	and tracking_active__c=false
                                                and Account__r.Record_Country__c IN : setOfCountries
                                        ]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Shipment_Order__c> shippingOrderLst  			    = (List<Shipment_Order__c>)scope;
        acc 										= new List<String>();
        Map<String,List<Shipment_Order__c>>	trackingNumberVsShippingOrderMap 	= new Map<String,List<Shipment_Order__c>>(); // Map of tracking number vs the list of assets
        Set<String> trackingNumbers								= new Set<String>();
        List<Shipment_Order__c> shpOrdersToBeUpdated						= new List<Shipment_Order__c>();
        
        // Populate tracking numbers set
        for(Shipment_Order__c so : shippingOrderLst){
        	trackingNumbers.add(so.Tracking_number__c);
        }
        
        // populate the tracking number vs the shipping orders map
        trackingNumberVsShippingOrderMap = populateTrackingNumberVsShippingOrdersMap(trackingNumbers);

    	if(trackingNumberVsShippingOrderMap.isEmpty())
    		return;
    	
    	// fetch the account map with contacts and addresses	
    	Map<id,Account> accContactLst = fetchAccountMap(acc);	
		
		// make callout for each individual tracking number one by one
		for(String trackingNumber : trackingNumberVsShippingOrderMap.keySet()){
            Shipment_Order__c so		= trackingNumberVsShippingOrderMap.get(trackingNumber)[0];
            Account a 			= accContactLst.get(so.account__c);
            String body			= populateRequestBody(so,a);
			string logName 		= 'aftershipIdUpdate'+so.Id;

            try{
				HttpResponse res	= makeCallout(intConfig,body,so.id,logName);
                parseResponse(res,trackingNumber,trackingNumberVsShippingOrderMap,shpOrdersToBeUpdated,logName);
            }catch(Exception e){
            	LoggingUtility.logError(logName,'Error ' + e.getMessage());
                system.debug(e.getMessage());
            }
		}
		
		// update the assets
		if(shpOrdersToBeUpdated.size() > 0)
			update shpOrdersToBeUpdated;
		LoggingUtility.commitLogs();

    }
    
    
     global void finish(Database.BatchableContext BC){ 
          
     }

	 private static Map<String,List<Shipment_Order__c>> populateTrackingNumberVsshippingOrdersMap(Set<String> trackingNumbers){
	 	Map<String,List<Shipment_Order__c>>	trackingNumberVsShipmentsMap 	= new Map<String,List<Shipment_Order__c>>();
	 	List<Shipment_Order__c> shipmentOrders = ShipmentOrderSelector.getShipmentOrderbyTracking (trackingNumbers);
    	
    	// populate the tracking number vs the list of assets map
    	for(Shipment_Order__c so : shipmentOrders){
    		if(!trackingNumberVsShipmentsMap.containsKey(so.tracking_number__c)){
                trackingNumberVsShipmentsMap.put(so.tracking_number__c,new List<Shipment_Order__c>());
    		}
            trackingNumberVsShipmentsMap.get(so.tracking_number__c).add(so);
            acc.add(so.Account__c); //SSC-1617
    	}
    	
    	return trackingNumberVsShipmentsMap;
	 }
	 
	 private static Map<Id,Account> fetchAccountMap(List<String> accIds){
	 	 Map<id,Account> accContactLst = new Map<id,account>([select id,
                                                                    (select id,
                                                                            phone,
                                                                            email,
                                                                            name,
                                                                            mobilePhone
                                                                            from contacts
                                                                            where contact_role__c='Owner'),
                                                                    (select id,
                                                                            GPA_Country_long_name__c,
                                                                            GPA_Postal_code_long_name__c
                                                                            from AddressDetails__r
                                                                            where Type__c INCLUDES ('Shipping Address'))
                                                                from account
                                                                where id in :accIds ]);
		
		return accContactLst;
	 }
	 
	 private static String populateRequestBody(Shipment_Order__c so,Account a){
	 	String cEmail 	='';
        String cPhone 	= '';
        String cName	='';
        String postCode ='';
        String country 	= '';
        
        String body		= '{"tracking": {' +
                        		+' "tracking_number":'+ ' "'+so.Tracking_Number__c +'",';
	 body += '"slug":"'+so.Shipping_Company__c+'"';

        for(Contact cn: a.contacts){
            if(cn.mobilePhone!=null)
                cPhone+='"'+cn.mobilePhone+'",';
            if(cn.email!=null )
                cEmail+='"'+cn.email+'",';
            cName=cn.name;
        }
        for(AddressDetail__c addr:a.AddressDetails__r ){
            if(addr.GPA_Postal_code_long_name__c!=null)
                postCode=addr.GPA_Postal_code_long_name__c;
            if(addr.GPA_Country_long_name__c!=null)
                Country=addr.GPA_Country_long_name__c;
        }

        if(cEmail!=null && cEmail!='')
        	body+=',"emails" :['+cemail.removeEndIgnorecase(',')+']';
        if(cPhone!=null && cPhone!='')
        	body+=',"smses" :['+cPhone.removeEndIgnorecase(',')+']';
        if(Country!=null && Country!='')
        	body+=',"tracking_postal_code":'+'"'+postCode+'"';
        if(postCode!=null && postCode!='')
        	body+=',"tracking_destination_country":'+'"'+country+'"';
        
        body +=',"customer_name" :'+'"'+cName+'"';
        body +='}}';
        
        return body;
	 }
	 
	 private static HttpResponse makeCallout(Integration_Config__c intConfig,String body,String assetId,String logName){
	 	Loggingutility.createLog(logName,'AFTERSHIP','ID_UPDATE',assetId);
        LoggingUtility.log(logName,'Body => ' + body);
	 	HttpResponse res 	= new HttpResponse();
	 	HttpRequest req 	= new HttpRequest();
        Http http 			= new Http();
        
	 	req.setEndpoint(intConfig.EndPoint__c+'trackings');
        req.setMethod('POST');
        req.setHeader('aftership-api-key',intConfig.AuthenticationToken__c);
        req.setHeader('Content-Type','application/json');
        req.setBody(body);
        LoggingUtility.captureTimeStamp(logName,'BEGIN');
        res = http.send(req);
        LoggingUtility.captureTimeStamp(logName,'END');
        LoggingUtility.log(logName,'\nResponse status : ' + res.getStatusCode() + '\nResponse => ' + res.getBody());
        return res;
	 }
	 
	 private static void parseResponse(HttpResponse res,String trackingNumber,
	 									Map<String,List<Shipment_Order__c>> trackingNumberVsAssetsMap,List<Shipment_Order__c> assetsToBeUpdated,
	 									String logName){
	 	
	 	if(res.getStatusCode()!=201  )
	 		return;
	 	
        system.debug(res.getBody());
        JSONParser parser = JSON.createParser(res.getBody());
        while (parser.nextToken() != null) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'tracking') {
                system.debug(parser.getCurrentName());
                while (parser.nextToken() != null) {
                    system.debug(parser.getText());
                    ClsRestAssetUpdAfterShip.Tracker trk=  (ClsRestAssetUpdAfterShip.Tracker)parser.readValueAs(ClsRestAssetUpdAfterShip.Tracker.class);
                    system.debug(trk);
                    if(trk!=null){
                    	LoggingUtility.log(logName,'\nNumber of assets ' + trackingNumberVsAssetsMap.get(trackingNumber).size());
                    	// update the after ship Id on all the assets having same tracking number
                    	for(Shipment_Order__c so : trackingNumberVsAssetsMap.get(trackingNumber)){
                    		so.Aftership_ID__c			= trk.id;
                            so.status__c 				= trk.tag;
                            so.Last_Tracking_Update__c	= trk.updated_at;
                            if(trk.tag=='Exception'){
                               for(ClsRestAssetUpdAfterShip.CheckPoint ch:trk.checkpoints){
                                    if(ch.tag=='Exception'){
                                        so.Tracking_Exception__c=ch.message;
                                        so.tracking_active__c=false;
                                    }
                                }
                            }else{
                                so.tracking_active__c=true;
                            }
                            assetsToBeUpdated.add(so);
                    	}
                        break;
                    }
            	}
        	}
    	}    
        	
	 }
}