force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Record_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Shop</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Facility_Account.recordType-meta.xml
<RecordType>
    <fullName>Facility_Account</fullName>
    <active>true</active>
    <label>Facility Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/AddressDetail__c/AddressDetail__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADR-{0000000}</displayFormat>
        <label>Address Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AddressDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>AddressDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/AddressLine__c.field-meta.xml
<CustomField>
    <fullName>AddressLine__c</fullName>
    <label>XAL AddressLine</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>XAL CountryCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryDevName__c.field-meta.xml
<CustomField>
    <fullName>CountryDevName__c</fullName>
    <label>XAL CountryDevName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <label>XAL CountryName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/SignedGoogleMapsPathRequest__c.field-meta.xml
<CustomField>
    <fullName>SignedGoogleMapsPathRequest__c</fullName>
    <description>Signed Google Maps Static API url path and request based on lat/lng of the inserted address. More info here https://developers.google.com/maps/documentation/static-maps/get-api-key#generating_valid_signatures</description>
    <label>GPA SignedGoogleMapsPathRequest</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AddressDetail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billing Address</fullName>
            </value>
            <value>
                <fullName>Shipping Address</fullName>
            </value>
            <value>
                <fullName>Restaurant Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Config__c/Integration_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Config</label>
</CustomObject>

force-app/main/default/objects/Integration_Config__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country of Lead</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <label>Lead Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
                <default>true</default>
                <label>Branch</label>
            </value>
            <value>
                <fullName>Branch - Main</fullName>
            </value>
            <value>
                <fullName>Branch - Kitchen Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Record_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Shop</fullName>
            </value>
            <value>
                <fullName>Courier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/PY_Lead.recordType-meta.xml
<RecordType>
    <fullName>PY_Lead</fullName>
    <active>true</active>
    <businessProcess>PY Lead Process</businessProcess>
    <description>PedidosYa Lead Process</description>
    <label>PY Lead</label>
</RecordType>

force-app/main/default/objects/xAL_Country__mdt/xAL_Country__mdt.object-meta.xml
<CustomObject>
    <label>xAL Country</label>
    <pluralLabel>xAL Countries</pluralLabel>
</CustomObject>

force-app/main/default/objects/xAL_Country__mdt/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>ISO 3166-1 alpha-2 country code</description>
    <label>Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FacilityUtilityControllerTest.cls
/**
* @author Shivani
* @date 15.05.2020
*
* @description Test class for FacilityUtilityController
*/
@IsTest
public class FacilityUtilityControllerTest {
    static final String TESTCOUNTRY = 'Test_Scenario_Country';
	static final xAL_Country__mdt COUNTRY = [
	        SELECT DeveloperName, MasterLabel, Code__c
	        FROM xAL_Country__mdt
	        WHERE DeveloperName = :TESTCOUNTRY];

     /*******************************************************************************************************
    * @description SSC-2796 - dummy Record creation before actual test method to test various conditions
    */
    @testSetup static void setup() {
        UnitTestDataFactory.getRecordtypeValues();

        Integration_Config__c cs1 = new Integration_Config__c(
		Name = 'GoogleMapsSignature', Password__c = 'Abvcd-asdfdgfhjklhnO0=');
		insert cs1;
        //Inserting record for PY
        Country__c pYCoutry = UnitTestDataFactory.createCountry('CL','Chile', 'EUR');
        insert pYCoutry;
        insertBusinessConfig(pYCoutry);

        List<Lead> leadList = UnitTestDataFactory.createLeads(1, pYCoutry,'Test_Lead', 'Test Company', 'EUR', 'BCCORP', 'PY_Lead');
        insert leadList;
        Account pYaccount = UnitTestDataFactory.createAccount('TestPY',pYCoutry,'PY_Account');
        insert pYaccount;

        //Inserting record for FP
        Country__c cdFP = UnitTestDataFactory.createCountry('HK', 'Hong Kong', 'EUR');
        insert cdFP;

        Account fpAccount = UnitTestDataFactory.createAccount('TESTFP', cdFP, 'FP_Account');
        fpAccount.Vertical__c = 'Restaurant';
        fpAccount.phone = '+85212345678';
        fpAccount.Record_Country__c = 'Hong Kong';
        insert fpAccount;

        AddressDetail__c addr = new AddressDetail__c(
		    Type__c = 'Restaurant Address;Billing Address',
		    Account__c = pYaccount.Id,
		    LatLng__Latitude__s = 10.0,
		    LatLng__Longitude__s = 5.0,
		    AddressLine__c = 'amazing address',
		    CountryDevName__c = COUNTRY.DeveloperName,
		    CountryName__c = COUNTRY.MasterLabel,
		    CountryCode__c = COUNTRY.Code__c
		);

		insert addr;


    }

    /*******************************************************************************************************
    * @description SSC-2796 - testing FacilityUtilityController for value assignment to Facility Business config wrapper
    */
    @IsTest
    public static void testFacilityUtilityControllerConstructorPositiveCase() {
        Lead leadRecord = [SELECT Id,RecordTypeId FROM Lead where LastName ='Test_Lead'];
        FacilityUtilityController facilityCont;
        ApexPages.StandardController sc = new ApexPages.StandardController(leadRecord);
        Test.startTest();
        facilityCont = new FacilityUtilityController(sc);
        Test.stopTest();

        System.assert(facilityCont.wrpForFacilityValidation != null,'Facility Config Wrapper value does not exist in Business cofig FOr PY');
        System.assert(facilityCont.wrpForFacilityValidation.CondLabels != null,'Conditional Label does not exist in Facility Config Wrapper  FOr PY');
        System.assert(facilityCont.wrpForFacilityValidation.RecTypes != null,'RecTypes does not exist in Facility Config Wrapper  FOr PY');
        System.assert(facilityCont.wrpForFacilityValidation.ErrMessages != null,'errMessages does not exist in Facility Config Wrapper  FOr PY');
        System.assertEquals('Restaurant Address',facilityCont.wrpForFacilityValidation.CondLabels.restaurantAddressType);
        System.assertEquals('Branch - Kitchen Restaurant',facilityCont.wrpForFacilityValidation.CondLabels.branchKitchenRestaurantAccountType);
        System.assertEquals('PY_Account',facilityCont.wrpForFacilityValidation.RecTypes.accRecordType);
        System.assertEquals('Facility_Account',facilityCont.wrpForFacilityValidation.RecTypes.facilityRecordType);
        System.assertNotEquals(null,facilityCont.wrpForFacilityValidation.ErrMessages.kitchenRestaurantFacilityValidationMessage);
        System.assertNotEquals(null,facilityCont.wrpForFacilityValidation.ErrMessages.errorValidationOnAddressForm);
        System.assertNotEquals(null,facilityCont.wrpForFacilityValidation.ErrMessages.errorAddressMessageForRestaurant);

    }
     /*******************************************************************************************************
    * @description SSC-2796 - testing FacilityUtilityController for Account Clone extension for different region
    */
    @IsTest
    public static void testFacilityUtilityControllerConstDifferentRegion() {
        Account fpAccount = [SELECT Id,RecordTypeId FROM Account where name ='TESTFP'];
        FacilityUtilityController facilityCont;
        ApexPages.StandardController sc = new ApexPages.StandardController(fpAccount);
        Test.startTest();
        facilityCont = new FacilityUtilityController(sc);
        Test.stopTest();
        System.assert(facilityCont.wrpForFacilityValidation != null,'Facility Config Wrapper value does not exist in Business cofig For FP' );
        System.assert(facilityCont.wrpForFacilityValidation.CondLabels == null,'CondLabels Wrapper value exists in Business cofig For FP');
    }

     /*******************************************************************************************************
    * @description SSC-2796 - testing FacilityUtilityController for Empty Extension
    */
    @IsTest
    public static void testFacilityUtilityControllerConstNegativeCase() {
        Account accRecrod = new Account();
        FacilityUtilityController facilityCont;
        ApexPages.StandardController sc = new ApexPages.StandardController(accRecrod);
        Test.StartTest();
        facilityCont = new FacilityUtilityController(sc);
        Test.stopTest();
        System.assert(facilityCont.wrpForFacilityValidation.CondLabels == null,'Facility Config Wrapper value exists in Business cofig empty record instance');
        System.assert(facilityCont.wrpForFacilityValidation.RecTypes == null,'Facility Config Wrapper value exists in Business cofig empty record instance');
        System.assert(facilityCont.wrpForFacilityValidation.ErrMessages == null,'Facility Config Wrapper value exists in Business cofig empty record instance');
        System.assert(facilityCont.wrpForFacilityValidation.AddModels == null,'Facility Config Wrapper value exists in Business cofig empty record instance');

    }

     /*******************************************************************************************************
    * @description SSC-2796 - testing FacilityUtilityController for adddress Details page
    */
    @IsTest
    public static void testFacilityUtilityControllerConstAddressDetails() {
        Account fpAccount = [SELECT Id,RecordTypeId FROM Account where name ='TestPY'];
        AddressDetail__c addDetail = [SELECT SignedGoogleMapsPathRequest__c,Account__c
                                      FROM AddressDetail__c
                                      WHERE Account__c =:fpAccount.Id];
        FacilityUtilityController facilityCont;
        ApexPages.StandardController sc = new ApexPages.StandardController(addDetail);
        Test.StartTest();
        facilityCont = new FacilityUtilityController(sc);
        Test.stopTest();
        System.assert(facilityCont.wrpForFacilityValidation.CondLabels != null,'Facility Config Wrapper cond lable values does not exist');
        System.assert(facilityCont.wrpForFacilityValidation.AddModels != null,'Facility Config Wrapper Address values does not exist');
        System.assertEquals('Egypt,Argentina,Chile,Bolivia',facilityCont.wrpForFacilityValidation.AddModels.xalNewCountries);
        System.assertEquals('Panamá,Paraguay',facilityCont.wrpForFacilityValidation.AddModels.xalCountries);
        System.assertEquals('Uruguay,Dominican Republic',facilityCont.wrpForFacilityValidation.AddModels.gpaCountries);
        System.assertEquals('',facilityCont.wrpForFacilityValidation.AddModels.daumCountries);
        System.assertNotEquals(null,facilityCont.wrpForFacilityValidation.ErrMessages.errorAddressMessageForKitchen);
        System.assertNotEquals(null,facilityCont.wrpForFacilityValidation.ErrMessages.typeFieldRequired);

    }

    /*******************************************************************************************************
    * @description SSC-2796- inserting business config for Facility
    * @param pYCoutry the country for which business config record will be inserted
    */
    public static void insertBusinessConfig(Country__c pYCoutry){
        String json = '{'+
		' \"CondLabels\" : {'+
		' \"restaurantAddressType\" : \"Restaurant Address\", '+
		' \"branchKitchenRestaurantAccountType\" : \"Branch - Kitchen Restaurant\" '+
		' },'+
		'\"RecTypes\" : { '+
		'	\"accRecordType\" : \"PY_Account\",'+
		'	\"facilityRecordType\" : \"Facility_Account\" '+
		'	},'+
		' \"ErrMessages\": { '+
		'	\"errorAddressMessageForKitchen\" : \"You cannot select Restaurant Address as Address type for Branch Kitchen. Please remove Restaurant Address.\", '+
		'	\"typeFieldRequired\" : \"Please select a value in Type field\" ,'+
		'	\"kitchenRestaurantFacilityValidationMessage\" : \"Please connect this Kitchen Restaurant to the Facility that it is located in before you proceed.\", '+
		'	\"errorValidationOnAddressForm\" : \"Please review errors in the form\" ,'+
		'	\"errorAddressMessageForRestaurant\" : \"You cannot change the Restaurant Address as Address type for Branch Kitchen.\"'+
		'	},'+
        ' \"AddModels\": { '+
		'	\"xalNewCountries\" : \"Egypt,Argentina,Chile,Bolivia\", '+
		'	\"xalCountries\" : \"Panamá,Paraguay\" ,'+
		'	\"gpaCountries\" : \"Uruguay,Dominican Republic\", '+
		'	\"daumCountries\" : \"\"'+
		'	}'+
		'}';

        //inserting business config record to
        Business_Config__c busConf = new Business_Config__c(Business_Rule_Name__c='checkParameters',Business_Rule_Value__c=json,Id_Country__c=pYCoutry.Id,Is_Active__c=true,Parent__c=true,Process_Name__c='LeadConversionAndAccountCloneFacilityCheck',Record_Type_Id__c='PY_Lead,PY_Account',Type__c='Process');
        insert busConf;
    }
}