force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Restaurant</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <description>SP-4411</description>
    <label>Account Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Installation</fullName>
                <default>true</default>
                <label>New - Awaiting Installation</label>
            </value>
            <value>
                <fullName>Installed successfully</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Uninstalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Design rejected</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Pending design approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trigger_Manager__c/Trigger_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Manager</label>
</CustomObject>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_Asset_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Asset_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Asset Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_Branding_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Branding_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Branding Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountCountryRemediation_Batch.cls
/**
* @author Mantas Jurkunas
* @date 13.11.2019
*
* @description Batch class that copies the account country field from Account to Asset and Branding objects.
*/

public without sharing class AccountCountryRemediation_Batch implements Database.Batchable<SObject>, Database.Stateful {

    private String objectQuery;
    private String accountField;
    private Integer errorCount;


    public static void run(Type objectType) {
        Database.executeBatch(new AccountCountryRemediation_Batch(objectType));
    }

    private AccountCountryRemediation_Batch(Type objectType) {
        if (objectType == Asset__c.class) {
            accountField = 'Account__r.Record_Country__c';
            objectQuery = 'SELECT Id, Status__c, Account__c, Account_Country__c, Account__r.Record_Country__c FROM Asset__c WHERE Account_Country__c = NULL AND Account__r.Record_Country__c != NULL';
        } else if (objectType == Branding_Content__c.class) {
            accountField = 'Restaurant_Name__r.Record_Country__c';
            objectQuery = 'SELECT Id, Status__c, Restaurant_Name__c, Account_Country__c, Restaurant_Name__r.Record_Country__c FROM Branding_Content__c WHERE Account_Country__c = NULL AND Restaurant_Name__r.Record_Country__c != NULL';
        } else {
            throw new AccountCountryRemediation_BatchException('Object Type not supported');
        }
        errorCount = 0;
    }

    public void execute(Database.BatchableContext param1, List<SObject> objects) {
        for (SObject obj: objects) {
            obj.put('Account_Country__c', ClsSObjectUtils.getFieldValue(obj, accountField));
        }
        List<Database.SaveResult> saveResults = Database.update(objects, false);

        System.debug('------------ Update Errors -------------');
        for ( Database.SaveResult saveRes: saveResults) {
            if (saveRes.getErrors().isEmpty()) {
                continue;
            }
            System.debug(saveRes.getErrors());
        }
        errorCount += saveResults.size();
    }

    public void finish(Database.BatchableContext param1) {
        toggleTriggers(false);
        System.debug('------------ Total Errors: ' + errorCount + ' -------------');
    }

    public Iterable<SObject> start(Database.BatchableContext param1) {
        toggleTriggers(true);
        return Database.query(objectQuery);
    }

    private void toggleTriggers(Boolean isDisabled) {
        Trigger_Manager__c manager = Trigger_Manager__c.getInstance();
        manager.Deactivate_Branding_Trigger__c = isDisabled;
        manager.Deactivate_Asset_Trigger__c = isDisabled;
        upsert manager;
    }

    public class AccountCountryRemediation_BatchException extends Exception {}

}