force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FP_Account.recordType-meta.xml
<RecordType>
    <fullName>FP_Account</fullName>
    <active>true</active>
    <label>FP Account</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Restaurant</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment Order</label>
    <referenceTo>Shipment_Order__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Shipping_Company__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Company__c</fullName>
    <description>The Company responsible for delivering the Asset to the restaurant.</description>
    <inlineHelpText>The Company responsible for delivering the Asset to the restaurant.</inlineHelpText>
    <label>Shipping Company</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AUS Post</fullName>
            </value>
            <value>
                <fullName>DH Staff</fullName>
            </value>
            <value>
                <fullName>DHL</fullName>
            </value>
            <value>
                <fullName>Fastway</fullName>
            </value>
            <value>
                <fullName>Epost</fullName>
            </value>
            <value>
                <fullName>Cvsnet</fullName>
            </value>
            <value>
                <fullName>Field Agent</fullName>
            </value>
            <value>
                <fullName>Sherpa</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>Servientrega</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Tracking_Active__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tracking Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>The tracking number given by the shipping company</description>
    <inlineHelpText>The tracking number given by the shipping company</inlineHelpText>
    <label>Tracking Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>The role the contact plays in the restaurant</description>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Owner</fullName>
            </value>
            <value>
                <fullName>Co-owner</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Franchise Contact</fullName>
            </value>
            <value>
                <fullName>Former Owner</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Previous Owner</fullName>
            </value>
            <value>
                <fullName>Ex-employee</fullName>
            </value>
            <value>
                <fullName>Billing Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
                <label>duplicate</label>
            </value>
            <value>
                <fullName>Additional Contact</fullName>
                <label>additional contact</label>
            </value>
            <value>
                <fullName>Restaurant Operations</fullName>
            </value>
            <value>
                <fullName>Customer Contact</fullName>
            </value>
            <value>
                <fullName>Landlord</fullName>
            </value>
            <value>
                <fullName>Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country on related Account</description>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <inlineHelpText>Country on related Account</inlineHelpText>
    <label>Contact Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/FP_Contact.recordType-meta.xml
<RecordType>
    <fullName>FP_Contact</fullName>
    <active>true</active>
    <label>FP Contact</label>
</RecordType>

force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to display current status of Shipment Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Tracking_Active__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field necessary for Aftership integration to continue tracking returning shipment</description>
    <label>Tracking Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnitTestSchedulerBatchCreateTrackingId.cls
@isTest
private class UnitTestSchedulerBatchCreateTrackingId {

public static String CRON_EXP = '0 0 0 15 3 ? 2022';
     private static Account accounts;
     private static Country__c country;
     private static Map<String,RecordType> mapRecordTypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String>{'Account','Contact','Asset__C'});
    
	
	@testSetup 
	public static void testSetup(){
	country = UnitTestDataFactory.createCountry('FP', 'Malaysia', 'MYR');
        Company__c com = UnitTestDataFactory.createCompany('FP', 'FP', country);
        insert new List<sObject> {country,com};
        UnitTestDataFactory.getRecordtypeValues();
        accounts = UnitTestDataFactory.createAccount('TestAccount', country, 'FP_Account');
        accounts.Record_Country__c = 'Malaysia';
        accounts.phone = '+6012345678';
        insert accounts;
        Contact cn = new Contact(lastname='test',
                               contact_role__c='Owner',
                               accountid=accounts.id, 
                               email='test@test.com', 
                                mobilephone='+6012345678',
                                recordtypeid=mapRecordTypes.get('FP_Contact').id);

        Shipment_Order__c ast1= new Shipment_Order__c(tracking_number__c='73658',
                                   status__c='Shipped',
                                   Account__c=accounts.id,
                                   tracking_active__c=false,
                                        Shipping_Company__c = 'ninjavan-my');

        Shipment_Order__c ast2= new Shipment_Order__c(tracking_number__c='73658',
                                   status__c='Shipped',
                                   Account__c=accounts.id,
                                   tracking_active__c=false,
                                       Shipping_Company__c = 'ninjavan-my');

        Shipment_Order__c ast3= new Shipment_Order__c(tracking_number__c='73658',
                                   status__c='Shipped',
                                   AfterShip_ID__c='123',
                                   tracking_active__c=true,
                                   Account__c=accounts.id,
                                      Shipping_Company__c = 'ninjavan-my');

        Shipment_Order__c ast4= new Shipment_Order__c(tracking_number__c='73658',
                                   status__c='Shipped',
                                   AfterShip_ID__c='123',
                                   tracking_active__c=true,
                                   Account__c=accounts.id,
                                       Shipping_Company__c = 'ninjavan-my');
        insert new List<sObject> {cn,ast1,ast2,ast3,ast4};
	}
	
    static testMethod void testBatch(){
    	Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());

        List<Integration_Config__c> intconfig=new List<Integration_Config__c>();
        intconfig.add(new Integration_Config__c(name='AfterShip',EndPoint__c='https://aftership.com/',AuthenticationToken__c='testtest',Countries__c = 'Malaysia'));

        insert intconfig;
        Test.startTest();

         	Database.executeBatch(new BatchCreateTrackingIdOnAfterShip());

        Test.stopTest();
    	
    	// verify that 4 assets have after ship id now
        List<Shipment_Order__c> shipmentOrders = [Select Id from Shipment_Order__c where AfterShip_ID__c != null];
        System.assertEquals(4,shipmentOrders.size());
        
        // verify that 2 assets have same after ship id now
        shipmentOrders = [Select Id from Shipment_Order__c where AfterShip_Id__c != '123'];
        System.assertEquals(2,shipmentOrders.size());
    }

    static testmethod void test() {
        Test.setMock(HttpCalloutMock.class, new UnitTestMockWebservice());

        List<Integration_Config__c> intconfig=new List<Integration_Config__c>();
        intconfig.add(new Integration_Config__c(name='AfterShip',EndPoint__c='https://aftership.com/',AuthenticationToken__c='testtest'));

        insert intconfig;
        Test.startTest();

          // Schedule the test job
        String jobId = System.schedule('ScheduleApexClassTest',
                            CRON_EXP,
                            new SchedulerBatchCreateTrackingId());

          // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered,
             NextFireTime
             FROM CronTrigger WHERE id = :jobId];

          // Verify the expressions are the same
        System.assertEquals(CRON_EXP,
        ct.CronExpression);

        Test.stopTest();
   }

    static testmethod void testClsRestAssetUpdAfetrship(){
        RestRequest req = new RestRequest();
        req.requestBody=Blob.valueof('{"meta":{"code":201},"msg":{"id":"123","tracking_ship_date":"2014-06-25","updated_at":"2014-06-25T09:23:08+00:00","expected_delivery":"2014-06-25T09:23:08+00:00","tracking_number":"73658","tag":"Exception","checkpoints":[{"tag":"Exception","message":"83dhu"}]}}');
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/UpdateShippingStatus';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        ClsRestShippingOrderUpdAftership.updateShippingStatus();
        test.stoptest();
		Date dt = Date.newInstance(2014,06,25);
		List<Shipment_Order__c> shipmentOrders = [Select Id from shipment_order__c where date_shipped__c = :dt];
		System.assertEquals(2,shipmentOrders.size());
    }
}