force-app/main/default/objects/Account/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <description>Country drop-down that will be automatically set if the user belongs to a single country. If not the user will be required to select a country from this drop-down. The page layout will be used to control the visibility of this drop-down</description>
    <label>Account Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Turtle</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Qatar</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Panamá</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
            <value>
                <fullName>Uruguay</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PY_Account.recordType-meta.xml
<RecordType>
    <fullName>PY_Account</fullName>
    <active>true</active>
    <label>PY Account</label>
</RecordType>

force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity relating to this Asset</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stock Item currently assigned to this Asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New from manufacturer, A1 - New used, B - Used few scratches, A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/N</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Yogiyo Stock Item, FI Stock Item, SE Stock Item</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>DH AU Asset</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Ordered, New - In Stock, Assigned, In Shipping, Delivered, Retour in Progress, Lost, Returned - at Manufacturer, Recycled, Damaged, Writeoff, Tested, Returned - In Stock, Awaiting Delivery/In Shipment, In Stock, Technical Issue, Exchange Requested, Takeov</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/No longer usable</value>
        </filterItems>
        <infoMessage>In stock devices</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Asset Assignment</relationshipLabel>
    <relationshipName>Asset_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/PY_Asset.recordType-meta.xml
<RecordType>
    <fullName>PY_Asset</fullName>
    <active>true</active>
    <description>Record Type For PedidosYa but to be applied globally in future</description>
    <label>PY_Asset</label>
</RecordType>

force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <description>SP-4411</description>
    <label>Account Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Item</label>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Branding &amp; Promotions</relationshipLabel>
    <relationshipName>Branding_Promotions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Yogiyo_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Sales Proccess</businessProcess>
    <description>KR Opportunity Recordtype</description>
    <label>Yogiyo Opportunity</label>
</RecordType>

force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <description>Items that were or are are held in stock</description>
    <label>Stock Item</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <label>Account Country</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <label>Restaurant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/recordTypes/Yogiyo_Stock_Item.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Stock_Item</fullName>
    <active>true</active>
    <description>Yogiyo Stock Items</description>
    <label>Yogiyo Stock Item</label>
</RecordType>

force-app/main/default/objects/Trigger_Manager__c/Trigger_Manager__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Manager</label>
</CustomObject>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_Asset_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Asset_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Asset Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Manager__c/fields/Deactivate_Branding_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_Branding_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate Branding Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountCountryRemediation_Test.cls
/**
* @author Mantas Jurkunas
* @date 13.11.2019
*
* @description Test class for the AccountCountryRemediation_Batch class
*/

@IsTest
private class AccountCountryRemediation_Test {

    @TestSetup
    static void setup() {
        UnitTestDataFactory.getRecordtypeValues();
        Trigger_Manager__c manager = Trigger_Manager__c.getInstance();
        manager.Deactivate_Asset_Trigger__c = true;
        manager.Deactivate_Branding_Trigger__c = true;
        upsert manager;
        Country__c c = UnitTestDataFactory.createCountry('UY', 'Uruguay', 'KWD');
        Country__c c2 = UnitTestDataFactory.createCountry('CL', 'Chile', 'KWD');
        insert new List<Country__c> {c, c2};
        Company__c com = UnitTestDataFactory.createCompany('PY', 'PY', c );
        Company__c com2 = UnitTestDataFactory.createCompany('PY', 'PY', c2 );
        insert new List<Company__c>{com, com2};
        Account pyAccount  = UnitTestDataFactory.createAccount('TestAccount', c, 'PY_Account');
        pyAccount.Record_Country__c = 'Uruguay';
        insert pyAccount;
        List<Opportunity> oppList = UnitTestDataFactory.createOpportunities(new List<Account>{pyAccount}, 1, 'Yogiyo_Opportunity', Date.today());
        insert oppList;
        List<Stock_Item__c> stockItems = UnitTestDataFactory.createStockItems(4, 'Yogiyo_Stock_Item', pyAccount, null, 'A1 - New used', Date.today(), Date.today().addDays(10), Date.today().addDays(-30), '1234567890', '1234567890', 'Korea Telekom', 'In Stock', 'Other');
        insert stockItems;
        Branding_Content__c bContent = new Branding_Content__c(Restaurant_Name__c = pyAccount.Id, Opportunity__c = oppList[0].Id);
        insert bContent;
        List<Asset__c> assets = UnitTestDataFactory.createAssets(10, pyAccount, oppList[0], Date.today().addDays(-10), true, stockItems[0], stockItems[1], 'PY_Asset', '12345674',
                '1', '1', Date.today(), Date.today(), 'En Route', true, 'Exchanged', 'Shared Information', 'Take over Information', 'Exchange Requested',
                Date.today().addDays(20), 'Yazi Logistics', '1234', 'none');
        insert assets;

    }


    @IsTest
    static void test_BrandingCountryUpdate() {
        Account pyAccount = AccountSelector.getAll()[0];
        Branding_Content__c bContent = BrandingContent_Selector.findByAccountIds(new Set<Id> {pyAccount.Id})[0];

        System.assertNotEquals(pyAccount.Record_Country__c, bContent.Account_Country__c);

        Test.startTest();
            AccountCountryRemediation_Batch.run(Branding_Content__c.class);
        Test.stopTest();

        bContent = BrandingContent_Selector.findByAccountIds(new Set<Id> {pyAccount.Id})[0];

        System.assertEquals(pyAccount.Record_Country__c, bContent.Account_Country__c);
    }

    @IsTest
    static void test_AssetCountryUpdate() {
        Account pyAccount = AccountSelector.getAll()[0];
        List<Asset__c> assets = AssetSelector.findActiveByAccountIds(new Set<Id> {pyAccount.Id});

        for (Asset__c asset: assets) {
            System.assertNotEquals(pyAccount.Record_Country__c, asset.Account_Country__c);
        }

        Test.startTest();
            AccountCountryRemediation_Batch.run(Asset__c.class);
        Test.stopTest();

        assets = AssetSelector.findActiveByAccountIds(new Set<Id> {pyAccount.Id});

        for (Asset__c asset: assets) {
            System.assertEquals(pyAccount.Record_Country__c, asset.Account_Country__c);
        }
    }
}