force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/UK_Account.recordType-meta.xml
<RecordType>
    <fullName>UK_Account</fullName>
    <active>true</active>
    <label>UK Account</label>
</RecordType>

force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <description>Lease End date</description>
    <label>End-date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Installation</fullName>
                <default>true</default>
                <label>New - Awaiting Installation</label>
            </value>
            <value>
                <fullName>Installed successfully</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Uninstalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Design rejected</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Pending design approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Termination_Reason__c</fullName>
    <label>Termination Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Cannot Contact</fullName>
            </value>
            <value>
                <fullName>Capacity - Competitors</fullName>
            </value>
            <value>
                <fullName>Capacity - Driver Issue</fullName>
            </value>
            <value>
                <fullName>Capacity - Order Volume</fullName>
            </value>
            <value>
                <fullName>Capacity - Own Website</fullName>
            </value>
            <value>
                <fullName>DH Delivery</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Legal Issue</fullName>
            </value>
            <value>
                <fullName>Logistics Issue</fullName>
            </value>
            <value>
                <fullName>Lost to Competition</fullName>
            </value>
            <value>
                <fullName>New Owner - New Contract</fullName>
            </value>
            <value>
                <fullName>New Owner - No New Contract</fullName>
            </value>
            <value>
                <fullName>No Delivery Service</fullName>
            </value>
            <value>
                <fullName>Not Enough Orders</fullName>
            </value>
            <value>
                <fullName>Not Interested in Product</fullName>
            </value>
            <value>
                <fullName>Onboarding Failure</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment Issue</fullName>
            </value>
            <value>
                <fullName>Poor Performance</fullName>
            </value>
            <value>
                <fullName>Pricing - Admin Fee</fullName>
                <label>Pricing - Admin fee</label>
            </value>
            <value>
                <fullName>Pricing - Commission</fullName>
            </value>
            <value>
                <fullName>Pricing - Merchant Fee</fullName>
                <label>Pricing - Merchant fee</label>
            </value>
            <value>
                <fullName>Pricing - Premium Placement</fullName>
            </value>
            <value>
                <fullName>Pricing - Setup Fee</fullName>
            </value>
            <value>
                <fullName>Product Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branding_Content__c/recordTypes/UK_Branding_Content.recordType-meta.xml
<RecordType>
    <fullName>UK_Branding_Content</fullName>
    <active>true</active>
    <label>UK Branding Content</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/UnitTestBatchTerminateBrandingContent.cls
@isTest
public class UnitTestBatchTerminateBrandingContent {
    
    @testSetup static void setup() {
		Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Branding_Content__c'});
		UnitTestDataFactory.getRecordtypeValues();

		Country__c uk = UnitTestDataFactory.createCountry('UK', 'United Kingdom', 'GBP');
		insert new List<Country__c> {uk};

		Business_Config__c b1 = UnitTestDataFactory.createBusinessConfig('BatchBrandingContentTermination', 'Process', 'terminateBradningContent', 'true', uk.id, 'UK_Branding_Content', true, true);
		Business_Config__c b2 = UnitTestDataFactory.createBusinessConfig('BatchBrandingContentTermination', 'Process', 'expiredStatus', 'Expired', uk.id, 'UK_Branding_Content', true, false);
		Business_Config__c b3 = UnitTestDataFactory.createBusinessConfig('BatchBrandingContentTermination', 'Process', 'terminationStatus', 'Terminated', uk.id, 'UK_Branding_Content', true, false);
		insert new List<sObject> {b1, b2, b3};

		Account acc1 = UnitTestDataFactory.createAccount('BatchTestClassAccount1', uk, 'UK_Account');
		insert new List<Account> {acc1};

		insert new Branding_Content__c(
		    Restaurant_Name__c 	= acc1.Id,
		    RecordTypeId 		= mapRecordtypes.get('UK_Branding_Content').Id,
		    End_Date__c 		= Date.today(),
		    status__c			= 'Installed successfully'
		);

	}
	
	@isTest
	public static void testExpiredStatus(){
		Test.startTest();
			Database.executeBatch(new BatchTerminateBrandingContent());
		Test.stopTest();
		
		Branding_Content__c bc = [Select Status__c from Branding_Content__c];
		
		System.assertEquals('Expired',bc.status__c);
	}
	
	@isTest
	public static void testTerminatedStatus(){
		Branding_Content__c bc 	= [Select Termination_Reason__c from Branding_Content__c];
		bc.Termination_Reason__c = 'test';
		update bc;
		
		Test.startTest();
			Database.executeBatch(new BatchTerminateBrandingContent());
		Test.stopTest();
		
		bc = [Select Status__c from Branding_Content__c];
		
		System.assertEquals('Terminated',bc.status__c);
	}
	
	@isTest static void testScheduleBatchTerminateBrandingContent() {
		Id jobId;

		Test.startTest();
			jobId = System.schedule('test job', '0 0 0 * * ?', new ScheduleBatchTerminateBrandingContent());
		Test.stopTest();

		CronTrigger[] jobs = [Select Id from CronTrigger Where Id = : jobId];

		System.assert(!jobs.isEmpty());

	}
	
	@isTest static void testNoBusinessConfigs(){
		Delete [Select Id from Business_Config__c];
		
		Test.startTest();
			Database.executeBatch(new BatchTerminateBrandingContent());
		Test.stopTest();
		
		Branding_Content__c bc = [Select Status__c from Branding_Content__c];
		
		System.assertNotEquals('Expired',bc.status__c);
		System.assertNotEquals('Terminated',bc.status__c);		
	}
	
	@isTest static void testDisbaledBusinessConfig(){
		Business_Config__c b = [Select Business_Rule_Value__c From Business_Config__c Where Business_Rule_Name__c = 'terminateBradningContent'];
		b.Business_Rule_Value__c = 'false';
		update b;
		
		Test.startTest();
			Database.executeBatch(new BatchTerminateBrandingContent());
		Test.stopTest();
		
		Branding_Content__c bc = [Select Status__c from Branding_Content__c];
		
		System.assertNotEquals('Expired',bc.status__c);
		System.assertNotEquals('Terminated',bc.status__c);	
	}
	
	
}