force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CD_Account.recordType-meta.xml
<RecordType>
    <fullName>CD_Account</fullName>
    <active>true</active>
    <description>Account for Click Delivery</description>
    <label>CD Account</label>
</RecordType>

force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>List_Product_Price__c.Requires_Branding__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>List_Product_Price__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/recordTypes/CD_Branding_Content.recordType-meta.xml
<RecordType>
    <fullName>CD_Branding_Content</fullName>
    <active>true</active>
    <label>CD Branding Content</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/CD_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>CD_List_Product_Group</fullName>
    <active>true</active>
    <label>CD List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Branding__c.field-meta.xml
<CustomField>
    <fullName>Requires_Branding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Branding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/CD_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>CD_List_Product_Price</fullName>
    <active>true</active>
    <label>CD List Product Price</label>
</RecordType>

force-app/main/default/classes/UnitTestCtrBrandingContentScreenEdit.cls
@isTest
private class UnitTestCtrBrandingContentScreenEdit {

	@testSetup static void setup() {
		UnitTestDataFactory.getRecordtypeValues();

		Country__c c = UnitTestDataFactory.createCountry('EC', 'Ecuador', 'USD');
		insert c;
		
		Company__c com = UnitTestDataFactory.createCompany('CD', 'CD', c);
		insert com;
		
		Account a = UnitTestDataFactory.createAccount('test', c, 'CD_Account');
		insert a;
		
		// create product Gruop
		List_Product_Group__c grp = UnitTestDataFactory.createProductGroup(com,c,'test', 'CD_List_Product_Group');
		insert grp;
		
		List<List_product_price__c> product = UnitTestDataFactory.createProducts(com, c,grp.Id,1, 'CD_List_Product_Price',0, true, 100.00, 1, false, 10);
		product[0].Requires_Branding__c = true;
		insert product;

		Branding_Content__c bc = new Branding_Content__c(Restaurant_Name__c = a.id,
		        OwnerId = UserInfo.getUserId(),
		        RecordTypeId = [Select id from recordType where DeveloperName = 'CD_Branding_Content'].Id);
		bc.product__c = product[0].Id;
		insert bc;
	}

	@isTest static void CtrBrandingContentScreenOnEditSetCorrectlyrecordTypeDevName() {
		Branding_Content__c bc = [Select id, RecordTypeId, OwnerId from Branding_Content__c limit 1];

		PageReference pref = Page.BrandingContentScreenEdit;
		pref.getParameters().put('id', bc.Id);

		Test.startTest();
		Test.setCurrentPage(pref);

		ApexPages.StandardController std = new ApexPages.StandardController(bc);
		CtrBrandingContentScreenEdit ctr = new CtrBrandingContentScreenEdit(std);

		Test.stopTest();

		System.assertEquals('CD_Branding_Content', ctr.recordTypeDevName);
	}

	@isTest static void CtrBrandingContentScreenEditOnNewSetCorrectlyRecordTypeDevName() {
		Branding_Content__c bc = new Branding_Content__c();

		PageReference pref = Page.BrandingContentScreenEdit;

		Test.startTest();
		Test.setCurrentPage(pref);

		ApexPages.StandardController std = new ApexPages.StandardController(bc);
		CtrBrandingContentScreenEdit ctr = new CtrBrandingContentScreenEdit(std);

		Test.stopTest();

		System.assert(String.isNotBlank(ctr.recordTypeDevName));
	}

}