force-app/main/default/objects/Account/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <description>this holds the name of the restaurant not the legal name of the company</description>
    <label>Restaurant Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Installation</fullName>
                <default>true</default>
                <label>New - Awaiting Installation</label>
            </value>
            <value>
                <fullName>Installed successfully</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Uninstalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Design rejected</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Pending design approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Apron</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Blade sign</fullName>
            </value>
            <value>
                <fullName>Flagship Store</fullName>
            </value>
            <value>
                <fullName>Hats/Caps</fullName>
            </value>
            <value>
                <fullName>Heating Bag</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Menu holder</fullName>
            </value>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Notepads/Pens</fullName>
            </value>
            <value>
                <fullName>Open and closed sign</fullName>
            </value>
            <value>
                <fullName>Other branded consumables</fullName>
            </value>
            <value>
                <fullName>Roofie</fullName>
            </value>
            <value>
                <fullName>Starter Package</fullName>
            </value>
            <value>
                <fullName>Sticker</fullName>
            </value>
            <value>
                <fullName>T-shirts</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BrandingContent_SelectorTest.cls
/**
 * Created by danish.farooq on 6/25/20.
 * @description Test class for BrandingContent_Selector
 */

@isTest
public  class BrandingContent_SelectorTest {

    @testSetup
    static void setup() {

        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountryMY = UnitTestDataFactory.createCountry('MY', Constants.COUNTRY_NAME_MALAYSIA, 'MYR');
        insert testCountryMY;

        Company__c testCompanyMY = UnitTestDataFactory.createCompany('FoodPanda', 'FoodPanda', testCountryMY);
        insert testCompanyMY;

        List<Account> fpAccount = UnitTestDataFactory.createAccounts(2, testCountryMY, Constants.FP_ACCOUNT_DEVELOPERNAME);
        fpAccount[0].phone = '+6012345678';
        fpAccount[1].phone = '+6012345678';
        insert fpAccount;

        List<Opportunity> fpOpportunity = UnitTestDataFactory.createOpportunities(fpAccount, 1, Constants.FP_OPPORTUNITY_DEVELOPERNAME, Date.today().addMonths(2));
        insert fpOpportunity;

        Branding_Content__c bContent = new Branding_Content__c(Restaurant_Name__c = fpAccount[0].Id, Opportunity__c = fpOpportunity[0].Id);
        bContent.Status__c = Constants.BRANDINGCONTENT_STATUS_INSTALLED_SUCCESSFULLY;
        bContent.Type__c = Constants.BRANDINGCONTENT_TYPE_WHITE_LABEL_APP;
        insert bContent;

    }

    @IsTest
    static void testBrandingSelector() {

        test.startTest();
        Opportunity opptyObj = Opportunity_Selector.getAll()[0];
        List<Branding_Content__c> lstBrandingContents = BrandingContent_Selector.findByAccountIds(new Set<Id>{ opptyObj.AccountId});
        system.assertEquals(1,lstBrandingContents.size());

        lstBrandingContents = BrandingContent_Selector.getBrandingByOpptyId(new Set<Id>{ opptyObj.Id}, Constants.BRANDINGCONTENT_TYPE_WHITE_LABEL_APP, new Set<string> {Constants.BRANDINGCONTENT_STATUS_INSTALLED_SUCCESSFULLY });
        system.assertEquals(1,lstBrandingContents.size());
        test.stopTest();
    }
}