force-app/main/default/objects/Account/fields/Revenue_Model__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Model__c</fullName>
    <label>Revenue Model</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ordering Platform</fullName>
            </value>
            <value>
                <fullName>Deal Subscription Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CD_Account.recordType-meta.xml
<RecordType>
    <fullName>CD_Account</fullName>
    <active>true</active>
    <description>Account for Click Delivery</description>
    <label>CD Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Talabat_Account.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Account</fullName>
    <active>true</active>
    <label>Talabat Account</label>
</RecordType>

force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>this hold the end date because the other end date is not writable</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity_Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity_Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity Quote Line Item</label>
    <referenceTo>Opportunity_Quote_Line_Item__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/recordTypes/CD_Contract.recordType-meta.xml
<RecordType>
    <fullName>CD_Contract</fullName>
    <active>true</active>
    <description>Contract for Click Delivery</description>
    <label>CD Contract</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/PY_Contract.recordType-meta.xml
<RecordType>
    <fullName>PY_Contract</fullName>
    <active>true</active>
    <label>PY Contract</label>
</RecordType>

force-app/main/default/objects/Contract/recordTypes/Talabat_Contract.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Contract</fullName>
    <active>true</active>
    <label>Talabat Contract</label>
</RecordType>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this service is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/recordTypes/Talabat_List_Service_Price.recordType-meta.xml
<RecordType>
    <fullName>Talabat_List_Service_Price</fullName>
    <active>true</active>
    <label>Talabat List Service Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Id_Tarif__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Tarif</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_DataLoaded__c.field-meta.xml
<CustomField>
    <fullName>Is_DataLoaded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this helps us not to trigger some triggers when it is true</description>
    <label>Is DataLoaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Migration_Notes_AU__c.field-meta.xml
<CustomField>
    <fullName>Migration_Notes_AU__c</fullName>
    <description>Notes for AU Opportunity Migration</description>
    <label>Migration Notes AU</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Setup_Fee_AU__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee_AU__c</fullName>
    <description>Setup Fee for AU, for migration only</description>
    <label>Setup Fee AU</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date_uk__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_uk__c</fullName>
    <description>For Migration Only</description>
    <inlineHelpText>Use field it the Start Date is NOT ASAP. Automatically populated via tariffs.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TarrifName_AU__c.field-meta.xml
<CustomField>
    <fullName>TarrifName_AU__c</fullName>
    <description>Tarrif Name for AU, for migration only</description>
    <label>TarrifName_AU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CD_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>CD_Opportunity</fullName>
    <active>true</active>
    <businessProcess>CD Sales Process</businessProcess>
    <description>Opportunity for Click Delivery</description>
    <label>CD Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Talabat_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Talabat Sales Process</businessProcess>
    <description>Talabat Opportunity</description>
    <label>Talabat Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_List_Service_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Service_Price__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Id List Service Price</label>
    <referenceTo>List_Service_Price__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/recordTypes/Talabat_Opportunity_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Line_Item</fullName>
    <active>true</active>
    <label>Talabat Opportunity Line Item</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Tarif__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Tarif</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_List_Service_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Service_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id List Service Price</label>
    <referenceTo>List_Service_Price__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Created&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/recordTypes/Talabat_Opportunity_Quote_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Quote_Line_Item</fullName>
    <active>true</active>
    <label>Talabat Opportunity Quote Line Item</label>
</RecordType>

force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which tariff is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Tariffs</relationshipLabel>
    <relationshipName>Tariffs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif__c/recordTypes/Talabat_Tarif.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Tarif</fullName>
    <active>true</active>
    <label>Talabat Tarif</label>
</RecordType>

force-app/main/default/classes/UnitTestBatchContractRenewal.cls
@isTest
private class UnitTestBatchContractRenewal {

    @testSetup static void setup() {
        Map<String, RecordType> mapRecordtypes = LibRecordTypeHelper.getRecordTypeForObjects(new Set<String> {'Opportunity', 'Contract'});
        UnitTestDataFactory.getRecordtypeValues();

        Country__c bh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        Country__c ec = UnitTestDataFactory.createCountry('EC', 'Ecuador', 'USD');
        insert new List<Country__c> {ec, bh};
        
        company__c com = UnitTestDataFactory.createCompany('Talabat', 'Talabat', bh);
            insert com;

        Business_Config__c b1 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'CountriesEnabledForAutoRenewal', 'Bahrain', bh.id, 'Talabat_Contract', true, true);
        Business_Config__c b2 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'RenewForNumberOfMonths', '12', bh.id, 'Talabat_Contract', true, false);
        Business_Config__c b3 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'expiredContractStatus', 'Expired', bh.id, 'Talabat_Contract', true, false);
        Business_Config__c b4 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'renewalContractStatus', 'Activated', bh.id, 'Talabat_Contract', true, false);
        Business_Config__c b5 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'updateExpiredContracts', 'true', bh.id, 'Talabat_Contract', true, false);

        Business_Config__c b6 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'expiredContractStatus', 'Expired', ec.id, 'CD_Contract', true, true);
        Business_Config__c b7 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'updateExpiredContracts', 'true', ec.id, 'CD_Contract', true, false);
        insert new List<sObject> {b1, b2, b3, b4, b5, b6, b7};

        Account acc1 = UnitTestDataFactory.createAccount('BatchTestClassAccount1', bh, 'Talabat_Account');
        Account acc2 = UnitTestDataFactory.createAccount('cd account', ec, 'CD_Account');
        insert new List<Account> {acc1, acc2};
        
        List_Service_Price__c lsp = UnitTestDataFactory.createService(com,bh,'testService1','Talabat_List_Service_Price',12,12,25,5,null,true,null,'Commission','ServiceType');
        insert lsp;
        Tarif__c t = UnitTestDataFactory.createTarif(com, bh , 'Free Tarif', 'Talabat_Tarif', false);
        insert t;

        // create business configs implemented for SSC-1982 : Tlife Commission
        List<Business_Config__c> configs = new List<Business_Config__c>();
        configs.add(UnitTestDataFactory.createBusinessConfig('TlifeRevenueModel','process', 'ContractServiceType','Deal Subscription Fee,Commission Fee,Logistics Fee', null,'Talabat_Contract',True,True));
        configs.add(UnitTestDataFactory.createBusinessConfig('TlifeRevenueModel','process', 'Commission Fee','Ordering Platform', null,'Talabat_Contract',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('TlifeRevenueModel','process', 'Deal Subscription Fee','Deal Subscription Service', null,'Talabat_Contract',True,false));
        configs.add(UnitTestDataFactory.createBusinessConfig('BatchContractRenewal','process', 'terminatedContractStatus','Terminated', null,'Talabat_Contract',True,false));
        insert configs;

        Country__c talabatCountry = UnitTestDataFactory.createCountry('AE', 'United Arab Emirates', 'AED');
        insert talabatCountry;

        Account talabatInstanceAccount = UnitTestDataFactory.createAccount('Talabat Account',talabatCountry,Constants.ACCOUNT_RT_TALABAT_ACCOUNT);
        talabatInstanceAccount.Revenue_Model__c = Constants.ACCOUNT_REVENUE_MODEL_ORDERING;
        insert talabatInstanceAccount;
        //SSC-1982 : Tlife Commission ends here


        Opportunity opp1 = new Opportunity(
            Setup_Fee_AU__c = 155,
            Start_Date_uk__c = Date.newInstance(2014, 12, 21),
            name = 'BatchTestOpp1',
            recordtypeid = mapRecordTypes.get('Talabat_Opportunity').id,
            AccountId = acc1.id,
            CloseDate = Date.newInstance(2014, 12, 21),
            StageName = 'Prospecting',
            TarrifName_AU__c = 'testTarif1',
            id_tarif__c=t.id,
            Is_DataLoaded__c = true,
            Migration_Notes_AU__c = 'Migration');

        Opportunity opp2 = new Opportunity(
            Setup_Fee_AU__c = 155,
            Start_Date_uk__c = Date.newInstance(2014, 12, 21),
            name = 'BatchTestOpp2',
            recordtypeid = mapRecordTypes.get('CD_Opportunity').id,
            AccountId = acc2.id,
            CloseDate = Date.newInstance(2014, 12, 21),
            StageName = 'Prospecting',
            TarrifName_AU__c = 'testTarif1',
                id_tarif__c=t.id,
        Is_DataLoaded__c = true,
            Migration_Notes_AU__c = 'Migration');
        insert new List<Opportunity> {opp1, opp2};
        
        
        Opportunity_Quote__c newQuote = new Opportunity_Quote__c(Id_Opportunity__c=opp1.id,status__c='Approved',ID_Account__c=acc1.id);
        insert newQuote;
       
        Opportunity_Line_Item__c oppService = UnitTestDataFactory.createOpportunityLineItemService('testService3',opp1,lsp.id,true,'Talabat_Opportunity_Line_Item',12,null,Date.today(),'Commission Fee',null);
        insert oppService;
        
        List<Opportunity_Quote_Line_Item__c> oppQuoteLine =  UnitTestDataFactory.createOpportunityQuoteLineItems(newQuote,1,False,'Talabat_Opportunity_Quote_Line_Item',12,1,True, 0, date.today(),'Commission Fee','Service');
        oppQuoteLine[0].id_opportunity__c=opp1.id;
        oppQuoteLine[0].id_list_service_price__c=lsp.id;
        insert oppQuoteLine ;
        newQuote.status__c='Accepted';
        update newQuote;

        Contract con1 = new Contract(name = 'test1',
                                     AccountId = acc1.id,
                                     Id_Opportunity__c = opp1.id,
                                     status = 'Draft',
                                     StartDate = Date.Today().addYears(-1),
                                     end_date__c = Date.Today().addDays(-1),
                                     id_opportunity_quote_line_item__c=oppQuoteLine[0].id,
                                     recordtypeid = mapRecordTypes.get('Talabat_Contract').id);
        Contract con2 = new Contract(name = 'test2',
                                     AccountId = acc2.id,
                                     Id_Opportunity__c = opp2.id,
                                     status = 'Draft',
                                     StartDate = Date.Today().addYears(-1),
                                     end_date__c = Date.Today().addDays(-1),
                                     recordtypeid = mapRecordTypes.get('CD_Contract').id);
        Contract con3 = new Contract(name = 'test2',
                                    AccountId = acc2.id,
                                    Id_Opportunity__c = opp2.id,
                                    status = 'Draft',
                                    StartDate = Date.Today(),
                                    end_date__c = Date.Today().addDays(20),
                                    recordtypeid = mapRecordTypes.get('PY_Contract').id);
        insert new List<Contract> {con1, con2, con3};

        con1.Status = 'Activated';
        con2.Status = 'Activated';
        update new List<Contract> {con1, con2};
    }

    @isTest static void batchContractRenewalDoesNothingIfNoBusinessConfig() {
        delete [select id from Business_Config__c];

        Contract c = [Select Status From Contract limit 1];

        Test.startTest();

        Database.executeBatch(new BatchContractRenewal());

        Test.stopTest();

        c = [Select Status, End_Date__c From Contract where id = : c.Id];

        System.assertEquals('Activated', c.Status);
        System.assert(c.End_Date__c <= Date.today());
    }

    @isTest static void batchContractRenewalDoesNothingIfNoBusinessLogic() {
        delete [Select Id from Business_Config__c Where Record_Type_Id__c like 'Tal%'];

        Contract talabatC = [Select Id from Contract Where RecordType.DeveloperName = 'Talabat_Contract' limit 1];

        Test.startTest();

        Database.executeBatch(new BatchContractRenewal());

        Test.stopTest();

        talabatC = [Select End_Date__c, Status From Contract Where Id = : talabatC.Id];
        System.assertEquals('Activated', talabatC.Status);
        System.assert(talabatC.End_Date__c <= Date.today());
    }

    @isTest static void testContractActivationThatStartToday() {
        Test.startTest();

        Database.executeBatch(new BatchContractRenewal());

        Test.stopTest();

        Boolean contractActivated = false;
        List<Contract> contracts = ContractSelector.getAll();
        for (Contract cont: contracts) {
            if (cont.StartDate == Date.today()) {
                contractActivated = 'Activated' == cont.Status;
                break;
            }
        }
        System.assert(contractActivated);
    }

    @isTest static void batchContractRenewalRenewContractCorrectly() {
        Contract talabatC = [Select Id from Contract Where RecordType.DeveloperName = 'Talabat_Contract' limit 1];

        Test.startTest();

        Database.executeBatch(new BatchContractRenewal());

        Test.stopTest();

        talabatC = [Select End_Date__c, Status, Last_renewal_date__c, Renewal_version__c From Contract WHere id = : talabatC.Id];

        System.assertEquals('Activated', talabatC.Status);
        System.assert(talabatC.End_Date__c > Date.today());
        System.assertEquals(1, talabatC.Renewal_version__c);
        System.assert(talabatC.Last_renewal_date__c >= Date.today());
    }

    @isTest static void batchContractRenewalDoesNotRenewContractIfAutoRenewIsDisabled() {
        Contract talabatC = [Select Do_not_auto_renew__c from Contract Where RecordType.DeveloperName = 'Talabat_Contract' limit 1];
        talabatC.Do_not_auto_renew__c = true;
        update talabatC;

        Test.startTest();

        Database.executeBatch(new BatchContractRenewal());

        Test.stopTest();

        talabatC = [Select End_Date__c, Status From Contract WHere id = : talabatC.Id];

        System.assertEquals('Expired', talabatC.Status);
        System.assert(talabatC.End_Date__c < Date.today());
    }

    @isTest static void batchContractRenewalDoesNotRenewContractIfCountryIsNotEnabledForAutoRenewal() {
        Contract cdC = [Select Id From Contract Where RecordType.DeveloperName like 'CD%' limit 1];

        Test.startTest();

        Database.executeBatch(new BatchContractRenewal());

        Test.stopTest();

        cdC = [Select Status, End_Date__c From Contract WHere Id =: cdC.Id];

        System.assertEquals('Expired', cdC.Status);
        System.assert(cdC.End_Date__c <= Date.today());
    }


    @isTest static void batchContractRenewalRenewContractCorrectlywithdiferentbatchsize() {

        Business_Config__c b7 = UnitTestDataFactory.createBusinessConfig('BatchContractRenewal', 'Process', 'BatchSize', '10', null, 'Global_Config', true, false);
        insert b7;
        Contract talabatC = [Select Id from Contract Where RecordType.DeveloperName = 'Talabat_Contract' limit 1];

        Test.startTest();

        SchedulableContext sc = null;
        ScheduleBatchContractRenewal tsc = new ScheduleBatchContractRenewal();
        tsc.execute(sc);

        Test.stopTest();

        talabatC = [Select End_Date__c, Status, Last_renewal_date__c, Renewal_version__c From Contract WHere id = : talabatC.Id];

        System.assertEquals('Activated', talabatC.Status);
        System.assert(talabatC.End_Date__c > Date.today());
        System.assertEquals(1, talabatC.Renewal_version__c);
        System.assert(talabatC.Last_renewal_date__c >= Date.today());
    }

    /**
    * @date     : [03/06/2020]
    * @method name  : testUpdateRevenueModel
    * @description  : Test method of the updateRevenueModel implemented for SSC-1982 : Tlife Commission
    */
    @IsTest
    public static void testUpdateRevenueModel() {
        Account talabatAccount = [Select id,Revenue_Model__c,RecordType.DeveloperName from Account where
        Revenue_Model__c =:  Constants.ACCOUNT_REVENUE_MODEL_ORDERING and  RecordType.DeveloperName =: Constants.ACCOUNT_RT_TALABAT_ACCOUNT limit 1];

        Test.startTest();
        List<Contract> talabatContractList = UnitTestDataFactory.createContracts(talabatAccount, Date.today().addDays(-2), Date.today(),
                Constants.CONTRACT_STATUS_DRAFT, Constants.CONTRACT_RT_TALABAT_CONTRACT,2, Constants.CONTRACT_SERVICE_COMMISSION_FEE);
        talabatContractList[0].End_Date__c = Date.today().addDays(-1);
        talabatContractList[1].Service_Type__c = Constants.CONTRACT_SERVICE_DEAL_SUBSCRIPTION;
        talabatContractList[0].Termination_Reason__c = Constants.CONTRACT_TERMINATION_REASON;
        talabatContractList[1].Termination_Reason__c = Constants.CONTRACT_TERMINATION_REASON;
        insert talabatContractList;
        System.assert(!talabatContractList.isEmpty());

        talabatContractList[1].Status = Constants.CONTRACT_STATUS_ACTIVATED;
        update talabatContractList;
        System.assert(!talabatContractList.isEmpty());

        Database.executeBatch(new BatchContractRenewal());
        Test.stopTest();
    }
}