force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type to determine the Asset Type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Online Marketing</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Premium placement</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Dish Level Photoshoot</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Car Leasing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Premium placement - 1 Month</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Asset__c.field-meta.xml
<CustomField>
    <fullName>Requires_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a product requires an asset</description>
    <label>Requires Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Id_List_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Price__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Opportunity Quote Line Items</relationshipLabel>
    <relationshipName>Opportunity_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Created&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to display current status of Shipment Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/Shipment_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment order items</description>
    <label>Shipment Order Line Item</label>
    <nameField>
        <label>Shipment Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Opportunity_Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Quote Line Item</label>
    <referenceTo>Opportunity_Quote_Line_Item__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Order__c</fullName>
    <label>Shipment Order</label>
    <referenceTo>Shipment_Order__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is to assing the stock item that should be deliver an copy on the asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>There is not stock Items available</errorMessage>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>New - In Stock, In Stock</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <description>Items that were or are are held in stock</description>
    <label>Stock Item</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>New - In Stock</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Shipping</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Retour in Progress</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Returned - at Manufacturer</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Writeoff</fullName>
            </value>
            <value>
                <fullName>Tested</fullName>
            </value>
            <value>
                <fullName>Returned - In Stock</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery/In Shipment</fullName>
            </value>
            <value>
                <fullName>In Stock</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Pick-up Needed</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShipmentOrderLineItemSelector.cls
/**
 * Created by w.novoa on 30.08.2019.
 */

public inherited sharing class ShipmentOrderLineItemSelector {
    public static map<Id, Shipment_Order_Line_Item__c> getShipmentLineItemsByOrder(set<Id> ShipmentOrderIds) {
        map<Id, Shipment_Order_Line_Item__c> mpShipmentOrderLineItems = new map<Id, Shipment_Order_Line_Item__c>();

        try {
            mpShipmentOrderLineItems = new map<Id, Shipment_Order_Line_Item__c>([select id,
                                                                                        Shipment_Order__c,
                                                                                        Opportunity_Quote_Line_Item__c,
                                                                                        Serial_Number__c,
                                                                                        Quantity__c ,
                                                                                        Shipment_Order__r.Status__c,
                                                                                        Stock_Item__c,
                                                                                        Name ,
                                                                                        Opportunity_Quote_Line_Item__r.id_list_product_price__r.Requires_Asset__c,
                                                                                        Opportunity_Quote_Line_Item__r.id_list_product_price__r.Product_Type__c
                                                                                from Shipment_Order_Line_Item__c
                                                                                where Shipment_Order__c IN : ShipmentOrderIds
                                                                                Order by Shipment_Order__c]);
        } catch (Exception e) {
            System.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }

        return mpShipmentOrderLineItems;

    }


}