force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Record_Country__c.field-meta.xml
<CustomField>
    <fullName>Record_Country__c</fullName>
    <formula>TEXT( Account.Record_Country__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_System__c.field-meta.xml
<CustomField>
    <fullName>Source_System__c</fullName>
    <description>Uses in Booking Rest Service. To store the information about external system name through which the booking was done.</description>
    <label>Source System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIDAS</fullName>
            </value>
            <value>
                <fullName>Restaurant Portal Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Ad_Sales_Type__c.field-meta.xml
<CustomField>
    <fullName>Ad_Sales_Type__c</fullName>
    <label>Ad Sales Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Based_On__c.field-meta.xml
<CustomField>
    <fullName>Based_On__c</fullName>
    <description>This will be copy from List service price when the Oportunity line item is created</description>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Orders</fullName>
            </value>
            <value>
                <fullName>Monetary Amounts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Booking_Api_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Api_Id__c</fullName>
    <externalId>true</externalId>
    <label>Booking Api Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Category_Id__c.field-meta.xml
<CustomField>
    <fullName>Category_Id__c</fullName>
    <label>Category Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/City_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>City_ZipCode__c</fullName>
    <label>Period / Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_In_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Commission_In_Percentage__c</fullName>
    <label>Commission In %</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_Per_Order__c.field-meta.xml
<CustomField>
    <fullName>Commission_Per_Order__c</fullName>
    <label>Commission Per Order</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_Type__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type__c</fullName>
    <formula>IF(ISPICKVAL(Commission_Type_Picklist__c, &apos;&apos;), 
TEXT(Id_List_Service_Price__r.Commission_Type__c), 
TEXT(Commission_Type_Picklist__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commission Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Commission_Type_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Commission_Type_Picklist__c</fullName>
    <description>In this field it will be copy the info from the list service price to keep the original value on the creation of the line item, the field Commission_Type will have to be delete in the future SP-3440</description>
    <label>Commission Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Per Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Deposit</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Deposit_Method__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Method__c</fullName>
    <label>Deposit Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bank Transfer</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Design_Note__c.field-meta.xml
<CustomField>
    <fullName>Design_Note__c</fullName>
    <label>Design Note</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/District_Id__c.field-meta.xml
<CustomField>
    <fullName>District_Id__c</fullName>
    <label>District Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Has_Related_Tarif__c.field-meta.xml
<CustomField>
    <fullName>Has_Related_Tarif__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Related Tarif</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_List_Price_Product__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Price_Product__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>List Product Price</label>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_List_Service_Price__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Service_Price__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Id List Service Price</label>
    <referenceTo>List_Service_Price__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Replacement_Order__c.field-meta.xml
<CustomField>
    <fullName>Id_Replacement_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Id Replacement Order</label>
    <referenceTo>Replacement_Order__c</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/index__c.field-meta.xml
<CustomField>
    <fullName>index__c</fullName>
    <label>index</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Installments__c.field-meta.xml
<CustomField>
    <fullName>Installments__c</fullName>
    <label>Installments</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/IsTiered__c.field-meta.xml
<CustomField>
    <fullName>IsTiered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsTiered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Listed_Price__c.field-meta.xml
<CustomField>
    <fullName>Listed_Price__c</fullName>
    <label>Listed Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Midas_Exception__c.field-meta.xml
<CustomField>
    <fullName>Midas_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field that indicates whether there was an exception when approving/canceling a booking in Midas</description>
    <inlineHelpText>Field that indicates whether there was an exception when approving/canceling a booking in Midas</inlineHelpText>
    <label>Midas Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Min__c.field-meta.xml
<CustomField>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Scaled__c.field-meta.xml
<CustomField>
    <fullName>Scaled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Scaled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Sub_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Sub_Product_Name__c</fullName>
    <label>Sub-Product Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Tier__c/Tier__c.object-meta.xml
<CustomObject>
    <label>Tier</label>
    <nameField>
        <label>Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tier__c/fields/Commission_in_percentage__c.field-meta.xml
<CustomField>
    <fullName>Commission_in_percentage__c</fullName>
    <label>Commission in %</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tier__c/fields/Commission_per_order__c.field-meta.xml
<CustomField>
    <fullName>Commission_per_order__c</fullName>
    <label>Commission per order</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tier__c/fields/Max__c.field-meta.xml
<CustomField>
    <fullName>Max__c</fullName>
    <label>Max</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tier__c/fields/Min__c.field-meta.xml
<CustomField>
    <fullName>Min__c</fullName>
    <label>Min</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItem_Selector.cls
/**
* @author Mantas Jurkunas
* @date 15.07.2019
*
* @description Selector for Opportunity_Line_Item__c records
*
*/

public with sharing class OpportunityLineItem_Selector {

    /**
     * @description selector method for test purposes
     *
     * @return List<Opportunity_Line_Item__c>
     */
    @TestVisible
    private static List<Opportunity_Line_Item__c> getAll() {
        List<Opportunity_Line_Item__c> listObj = new List<Opportunity_Line_Item__c>();
        try {
            listObj = [SELECT Based_On__c, Commission_Type__c, Scaled__c, Commission_Type_Picklist__c, Midas_Exception__c, Booking_Api_Id__c, Id_Opportunity__c  FROM Opportunity_Line_Item__c];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return listObj;
    }

    /**
     * @description selector method to query OpportunityLineItems based on OpportunityId
     * @Param Set of Opportunity Id
     * @return List<Opportunity_Line_Item__c>
     */
    public static List<Opportunity_Line_Item__c> getOLIByOpportunityId(final set<Id> oppIds) {
        List<Opportunity_Line_Item__c> listObj = new List<Opportunity_Line_Item__c>();
        try {
            listObj = [SELECT Id,Booking_Api_Id__c,Id_Opportunity__c,Id_Opportunity__r.Source_System__c from Opportunity_Line_Item__c where Id_Opportunity__c =:oppIds ];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return listObj;
    }

    /**
     * @description selector method to query OpportunityLineItems based on Booking Id
     * @Param Set of Opportunity Id
     * @return List<Opportunity_Line_Item__c>
     */
    public static List<Opportunity_Line_Item__c> getOLIByBookingId(List<string> bookingIds) {
        List<Opportunity_Line_Item__c> listObj = new List<Opportunity_Line_Item__c>();
        try {
            listObj = [select id, Booking_Api_Id__c, Id_Opportunity__r.record_country__c,Id_Opportunity__c,
                    Id_Opportunity__r.Source_System__c,Id_List_Price_Product__r.company__r.name, Interval__c,
                    Quantity__c, Unit_Cost__c, Sub_Product_Name__c, Budget__c, Name
            from Opportunity_line_item__c
            where Booking_Api_Id__c in: bookingIds];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return listObj;
    }

    /**
     * @description selector method to query OpportunityLineItems based on OpportunityId.
     *  this returns large amount of data and should be only used if most of the data is necessary, otherwise use getOLIByOpportunityId instead.
     * @Param Set of Opportunity Id
     * @return List<Opportunity_Line_Item__c>
     */
    public static List<Opportunity_Line_Item__c> getByOpportunityIdsForTariff(Set<Id> opportunityIds) {
        return [SELECT Ad_Sales_Type__c,Booking_Api_Id__c,Category_Id__c,Category__c,City_ZipCode__c,Commission_In_Percentage__c,Commission_Per_Order__c,
                Commission_Type__c,Deposit_Method__c,Deposit__c,Design_Note__c,Discount__c,District_Id__c,District__c,End_Date__c,Has_Related_Tarif__c,
                Id,Id_List_Price_Product__c,Id_List_Service_Price__c,Id_Opportunity__c,Id_Replacement_Order__c,index__c,Installments__c,IsTiered__c,
                Line_Item_Type__c,Listed_Price__c,Max__c,Min__c,Name,Number_of_Copies__c,OldOppQuoteLineId__c,Online_Payment_Fee__c,Position_fm__c,
                Position__c,Product_Group__c,Quantity__c,RecordTypeId,Recurring_Fee__c,Size__c,Start_Date__c,Subsidy__c,Sub_type__c,Total_Amount__c,
                Weight__c,Id_List_Add_On__c,ContractAddition__c,Billable_Account__c,Specifications__c,Scaled__c,Id_List_Price_Product__r.Company__r.Name,
                Commission_Type_Picklist__c,  Based_On__c, Source_grid__c, Delivery__c,
        (SELECT Min__c,Max__c,Commission_in_percentage__c,Commission_per_order__c,Id_Opportunity_Quote_Line_Item__c,Id_Opportunity_Line_Item__c
        FROM Tiers__r
        ORDER BY Min__c)
        FROM Opportunity_Line_Item__c
        WHERE Id_Opportunity__c IN :opportunityIds
        ORDER BY Id_List_Price_Product__r.Company__r.Name];
    }
}