force-app/main/default/objects/Bank_Detail__c/Bank_Detail__c.object-meta.xml
<CustomObject>
    <description>SP-3699 [APAC - Bank detail creation/update process]</description>
    <label>Bank Detail</label>
    <nameField>
        <displayFormat>BD-{000000000}</displayFormat>
        <label>Bank Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Scheduled Update Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BankDetail_Selector.cls
/**
 * Created by c.kumari on 26.09.2019.
 */

public with sharing class BankDetail_Selector {

    /**
   * Retrieves Bank Detail Record based on status and account Id
   * @param  account
   * @return Bank Detail Record
   */

    public static List<Bank_Detail__c> getByAccountIds(set<Id> accountIds){

        List<Bank_Detail__c> bankInfo = new List<Bank_Detail__c>();
        try {
            bankInfo = [SELECT
                    Id, Status__c, Account__c,CreatedById
            FROM Bank_Detail__c
            WHERE Account__c IN :accountIds
            AND Status__c != 'Inactive'];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return bankInfo;

    }


}