force-app/main/default/objects/Tarif__c/Tarif__c.object-meta.xml
<CustomObject>
    <description>this is the tarif name</description>
    <label>Tariff</label>
    <nameField>
        <label>Tarif Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tariffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif_Member__c/Tarif_Member__c.object-meta.xml
<CustomObject>
    <description>this shows the services and products that belong to a specific tarif</description>
    <label>Tarif Member</label>
    <nameField>
        <displayFormat>TAI-{000000}</displayFormat>
        <label>Tarif Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tarif Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarif_Member__c/fields/Id_Tarif_Item__c.field-meta.xml
<CustomField>
    <fullName>Id_Tarif_Item__c</fullName>
    <description>this holds the id of tarif member</description>
    <label>Id Tarif Item</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/fields/Tarif_Name__c.field-meta.xml
<CustomField>
    <fullName>Tarif_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the tarif name</description>
    <label>Tarif Name</label>
    <referenceTo>Tarif__c</referenceTo>
    <relationshipLabel>Tarif Members</relationshipLabel>
    <relationshipName>Tarif_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tarif_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>this helps in identifying product or service record id.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TarifMember_Selector.cls
/**
* @author Mantas Jurkunas
* @date 09.01.2019
*
* @description Selector class for retrieving Tarif Member records
*/
public with sharing class TarifMember_Selector {

    /*******************************************************************************************************
   * @description Queries for tarif member with 0 commission
   * @return Tarif_Member__c
   */

    public static Tarif_Member__c findTarifMemberByTarifName(String tarifName) {
        Tarif_Member__c tarifMember;
        try {
            tarifMember = [SELECT Id, Name, Tarif_Name__c, Id_Tarif_Item__c, Type__c FROM Tarif_Member__c WHERE Tarif_Name__r.Name = :tarifName AND Type__c = 'Product' LIMIT 1];
        } catch(Exception e) {
            system.debug('Error: '+e.getMessage());
            LoggingUtility.commitLogs();
        }
        return tarifMember;
    }
    /**
   * @Description: This method get tarif member details from tarif Ids
     @param             : Set of Tarif Ids
     @Return             : List of Tarif Member
     @TriggerContext     :  After Update
     @Ticket #           : SSC-1979
    */
    public static List<Tarif_Member__c> getTarifMembersByTarifIds(Set<Id> setOfTarifIds){

        List<Tarif_Member__c> lstOfTarifMembers = new List<Tarif_Member__c>();

        try{
            lstOfTarifMembers = [SELECT Id,Name,Tarif_Name__c,
                                Id_Tarif_Item__c, Type__c FROM
                                Tarif_Member__c WHERE Tarif_Name__c IN : setOfTarifIds];
        }
        catch(Exception e){
            system.debug('Error: '+e.getMessage());
        }
        return lstOfTarifMembers;
    }
}