force-app/main/default/objects/Branding_Content__c/Branding_Content__c.object-meta.xml
<CustomObject>
    <label>Branding &amp; Promotions</label>
    <nameField>
        <displayFormat>BC-{000}</displayFormat>
        <label>Branding Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branding &amp; Promotions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branding_Content__c/fields/Account_Country__c.field-meta.xml
<CustomField>
    <fullName>Account_Country__c</fullName>
    <description>SP-4411</description>
    <label>Account Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Restaurant_Name__c.field-meta.xml
<CustomField>
    <fullName>Restaurant_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Restaurant Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branding Content</relationshipLabel>
    <relationshipName>Branding_Content</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Installation</fullName>
                <default>true</default>
                <label>New - Awaiting Installation</label>
            </value>
            <value>
                <fullName>Installed successfully</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Transferred</fullName>
            </value>
            <value>
                <fullName>Uninstalled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Design rejected</fullName>
            </value>
            <value>
                <fullName>Pending final approval</fullName>
            </value>
            <value>
                <fullName>Pending design approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branding_Content__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Apron</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Blade sign</fullName>
            </value>
            <value>
                <fullName>Flagship Store</fullName>
            </value>
            <value>
                <fullName>Hats/Caps</fullName>
            </value>
            <value>
                <fullName>Heating Bag</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Menu holder</fullName>
            </value>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Notepads/Pens</fullName>
            </value>
            <value>
                <fullName>Open and closed sign</fullName>
            </value>
            <value>
                <fullName>Other branded consumables</fullName>
            </value>
            <value>
                <fullName>Roofie</fullName>
            </value>
            <value>
                <fullName>Starter Package</fullName>
            </value>
            <value>
                <fullName>Sticker</fullName>
            </value>
            <value>
                <fullName>T-shirts</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrandingContent_Selector.cls
/**
* @author Mantas Jurkunas
* @date 08.10.2019
*
* @description Selector class for branding content
*/

public class BrandingContent_Selector {

    public static List<Branding_Content__c> findByAccountIds(Set<Id> ids) {
        List<Branding_Content__c> brandings = new List<Branding_Content__c>();
        try {
            brandings = [SELECT Id, Restaurant_Name__c, Account_Country__c FROM Branding_Content__c WHERE Restaurant_Name__c IN :ids];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return brandings;
    }
    /**
   * @description return Brands against opportunity Id
   * @param opptySet contains set Of Opportunity
   * @param typeOfBrand type of branding Contents
   * @param setOfStatus statuses of that brand
   * @return List of Branding_Content__c
   * Jira Ticket SSC-3462
   */
    public static List<Branding_Content__c> getBrandingByOpptyId(Set<Id> opptySet, string typeOfBrand, Set<String> setOfStatus){

        typeOfBrand = '%' + typeOfBrand + '%';
        List<Branding_Content__c> brandingLst = new List<Branding_Content__c>();
        brandingLst = [select id, status__c, opportunity__c
                        from branding_Content__c
                        where type__c like : typeOfBrand and opportunity__c in :opptySet
                        AND Status__c IN : setOfStatus];
        return brandingLst;
    }

}