force-app/main/default/objects/Lead/fields/GRID__c.field-meta.xml
<CustomField>
    <fullName>GRID__c</fullName>
    <description>GRID to be transferred to account when lead record is converted</description>
    <label>GRID</label>
    <length>7</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/GRIDSequence__c.field-meta.xml
<CustomField>
    <fullName>GRIDSequence__c</fullName>
    <description>lead grid sequence, de migration</description>
    <displayFormat>{000000000}</displayFormat>
    <label>GRIDSequence</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/BatchPopulateGrid.cls
global class BatchPopulateGrid implements Database.Batchable<sObject> {

	String query;

	global BatchPopulateGrid(String obj) {
		if (obj == 'Lead') {
			query = 'SELECT GRID__c, GRIDSequence__c FROM ' + obj + ' WHERE GRIDSequence__c != \'\' AND GRID__c = \'\' AND IsConverted = false';
		} else {
			query = 'SELECT GRID__c, GRIDSequence__c FROM ' + obj + ' WHERE GRIDSequence__c != \'\' AND GRID__c = \'\'';
		}
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		for (sObject obj : scope) {
			Integer seq = Integer.valueOf(String.valueOf(obj.get('GRIDSequence__c')));
			obj.put('GRID__c', UtilsGlobalIdentifier.getGlobalIdentifierFromSequenceNumber(seq));
		}
		update scope;
	}

	global void finish(Database.BatchableContext BC) {

	}

}