force-app/main/default/objects/Approval_Rule__c/Approval_Rule__c.object-meta.xml
<CustomObject>
    <label>Approval Rule</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Approval Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>SSC-2182</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Add_On__c.field-meta.xml
<CustomField>
    <fullName>Add_On__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Add On</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND (2 OR 3)) OR (4 AND 5)</booleanFilter>
        <errorMessage>You can choose only your country related records</errorMessage>
        <filterItems>
            <field>List_Add_On__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>FP_List_Add_On</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>APAC FoodPanda</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>DHH Delivery Hero Holding</value>
        </filterItems>
        <filterItems>
            <field>List_Add_On__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PY_List_Add_On</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>UY Pedidosya, DHH Delivery Hero Holding</value>
        </filterItems>
        <infoMessage>You can choose only your country related records</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>List_Add_On__c</referenceTo>
    <relationshipLabel>Approval Rules</relationshipLabel>
    <relationshipName>Approval_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/AddOn_Approver2__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddOn Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/AddOn_Approver3__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddOn Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_RulesEsK0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/AddOn_Approver4__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddOn Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_RulesEsKK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/AddOn_Approver__c.field-meta.xml
<CustomField>
    <fullName>AddOn_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AddOn Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Applies_To__c.field-meta.xml
<CustomField>
    <fullName>Applies_To__c</fullName>
    <inlineHelpText>Select quote line item types tor which this rule will apply</inlineHelpText>
    <label>Submit for approval</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commissions</fullName>
            </value>
            <value>
                <fullName>Products</fullName>
            </value>
            <value>
                <fullName>Add-ons</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Commission__c.field-meta.xml
<CustomField>
    <fullName>Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commission</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 OR 6) AND (2 OR 3) OR (4 AND 5) OR (7 AND 8)</booleanFilter>
        <errorMessage>You can choose only your country related records</errorMessage>
        <filterItems>
            <field>List_Service_Price__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>FP_List_Service_Price</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>APAC FoodPanda</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>DHH Delivery Hero Holding</value>
        </filterItems>
        <filterItems>
            <field>List_Service_Price__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PY_List_Service_Price</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>DHH Delivery Hero Holding, UY Pedidosya</value>
        </filterItems>
        <filterItems>
            <field>List_Service_Price__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Talabat_List_Service_Price</value>
        </filterItems>
        <filterItems>
            <field>List_Service_Price__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CZ_List_Service_Price</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>CZ Dame Jidlo</value>
        </filterItems>
        <infoMessage>You can choose only your country related records</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>List_Service_Price__c</referenceTo>
    <relationshipLabel>Approval Rules</relationshipLabel>
    <relationshipName>Approval_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Approval Rules</relationshipLabel>
    <relationshipName>Approval_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level1_Approver2__c.field-meta.xml
<CustomField>
    <fullName>Level1_Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1 Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level1_Approver3__c.field-meta.xml
<CustomField>
    <fullName>Level1_Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1 Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level1_Approver4__c.field-meta.xml
<CustomField>
    <fullName>Level1_Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1 Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level1_Approver__c.field-meta.xml
<CustomField>
    <fullName>Level1_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 1 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level1_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Level1_Percentage__c</fullName>
    <formula>IF( CONTAINS(Level1__c , &apos;%&apos;),
VALUE(SUBSTITUTE( SUBSTITUTE( TRIM(Level1__c) , &apos; &apos;, &apos;&apos;) , &apos;%&apos;, &apos;&apos;)) / 100,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level 1 Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level1_Value__c.field-meta.xml
<CustomField>
    <fullName>Level1_Value__c</fullName>
    <formula>IF( CONTAINS(Level1__c , &apos;%&apos;),
0,
VALUE(SUBSTITUTE( TRIM(Level1__c) , &apos; &apos;, &apos;&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level 1 Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level2_Approver2__c.field-meta.xml
<CustomField>
    <fullName>Level2_Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 2 Approver 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level2_Approver3__c.field-meta.xml
<CustomField>
    <fullName>Level2_Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 2 Approver 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level2_Approver4__c.field-meta.xml
<CustomField>
    <fullName>Level2_Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 2 Approver 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level2_Approver__c.field-meta.xml
<CustomField>
    <fullName>Level2_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Level 2 Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approval_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level2_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Level2_Percentage__c</fullName>
    <formula>IF( CONTAINS(Level2__c , &apos;%&apos;),
VALUE(SUBSTITUTE(  SUBSTITUTE(TRIM(Level2__c), &apos; &apos;, &apos;&apos;), &apos;%&apos;, &apos;&apos;)) / 100,
0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level 2 Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Level2_Value__c.field-meta.xml
<CustomField>
    <fullName>Level2_Value__c</fullName>
    <formula>IF( CONTAINS(Level2__c , &apos;%&apos;),
0,
VALUE(SUBSTITUTE( TRIM(Level2__c) , &apos; &apos;, &apos;&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Level 2 Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND (2 OR 3)) OR (4 AND 5)</booleanFilter>
        <errorMessage>You can choose only your country related records</errorMessage>
        <filterItems>
            <field>List_Product_Price__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>FP_List_Product_Price</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>APAC FoodPanda</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>DHH Delivery Hero Holding</value>
        </filterItems>
        <filterItems>
            <field>List_Product_Price__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>PY_List_Product_Price</value>
        </filterItems>
        <filterItems>
            <field>$User.Entity__c</field>
            <operation>equals</operation>
            <value>DHH Delivery Hero Holding, UY Pedidosya</value>
        </filterItems>
        <infoMessage>You can choose only your country related records</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>List_Product_Price__c</referenceTo>
    <relationshipLabel>Approval Rules</relationshipLabel>
    <relationshipName>Approval_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Vertical_Segment__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Segment__c</fullName>
    <label>Vertical Segment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Vertical_Segment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Approval_Rule__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <formula>IF(Commission__c != null, 10, 0) +
IF(Product__c  != null, 10, 0) +
IF(Add_On__c  != null, 10, 0) +
IF(Company_Code__c  != null, 3, 0) +
IF(Country__c  != null, 2, 0) +
IF(City__c  != null, 2, 0) +
IF(ISPICKVAL(Platform__c, &apos;&apos;), 0, 2)+
IF(ISBLANK(Vertical_Segment__c), 0,1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Arbitrary number that represents the weight of each rule.This is used in determining the priority in cases where multiple rules satisfy the same scenario.</inlineHelpText>
    <label>Weight</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Vertical_Segment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Baby</fullName>
    </customValue>
    <customValue>
        <fullName>Bakery</fullName>
    </customValue>
    <customValue>
        <fullName>Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>Cosmetics</fullName>
    </customValue>
    <customValue>
        <fullName>Darkstores</fullName>
    </customValue>
    <customValue>
        <fullName>Desert</fullName>
    </customValue>
    <customValue>
        <fullName>Drinks</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Entertainment</fullName>
    </customValue>
    <customValue>
        <fullName>Flowers</fullName>
    </customValue>
    <customValue>
        <fullName>Furniture</fullName>
    </customValue>
    <customValue>
        <fullName>Groceries</fullName>
    </customValue>
    <customValue>
        <fullName>Healthcare &amp; Beauty</fullName>
    </customValue>
    <customValue>
        <fullName>Home &amp; Gifts</fullName>
    </customValue>
    <customValue>
        <fullName>Home Based Kitchen</fullName>
    </customValue>
    <customValue>
        <fullName>Ice cream</fullName>
    </customValue>
    <customValue>
        <fullName>Party Supplies</fullName>
    </customValue>
    <customValue>
        <fullName>Pets</fullName>
    </customValue>
    <customValue>
        <fullName>Pharmacy</fullName>
    </customValue>
    <customValue>
        <fullName>Regular Restaurant</fullName>
    </customValue>
    <customValue>
        <fullName>Shops</fullName>
    </customValue>
    <customValue>
        <fullName>Stationery</fullName>
    </customValue>
    <customValue>
        <fullName>Street Kitchen</fullName>
    </customValue>
    <customValue>
        <fullName>Supplements</fullName>
    </customValue>
    <customValue>
        <fullName>Toys</fullName>
    </customValue>
    <masterLabel>Vertical Segment</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ApprovalRuleSelector.cls
/**
* @author Krunoslav Bilicic
* @date 11.9.2019
*
* @description Selector class for retrieving Approval Rule records
*/

public class ApprovalRuleSelector  {
    public static List<Approval_Rule__c> getApprovalRules(Set<Id> comms, Set<Id> products, Set<Id> addOns, Set<string> country, Set<string> companyCode, Set<string> platforms)  {
        return [
            SELECT Id, Name, Commission__c, Product__c, Add_On__c,
                Level1_Value__c, Level1_Percentage__c, Level1_Approver__c, Level1_Approver2__c, Level1_Approver3__c, Level1_Approver4__c,
                Level2_Value__c, Level2_Percentage__c, Level2_Approver__c, Level2_Approver2__c, Level2_Approver3__c, Level2_Approver4__c,
                AddOn_Approver__c, AddOn_Approver2__c, AddOn_Approver3__c, AddOn_Approver4__c,
                Country__c, Country__r.Name, City__c,
                Platform__c, Company_Code__c, Weight__c,
                Applies_To__c,Vertical_Segment__c
                FROM Approval_Rule__c
                WHERE (Commission__c IN :comms
                OR Product__c IN :products
                OR Add_On__c IN :addOns
                OR Country__r.Name IN :country 
                OR Company_Code__c IN :companyCode 
                OR Platform__c IN :platforms)
                AND Active__c = TRUE
            ];
    }
}