force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/Opportunity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Line Item</label>
    <nameField>
        <label>Opportunity Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Line_Item__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Line Items</relationshipLabel>
    <relationshipName>Opportunity_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CustomReportList_AuraControllerTest.cls
/**
* @author Mantas Jurkunas
* @date 19.08.2019
*
* @description Test class for CustomReportList_AuraController
* @see CustomReportList_AuraController
*/
@IsTest
public with sharing class CustomReportList_AuraControllerTest {

    @TestSetup
    public static void setup() {
        Business_Config__c config1 = UnitTestDataFactory.createBusinessConfig('CustomReports', 'Process', 'Opportunities', '{"queryCondition":null,"parentLookupField":null,"objectName":"Account","fieldSetName":"OptTriggerQuery","fieldSetMembers":null,"dataMap":null,"children":[{"queryCondition":null,"parentLookupField":"AccountId","objectName":"Opportunity","fieldSetName":"Test_FieldSet","fieldSetMembers":null,"dataMap":null,"children":[{"queryCondition":null,"parentLookupField":"Id_Opportunity__c", "stackValues": true,"objectName":"Opportunity_Line_Item__c","fieldSetName":"Test_FieldSet","fieldSetMembers":null,"dataMap":null,"children":null}]}]}', null, 'Yogiyo', true, true);
        insert config1;
    }

    @IsTest
    public static void test_getReportDescription() {
        List<CustomReportList_AuraController.ReportDescription> description = CustomReportList_AuraController.getReportDefinitionList();
        System.assertEquals(1, description.size());
    }
}