force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Reason__c</fullName>
    <label>Closed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Take Online</fullName>
            </value>
            <value>
                <fullName>Take Online is not possible</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Not Successful</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Create Retention Task</fullName>
            </value>
            <value>
                <fullName>Create Take Offline Task for Non Contracted</fullName>
            </value>
            <value>
                <fullName>Take Offline</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Not Successful - Data Missing</fullName>
            </value>
            <value>
                <fullName>Not Successful - Commission is not correct</fullName>
            </value>
            <value>
                <fullName>Back Online</fullName>
            </value>
            <value>
                <fullName>Not Reachable</fullName>
            </value>
            <value>
                <fullName>Spam</fullName>
            </value>
            <value>
                <fullName>Duplicated</fullName>
            </value>
            <value>
                <fullName>Auto Closed</fullName>
            </value>
            <value>
                <fullName>Escalated to AM</fullName>
            </value>
            <value>
                <fullName>Successful Call</fullName>
            </value>
            <value>
                <fullName>Call Scheduled</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (Agent)</fullName>
            </value>
            <value>
                <fullName>Improvement on KPI’s (AM)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (1 st Incident)</fullName>
            </value>
            <value>
                <fullName>Restaurant Taken Offline (Permanent)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Send_Survey__c.field-meta.xml
<CustomField>
    <fullName>Send_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Helper field. When checked by Batch will trigger workflow/outbound message to Qualtrics</description>
    <label>Send Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchOnboardingSendSurvey.cls
/**
* @Description: This batch updates the send survey flag on Onboarding Cases after 7 days of closure.
*/
global class BatchOnboardingSendSurvey implements Database.Batchable<sObject>,Schedulable{
    public String recordTypes;
    public String caseStatus;
    public String caseClosedReason;
    public Integer numberOfDays;
    private Map<String, Map<String, Map<String, Business_Config__c>> > moam =
            LibBusinessConfig.motherOfAllBusinessMaps;
    private static Map<String, Business_Config__c> mapBusinessRules;

    public BatchOnboardingSendSurvey(){
        Map<String, Map<String, Business_Config__c>> mapBusinessLogic 	= moam.get('BatchOnboardingSurvey');
        if(mapBusinessLogic != null){
            mapBusinessRules 	= mapBusinessLogic.get('Global_Config');
            if(mapBusinessRules != null) {
                if(mapBusinessRules.ContainsKey('recordTypes')){
                    recordTypes = mapBusinessRules.get('recordTypes').Business_rule_Value__c;
                }
                if(mapBusinessRules.ContainsKey('numberOfDays')){
                    numberOfDays = Integer.valueOf(mapBusinessRules.get('numberOfDays').Business_Rule_Value__c);
                }
                if(mapBusinessRules.ContainsKey('closedReason')){
                    caseClosedReason = mapBusinessRules.get('closedReason').Business_Rule_Value__c;
                }
                if(mapBusinessRules.ContainsKey('Status')){
                    caseStatus = mapBusinessRules.get('Status').Business_Rule_Value__c;
                }
            }
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {

        Date resolvedDate;
        Id recordTypeId;
        If(numberOfDays != null) {
            resolvedDate = Date.today().addDays(-numberOfDays);
        }
        If(recordTypes != null) {
            recordTypeId = LibRecordTypeHelper.getRecordTypeValue(recordTypes);
        }

        return Database.getQueryLocator([SELECT Id,Status,
        RecordTypeId,ClosedDate,Closed_Reason__c,Send_Survey__c
        FROM CASE
        WHERE RecordTypeId = :recordTypeId
        AND ClosedDate < :resolvedDate
        AND Status = :caseStatus
        AND Closed_Reason__c = :caseClosedReason
        AND Send_Survey__c = false]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Case> casesTobeClosed = (List<Case>)scope;
        for(Case cs : casesToBeClosed){
            cs.Send_Survey__c = true;
        }

        // In case of failure perform partial update
        List<Database.saveResult> results = Database.update(casesTobeClosed,false);
        LoggingUtility.createLog('BatchOnboardingSendSurvey','BATCH','CASE Onboarding Survey',null);
        Boolean isError = false;
        for(Database.saveResult result : results){
            if(!result.isSuccess()){
                LoggingUtility.logError('BatchOnboardingSendSurvey','BatchOnboardingSendSurvey: Update failed for case ' + result.getId() +
                        ' Errors '  + result.getErrors() + '\n');
                System.debug(Logginglevel.ERROR,'BatchOnboardingSendSurvey: Update failed for case ' + result.getId() +
                        ' Errors '  + result.getErrors());
                isError = true;
            }
        }

        // Do Logging in case of error.
        if(isError){
            LoggingUtility.commitLogs();
        }

    }

    global void finish(Database.BatchableContext BC) {

    }

    // Scheduler for the batch
    global void execute(SchedulableContext sc) {
        BatchOnboardingSendSurvey batch = new BatchOnboardingSendSurvey();
        Database.executebatch(batch);
    }
}