force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <description>Determines the quote type to be selected</description>
    <label>Quote Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ClsQuoteLineItemProcessor.cls
/**
* @author Alyana Navarro
* @date 21.01.2020
*
* @description Class that contains methods for Opportunity Quote Line Item
*/
public class ClsQuoteLineItemProcessor {
    private static Map<String, Map<String,Map<String,Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
    
    /**
    * @description Update Opportunity Quote Quote Type based on Quote Line Items.
    * @param Opportunity_Quote__c - Opportunity Quote to be updated.
    * @param Opportunity - Related Opportunity of the Quote.
    * @param Opportunity_Quote_Line_Item__c - Opportunity Quote Line Item to be checked.
    * @return Opportunity_Quote__c - Quote with updated Quote Type if Quote Line Item is matched
    **/
	public static Opportunity_Quote__c updateQuoteType(Opportunity_Quote__c oppQuote, Opportunity opportunity, Opportunity_Quote_Line_Item__c oppQuoteLineItem){
        Boolean isMatch = false;
        List<String> ruleTempList;
        Map<String, String> oppLineItemRuleMap;
        Map<String, String> bRuleNameTempMap = new Map<String, String>();
        Map<String,Business_Config__c> mapBusinessRules;
        Map<String,Map<String,Business_Config__c>> mapBusinessLogic = moam.get('nintexQuoteFilters');

        if(mapBusinessLogic != null && !mapBusinessLogic.isEmpty()){
            mapBusinessRules = mapBusinessLogic.get(opportunity.RecordType.DeveloperName);
        }

        if(mapBusinessRules != null){
            for(String bRuleConfig : mapBusinessRules.keySet()){
                isMatch = true;
                bRuleNameTempMap = new Map<String, String>();
                for(String bRuleKey : mapBusinessRules.get(bRuleConfig).Business_Rule_Name__c.split(';')){
                    if(!bRuleKey.equals(Constants.BUSINESSCONIFG_RULENAME_CHECKCOMMISSIONTYPES)){ //SSC-1929
                        ruleTempList = bRuleKey.split(':');
                        bRuleNameTempMap.put(ruleTempList[0], ruleTempList[1]);
                    }
                }

                if(!bRuleNameTempMap.containsKey('Opportunity_Quote_Line_Item__c')){
                    continue;
                } else {
                    oppLineItemRuleMap = (Map<String, String>) JSON.deserialize(bRuleNameTempMap.get('Opportunity_Quote_Line_Item__c').replaceAll('=', ':'), Map<String, String>.class);
                }

                for(String bRuleKey : bRuleNameTempMap.keySet()){
                    if(bRuleKey == 'Opportunity_Quote_Line_Item__c'){
                        for(String innerBRuleKey : oppLineItemRuleMap.keySet()){
                            if(oppQuoteLineItem.get(innerBRuleKey) != oppLineItemRuleMap.get(innerBRuleKey)){
                                isMatch = false;
                                break;
                            }
                        }
                    } else if(isMatch && opportunity.get(bRuleKey) != bRuleNameTempMap.get(bRuleKey)){
                        isMatch = false;
                    }

                    if(!isMatch){
                        break;
                    }
                }

                if(isMatch){
                    oppQuote.Quote_Type__c = mapBusinessRules.get(bRuleConfig).Business_Rule_Value__c;
                    oppQuote.Template_Name__c = mapBusinessRules.get(bRuleConfig).Business_Rule_Value__c;
                    break;
                }
            }
        }

        return oppQuote;
    }
}