force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>A company that a user belongs to. A user can belong to more than one company</description>
    <label>Company Name</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yogiyo</fullName>
            </value>
            <value>
                <fullName>Talabat</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>CD</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>PY</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>FP</fullName>
            </value>
            <value>
                <fullName>YE</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>HS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomReportList_AuraController.cls
/**
* @author Mantas Jurkunas
* @date 19.08.2019
*
* @description Controller for CustomReportList component
*/
public with sharing class CustomReportList_AuraController {

    @AuraEnabled
    public static List<ReportDescription> getReportDefinitionList() {
        List<ReportDescription> reportDescriptionList = new List<ReportDescription>();
        Map<String, Map<String, Business_Config__c>> mapBusinessProcess= LibBusinessConfig.motherOfAllBusinessMaps.get('CustomReports');
        if (mapBusinessProcess == null || mapBusinessProcess.isEmpty()) {
            return reportDescriptionList;
        }
        User currentUser = [SELECT Company_Name__c FROM User WHERE Id = :UserInfo.getUserId()];
        List<String> userCompanies = currentUser.Company_Name__c.split(';');
        if (userCompanies == null || userCompanies.isEmpty()) {
            return reportDescriptionList;
        }
        for (String userCompany: userCompanies) {
            if (!mapBusinessProcess.containsKey(userCompany.trim())) {
                continue;
            }
            Map<String, Business_Config__c> reportDescriptionMap = mapBusinessProcess.get(userCompany.trim());
            for (String reportName: reportDescriptionMap.keySet()) {
                reportDescriptionList.add(new ReportDescription(reportName, reportDescriptionMap.get(reportName).Business_Rule_Value__c));
            }
        }
        return reportDescriptionList;
    }

    @TestVisible
     private class ReportDescription {
         @AuraEnabled public String definitionJson;
         @AuraEnabled public String reportName;
         @AuraEnabled public Boolean isVisible;

         public ReportDescription(String reportName, String definitionJson) {
             this.reportName = reportName;
             this.definitionJson = definitionJson;
             this.isVisible = false;
         }
     }
}