force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Id_Country__c.field-meta.xml
<CustomField>
    <fullName>Id_Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup field to Country object</description>
    <label>Id Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Business Configs</relationshipLabel>
    <relationshipName>Business_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To distinguish between additional rule and the main rule</description>
    <label>Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Paraguay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stage_1_Completed__c.field-meta.xml
<CustomField>
    <fullName>Stage_1_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for Talabat Quality Check cases tracks when Legal team approve the documents</description>
    <label>Stage 1 Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CD_Entry_Case.recordType-meta.xml
<RecordType>
    <fullName>CD_Entry_Case</fullName>
    <active>true</active>
    <businessProcess>CD Entry Process</businessProcess>
    <description>Menu Processing Case for Click Delivery</description>
    <label>CD Entry Case</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Country of Lead</description>
    <label>User Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Franchise</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
                <default>true</default>
                <label>Branch</label>
            </value>
            <value>
                <fullName>Branch - Main</fullName>
            </value>
            <value>
                <fullName>Branch - Kitchen Restaurant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Yogiyo_Lead.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Lead</fullName>
    <active>true</active>
    <businessProcess>Yogiyo Lead Process</businessProcess>
    <description>Korea Lead Record Type</description>
    <label>Yogiyo Lead</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CD_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>CD_Opportunity</fullName>
    <active>true</active>
    <businessProcess>CD Sales Process</businessProcess>
    <description>Opportunity for Click Delivery</description>
    <label>CD Opportunity</label>
</RecordType>

force-app/main/default/objects/Platform_Country__c/Platform_Country__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Platform Country</label>
</CustomObject>

force-app/main/default/objects/Platform_Country__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PlatformCache__c/PlatformCache__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PlatformCache</label>
</CustomObject>

force-app/main/default/objects/PlatformCache__c/fields/CachePartitionSize__c.field-meta.xml
<CustomField>
    <fullName>CachePartitionSize__c</fullName>
    <description>Default cache partition size</description>
    <label>CachePartitionSize</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TLB_Approval_Matrix__c/TLB_Approval_Matrix__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TLB Approval Matrix</label>
</CustomObject>

force-app/main/default/objects/TLB_Approval_Matrix__c/fields/CountryName__c.field-meta.xml
<CustomField>
    <fullName>CountryName__c</fullName>
    <label>CountryName</label>
    <length>42</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TLB_Approval_Matrix__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>set to true if approver wants to receive approval emails</description>
    <label>Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TLB_Approval_Matrix__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UnitTestLibBusinessConfig.cls
@isTest
private class UnitTestLibBusinessConfig {
    private static User testUser;
    private static Country__c country;
    private static Company__c company;
    private static List<Account> accts;
    private static List<Lead> leads;
    private static Business_Config__c configTrigger;
    private static Business_Config__c configProcess;

    static {
        testUser = UnitTestDataFactory.createUser('Yogiyo Sales Management', 'yogiyounittestuser@deliveryhero.com', 'Yogiyo', 'KR');
        insert testUser;
        List<Platform_Country__c> platformCountry =new List<Platform_Country__c>();
        platformCountry.add(new Platform_Country__c(name='TalabatPlatform',country__c='Kuwait,Bahrain,Saudi Arabia,Oman,Qatar,United Arab Emirates'));
        platformCountry.add(new Platform_Country__c(name='FOCPlatform', country__c='Lebanon,Qatar,United Arab Emirates'));
        insert platformCountry;
        UnitTestDataFactory.getRecordtypeValues();
        System.runAs(testUser){
            country = UnitTestDataFactory.createCountry('KR', 'Korea', 'KRW');
            insert country;

            company = UnitTestDataFactory.createCompany('Yogiyo', 'Yogiyo', country);
            company.CurrencyIsoCode = country.CurrencyIsoCode;
            insert company;

            leads = UnitTestDataFactory.createLeads(201, country, 'Test Lead','Test Company', 'KRW', 'Test Burgers - Not for eating', 'Yogiyo_Lead');
            //insert leads;
            /*accts = UnitTestDataFactory.createAccounts(201, country, 'Yogiyo_Account');
            insert accts;*/
            configTrigger = UnitTestDataFactory.createBusinessConfig('Test Trigger', 'Trigger', 'Test Rule', 'Test Value', country.Id, 'Yogiyo_Account', true, true);
            configProcess = UnitTestDataFactory.createBusinessConfig('Test Process', 'Process', 'Test Rule', 'Test Value', country.Id, 'Yogiyo_Account', true, true);

            TLB_Approval_Matrix__c approvalSetting_level1 = new TLB_Approval_Matrix__c(
                    Name = 'Level1',
                    CountryName__c = 'Arab Emirates',

                    Notification__c = true,
                    Role__c = 'HOS'

            );

            TLB_Approval_Matrix__c approvalSetting_level2 = new TLB_Approval_Matrix__c(
                    Name = 'Level2',
                    CountryName__c = 'Arab Emirates',

                    Notification__c = true,
                    Role__c = 'Legal'

            );

            insert new List<sObject>{approvalSetting_level2,approvalSetting_level1};

            //RecortType rt = new RecortType(DeveloperName = 'Yogiyo_Lead');
        }
    }

    @isTest static void test_determineApprover(){
        TLB_Approval_Matrix__c approvalEntry;
        Test.startTest();

        System.runas(testUser){
            // approvalEntry = LibBusinessConfig.determineApprover('Arab Emirates', 1);
        }

        Test.stopTest();

        // System.assertNotEquals(null,approvalEntry);
    }


    @isTest static void test_setCountryLookUp() {

        Test.startTest();

        System.assertEquals(null, leads[0].Country__c);

        System.runAs(testUser){
            insert leads;
        }

        Test.stopTest();

        Lead testLead = [SELECT Id, Name, Country__c FROM Lead WHERE id = :leads[0].Id];
        System.assertEquals(country.Id, testLead.Country__c);
    }

    @isTest static void test_isTriggerActive() {
        Test.startTest();

        System.assertEquals(null, LibBusinessConfig.isTriggerActive('Test Trigger'));

        System.runAs(testUser){
            insert configTrigger;
        }

        Test.stopTest();
        System.assertEquals(true, LibBusinessConfig.isTriggerActive('Test Trigger'));
    }

    @isTest static void test_getRecordTypeToRecordTypeAssignment(){
        Test.startTest();

        System.runAs(testUser){
            insert configProcess;
            System.assertEquals('Test Value', LibBusinessConfig.getRecordTypeToRecordTypeAssignment('Test Process').get('Test Rule'));
        }

        Test.stopTest();
    }

    @isTest static void test_getGerenericProcessDataWithCountry(){
        Test.startTest();

        System.runAs(testUser){
            insert configProcess;
            System.assertEquals('Test Value', LibBusinessConfig.getGerenericProcessDataWithCountry('Test Process').get('KR').get('Test Rule').Business_Rule_Value__c);
        }

        Test.stopTest();
    }

    @isTest static void test_getUserCompanies(){
        Test.startTest();

        System.runAs(testUser){
            System.debug('@@@@ calling test_getUserCompanies : ' + LibBusinessConfig.getUserCompanies());
            System.assertEquals(1, LibBusinessConfig.getUserCompanies().size());
            System.assertEquals('Yogiyo', LibBusinessConfig.getUserCompanies()[0].Name);
        }

        Test.stopTest();
    }

    @isTest static void test_getUserCountries(){
        Test.startTest();

        System.runAs(testUser){
            System.assertEquals(1, LibBusinessConfig.getUserCountries().size());
            System.assertEquals('Korea', LibBusinessConfig.getUserCountries()[0].Name);
        }

        Test.stopTest();
    }

    @isTest static void test_getRecordTypeDevName(){
        Test.startTest();

        System.runAs(testUser){
            insert leads;
            System.assertEquals('Yogiyo_Lead', LibBusinessConfig.getRecordTypeDevName(leads[0], 'Lead'));
        }

        Test.stopTest();
    }

    @isTest static void test_determineCompany(){
        Test.startTest();

        System.runAs(testUser){
            System.assertEquals('Yogiyo', LibBusinessConfig.determineCompany('Yogiyo_Account'));
            System.assertEquals('DH_AU', LibBusinessConfig.determineCompany('DH_AU_Account'));
        }

        Test.stopTest();
    }

    @isTest static void test_recordCurrencyMap(){
        Test.startTest();

        System.runAs(testUser){
            System.assertEquals('KRW', LibBusinessConfig.recordCurrencyMap().get('Korea'));
        }

        Test.stopTest();
    }
    /**
     * @description test that the partion of the bussiness configs work properly
     *
     * @param None
     */
    @isTest static void readMultipartionBussinessRules(){
        String partitionCache = 'local.BusinessConfigCache';

        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountry = UnitTestDataFactory.createCountry('PY', 'Paraguay', 'COP');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('PedidosYA', 'PedidosYA', testCountry);
        insert testCompany;
        Business_Config__c process1 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process2 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 2',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        insert new List<sObject>{process1,process2};

        test.startTest();
        Cache.OrgPartition orgCache = Cache.Org.getPartition(partitionCache);
        system.assertEquals(0,orgCache.getKeys().size());
        Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
        system.assertEquals(1,orgCache.getKeys().size());
        moam = LibBusinessConfig.motherOfAllBusinessMaps;
        System.assertNotEquals(null,moam.get('EventBus'));
        LibBusinessConfig.cleanOrgCache();
        system.assertEquals(0,orgCache.getKeys().size());


        test.stopTest();

    }

    /**
     * @description test that the partion of the bussiness configs work properly
     *
     * @param None
     */
    @isTest static void readMultipartionBussinessRulesHitTime(){
        String partitionCache = 'local.BusinessConfigCache';

        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountry = UnitTestDataFactory.createCountry('PY', 'Paraguay', 'COP');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('PedidosYA', 'PedidosYA', testCountry);
        insert testCompany;
        Business_Config__c process1 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process2 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 2',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        insert new List<sObject>{process1,process2};

        Test.startTest();

        Cache.OrgPartition orgCachePartition = Cache.Org.getPartition(partitionCache);
        System.assertEquals(0,orgCachePartition.getKeys().size(), 'The org cache must start empty in the test');

        Long startTime = 0;
        Long endTime = 0;
        Long totalTimeCacheMiss = 0;
        Long totalTimeCacheHit = 0;

        startTime = System.currentTimeMillis();
        Map<String, Map<String, Map<String, Business_Config__c>> > moam1 = LibBusinessConfig.motherOfAllBusinessMaps;
        endTime = System.currentTimeMillis();
        totalTimeCacheMiss = endTime - startTime;
        System.assertEquals(1,orgCachePartition.getKeys().size(),'The org cache must have one key after the first miss');

        startTime = System.currentTimeMillis();
        Map<String, Map<String, Map<String, Business_Config__c>> > moam2 = LibBusinessConfig.motherOfAllBusinessMaps;
        endTime = System.currentTimeMillis();
        totalTimeCacheHit = endTime - startTime;

        System.assert( totalTimeCacheMiss > totalTimeCacheHit ,'The second time must we call the method we should obtain a hit and the execution time must be less');

        Test.stopTest();
    }

    /**
     * @description test that the partion of the bussiness configs work properly
     *
     * @param None
     */
    @isTest static void readMultipartionBussinessRulesMissReload(){
        String partitionCache = 'local.BusinessConfigCache';

        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountry = UnitTestDataFactory.createCountry('PY', 'Paraguay', 'COP');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('PedidosYA', 'PedidosYA', testCountry);
        insert testCompany;
        Business_Config__c process1 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.Id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process2 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.Id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 2',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        insert new List<SObject>{process1,process2};

        Test.startTest();

        Cache.OrgPartition orgCachePartition = Cache.Org.getPartition(partitionCache);
        System.assertEquals(0,orgCachePartition.getKeys().size(), 'The org cache must start empty in the test');

        Map<String, Map<String, Map<String, Business_Config__c>> > moam1 = LibBusinessConfig.motherOfAllBusinessMaps;
        System.assertEquals(1,orgCachePartition.getKeys().size(),'The org cache must have one key after the first miss');

        // Simulate a cache miss
        orgCachePartition.put( String.valueOf('0'), '' );

        // Call the method directly to force the retrieval of the cache
        Map<String, Map<String, Map<String, Business_Config__c>> > moam2 = LibBusinessConfig.retrieveBusinessConfigFromCache();
        System.assertEquals(1,orgCachePartition.getKeys().size(),'The org cache must have one key after the second miss');
        System.assert( orgCachePartition.get('0') instanceof Map<String, Map<String, Map<String, Business_Config__c>>>,'The org cache contents must be a valid structure');

        Test.stopTest();
    }

    @isTest
    static void testClearOrgCache() {
        PlatformCache__c setting = new PlatformCache__c();
        setting.Name = 'BusinessConfig';
        setting.CachePartitionSize__c = 3;
        insert setting;
        
        String partitionCache = 'local.BusinessConfigCache';

        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountry = UnitTestDataFactory.createCountry('PY', 'Paraguay', 'COP');
        insert testCountry;
        Company__c testCompany = UnitTestDataFactory.createCompany('PedidosYA', 'PedidosYA', testCountry);
        insert testCompany;
        Business_Config__c process1 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process2 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 2',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process3 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 3',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process4 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 4',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        Business_Config__c process5 = new Business_Config__c(Business_Rule_Name__c='TypesException',Business_Rule_Value__c='Brand,Group,Holding,Regional / Global HQ',Id_Country__c=testCountry.id,Is_Active__c=true,Parent__c=true,Process_Name__c='EventBus 5',Record_Type_Id__c='Yogiyo_Account',Type__c='Process');
        insert new List<sObject>{process1,process2,process3,process4,process5};

        Cache.OrgPartition orgCache = Cache.Org.getPartition(partitionCache);
        Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
        
        System.assertNotEquals(0,orgCache.getKeys().size(), 'Cache should not be empty');
        
        test.startTest();
            LibBusinessConfig.cleanOrgCache();
        test.stopTest();
        
        System.assertEquals(0,orgCache.getKeys().size(), 'Cache should be empty');
    }
    
    @isTest
    static void testSetMotherOfAllBusinessMaps() {
        LibBusinessConfig.motherOfAllBusinessMaps = null;
            
        test.startTest();
            LibBusinessConfig.setMotherOfAllBusinessMaps(new Map<String, Map<String, Map<String, Business_Config__c>>>());
        test.stopTest();
        
        System.assertNotEquals(null, LibBusinessConfig.motherOfAllBusinessMaps, 'motherOfAllBusinessMaps should not be null');
    }
    
    @isTest
    static void testGetBusinessConfigFromRuleMap() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c beh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        insert beh;
        Country__c my = UnitTestDataFactory.createCountry('MY', 'Malaysia', 'MYR');
        insert my;
        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',
                                                       Business_Rule_Value__c='TestTemplate',Id_Country__c=beh.id,Is_Active__c=true,
                                                       Parent__c=true,Process_Name__c='OppQuoteProcess',
                                                       Record_Type_Id__c='Talabat_Account',Type__c='Process');
        Business_Config__c b2 = new Business_Config__c(Business_Rule_Name__c = 'Status__c', 
                                                       Business_Rule_Value__c = 'Accepted', Id_Country__c = beh.id, Is_Active__c = true, 
                                                       Parent__c = true, Process_Name__c = 'OppTypeAndStageProcess', 
                                                       Record_Type_Id__c = 'Talabat_Opportunity_Quote', Type__c = 'Process');
        insert new List<Business_Config__c> { b1, b2 };
        LibBusinessConfig.createMotherOfAllBusinessMapsOptimized();
        List<RecordType> recTypeIds = [SELECT Id FROM RecordType WHERE DeveloperName = 'Talabat_Account'];
        
        test.startTest();
            Business_Config__c businessConfig = LibBusinessConfig.getBusinessConfigFromRuleMap('OppQuoteProcess', recTypeIds[0].Id, 'OppQuoteEmailTemplate');
        test.stopTest();
        
        System.assertEquals('OppQuoteProcess', businessConfig.Process_Name__c, 'Returned process name should be OppQuoteProcess');
    }
    
    @isTest
    static void testGetRecordTypesForProcess() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c beh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        insert beh;
        Country__c my = UnitTestDataFactory.createCountry('MY', 'Malaysia', 'MYR');
        insert my;
        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',
                                                       Business_Rule_Value__c='TestTemplate',Id_Country__c=beh.id,Is_Active__c=true,
                                                       Parent__c=true,Process_Name__c='OppQuoteProcess',
                                                       Record_Type_Id__c='Talabat_Account',Type__c='Process');
        insert b1;
        
        test.startTest();
            Set<String> recTypes = LibBusinessConfig.getRecordTypesForProcess('OppQuoteProcess');
        test.stopTest();
        
        System.assertEquals(true, recTypes.contains('Talabat_Account'), 'Returned set should contain Talabat_Account rec type');
    }
    
    @isTest
    static void testGetGenericProcessData() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c beh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        insert beh;
        Country__c my = UnitTestDataFactory.createCountry('MY', 'Malaysia', 'MYR');
        insert my;
        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',
                                                       Business_Rule_Value__c='TestTemplate',Id_Country__c=beh.id,Is_Active__c=true,
                                                       Parent__c=true,Process_Name__c='OppQuoteProcess',
                                                       Record_Type_Id__c='Talabat_Account',Type__c='Process');
        insert b1;
        
        test.startTest();
            Map<String, Map<String, Business_Config__c>> processData = LibBusinessConfig.getGenericProcessData('OppQuoteProcess');
        test.stopTest();
        
        System.assertEquals(true, processData.containsKey('Talabat_Account'), 'Business configs should contain Talabat_Account rec type');
        System.assertEquals(true, processData.get('Talabat_Account').containsKey('OppQuoteEmailTemplate'), 'Business configs should contain key OppQuoteEmailTemplate');
    }
    
    @isTest
    static void testGetBCDataWithProAndCountryAndRecType() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c beh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        insert beh;
        Country__c my = UnitTestDataFactory.createCountry('MY', 'Malaysia', 'MYR');
        insert my;
        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',
                                                       Business_Rule_Value__c='TestTemplate',Id_Country__c=beh.id,Is_Active__c=true,
                                                       Parent__c=true,Process_Name__c='OppQuoteProcess',
                                                       Record_Type_Id__c='Talabat_Account',Type__c='Process');
        insert b1;
        
        test.startTest();
             Map<String,Map<String,Map<String, Business_Config__c>>> bcData = LibBusinessConfig.getBCDataWithProAndCountryAndRecType('OppQuoteProcess', new List<String> { 'Bahrain' }, new List<String> {'Talabat_Account'});
        test.stopTest();
        
        System.assertEquals(true, bcData.keySet() != null);
        System.assertEquals(true, bcData.containsKey('Talabat_Account'), 'Business configs should contain Talabat_Account rec type');
        System.assertEquals(true, bcData.get('Talabat_Account').containsKey('Bahrain'), 'Business configs should contain key Bahrain');
    }
    
    @isTest
    static void testGetBCDataWithProAndCountryAndRecType_WithoutCountry() {
        UnitTestDataFactory.getRecordtypeValues();
        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',
                                                       Business_Rule_Value__c='TestTemplate',Id_Country__c=null, Is_Active__c=true,
                                                       Parent__c=true,Process_Name__c='OppQuoteProcess',
                                                       Record_Type_Id__c='Talabat_Account',Type__c='Process');
        insert b1;
        
        test.startTest();
             Map<String,Map<String,Map<String, Business_Config__c>>> bcData = LibBusinessConfig.getBCDataWithProAndCountryAndRecType('OppQuoteProcess', new List<String> { 'Bahrain' }, new List<String> {'Talabat_Account'});
        test.stopTest();
        
        System.assertEquals(true, bcData.keySet() != null);
        System.assertEquals(true, bcData.containsKey('Talabat_Account'), 'Business configs should contain Talabat_Account rec type');
        System.assertEquals(true, bcData.get('Talabat_Account').containsKey('ALL'), 'Business configs should contain key ALL');
    }
    
    @isTest
    static void testCreateMotherOfAllBusinessMapsOptimized() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c beh = UnitTestDataFactory.createCountry('BH', 'Bahrain', 'BHD');
        insert beh;
        Country__c my = UnitTestDataFactory.createCountry('MY', 'Malaysia', 'MYR');
        insert my;
        Business_Config__c b1 = new Business_Config__c(Business_Rule_Name__c='OppQuoteEmailTemplate',
                                                       Business_Rule_Value__c='TestTemplate',Id_Country__c=beh.id,Is_Active__c=true,
                                                       Parent__c=true,Process_Name__c='OppQuoteProcess',
                                                       Record_Type_Id__c='Talabat_Account',Type__c='Process');
        Business_Config__c b2 = new Business_Config__c(Business_Rule_Name__c = 'Status__c', 
                                                       Business_Rule_Value__c = 'Accepted', Id_Country__c = beh.id, Is_Active__c = true, 
                                                       Parent__c = true, Process_Name__c = 'OppTypeAndStageProcess', 
                                                       Record_Type_Id__c = 'Talabat_Opportunity_Quote', Type__c = 'Process');
        insert new List<Business_Config__c> { b1, b2 };
        
        test.startTest();
            Map<String,Map<String,Map<String, Business_Config__c>>> moam = LibBusinessConfig.createMotherOfAllBusinessMapsOptimized();
        test.stopTest();
        
        System.assertEquals(true, moam.keySet() != null, 'moam should not be empty');
    }



    @isTest
    static void testDetermineApproverMap() {
        UnitTestDataFactory.getRecordtypeValues();
        Country__c cd = UnitTestDataFactory.createCountry('CD', 'Colombia', 'COP');
        insert cd;
        Account acco = UnitTestDataFactory.createAccount('TEST', cd, 'CD_Account');
        acco.Type = 'Branch - main';
        insert acco;
        Opportunity oppt = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'CD_Opportunity', Date.today());
        oppt.Business_Type__c = 'New Business';
        Opportunity oppt2 = UnitTestDataFactory.createOpportunity(acco.Name, acco, 'CD_Opportunity', Date.today());
        oppt2.Business_Type__c = 'New Business';
        insert new List<Opportunity>{oppt, oppt2};
        Case acase = UnitTestDataFactory.createCase(acco, 'New', 'Quality Check', '', '', cd, 'CD_Entry_Case', '');
        acase.Stage_1_Completed__c = true;
        acase.Opportunity__c = oppt.Id;
        acase.Closed_Reason__c = 'Take Online';

        Case acase1 = UnitTestDataFactory.createCase(acco, 'Please Check', 'Quality Check', '', '', cd, 'CD_Entry_Case', '');
        acase1.Opportunity__c = oppt2.Id;
        acase1.Closed_Reason__c = 'Take Online';

        List<Case> caseList = new List<Case>{acase, acase1};
        insert caseList;

        Business_Config__c businessConfig0_1 = UnitTestDataFactory.createBusinessConfig('QualityCheckInternalCase', 'Process','validAccountForSecondStage', acco.Type, cd.Id, 'CD_Opportunity', true, true );
        Business_Config__c businessConfig0_2 = UnitTestDataFactory.createBusinessConfig('QualityCheckInternalCase', 'Process','validOppBusinessTypeForSecondStage', oppt.Business_Type__c, cd.Id, 'CD_Opportunity', true, false );
        Business_Config__c businessConfig0_3 = UnitTestDataFactory.createBusinessConfig('QualityCheckInternalCase', 'Process', 'assignmentMap', '{"Germany":"00G1r000003JwK5","Bahrain":"00Gw00000034PPe","Colombia":"00Gw00000034PPe","Kuwait":"00Gw00000034PPe","Lebanon":"00Gw00000034PPe","Oman":"00Gw00000034PPe","Qatar":"00Gw00000034PPe","Kingdom of Saudi Arabia":"00Gw00000034PPe","United Arab Emirates":"00Gw00000034PPe","Jordan":"00Gw00000034PPe"}', cd.Id, 'CD_Opportunity', true, false );
        Business_Config__c businessConfig0_4 = UnitTestDataFactory.createBusinessConfig('QualityCheckInternalCase', 'Process', 'recordTypeMap', '{"Germany":"0121r000000V9wh","Bahrain":"012w0000000MPceAAG","Colombia":"012w0000000MPceAAG","Lebanon":"012w0000000MPceAAG","Oman":"012w0000000MPceAAG","Qatar":"012w0000000MPceAAG","Kingdom of Saudi Arabia":"012w0000000MPceAAG","United Arab Emirates":"012w0000000MPceAAG","Jordan":"012w0000000MPceAAG"}', cd.Id, 'CD_Opportunity', true, false );
        Business_Config__c businessConfig0_5 = UnitTestDataFactory.createBusinessConfig('QualityCheckInternalCase', 'Process','QualityCheckCaseSecondStage', 'RecordTypeId=012w0000000MPce,Type=Quality Check,subject=Quality Check,status=Operation Check,ownerid=00Gw00000034QshEAE', cd.Id, 'CD_Opportunity', true, true );
        Map<String, Business_Config__c> bconfMap_1 = new Map<String, Business_Config__c>{businessConfig0_1.Business_Rule_Name__c => businessConfig0_1, businessConfig0_2.Business_Rule_Name__c => businessConfig0_2, businessConfig0_3.Business_Rule_Name__c => businessConfig0_3, businessConfig0_4.Business_Rule_Name__c => businessConfig0_4, businessConfig0_5.Business_Rule_Name__c => businessConfig0_5};
        Map<String, Map<String, Business_Config__c>> bconfMap_1f = new Map<String, Map<String, Business_Config__c>>{'CD_Opportunity' => bconfMap_1};
        ClsOpportunityProcessor.moam = new Map<String, Map<String, Map<String, Business_Config__c>>>{businessConfig0_1.Process_Name__c => bconfMap_1f};
        
        Test.startTest();
            Map<String,Map<string,OpportunityTeamMember>> oppTeamMembers = LibBusinessConfig.determineApproverMap(oppt.Id);
        Test.stopTest();

        System.assertNotEquals(null, oppTeamMembers, 'Returned map should not be null');
    }

}