force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LiveChatTranscript/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Myanmar</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>Customer ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ChatPageController.cls
/**
* @author: Nithin Pandhem
* @date 17.03.2020.
* @description:Apex Controller for a oneView Iframe lightning component.
*/
public class ChatPageController{
    private static Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;

    /***
    * @description This apex method is called from Init handler 
    * SCC-141 : OneView Iframe on ChatPage
    * @return String
    */
    @auraEnabled
    public static string getOneViewUrl(String chatRecId,String iFrameUrl){
        String baseUrl =iFrameUrl;
        Map<String,Map<String, Business_Config__c>> mapBusinessLogic = moam.get('ChatBotConfigs');
        Map <String, Business_Config__c> mapBusinessRules = mapBusinessLogic.get('Global_Config');
        Map<String, String> entityMap = (Map<String, String>) JSON.deserialize(mapBusinessRules.get('platformEntityMapping').Business_Rule_Value__c,Map<String, String>.class);
        if(entityMap.isEmpty()){
            return baseUrl;
        }
        String chatId = chatRecId;
        String platform;
        String country;
        string entity;
        string orderId;
        String customerid;
        String oneViewUrl;
        List<LiveChatTranscript>  chatList = LiveChatTranscriptSelector.getChatCaseFieldsByChatTranscriptsId(chatId);
        if(chatList.size()==0){
            return baseUrl;
        }
        try{
            String platformEntityValue = chatList[0].Case.Platform__c+'_'+chatList[0].Case.Country__c;
            if(!entityMap.containsKey(platformEntityValue)){
                return baseUrl;
            }else{
                entity = entityMap.get(platformEntityValue);
            }
            orderId = chatList[0].Case.Order_Number__c;
            customerid  = chatList[0].Case.Customer_ID__c;
            oneViewUrl = baseUrl+'?userId='+customerid+'&orderId='+orderId+'&globalEntityId='+entity;
            return oneViewUrl;
        }catch(Exception ex){
            LoggingUtility.logError(ChatPageController.class.getName(),'Error => ' + ex.getMessage() + '\nLine Number : ' + ex.getLineNumber());
            return  baseUrl;
        }
    }
}