force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Id_Opportunity_Quote_Line_Item__r.Id_List_Service_Price__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the id of the opportunity</description>
    <label>Id Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/List_Product_Group__c.object-meta.xml
<CustomObject>
    <description>this is the collection name of the group for products</description>
    <label>List Product Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Product Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Group__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this product group is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Product Groups</relationshipLabel>
    <relationshipName>List_Product_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Group__c/recordTypes/FI_List_Product_Group.recordType-meta.xml
<RecordType>
    <fullName>FI_List_Product_Group</fullName>
    <active>true</active>
    <label>FI List Product Group</label>
</RecordType>

force-app/main/default/objects/List_Product_Price__c/List_Product_Price__c.object-meta.xml
<CustomObject>
    <description>this holds the list price for products, this is linked to Opportunity product</description>
    <label>List Product Price</label>
    <nameField>
        <displayFormat>LPP-{000000}</displayFormat>
        <label>ListPrice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Products Price</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Product_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which product belongs.</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Products Price</relationshipLabel>
    <relationshipName>List_Products_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Id_List_Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Id_List_Product_Group__c</fullName>
    <description>this information gives you to which product group this product belongs</description>
    <label>List Product Group</label>
    <referenceTo>List_Product_Group__c</referenceTo>
    <relationshipName>Id_List_Price_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this attribute activates the product, so that this product is able to select in the opportunity</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <description>Product Type to determine the Asset Type</description>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
            <value>
                <fullName>Exclusive Special Offer</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Online Marketing</fullName>
            </value>
            <value>
                <fullName>White Label Web</fullName>
            </value>
            <value>
                <fullName>White Label App</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Premium placement</fullName>
            </value>
            <value>
                <fullName>Premium Listing</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Dish Level Photoshoot</fullName>
            </value>
            <value>
                <fullName>Merchandise</fullName>
            </value>
            <value>
                <fullName>Car Leasing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Premium placement - 1 Month</fullName>
            </value>
            <value>
                <fullName>Penalty</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Add_On__c.field-meta.xml
<CustomField>
    <fullName>Requires_Add_On__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Asset__c.field-meta.xml
<CustomField>
    <fullName>Requires_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a product requires an asset</description>
    <label>Requires Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/fields/Requires_Branding__c.field-meta.xml
<CustomField>
    <fullName>Requires_Branding__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Branding</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Product_Price__c/recordTypes/FI_List_Product_Price.recordType-meta.xml
<RecordType>
    <fullName>FI_List_Product_Price</fullName>
    <active>true</active>
    <label>FI List Product Price</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/FI_Opportunity.recordType-meta.xml
<RecordType>
    <fullName>FI_Opportunity</fullName>
    <active>true</active>
    <businessProcess>Sweden Sales Process</businessProcess>
    <description>Finland Sales process</description>
    <label>FI Opportunity</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/FI_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>FI_Opportunity_Quote</fullName>
    <active>true</active>
    <label>FI Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Line_Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Type__c</fullName>
    <label>Line Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Sub_type__c.field-meta.xml
<CustomField>
    <fullName>Sub_type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Line_Item_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Transmission Fee</fullName>
            </value>
            <value>
                <fullName>Commission Fee</fullName>
            </value>
            <value>
                <fullName>Online Payment Fee</fullName>
            </value>
            <value>
                <fullName>White Label Website Fee</fullName>
            </value>
            <value>
                <fullName>Order Now Button Fee</fullName>
            </value>
            <value>
                <fullName>RFV Discount</fullName>
            </value>
            <value>
                <fullName>Branding Discount</fullName>
            </value>
            <value>
                <fullName>White Label Website Discount</fullName>
            </value>
            <value>
                <fullName>Order Now Button Discount</fullName>
            </value>
            <value>
                <fullName>Exclusive Branding Discount</fullName>
            </value>
            <value>
                <fullName>Fixed Amount</fullName>
            </value>
            <value>
                <fullName>Terminal Box</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
            <value>
                <fullName>Pizza Cartons</fullName>
            </value>
            <value>
                <fullName>Menu Printing</fullName>
            </value>
            <value>
                <fullName>Recurring Fee</fullName>
            </value>
            <value>
                <fullName>Monthly Box Fee</fullName>
            </value>
            <value>
                <fullName>Setup Fee</fullName>
            </value>
            <value>
                <fullName>Promotions</fullName>
            </value>
            <value>
                <fullName>Annual Fee</fullName>
            </value>
            <value>
                <fullName>Renewal Fee</fullName>
            </value>
            <value>
                <fullName>Automatic</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Premium Placement</fullName>
            </value>
            <value>
                <fullName>Apron</fullName>
            </value>
            <value>
                <fullName>Caps</fullName>
            </value>
            <value>
                <fullName>Heating Bag</fullName>
            </value>
            <value>
                <fullName>Notepads and Pens</fullName>
            </value>
            <value>
                <fullName>Roofie</fullName>
            </value>
            <value>
                <fullName>T-shirt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/recordTypes/FI_Opportunity_Quote_Line_Item.recordType-meta.xml
<RecordType>
    <fullName>FI_Opportunity_Quote_Line_Item</fullName>
    <active>true</active>
    <label>FI Opportunity Quote Line Item</label>
</RecordType>

force-app/main/default/classes/ClsQuoteLineItemProcessor_Test.cls
@IsTest
public class ClsQuoteLineItemProcessor_Test {
	
    @testSetup 
    static void setup() {
        // CREATE COUNTRY
        Country__c fi = UnitTestDataFactory.createCountry('FI', 'Finland', 'EUR');
        insert fi;

        // CREATE COMPANY
        Company__c com = UnitTestDataFactory.createCompany('PizzaOnline_FI', 'FI', fi);
        insert com;

        // CREATE BUSINESS CONFIGS 
        List<Business_Config__c> businessConfigList = new List<Business_Config__c>();
        Business_Config__c bConfigParent 
            = UnitTestDataFactory.createBusinessConfig(
                'nintexQuoteFilters', 
                'Process',
                'Business_Type__c:New Business;Type:Contract Only', 
                'FI Quote - New Business 1', 
                fi.Id, 
                'FI_Opportunity', 
                true, 
                true);

        Map<String, String> childBRuleMap = new Map<String, String>{
            'Business_Type__c:New Business;Type:Contract Only' => 'FI Quote - New Business 1',
            'Business_Type__c:New Business;Type:Contract & Product' => 'FI Quote - New Business 1',
            'Business_Type__c:Upgrade/Upsell;Type:Product Only' => 'FI Quote - New Business 2',
            'Business_Type__c:Upgrade/Upsell;Type:Product Only;Opportunity_Quote_Line_Item__c:{"Line_Item_Type__c"="Product", "Sub_Type__c"="Premium Listing"}' => 'FI Quote - Premium Listing',
            'Business_Type__c:Upgrade/Upsell;Type:Product Only;Opportunity_Quote_Line_Item__c:{"Line_Item_Type__c"="Product", "Sub_Type__c"="Merchandise"}' => 'FI Quote - Merchandise'
        };

        businessConfigList.add(bConfigParent);
        for(String key : childBRuleMap.keySet()){
            Business_Config__c bConfigTemp = UnitTestDataFactory.createBusinessConfig(
                'nintexQuoteFilters', 'Process', key, childBRuleMap.get(key), fi.Id, 'FI_Opportunity', true, false);
            bConfigTemp.Is_Active__c = true;
            businessConfigList.add(bConfigTemp);
        }

        insert businessConfigList;

        // CREATE LIST PRODUCT GROUP
        List_Product_Group__c lpg = UnitTestDataFactory.createProductGroup(com, fi , 'Merchandise', 'FI_List_Product_Group');
        List_Product_Group__c lpg1 = UnitTestDataFactory.createProductGroup(com, fi , 'Add. Charges', 'FI_List_Product_Group');

        insert new List<List_Product_Group__c> {lpg, lpg1};

        // CREATE LIST PRODUCT PRICE
        List_Product_Price__c lpp = UnitTestDataFactory.createProduct(com, fi , 'DH Jacket', lpg.Id, 'FI_List_Product_Price', 1, true, 100, 1, false, 20);
        List_Product_Price__c lpp1 = UnitTestDataFactory.createProduct(com, fi , 'Premium Placement', lpg1.Id, 'FI_List_Product_Price', 1, true, 100, 1, false, 20);
        lpp.Product_Type__c = 'Merchandise';
        lpp1.Product_Type__c = 'Premium Listing';
        lpp.Requires_Branding__c = false;
        lpp.Requires_Asset__c = false;
        lpp.Requires_Add_On__c = true;

        insert new List<List_Product_Price__c> {lpp1, lpp};
    }
    
    /*******************************************************************************************************
    * @description test for updating Quote Type in Opportunity Quote
    */
    @IsTest
    public static void testUpdateQuoteType(){
        UnitTestDataFactory.getRecordtypeValues();

        Country__c fi = [SELECT Id, Name, CurrencyIsoCode FROM Country__c WHERE Name = 'Finland'];
        Company__c com = [SELECT Id, Name FROM Company__c WHERE Country__c =: fi.Id];
        
        List<List_Product_Price__c> listProductPriceList = [SELECT Id, Name, Product_Type__c, Id_List_Product_Group__c
                                                            FROM List_Product_Price__c];
        Map<Id, List_Product_Group__c> listProductGroupMap = new Map<Id, List_Product_Group__c>(
            [SELECT Id, Name
             FROM List_Product_Group__c]
        );

        // CREATE ACCOUNT
        Account acc = new Account();
        acc = UnitTestDataFactory.createAccount('Test FI Account 1', fi, 'FP_Account');
        insert acc;

        //CREATE CONTACT
        List<Contact> conList = UnitTestDataFactory.createContacts(new List<Account>{acc}, 'FI Contact', 'Test', '', 'Owner', 1, 'testFPContact', 'FP_Contact');
        insert conList;

        // CREATE OPPORTUNITY
        Opportunity opportunity;
        List<Opportunity> opportunityList = new List<Opportunity>();
        for(Integer counter = 0; counter < 2; counter++){
            opportunity = UnitTestDataFactory.createOpportunity(acc.Name + ' ' + (counter + 1), acc, 'FI_Opportunity', Date.today());
            opportunity.Business_Type__c = 'Upgrade/Upsell';
            opportunity.Type = 'Product Only';
            opportunityList.add(opportunity);
        }
        
        insert opportunityList;

        // CREATE OPPORTUNITY QUOTE
        Opportunity_Quote__c oppQuoteTemp;
        List<Opportunity_Quote__c> oppQuoteList = new List<Opportunity_Quote__c>();
        for(Opportunity oppTemp : opportunityList){
            oppQuoteTemp = new Opportunity_Quote__c(Id_Opportunity__c = oppTemp.Id, Status__c = 'Accepted');
            oppQuoteTemp.RecordTypeId = LibRecordTypeHelper.getRecordTypeValue('FI_Opportunity_Quote');
            oppQuoteTemp.Id_Account__c = acc.Id;
            oppQuoteList.add(oppQuoteTemp);
        }
        
        insert oppQuoteList;

        // CREATE OPPORTUNITY QUOTE LINE ITEM
        Opportunity_Quote_Line_Item__c oppQuoteLineItemTemp;
        List<Opportunity_Quote_Line_Item__c> oppQuoteLineItemList = new List<Opportunity_Quote_Line_Item__c>();
        Integer counter = 0;
        for(Opportunity_Quote__c oppQuoteLoop : oppQuoteList){
            oppQuoteLineItemTemp = UnitTestDataFactory.createOpportunityQuoteLineItems(oppQuoteLoop, listProductPriceList[counter].Id, listProductGroupMap.get(listProductPriceList[counter].Id_List_Product_Group__c).Id, 4, true, 'FI_Opportunity_Quote_Line_Item', 1, '20', 200.0, 2, 300.0, 'Product')[0];
            oppQuoteLineItemTemp.Id_Opportunity__c = oppQuoteLoop.Id_Opportunity__c;
            oppQuoteLineItemTemp.Sub_Type__c = listProductPriceList[counter++].Product_Type__c;

            oppQuoteLineItemList.add(oppQuoteLineItemTemp);
        }

        Test.startTest();
            insert oppQuoteLineItemList;
        Test.stopTest();

        oppQuoteList = [SELECT Id, Name, Quote_Type__c FROM Opportunity_Quote__c];
        
        for(Opportunity_Quote__c oppQuote : oppQuoteList){
            if(oppQuote.Quote_Type__c != 'FI Quote - Merchandise' && oppQuote.Quote_Type__c != 'FI Quote - Premium Listing'){
                system.assert(false, 'Quote Type not correctly updated; ' + oppQuote.Quote_Type__c);
            }
        }
    }
}