force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountryCompanyMapping__c/CountryCompanyMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CountryCompanyMapping</label>
</CustomObject>

force-app/main/default/objects/CountryCompanyMapping__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/xAL_Address__c.object-meta.xml
<CustomObject>
    <label>xAL Address</label>
    <nameField>
        <displayFormat>XAL-ADD-{0000}</displayFormat>
        <label>xAL Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>xAL Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xAL_Address__c/fields/Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Address_Id__c</fullName>
    <label>Address Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Province</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Suburb</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_AdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>xAL_AdministrativeAreaName__c</fullName>
    <label>Administrative Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_Country__c.field-meta.xml
<CustomField>
    <fullName>xAL_Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_DependentLocalityName__c.field-meta.xml
<CustomField>
    <fullName>xAL_DependentLocalityName__c</fullName>
    <label>Dependent Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_LocalityName__c.field-meta.xml
<CustomField>
    <fullName>xAL_LocalityName__c</fullName>
    <label>Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_SubAdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>xAL_SubAdministrativeAreaName__c</fullName>
    <label>SubAdministrative Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Uruguay</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Laos</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Myanmar</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <description>Countries for xAL model</description>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/xALAddress_Utils.cls
/**
* @author Mantas Jurkunas
* @date 09.09.2019
*
* @description Utility class for xAL_Address
*/

public with sharing class xALAddress_Utils {

    public static final Set<String> ID_FIELDS = new Set<String> {
            xAL_Address__c.xAL_Country__c.getDescribe().getLocalName(),
            xAL_Address__c.xAL_AdministrativeAreaName__c.getDescribe().getLocalName(),
            xAL_Address__c.xAL_SubAdministrativeAreaName__c.getDescribe().getLocalName(),
            xAL_Address__c.xAL_LocalityName__c.getDescribe().getLocalName(),
            xAL_Address__c.xAL_DependentLocalityName__c.getDescribe().getLocalName()
    };

    public static void populateAddressIds(List<xAL_Address__c> addresses) {
        for (xAL_Address__c address: addresses) {
            address.Address_Id__c = combineAddressFieldsToId(address, ID_FIELDS);
        }
    }

    private static String combineAddressFieldsToId(xAL_Address__c address, Set<String> fieldNames) {
        String addressId = '';
        for (String fieldName: fieldNames) {
            addressId += address.get(fieldName) == null ? '' : address.get(fieldName);
        }
        return addressId;
    }

    public static List<xAL_Address__c> getNextAddressLineValues(xAL_Address__c xALAddress) {
        List<xAL_Address__c> addresses = new List<xAL_Address__c>();
        CountryCompanyMapping__c companyInfo = CountryCompanyMapping__c.getInstance(xALAddress.xAL_Country__c);
        String recordTypeId = LibRecordTypeHelper.getRecordTypeValue(companyInfo.Company_Code__c + '_Account');
        Business_Config__c businessConfig = LibBusinessConfig.getBusinessConfigFromRuleMap('xALAddressObject', recordTypeId,xALAddress.xAL_Country__c + 'AddressMappingJSON');
        if(businessConfig == null) {
            businessConfig = LibBusinessConfig.getBusinessConfigFromRuleMap('xALAddressObject', recordTypeId,'AddressMappingJSON');
        }
        if (businessConfig == null) {
            return addresses;
        }
        Map<String, String> typeMap = (Map<String, String>) JSON.deserialize(businessConfig.Business_Rule_Value__c, Map<String, String>.class);
        if (!typeMap.containsKey(xALAddress.Type__c)) {
            return addresses;
        }
        addresses = xALAddress_Selector.getByIdAndType(xALAddress, typeMap.get(xALAddress.Type__c), getValueField(xALAddress));
        return addresses;
    }

    private static String getValueField(xAL_Address__c xALAddress) {
        String valueField;
        List<String> fieldNames = new List<String>(ID_FIELDS);
        for (Integer index=fieldNames.size()-1; index >= 0; index--) {
            if (xALAddress.get(fieldNames.get(index)) != null) {
                valueField = fieldNames.get(index);
                break;
            }
        }
        return valueField;
    }
  
    /**
    * @author William Castillo
    * @date 05.02.2020
    * @description get a map with the visibility of the text fields that should be display in the xal address moodel
    * @param CountryString
    * @return map<String,Boolean> key fielsd, values visible or not.
    */
    public static map<String,Boolean> getNextAddresslineText(String CountryString) {
        Map<String, map<String,Boolean>> mpFieldsbyCountry  = new Map<String, map<String,Boolean>>();
        map<String,Boolean> mpFields = new map<String,Boolean>();
        CountryCompanyMapping__c companyInfo = CountryCompanyMapping__c.getInstance(CountryString);
        String recordTypeId = LibRecordTypeHelper.getRecordTypeValue(companyInfo.Company_Code__c + '_Account');
        Business_Config__c businessConfig = LibBusinessConfig.getBusinessConfigFromRuleMap('xALAddressObject', recordTypeId,'TextFieldVisibility');

        if (businessConfig == null) {
            return mpFields;
        }
        mpFieldsbyCountry = (Map<String, map<String,Boolean>>) JSON.deserialize(businessConfig.Business_Rule_Value__c, Map<String, map<String,Boolean>>.class);
        if(mpFieldsbyCountry.containsKey(CountryString)){
            return mpFieldsbyCountry.get(CountryString);
        }
        return mpFields;
    }

}