force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Opportunity.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Lost_Reason__c</fullName>
    <label>Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>0% Commission Upselling</fullName>
            </value>
            <value>
                <fullName>Auto Closed</fullName>
            </value>
            <value>
                <fullName>Bad debtor</fullName>
            </value>
            <value>
                <fullName>Best Price Guarantee</fullName>
            </value>
            <value>
                <fullName>Business Closed</fullName>
            </value>
            <value>
                <fullName>Business Temporarily out of service</fullName>
            </value>
            <value>
                <fullName>Cannot Contact</fullName>
            </value>
            <value>
                <fullName>Capacity - Competitor</fullName>
            </value>
            <value>
                <fullName>Capacity - Driver Issue</fullName>
            </value>
            <value>
                <fullName>Capacity - Order Volume</fullName>
            </value>
            <value>
                <fullName>Capacity - Own Website</fullName>
            </value>
            <value>
                <fullName>Change of Business Name</fullName>
            </value>
            <value>
                <fullName>Comission too high</fullName>
            </value>
            <value>
                <fullName>Commission Upselling</fullName>
            </value>
            <value>
                <fullName>Contract never received</fullName>
            </value>
            <value>
                <fullName>Decision Maker Not Reached</fullName>
            </value>
            <value>
                <fullName>Delivery Area / MOV</fullName>
            </value>
            <value>
                <fullName>Does not accept Online Payment</fullName>
            </value>
            <value>
                <fullName>Do not Contact</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Exclusive with competitor</fullName>
            </value>
            <value>
                <fullName>Franchise Contract - Commission Change</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>High Failure Rate</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Issues with payments to restaurant</fullName>
            </value>
            <value>
                <fullName>Language issues</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Legal Issues</fullName>
            </value>
            <value>
                <fullName>Onboarding Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CloseOpportunities_Utils.cls
/**
* @author Mantas Jurkunas
* @date 14.04.2020
*
* @description Utility class containing methods related to closing opportunities with failed onboarding
*/
public without sharing class CloseOpportunities_Utils {
    private static CloseOpportunities_Utils utilsInstance;
    private static final String LOG_NAME = 'CloseOpportunities';
    private static final String LOG_TYPE = 'LOGGING';
    private static final String LOG_SUBTYPE = 'CLose Lost Opportunities';
    /**
     * @description Business config process name
     */
    public static final String AUTO_CLOSE_PROCESS_NAME = 'OpportunityAutoClose';
    private static final String CASE_LIMIT = 'OnboardingFailedCaseLimit';
    private static final String FOLLOWUP_LIMIT = 'FailedOpportunitiesFollowupLimit';

    private CloseOpportunities_Utils() {
    }

    /**
    * @description get instance of the utility class
    *
    * @return instance of this class
    */
    public static CloseOpportunities_Utils getInstance() {
        if (utilsInstance == null) {
            utilsInstance = new CloseOpportunities_Utils();
        }
        return utilsInstance;
    }

    /**
    * @description Method checks if opportunity has reached the limit of onboarding failed cases and closes the opportunity.
    *
    * @param failedCases filtered cases with onboarding failed
    *
    * @return opportunities that have to be closed
    */
    public List<Opportunity> checkFailedOpportunities(List<Case> failedCases) {
        Set<Id> opportunityIds = ClsSObjectUtils.extractSetIds(failedCases, Case.Opportunity__c.getDescribe().getLocalName());
        List<Case> relatedCases = CaseSelector.getOnboardingFailedByOppIds(opportunityIds);
        if (relatedCases.isEmpty()) { return new List<Opportunity>(); }
        Map<Id, List<Case>> oppCaseMap = ClsSObjectUtils.convertToIdMap(relatedCases, Case.Opportunity__c.getDescribe().getLocalName());
        return filterOpportunitiesForUpdate(oppCaseMap);
    }

    /**
    * @description Checks opportunities that are stuck in onboarding failed for too long and closes them.
    *
    * @param opportunities records that are in status 'Onboarding Failed'
    *
    * @return opportunities that have to be closed
    */
    public List<Opportunity> checkFailedOpportunities(List<Opportunity> opportunities) {
        List<OpportunityFieldHistory> fieldHistories = getOpportunityFieldHistories(new Map<Id, Opportunity>(opportunities).keySet());
        if (fieldHistories.isEmpty()) { return new List<Opportunity>(); }
        Map<Id, List<OpportunityFieldHistory>> oppFieldHistoryMap = ClsSObjectUtils.convertToIdMap(fieldHistories, OpportunityFieldHistory.OpportunityId.getDescribe().getLocalName());
        return filterOpportunitiesForUpdate(opportunities, oppFieldHistoryMap);
    }

    private List<Opportunity> filterOpportunitiesForUpdate(Map<Id, List<Case>> relatedOppCaseMap) {
        Set<Opportunity> filteredOpportunities = new Set<Opportunity>();
        for (Id opportunityId: relatedOppCaseMap.keySet()) {
            List<Case> relatedCases = relatedOppCaseMap.get(opportunityId);
            Business_Config__c caseLimitConfig = LibBusinessConfig.getBusinessConfigFromRuleMap(AUTO_CLOSE_PROCESS_NAME, relatedCases.get(0).Opportunity__r.RecordTypeId, CASE_LIMIT);
            Boolean isCaseLimitNotReached = caseLimitConfig == null || relatedCases.size() < Integer.valueOf(caseLimitConfig.Business_Rule_Value__c);
            if (isCaseLimitNotReached) { continue; }
            Opportunity failedOpp = setOpportunityLost(new Opportunity(Id = opportunityId));
            filteredOpportunities.add(failedOpp);
        }
        return new List<Opportunity> (filteredOpportunities);
    }

    private List<Opportunity> filterOpportunitiesForUpdate(List<Opportunity> opportunities, Map<Id, List<OpportunityFieldHistory>> oppFieldHistoryMap) {
        List<Opportunity> filteredOpportunities = new List<Opportunity>();
        for (Opportunity opp: opportunities) {
            if (!oppFieldHistoryMap.containsKey(opp.Id)) { continue; }
            Business_Config__c followupLimitConfig = LibBusinessConfig.getBusinessConfigFromRuleMap(AUTO_CLOSE_PROCESS_NAME, opp.RecordTypeId, FOLLOWUP_LIMIT);
            Datetime historyDate = oppFieldHistoryMap.get(opp.Id).get(0).CreatedDate;
            // Check if test is running since created date cannot be set on the field history when testing
            Boolean isOpportunityNotExpired = followupLimitConfig == null || !Test.isRunningTest() && historyDate.date().daysBetween(Date.today()) <= Integer.valueOf(followupLimitConfig.Business_Rule_Value__c);
            if (isOpportunityNotExpired) { continue; }
            filteredOpportunities.add(setOpportunityLost(opp));
        }
        return filteredOpportunities;
    }

    /**
    * @description method updates opportunities and logs any errors while saving
    *
    * @param opportunities records to update
    *
    * @return class instance
    */
    public CloseOpportunities_Utils updateOpportunities(List<Opportunity> opportunities) {
        List<Database.SaveResult> saveResults = Database.update(opportunities, false);
        for (Integer index = 0; index < opportunities.size(); index++) {
            if (saveResults.get(index).isSuccess()) {
                continue;
            }
            String errorMessage = ClsSObjectUtils.getErrorString(saveResults.get(index), opportunities.get(index));
            if (String.isNotEmpty(errorMessage)) {
                LoggingUtility.createLog(LOG_NAME + index, LOG_TYPE, LOG_SUBTYPE, null);
                LoggingUtility.logError(LOG_NAME + index, errorMessage);
            }
        }
        return this;
    }

    /**
    * @description commit logs that were created throughout the process
    */
    public void commitLogs() {
        LoggingUtility.commitLogs(true);
    }

    private Opportunity setOpportunityLost(Opportunity opp) {
        opp.StageName = 'Closed Lost';
        opp.Lost_Reason__c = 'Onboarding Failed';
        return opp;
    }

    private List<OpportunityFieldHistory> getOpportunityFieldHistories(Set<Id> opportunityIds) {
        // Need to return mock data since field history cannot be inserted.
        if (Test.isRunningTest()) {
            return UnitTestDataFactory.createOpportunityFieldHistories(opportunityIds);
        }
        return OpportunityFieldHistory_Selector.getByOpportunityIds(opportunityIds);
    }
}