force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_1__c</fullName>
    <label>Case Reason Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Across Journey</fullName>
            </value>
            <value>
                <fullName>Activation or deactivation of restaurant</fullName>
            </value>
            <value>
                <fullName>Billing inquiries</fullName>
            </value>
            <value>
                <fullName>Content update</fullName>
            </value>
            <value>
                <fullName>Contract and Sales inquiries</fullName>
            </value>
            <value>
                <fullName>Customer complaints or negative feedback</fullName>
            </value>
            <value>
                <fullName>Customer evaluations inquiry</fullName>
            </value>
            <value>
                <fullName>Customer inquiry before order placement</fullName>
            </value>
            <value>
                <fullName>Finance inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Live order inquiries by restaurant</fullName>
            </value>
            <value>
                <fullName>Live Order Process</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by customer</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other customer inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Other restaurant inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Partner data update</fullName>
            </value>
            <value>
                <fullName>Partner Feedback</fullName>
            </value>
            <value>
                <fullName>Post-Delivery</fullName>
            </value>
            <value>
                <fullName>Restaurant data update</fullName>
            </value>
            <value>
                <fullName>Restaurant Supply</fullName>
            </value>
            <value>
                <fullName>Sales inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Technical Inquiry</fullName>
            </value>
            <value>
                <fullName>Technical problems &amp; questions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_2__c</fullName>
    <label>Case Reason Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>9Cookies</fullName>
                <isActive>false</isActive>
                <label>9Cookies</label>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Basic profile change</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation by restaurant</fullName>
            </value>
            <value>
                <fullName>Cancellation of order by customer</fullName>
            </value>
            <value>
                <fullName>Change order details</fullName>
            </value>
            <value>
                <fullName>Changes to restaurant profile</fullName>
            </value>
            <value>
                <fullName>Change to order</fullName>
            </value>
            <value>
                <fullName>Contactless delivery</fullName>
            </value>
            <value>
                <fullName>Customer account</fullName>
            </value>
            <value>
                <fullName>Customer evaluations</fullName>
            </value>
            <value>
                <fullName>Customer reviews for partners</fullName>
            </value>
            <value>
                <fullName>Customer service complaint</fullName>
            </value>
            <value>
                <fullName>Deals update</fullName>
            </value>
            <value>
                <fullName>Delivery changes</fullName>
            </value>
            <value>
                <fullName>Delivery complaint</fullName>
            </value>
            <value>
                <fullName>Delivery inquiries</fullName>
            </value>
            <value>
                <fullName>Delivery Inquiry</fullName>
            </value>
            <value>
                <fullName>Delivery time</fullName>
            </value>
            <value>
                <fullName>Door Sticker Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Food complaint</fullName>
            </value>
            <value>
                <fullName>Food issue</fullName>
            </value>
            <value>
                <fullName>Frontend issue</fullName>
            </value>
            <value>
                <fullName>Front end website</fullName>
            </value>
            <value>
                <fullName>General customer complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ResolvedDate__c.field-meta.xml
<CustomField>
    <fullName>ResolvedDate__c</fullName>
    <description>SP-1856</description>
    <label>Resolved Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/DE_Inbound_Case.recordType-meta.xml
<RecordType>
    <fullName>DE_Inbound_Case</fullName>
    <active>true</active>
    <businessProcess>DE Inbound Process</businessProcess>
    <label>DE Inbound Case</label>
</RecordType>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/UpdateCaseReasonsCodeMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>UpdateCaseReasonsCodeMapping</label>
</CustomObject>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelNew1__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelNew1__c</fullName>
    <label>CaseReasonLevelNew1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelNew2__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelNew2__c</fullName>
    <label>CaseReasonLevelNew2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelNew3__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelNew3__c</fullName>
    <label>CaseReasonLevelNew3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelOld1__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelOld1__c</fullName>
    <label>CaseReasonLevelOld1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelOld2__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelOld2__c</fullName>
    <label>CaseReasonLevelOld2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelOld3__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelOld3__c</fullName>
    <label>CaseReasonLevelOld3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCaseReasonCoding_BatchTest.cls
/**
 * Created by c.kumari on 12.03.2019.
 */

@IsTest
public class UpdateCaseReasonCoding_BatchTest {

    @testSetup
    public static void setupData(){
        UnitTestDataFactory.getRecordtypeValues();

        Country__c c = UnitTestDataFactory.createCountry('DE','Germany', 'EUR');
        insert c;
        Account acc = UnitTestDataFactory.createAccount('UpdateCaseReasonCoding_Batch',c,'DE_Account');
        insert acc;

        List<UpdateCaseReasonsCodeMapping__c> crMap=new List<UpdateCaseReasonsCodeMapping__c>();
        UpdateCaseReasonsCodeMapping__c crMap1 = new UpdateCaseReasonsCodeMapping__c();
        crMap1.Name='CaseReason1';
        crMap1.CaseReasonLevelOld1__c='Across Journey';
        crMap1.CaseReasonLevelOld2__c='Technical Issue';
        crMap1.CaseReasonLevelOld3__c='Website issue';
        crMap1.CaseReasonLevelNew1__c='Across Journey';
        crMap1.CaseReasonLevelNew2__c='Technical Issue';
        crMap1.CaseReasonLevelNew3__c='Website issue';
        crMap1.Type__c='Customer';
        crMap.add(crMap1);
        UpdateCaseReasonsCodeMapping__c crMap2 = new UpdateCaseReasonsCodeMapping__c();
        crMap2.Name='CaseReason2';
        crMap2.CaseReasonLevelOld2__c='Technical Issue';
        crMap2.CaseReasonLevelOld3__c='Website issue';
        crMap2.CaseReasonLevelNew2__c='Technical Issue';
        crMap2.CaseReasonLevelNew3__c='Website issue';
        crMap.add(crMap2);
        UpdateCaseReasonsCodeMapping__c crMap3 = new UpdateCaseReasonsCodeMapping__c();
        crMap3.Name='CaseReason3';
        crMap3.CaseReasonLevelOld3__c='Website issue';
        crMap3.CaseReasonLevelNew3__c='Website issue';
        crMap.add(crMap3);
        UpdateCaseReasonsCodeMapping__c crMap4 = new UpdateCaseReasonsCodeMapping__c();
        crMap4.Name='CaseReason4';
        crMap4.CaseReasonLevelOld1__c='Across Journey';
        crMap4.CaseReasonLevelOld2__c='Technical Issue';
        crMap4.CaseReasonLevelNew1__c='Across Journey';
        crMap4.CaseReasonLevelNew2__c='Technical Issue';
        crMap4.Type__c='Customer';
        crMap.add(crMap4);
        UpdateCaseReasonsCodeMapping__c crMap5 = new UpdateCaseReasonsCodeMapping__c();
        crMap5.Name='CaseReason5';
        crMap5.CaseReasonLevelOld1__c='Across Journey';
        crMap5.CaseReasonLevelNew1__c='Across Journey';
        crMap.add(crMap5);
        UpdateCaseReasonsCodeMapping__c crMap6 = new UpdateCaseReasonsCodeMapping__c();
        crMap6.Name='CaseReason6';
        crMap6.CaseReasonLevelOld2__c='Technical Issue';
        crMap6.CaseReasonLevelNew2__c='Technical Issue';
        crMap.add(crMap6);
        insert crMap;

        List<Case> cases = new List<Case>();
        Case cs1 = UnitTestDataFactory.createCase(acc,'Resolved','Customer',null,'Chat',c,'DE_Inbound_Case','test');
        cs1.resolvedDate__c = Date.today().addDays(-20);
        cs1.order_number__c = '90123456789012';
        cs1.Case_Reason_Level_1__c = 'Across Journey';
        cs1.Case_Reason_Level_2__c = 'Technical Issue';
        cs1.Case_Reason_Level_3__c = 'Website issue';
        cs1.customer_email__c = 'test@test.com';
        cs1.Platform__c = 'LieferheldDE';
        cs1.Description = 'test';
        cs1.Status = 'Closed';
        cs1.Closed_Reason__c = 'Successful';
        cases.add(cs1);
        Case cs2 = UnitTestDataFactory.createCase(acc,'Resolved','Customer',null,'Chat',c,'DE_Inbound_Case','test');
        cs2.resolvedDate__c = Date.today().addDays(-2);
        cs2.order_number__c = '90123456789012';
        cs2.Case_Reason_Level_1__c = 'Across Journey';
        cs2.Case_Reason_Level_2__c = 'Technical Issue';
        cs2.customer_email__c = 'test@test.com';
        cs2.Platform__c = 'LieferheldDE';
        cs2.Description = 'test';
        cs2.Status = 'Closed';
        cs2.Closed_Reason__c = 'Successful';
        cases.add(cs2);

        Case cs3 = UnitTestDataFactory.createCase(acc,'Resolved','Customer',null,'Chat',c,'DE_Inbound_Case','test');
        cs3.resolvedDate__c = Date.today().addDays(-2);
        cs3.order_number__c = '90123456789012';
        cs3.Case_Reason_Level_1__c = 'Across Journey';
        cs3.customer_email__c = 'test@test.com';
        cs3.Platform__c = 'LieferheldDE';
        cs3.Description = 'test';
        cs3.Status = 'Closed';
        cs3.Closed_Reason__c = 'Successful';
        cases.add(cs3);
        insert cases;

        //update new List<Case>{cs1};

        // create configs
        Business_Config__c config = UnitTestDataFactory.createBusinessConfig('BatchUpdateCaseResonCoding', 'Process', 'recordTypes', 'DE_Inbound_Case,Talabat_Inbound_Case', null, 'Global_Config', true, true);
        Business_Config__c config1 = UnitTestDataFactory.createBusinessConfig('BatchUpdateCaseResonCoding', 'Process', 'closedDateRange', '-30', null, 'Global_Config', true, false);
        insert new List<sObject>{config,config1};
    }

    @isTest
    public static void testUpdateCaseReasonCoding(){
        String CRON_EXP = '0 0 0 15 3 ? 2022';
        datetime d=datetime.newInstance(2019,1,1);
        Test.startTest();
        UpdateCaseReasonCoding_Batch batch = new UpdateCaseReasonCoding_Batch('IsClosed = true');
        Id batchjobId = Database.executebatch(batch);
        Test.stopTest();
        List<Case> cases = [Select Id from Case where IsCaseReasonUpdated__c = true];
        system.assertEquals(3,cases.size());
    }

}