force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Croatia</fullName>
            </value>
            <value>
                <fullName>Czech</fullName>
                <isActive>false</isActive>
                <label>Czech</label>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Dominican Republic</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Global</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Jordan</fullName>
            </value>
            <value>
                <fullName>Kingdom of Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LiveChatTranscript/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Myanmar</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <externalId>true</externalId>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AutoCloseTab_AuraController.cls
public class AutoCloseTab_AuraController {
    @AuraEnabled
    public static String isCaseClosed(Id recId){
        Case caseRec = new Case();
        String caseId='';
        try {
            if (string.valueOf(recId.getSobjectType()) == 'LiveChatTranscript') {
                List<LiveChatTranscript> chats = LiveChatTranscriptSelector.getChatCaseFieldsByChatTranscriptsId(recId);
                if (chats.size() > 0) {
                    caseId = chats[0].CaseId;
                }
            } else if (string.valueOf(recId.getSobjectType()) == 'Case') {
                caseId = recId;
            }
            if (caseId == '') {
                return null;
            }
            caseRec = CaseSelector.getCaseDetailsById(caseId);
            if (caseRec == null) {
                caseRec.Status = null;
            }
            return caseRec.Status;
        } catch(Exception e){
            system.debug('Logging error: '+e);
            return null;
        }
    }

    /* Name: sendSurvey
     * @description Method to set the callout parameters (endpoint and body) based on the platform & invoke the sendSurveyCallout method.
     * @return String (generic message to notify of the failure in sending survey)
     * Params recId: Record Id of the chat
     * Dependency: PostChatSurvey business config
     */
    @AuraEnabled
    public static String sendSurvey(String recId){
        //Initial null checks on business config.
        Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
        Map<String, Map<String, Business_Config__c>> mapPostChatBusinessLogic = moam.get('PostChatSurvey');
        Map<String, Map<String, Business_Config__c>> mapChatBotConfigBusinessLogic = moam.get('ChatBotConfigs');
        Boolean isBusinessConfigNull = mapChatBotConfigBusinessLogic==null || mapChatBotConfigBusinessLogic.isEmpty() || mapChatBotConfigBusinessLogic.get('Global_Config')==null ||
                mapPostChatBusinessLogic==null || mapPostChatBusinessLogic.isEmpty() || mapPostChatBusinessLogic.get('Global_Config')==null;
        if(isBusinessConfigNull){
            return 'No business config present';
        }
        Map<String, Business_Config__c> mapPostChatBusinessRules = mapPostChatBusinessLogic.get('Global_Config');
        Map<String, Business_Config__c> mapPlatformEntityBusinessRules = mapChatBotConfigBusinessLogic.get('Global_Config');
        List<LiveChatTranscript> currentRecord = LiveChatTranscriptSelector.getChatCaseFieldsByChatTranscriptsId(recId);
        if(currentRecord.isEmpty() || String.isBlank(currentRecord[0].Platform__c)){
            return 'No platform on chat';
        }

        //setting business config value to _STG if sandbox
        String keyForBusinessConfig='';
        if([SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox){
            keyForBusinessConfig = currentRecord[0].Platform__c+Label.Staging_Suffix;
        }
        else{
            keyForBusinessConfig = currentRecord[0].Platform__c;
        }
        if(!mapPostChatBusinessRules.containsKey(keyForBusinessConfig)){
            return 'No business config present for the platform';
        }

        //Getting values from business config
        String endpoint=mapPostChatBusinessRules.get('Endpoint').Business_Rule_Value__c;
        String bodyStructure=mapPostChatBusinessRules.get('Body').Business_Rule_Value__c;
        Map<String,String> platformBusinessRuleRec = (Map<String,String>) JSON.deserialize(mapPostChatBusinessRules.get(keyForBusinessConfig).Business_Rule_Value__c, Map<String,String>.class);
        Map<String,String> entityMap	= (Map<String,String>)JSON.deserialize(mapPlatformEntityBusinessRules.get('platformEntityMapping').Business_Rule_Value__c,Map<String, String>.class);
        boolean isPlatformEntityRecordByCasePresent = currentRecord[0].CaseId!=null && entityMap.containsKey(currentRecord[0].Case.Platform__c+'_'+currentRecord[0].Case.Country__c);
        if(!isPlatformEntityRecordByCasePresent) {
            return 'No platform entity mapping found';
        }
        String platformEntityValue = entityMap.get(currentRecord[0].Case.Platform__c+'_'+currentRecord[0].Case.Country__c);
        //Setting values for custom URL and Request Body based on business config
        String customSurveyURI = setSurveyURL(platformBusinessRuleRec.get('surveyURL'),currentRecord[0],platformEntityValue,mapPostChatBusinessRules.get('SurveyURLMapping').Business_Rule_Value__c);
        if(customSurveyURI=='') {
            return 'Failed to create survey url';
        }
        String requestBody = setRequestBody(bodyStructure, platformBusinessRuleRec, customSurveyURI, currentRecord[0]);

        //make callout to send survey
        sendSurveyCallout(endpoint, requestBody, currentRecord[0].Id);
        return 'Success';
    }

    /* Name: setSurveyURL
     * @description Method to set the survey url to be sent to the customer.
     * @return String (formulated survey url)
     * Params surveyURL: surveylink, chatRec: chat transcript rercord, platformEntityValue: global entity id based on platform and country, surveyURLMapping: url parameters
     */
    public static String setSurveyURL(String surveyURL, LiveChatTranscript chatRec, String platformEntityValue, String surveyURLMapping){
        Map<String,String> surveyURLMap = (Map<String,String>)JSON.deserialize(surveyURLMapping,Map<String, String>.class);
        String urlParams='';
        for(String param:surveyURLMap.keySet()){
            List<String> field=surveyURLMap.get(param).split('&&');
            String fieldValue= (string)chatRec.getSObject(field[0]).get(field[1]);
            if(fieldValue == null){
                continue;
            }
            urlParams=urlParams+'&'+param+'='+fieldValue.toLowerCase();
        }
        if(urlParams=='') {
            return '';
        }
        surveyURL = surveyURL + '?survey_origin=braze&global_entity_id=' + platformEntityValue.toLowerCase() + urlParams;
        return surveyURL;
    }

    /* Name: setRequestBody
     * @description Method to set the request body to be sent to braze system.
     * @return String (formulated request body)
     * Params bodyStructure: json request body, paramMapping: key value map for body parameters, surveyURL: url of the survey to be sent to the customer, chatRec: live chat transcript record
     */
    public static String setRequestBody(String bodyStructure, Map<String,String> paramMapping, String surveyURL, LiveChatTranscript chatRec){
        String body='';
        body=bodyStructure.replace('<email__c>',chatRec.Email__c);
        //Updating keys/params in body based on platform
        boolean valueSet=true;
        for(String paramKey:paramMapping.keySet()){
            String value='';
            if(paramKey=='surveyURL'){
                body=body.replace('<surveyURL>',surveyURL);
                continue;
            }
            boolean isComplexCondition = paramMapping.get(paramKey).containsIgnoreCase('Android=') || paramMapping.get(paramKey).containsIgnoreCase('iOS=');
            if(isComplexCondition){
                List<String>  platformSpecificValues = paramMapping.get(paramKey).split(',');
                for(String platformValue: platformSpecificValues){
                    if(platformValue.split('=')[0]==chatRec.Platform){
                        value=platformValue.split('=')[1];
                    }
                }
            }
            else{
                value=paramMapping.get(paramKey);
            }
            if(value=='') {
                valueSet=false;
                break;
            }
            body=body.replace('<' + paramKey + '>', value);
        }

        if(valueSet==false){
            return 'Request body could not be formulated as all the parameters are not defined';
        }
        return body;
    }

    /* Name: sendSurveyCallout
     * Type: Future: callouts=true.
     * @description Method to make a REST call.
     * @return Type: void
     * Params endpoint: URL of the target environment, body: JSON body to send as part of the request, recordId: Record Id of the chat
     */
    @Future(Callout=true)
    public static void sendSurveyCallout(String endpoint,String body,String recordId){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        request.setBody(body);
        try {
            HttpResponse response = http.send(request);
            if (response.getStatusCode() != 201 && response.getStatusCode() != 200) {
                LoggingUtility.createLog('PostChatSurveys', 'PostChatSurveys', '', '');
                LoggingUtility.logError('PostChatSurveys', 'PostChatSurveyFailure: Unable to send survey after chat completion ' + recordId + ' Errors ' + response.getStatusCode() + '\n' + response.getStatus());
                LoggingUtility.commitLogs();
            }
        }catch(Exception e){
            LoggingUtility.createLog('PostChatSurveys', 'PostChatSurveys', '', '');
            LoggingUtility.logError('PostChatSurveys', 'PostChatSurveyFailure: Unable to send survey after chat completion ' + recordId + ' Errors ' + e.getMessage());
            LoggingUtility.commitLogs();
        }
    }
}