force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>Downgrade</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Franchise Extension</fullName>
            </value>
            <value>
                <fullName>Win Back</fullName>
            </value>
            <value>
                <fullName>Upgrade/Upsell</fullName>
            </value>
            <value>
                <fullName>Complementary Contract</fullName>
            </value>
            <value>
                <fullName>Legal Form Change</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Switch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Account__c.field-meta.xml
<CustomField>
    <fullName>Id_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this holds the account id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WelcomeEmailHandler.cls
/**
 * Created by g.singh on 18/05/2020.
 */

public with sharing class WelcomeEmailHandler {
	
    private static Map<String, Map<String,Map<String,Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
    
    /**
    * @Description: Sends welcome email on quote status change 
    * @param List<Opportunity_Quote__c> newQuoteList
    * @param List<Opportunity_Quote__c> oldQuoteMap
    * @return void
    */
    public static void sendWelcomeEmail(List<Opportunity_Quote__c> newQuoteList, Map<Id,Opportunity_Quote__c> oldQuoteMap){
        EmailTemplate welcomEmailTemplate;
        Set<Id> accountIdSet = new Set<Id>();
        List<Id> opportunityIdList = new List<Id>();
        List<Opportunity_Quote__c> oppQuoteForProcessList = new List<Opportunity_Quote__c>();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        Map<Id, Account> accountMap = new Map<Id, Account>();
        Map<String,Map<String,Business_Config__c>> bConfigByRecordTypeIdMap = moam.get('QuoteWelcomeEmail');
        List<String> emailTemplateNames = new List<String>();
        Map<String, EmailTemplate> emailTemplateByDevName = new Map<String, EmailTemplate>();

        if(bConfigByRecordTypeIdMap == null){
            return;
        }

        for (Opportunity_Quote__c oppQuote : newQuoteList) {
            Map<String,Business_Config__c> bConfigByBRuleNameMap = bConfigByRecordTypeIdMap.get(LibRecordTypeHelper.getRecordTypeValue(oppQuote.RecordTypeId));

            if (bConfigByBRuleNameMap == null
                || bConfigByBRuleNameMap.keyset().isEmpty()
                || !bConfigByBRuleNameMap.containsKey('QuoteStatus')
                || !bConfigByBRuleNameMap.containsKey('EmailTemplate'))
            {
                    continue;
            }
            
            if (oppQuote.Status__c != oldQuoteMap.get(oppQuote.Id).Status__c
                && bConfigByBRuleNameMap.get('QuoteStatus').Business_Rule_Value__c.contains(oppQuote.Status__c))
            {
                oppQuoteForProcessList.add(oppQuote);
                accountIdSet.add(oppQuote.Id_Account__c);
                opportunityIdList.add(oppQuote.Id_Opportunity__c);
                emailTemplateNames.add(bConfigByBRuleNameMap.get('EmailTemplate').Business_Rule_Value__c);
            }
        }

        accountMap.putAll(AccountSelector.getByIds(accountIdSet));
        Map<Id, Opportunity> relatedOpportunityMap = new Map<Id, Opportunity>(Opportunity_Selector.getSelected(opportunityIdList));
        List<EmailTemplate> emailTemplateList = EmailTemplateSelector.getTemplatesByDeveloperName(emailTemplateNames);

        for (EmailTemplate emailTemplate : emailTemplateList) {
            emailTemplateByDevName.put(emailTemplate.DeveloperName, emailTemplate);
        }

        for (Opportunity_Quote__C oppQuote : oppQuoteForProcessList) {
            if (accountMap.containsKey(oppQuote.Id_Account__c) && accountMap.get(oppQuote.Id_Account__c).Contacts.size() > 0) {
                Contact con = accountMap.get(oppQuote.Id_Account__c).Contacts[0];
                Opportunity relatedOpp = relatedOpportunityMap.get(oppQuote.Id_Opportunity__c);
                Map<String,Business_Config__c> bConfigByBRuleNameMap = bConfigByRecordTypeIdMap.get(LibRecordTypeHelper.getRecordTypeValue(oppQuote.RecordTypeId));
                
                if (bConfigByBRuleNameMap == null
                    || bConfigByBRuleNameMap.keyset().isEmpty()
                    || !bConfigByBRuleNameMap.containsKey('businessTypes'))
                {
                    continue;
                }

                if (bConfigByBRuleNameMap.get('businessTypes').Business_Rule_Value__c.contains(relatedOpp.Business_Type__c) && isOpportunityTypeValid(relatedOpp, oppQuote.RecordTypeId)) {
                    welcomEmailTemplate = emailTemplateByDevName.get(bConfigByBRuleNameMap.get('EmailTemplate').Business_Rule_Value__c);
                    emailList.add(createEmail(welcomEmailTemplate.Id, oppQuote.Id_Opportunity__c, con.Id, relatedOpp.Owner.Email));
                }
            }
        }

        if (!emailList.isEmpty()) {
            try {
                Messaging.sendEmail(emailList);
            } catch (Exception exc) {
                // TO-DO
                if(Test.isRunningTest()){
                    throw exc;
                }
                system.debug('Error : ' + exc.getMessage() + '>>> Stacktrace : ' + exc.getStackTraceString());
            }
        }
    }

    /**
    * @description check if the opportunity type is valid
    * @param opportunity opportunity to check
    * @param quoteRecordTypeId record type id to retrieve configuration
    * @return boolean result if the type is valid
    */
    private static Boolean isOpportunityTypeValid(Opportunity opportunity, Id quoteRecordTypeId) {
        Business_Config__c oppTypeConfig = LibBusinessConfig.getBusinessConfigFromRuleMap('QuoteWelcomeEmail', quoteRecordTypeId, 'opportunityTypes');
        if (oppTypeConfig == null) {
            return true;
        }
        return oppTypeConfig.Business_Rule_Value__c.containsIgnoreCase(opportunity.Type);
    }

    /**
    * @Description: Creates SingleEmailMessage
    * @param Id emailTemplateId
    * @param Id whatId
    * @param Id targetId
    * @return Messaging.SingleEmailMessage
    */
    private static Messaging.SingleEmailMessage createEmail(Id emailTemplateId, Id whatId, Id targetId, String replyToEmail){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setReplyTo(replyToEmail);
        mail.setTargetObjectId(targetId);
        mail.setWhatId(whatId);
        mail.setTreatTargetObjectAsRecipient(true);
        mail.setTemplateId(emailTemplateId);

        return mail;
    }
}