force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_1__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_1__c</fullName>
    <label>Case Reason Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Across Journey</fullName>
            </value>
            <value>
                <fullName>Activation or deactivation of restaurant</fullName>
            </value>
            <value>
                <fullName>Billing inquiries</fullName>
            </value>
            <value>
                <fullName>Content update</fullName>
            </value>
            <value>
                <fullName>Contract and Sales inquiries</fullName>
            </value>
            <value>
                <fullName>Customer complaints or negative feedback</fullName>
            </value>
            <value>
                <fullName>Customer evaluations inquiry</fullName>
            </value>
            <value>
                <fullName>Customer inquiry before order placement</fullName>
            </value>
            <value>
                <fullName>Finance inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Live order inquiries by restaurant</fullName>
            </value>
            <value>
                <fullName>Live Order Process</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by customer</fullName>
            </value>
            <value>
                <fullName>Live order process inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Other customer inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Other restaurant inquiries or feedback</fullName>
            </value>
            <value>
                <fullName>Partner data update</fullName>
            </value>
            <value>
                <fullName>Partner Feedback</fullName>
            </value>
            <value>
                <fullName>Post-Delivery</fullName>
            </value>
            <value>
                <fullName>Restaurant data update</fullName>
            </value>
            <value>
                <fullName>Restaurant Supply</fullName>
            </value>
            <value>
                <fullName>Sales inquiry by restaurant</fullName>
            </value>
            <value>
                <fullName>Technical Inquiry</fullName>
            </value>
            <value>
                <fullName>Technical problems &amp; questions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_2__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_2__c</fullName>
    <label>Case Reason Level 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>9Cookies</fullName>
                <isActive>false</isActive>
                <label>9Cookies</label>
            </value>
            <value>
                <fullName>Account management</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Basic profile change</fullName>
            </value>
            <value>
                <fullName>Box</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Cancellation by restaurant</fullName>
            </value>
            <value>
                <fullName>Cancellation of order by customer</fullName>
            </value>
            <value>
                <fullName>Change order details</fullName>
            </value>
            <value>
                <fullName>Changes to restaurant profile</fullName>
            </value>
            <value>
                <fullName>Change to order</fullName>
            </value>
            <value>
                <fullName>Contactless delivery</fullName>
            </value>
            <value>
                <fullName>Customer account</fullName>
            </value>
            <value>
                <fullName>Customer evaluations</fullName>
            </value>
            <value>
                <fullName>Customer reviews for partners</fullName>
            </value>
            <value>
                <fullName>Customer service complaint</fullName>
            </value>
            <value>
                <fullName>Deals update</fullName>
            </value>
            <value>
                <fullName>Delivery changes</fullName>
            </value>
            <value>
                <fullName>Delivery complaint</fullName>
            </value>
            <value>
                <fullName>Delivery inquiries</fullName>
            </value>
            <value>
                <fullName>Delivery Inquiry</fullName>
            </value>
            <value>
                <fullName>Delivery time</fullName>
            </value>
            <value>
                <fullName>Door Sticker Request</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Follow up on existing case</fullName>
            </value>
            <value>
                <fullName>Food complaint</fullName>
            </value>
            <value>
                <fullName>Food issue</fullName>
            </value>
            <value>
                <fullName>Frontend issue</fullName>
            </value>
            <value>
                <fullName>Front end website</fullName>
            </value>
            <value>
                <fullName>General customer complaint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Reason_Level_3__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Level_3__c</fullName>
    <label>Case Reason Level 3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Reason_Level_2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account deletion</fullName>
            </value>
            <value>
                <fullName>Account management feedback on existing issue required</fullName>
            </value>
            <value>
                <fullName>Account management meeting request</fullName>
            </value>
            <value>
                <fullName>Add items/ toppings</fullName>
            </value>
            <value>
                <fullName>Add menu category</fullName>
            </value>
            <value>
                <fullName>Address</fullName>
            </value>
            <value>
                <fullName>Address change</fullName>
            </value>
            <value>
                <fullName>Allergens Update</fullName>
            </value>
            <value>
                <fullName>App complaint by customer</fullName>
            </value>
            <value>
                <fullName>App does not receive orders</fullName>
            </value>
            <value>
                <fullName>App issue</fullName>
            </value>
            <value>
                <fullName>App problem ‒ 9Cookies</fullName>
            </value>
            <value>
                <fullName>App shows blank screen</fullName>
            </value>
            <value>
                <fullName>Automations - Backend Ticket</fullName>
            </value>
            <value>
                <fullName>Automations - Missed Contact</fullName>
            </value>
            <value>
                <fullName>Bank account details change</fullName>
            </value>
            <value>
                <fullName>Branded material request</fullName>
            </value>
            <value>
                <fullName>Calculation mistakes in invoice</fullName>
            </value>
            <value>
                <fullName>Cancellation reason inquiry</fullName>
            </value>
            <value>
                <fullName>Cannot apply</fullName>
            </value>
            <value>
                <fullName>Category hide or unhide</fullName>
            </value>
            <value>
                <fullName>Change/upload listing image</fullName>
            </value>
            <value>
                <fullName>Change/upload product photo</fullName>
            </value>
            <value>
                <fullName>Change account details</fullName>
            </value>
            <value>
                <fullName>Change delivery time</fullName>
            </value>
            <value>
                <fullName>Change of business registration</fullName>
            </value>
            <value>
                <fullName>Change of mind</fullName>
            </value>
            <value>
                <fullName>Change of owner</fullName>
            </value>
            <value>
                <fullName>Change or upload logo</fullName>
            </value>
            <value>
                <fullName>Changes in delivery fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/IsCaseReasonUpdated__c.field-meta.xml
<CustomField>
    <fullName>IsCaseReasonUpdated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Temporary flag to update to exclude the records already</description>
    <label>IsCaseReasonUpdated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/UpdateCaseReasonsCodeMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>UpdateCaseReasonsCodeMapping</label>
</CustomObject>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelNew1__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelNew1__c</fullName>
    <label>CaseReasonLevelNew1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelNew2__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelNew2__c</fullName>
    <label>CaseReasonLevelNew2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelNew3__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelNew3__c</fullName>
    <label>CaseReasonLevelNew3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelOld1__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelOld1__c</fullName>
    <label>CaseReasonLevelOld1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelOld2__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelOld2__c</fullName>
    <label>CaseReasonLevelOld2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UpdateCaseReasonsCodeMapping__c/fields/CaseReasonLevelOld3__c.field-meta.xml
<CustomField>
    <fullName>CaseReasonLevelOld3__c</fullName>
    <label>CaseReasonLevelOld3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateCaseReasonCoding_Batch.cls
/**
* @Description: This batch updates the case reason level 1,2 and 3 and type based on the new reason mapping.
*/
global class UpdateCaseReasonCoding_Batch implements Database.Batchable<sObject>{
    public List<String> recordTypesList = new List<String>();
    public Integer numberOfDays;
    private Map<String, Map<String, Map<String, Business_Config__c>> > moam =
            LibBusinessConfig.motherOfAllBusinessMaps;
    private static Map<String, Business_Config__c> mapBusinessRules;
    public List<UpdateCaseReasonsCodeMapping__c> listCaseMDT;
    public Map<String,UpdateCaseReasonsCodeMapping__c > mapCaseReasonLevel1;
    public Map<String,UpdateCaseReasonsCodeMapping__c > mapCaseReasonLevel2;
    public Map<String,UpdateCaseReasonsCodeMapping__c > mapCaseReasonLevel3;
    public Map<String,UpdateCaseReasonsCodeMapping__c > mapCaseReasonOnlyLevel1;
    public Map<String,UpdateCaseReasonsCodeMapping__c > mapCaseReasonOnlyLevel2;
    public Map<String,UpdateCaseReasonsCodeMapping__c > mapCaseReasonOnlyLevel1And2;
    public String whereClause;


    public UpdateCaseReasonCoding_Batch(String whereCondition){
        whereClause=whereCondition;
        Map<String, Map<String, Business_Config__c>> mapBusinessLogic 	= moam.get('BatchUpdateCaseResonCoding');
        if(mapBusinessLogic != null){
            mapBusinessRules 	= mapBusinessLogic.get('Global_Config');
            if(mapBusinessRules != null) {
                if(mapBusinessRules.ContainsKey('recordTypes')){
                    recordTypesList = mapBusinessRules.get('recordTypes').Business_rule_Value__c.split(',');
                }
                /*if(mapBusinessRules.ContainsKey('closedDateRange')){
                    numberOfDays = Integer.valueOf(mapBusinessRules.get('closedDateRange').Business_Rule_Value__c);
                }*/
            }
        }
        //Get all the mapping from custom setting and store once
        listCaseMDT = UpdateCaseReasonsCodeMapping__c.getall().values();
        mapCaseReasonLevel1 = new Map<String,UpdateCaseReasonsCodeMapping__c>();
        mapCaseReasonLevel2 = new Map<String,UpdateCaseReasonsCodeMapping__c>();
        mapCaseReasonLevel3 = new Map<String,UpdateCaseReasonsCodeMapping__c>();
        mapCaseReasonOnlyLevel1 = new Map<String,UpdateCaseReasonsCodeMapping__c>();
        mapCaseReasonOnlyLevel1And2 = new Map<String,UpdateCaseReasonsCodeMapping__c>();
        mapCaseReasonOnlyLevel2 = new Map<String,UpdateCaseReasonsCodeMapping__c>();

        for(UpdateCaseReasonsCodeMapping__c caseMDT : listCaseMDT) {
            if ((caseMDT.CaseReasonLevelOld1__c != null && caseMDT.CaseReasonLevelOld2__c != null && caseMDT.CaseReasonLevelOld3__c != null)) {
                mapCaseReasonLevel1.put(caseMDT.CaseReasonLevelOld1__c + caseMDT.CaseReasonLevelOld2__c + caseMDT.CaseReasonLevelOld3__c, caseMDT);
            }
            if ((caseMDT.CaseReasonLevelOld1__c != null && caseMDT.CaseReasonLevelOld2__c != null && caseMDT.CaseReasonLevelOld3__c == null)) {
                mapCaseReasonOnlyLevel1And2.put(caseMDT.CaseReasonLevelOld1__c + caseMDT.CaseReasonLevelOld2__c, caseMDT);
            }
            if ((caseMDT.CaseReasonLevelOld1__c != null && caseMDT.CaseReasonLevelOld2__c == null && caseMDT.CaseReasonLevelOld3__c == null)) {
                mapCaseReasonOnlyLevel1.put(caseMDT.CaseReasonLevelOld1__c, caseMDT);
            }
            if (caseMDT.CaseReasonLevelOld1__c == null && caseMDT.CaseReasonLevelOld2__c != null && caseMDT.CaseReasonLevelOld3__c != null) {
                mapCaseReasonLevel2.put(caseMDT.CaseReasonLevelOld2__c + caseMDT.CaseReasonLevelOld3__c, caseMDT);
            }
            if (caseMDT.CaseReasonLevelOld1__c == null && caseMDT.CaseReasonLevelOld2__c != null && caseMDT.CaseReasonLevelOld3__c == null) {
                mapCaseReasonOnlyLevel2.put(caseMDT.CaseReasonLevelOld2__c, caseMDT);
            }
            if (caseMDT.CaseReasonLevelOld1__c == null && caseMDT.CaseReasonLevelOld2__c == null && caseMDT.CaseReasonLevelOld3__c != null) {
                mapCaseReasonLevel3.put(caseMDT.CaseReasonLevelOld3__c, caseMDT);
            }
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {

        List<Id> recordTypeIds 	= new List<Id>();
        //DateTime closedDateValue		= Date.today().addDays(-numberOfDays);

        for(String rec : recordTypesList){
            recordTypeIds.add(LibRecordTypeHelper.getRecordTypeValue(rec));
        }
        String query='SELECT Id,Case_Reason_Level_1__c, Case_Reason_Level_2__c, Case_Reason_Level_3__c,Type, IsCaseReasonUpdated__c FROM CASE WHERE RecordTypeId IN :recordTypeIds AND IsCaseReasonUpdated__c = false AND '+whereClause;
        /*return Database.getQueryLocator([SELECT Id,Case_Reason_Level_1__c,
                                         Case_Reason_Level_2__c,
                                         Case_Reason_Level_3__c,Type,
                                         IsCaseReasonUpdated__c
                                            FROM CASE
                                            WHERE RecordTypeId IN :recordTypeIds
                                            AND IsCaseReasonUpdated__c = false
                                            AND ((IsClosed = false)
                                            OR (ClosedDate > :closedDateValue
                                            AND IsClosed = true))
                                            ]);*/
        system.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        String caseKeyString1;
        String caseKeyString2;
        String caseKeyString3;
        List<Case> casesTobeUpdated = (List<Case>)scope;

            for(Case caseRec : casesTobeUpdated){
                caseKeyString1 = '';caseKeyString2 = '';caseKeyString3 = '';
                if(caseRec.Case_Reason_Level_1__c != null){
                    caseKeyString1=caseRec.Case_Reason_Level_1__c;
                }
                if(caseRec.Case_Reason_Level_2__c != null){
                    caseKeyString2= caseRec.Case_Reason_Level_2__c;
                }
                if(caseRec.Case_Reason_Level_3__c != null){
                    caseKeyString3= caseRec.Case_Reason_Level_3__c;
                }
                if(caseRec.Type=='Customer Request' || caseRec.Type=='Other'){
                    caseRec.Type='Customer';
                }
                if(caseRec.Type=='Restaurant Request'){
                    caseRec.Type='Partner';
                }
                //New value assignment for Case Reason level 1
                if(mapCaseReasonLevel1.containsKey(caseKeyString1+caseKeyString2+caseKeyString3)){
                    if(mapCaseReasonLevel1.get(caseKeyString1+caseKeyString2+caseKeyString3).CaseReasonLevelNew1__c != null){
                        caseRec.Case_Reason_Level_1__c = mapCaseReasonLevel1.get(caseKeyString1+caseKeyString2+caseKeyString3).CaseReasonLevelNew1__c;
                        if(mapCaseReasonLevel1.get(caseKeyString1+caseKeyString2+caseKeyString3).Type__c!=null && mapCaseReasonLevel1.get(caseKeyString1+caseKeyString2+caseKeyString3).Type__c!='')
                            caseRec.Type=mapCaseReasonLevel1.get(caseKeyString1+caseKeyString2+caseKeyString3).Type__c;
                    }
                }else if(mapCaseReasonOnlyLevel1And2.containsKey(caseKeyString1+caseKeyString2)){
                    if(mapCaseReasonOnlyLevel1And2.get(caseKeyString1+caseKeyString2).CaseReasonLevelNew1__c != null){
                        caseRec.Case_Reason_Level_1__c = mapCaseReasonOnlyLevel1And2.get(caseKeyString1+caseKeyString2).CaseReasonLevelNew1__c;
                        if(mapCaseReasonOnlyLevel1And2.get(caseKeyString1+caseKeyString2).Type__c!=null && mapCaseReasonOnlyLevel1And2.get(caseKeyString1+caseKeyString2).Type__c!='')
                            caseRec.Type=mapCaseReasonOnlyLevel1And2.get(caseKeyString1+caseKeyString2).Type__c;
                    }
                }else if(mapCaseReasonOnlyLevel1.containsKey(caseKeyString1)){
                    if(mapCaseReasonOnlyLevel1.get(caseKeyString1).CaseReasonLevelNew1__c != null){
                        caseRec.Case_Reason_Level_1__c = mapCaseReasonOnlyLevel1.get(caseKeyString1).CaseReasonLevelNew1__c;
                        if(mapCaseReasonOnlyLevel1.get(caseKeyString1).Type__c!=null && mapCaseReasonOnlyLevel1.get(caseKeyString1).Type__c!='')
                            caseRec.Type=mapCaseReasonOnlyLevel1.get(caseKeyString1).Type__c;
                    }
                }
                //New value assignment for Case Reason level 2
                if(mapCaseReasonLevel2.containsKey(caseKeyString2+caseKeyString3)){
                    if(mapCaseReasonLevel2.get(caseKeyString2+caseKeyString3).CaseReasonLevelNew2__c != null){
                        caseRec.Case_Reason_Level_2__c = mapCaseReasonLevel2.get(caseKeyString2+caseKeyString3).CaseReasonLevelNew2__c;
                    }
                }else if(mapCaseReasonOnlyLevel2.containsKey(caseKeyString2)){
                    if(mapCaseReasonOnlyLevel2.get(caseKeyString2).CaseReasonLevelNew2__c != null){
                        caseRec.Case_Reason_Level_2__c = mapCaseReasonOnlyLevel2.get(caseKeyString2).CaseReasonLevelNew2__c;
                    }
                }
                //New value assignment for Case Reason level 3
                if(mapCaseReasonLevel3.containsKey(caseKeyString3)){
                    if(mapCaseReasonLevel3.get(caseKeyString3).CaseReasonLevelNew3__c != null){
                    caseRec.Case_Reason_Level_3__c = mapCaseReasonLevel3.get(caseKeyString3).CaseReasonLevelNew3__c;
                    }
                }
                caseRec.IsCaseReasonUpdated__c = true;
            }

        // In case of failure perform partial update
        List<Database.saveResult> results = Database.update(casesTobeUpdated,false);
        LoggingUtility.createLog('UpdateCaseReasonCoding_Batch','BATCH','CASE Reason Update Error',null);
        Boolean isError = false;
        for(Integer i=0;i<results.size();i++){
            if(!results[i].isSuccess()){
                LoggingUtility.logError('UpdateCaseReasonCoding_Batch','UpdateCaseReasonCoding_Batch: Update failed for case ' + casesTobeUpdated[i].Id +
                        ' Errors '  + results[i].getErrors() + '\n');
                isError = true;
            }
        }
        // Do Logging in case of error.
        if(isError){
            LoggingUtility.commitLogs();
        }
    }

    global void finish(Database.BatchableContext BC) {

    }

}