force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Name__c</fullName>
    <description>eg: winbackDueDays, owner,..</description>
    <label>Business Rule Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>flag for the business process</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>ProcessName or TriggerName</description>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>eg: xxxxxxxxxxxxx(record type id)</description>
    <inlineHelpText>Add only 18 character valid ID</inlineHelpText>
    <label>Record Type Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>guess what , this holds the countries plus their iso codes</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LiveChatTranscript/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Colombia</fullName>
            </value>
            <value>
                <fullName>Ecuador</fullName>
            </value>
            <value>
                <fullName>Peru</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Myanmar</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Laos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Restaurant Request</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AutoCloseChatControllerTest.cls
@isTest
public with sharing class AutoCloseChatControllerTest {
    @isTest
    public static void AutoCloseChatControllerTest() {
		Business_Config__c bc1 = new Business_Config__c(
			Business_Rule_Name__c = 'AutoCloseChatTime',
			Process_Name__c = 'AutoCloseChatTime',
			Record_Type_Id__c = 'AutoCloseChatTime',
			Type__c = 'Process'
		);
		insert bc1;
		
		Business_Config__c bc2 = new Business_Config__c(
			Business_Rule_Name__c = 'Foodpanda',
			Business_Rule_Value__c = '{ "Hong Kong": { "warning": 2, "warningClose": 5, "inactiveClose": 10 }, "Berlin": { "warning": 2, "warningClose": 5, "inactiveClose": 10 } }',
			Is_Active__c = true,
			Record_Type_Id__c = 'AutoCloseChatTime',
			Type__c = 'Process'
		);
		insert bc2;
		
        LiveChatVisitor visitor=new LiveChatVisitor();
        insert visitor;
		
		LiveChatTranscript ltr = new LiveChatTranscript(Country__c = 'Hong Kong',
														Platform__c = 'Foodpanda',
														LiveChatVisitorId = visitor.Id);
		insert ltr;

		Integer[] times =+ AutoCloseChatController.getTimes(ltr.Id);
		system.assertEquals(5000, times[0]); 
		system.assertEquals(10000, times[1]); 
		system.assertEquals(90000, times[2]); 
	}
}