force-app/main/default/objects/Business_Config__c/Business_Config__c.object-meta.xml
<CustomObject>
    <description>This object hold records of all trigger and business process data for a specific country and recordtypeid</description>
    <label>Business Config</label>
    <nameField>
        <label>Business Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Config__c/fields/Business_Rule_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Rule_Value__c</fullName>
    <description>eg: 20,xxxxxxxxxxxx(ID),...</description>
    <inlineHelpText>if the value is ID then add only 18 character valid id.</inlineHelpText>
    <label>Business Rule Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Burger King</fullName>
    </customValue>
    <customValue>
        <fullName>domicilios.com</fullName>
    </customValue>
    <customValue>
        <fullName>hungryhouse</fullName>
    </customValue>
    <customValue>
        <fullName>LieferheldDE</fullName>
    </customValue>
    <customValue>
        <fullName>limadelivery.com</fullName>
    </customValue>
    <customValue>
        <fullName>Mat24</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam</fullName>
    </customValue>
    <customValue>
        <fullName>Mjam App</fullName>
    </customValue>
    <customValue>
        <fullName>Netkellner</fullName>
    </customValue>
    <customValue>
        <fullName>Not in Auction</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G9</fullName>
    </customValue>
    <customValue>
        <fullName>Not in G-Market</fullName>
    </customValue>
    <customValue>
        <fullName>OnlinePizza</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaDE</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaOnline</fullName>
    </customValue>
    <customValue>
        <fullName>PizzaPortal</fullName>
    </customValue>
    <customValue>
        <fullName>Talabat</fullName>
    </customValue>
    <customValue>
        <fullName>Yogiyo</fullName>
    </customValue>
    <customValue>
        <fullName>Foodora</fullName>
    </customValue>
    <customValue>
        <fullName>PedidosYa</fullName>
    </customValue>
    <customValue>
        <fullName>clickdelivery.com.pe</fullName>
    </customValue>
    <customValue>
        <fullName>adomicilioYa.com</fullName>
    </customValue>
    <customValue>
        <fullName>Butakhae</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>FoodOnClick</fullName>
    </customValue>
    <customValue>
        <fullName>Appetito24</fullName>
    </customValue>
    <customValue>
        <fullName>Netpincer</fullName>
    </customValue>
    <customValue>
        <fullName>Foodpanda</fullName>
    </customValue>
    <customValue>
        <fullName>Yemeksepeti</fullName>
    </customValue>
    <customValue>
        <fullName>Otlob</fullName>
    </customValue>
    <masterLabel>Platform</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmailActionOverride.cls
global class EmailActionOverride implements  QuickAction.QuickActionDefaultsHandler {
    global EmailActionOverride() {}

    // The main interface method
    global void onInitDefaults(QuickAction.QuickActionDefaults[] defaults) {
        QuickAction.SendEmailQuickActionDefaults sendEmailDefaults = (QuickAction.SendEmailQuickActionDefaults)defaults.get(0);
        Case reqCase = CaseSelector.getCaseWithDynamicFields('EmailTemplatePrepopulateCriteriaFields',string.valueOf(sendEmailDefaults.getContextId()));
        if(reqCase!=null) {
            //Get the business config record for CaseEmailPrepoulateConfigs for the correct platform
            Map<String, Map<String, Map<String, Business_Config__c>> > moam = LibBusinessConfig.motherOfAllBusinessMaps;
            Map<String, Map<String, Business_Config__c>> mapBusinessLogic = moam.get('CaseEmailPrepoulateConfigs');
            Map<String, Business_Config__c> mapBusinessRules=new map<String, Business_Config__c>();
            if(mapBusinessLogic!=null) {
                mapBusinessRules = mapBusinessLogic.get(reqCase.Platform__c);
                if(mapBusinessRules!=null) {
                    Map<String,String> paramValueMap=new map<String,String>();
                    if(mapBusinessRules.containsKey('Parameters')){
                        List<String> params=mapBusinessRules.get('Parameters').Business_Rule_Value__c.split(',');
                        for(String param:params){
                            String businessConfigValue=fetchKeyValue(reqCase, mapBusinessRules, param);
                            if(businessConfigValue.contains('&&')){
                                String paramValue=businessConfigValue.split('&&')[0];
                                String emailField=businessConfigValue.split('&&')[1];
                                paramValueMap.put(emailField,paramValue);
                            }
                        }
                    }
                    if(paramValueMap!=null && paramValueMap.containsKey('Template')){
                        EmailTemplate temp=EmailTemplateSelector.getTemplateByName(paramValueMap.get('Template'));
                        if(temp!=null) {
                            sendEmailDefaults.setTemplateId(temp.id);
                            sendEmailDefaults.setInsertTemplateBody(true);
                            sendEmailDefaults.setIgnoreTemplateSubject(false);
                        }
                    }
                    EmailMessage emailMessage = (EmailMessage) sendEmailDefaults.getTargetSObject();
                    for(String param:paramValueMap.keyset()){
                        if(param!='Template'){
                            if(param=='ToAddress'){
                                String toAddress='';
                                if(reqCase.Customer_Email__c!=null)
                                    toAddress = reqCase.Customer_Email__c+','+paramValueMap.get(param);
                                else
                                    toAddress = paramValueMap.get(param);
                                emailMessage.put(param,toAddress);
                            }
                            else
                                emailMessage.put(param,paramValueMap.get(param));
                        }
                    }
                }
            }
        }
    }

    private Map<String, Map<String,String>> createBusinessRuleMaps(Map<String, Business_Config__c> mapBusinessRules, String keyValue){
        return (Map<String, Map<String,String>>) JSON.deserialize(mapBusinessRules.get(keyValue).Business_Rule_Value__c, Map<String, Map<String,String>>.class);
    }

    private String fetchKeyValue(Case reqCase,Map<String, Business_Config__c> mapBusinessRules, String keyValue){
        Map<String, Map<String,String>> criteriaValues=createBusinessRuleMaps(mapBusinessRules,keyValue);
        String returnValue='';
        for(String i:criteriaValues.keySet()){
            Boolean flag=true;
            if(criteriaValues.get(i).get('Criteria')!=null){
                List<String> criteriaStrings=new List<String>();
                if(criteriaValues.get(i).get('Criteria').contains('&&'))
                    criteriaStrings=criteriaValues.get(i).get('Criteria').split('&&');
                else{
                    criteriaStrings.add(criteriaValues.get(i).get('Criteria'));
                }
                for(Integer j=0;j<criteriaStrings.size();j++){
                    if(reqCase.get(criteriaStrings[j])!=criteriaValues.get(i).get(criteriaStrings[j])) {
                        flag = false;
                        break;
                    }
                }
                if(flag){
                    //For Params other than template
                    if(criteriaValues.get(i).containsKey('TargetField'))
                        returnValue=criteriaValues.get(i).get(keyValue)+'&&'+criteriaValues.get(i).get('TargetField');
                }
            }
        }
        return returnValue;
    }
    

}