force-app/main/default/objects/API_SalesforceInternalConstants__mdt/API_SalesforceInternalConstants__mdt.object-meta.xml
<CustomObject>
    <description>Contains the constants like end point, message that need to be used in REST API call for DMLs on setup objects</description>
    <label>API_SalesforceInternalConstants</label>
    <pluralLabel>API_SalesforceInternalConstants</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Country_Mapping__mdt/Platform_Country_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>A mapping for the platform and country fields to prevent users from selecting the wrong country for a platform.</description>
    <label>Platform Country Mapping</label>
    <pluralLabel>Platform Country Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Platform_Country_Mapping__mdt/fields/Countries__c.field-meta.xml
<CustomField>
    <fullName>Countries__c</fullName>
    <description>Countries for the platform</description>
    <label>Countries</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Platform_Country_Mapping__mdt/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Country_Mapping__mdt/fields/Profiles_to_skip_validation__c.field-meta.xml
<CustomField>
    <fullName>Profiles_to_skip_validation__c</fullName>
    <defaultValue>&apos;System Administrator, Global Salesforce Team&apos;</defaultValue>
    <description>Comma separated profiles to skip validation</description>
    <label>Profiles to skip validation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Country_Mapping__mdt/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Country_Mapping__mdt/fields/User_Role_Prefix__c.field-meta.xml
<CustomField>
    <fullName>User_Role_Prefix__c</fullName>
    <label>User Role Prefix</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomMetadataSelector.cls
/* Created By: Preeti Bansal
 * Description: API related variables or configurations
 * Created Date: 03-Jan-2020
 */

public class CustomMetadataSelector {
    
	/* @desc: Gives Map of names and values
	 * @param: DeveloperName of setting
    */
	
    public static Map<String,String>  getAPIConstanst(Set<String> pNames){
        List<API_SalesforceInternalConstants__mdt> mdt = new List<API_SalesforceInternalConstants__mdt>();
        Map<String,String> mapOfConstNames = new Map<String,String>();
        FOR(API_SalesforceInternalConstants__mdt m : [SELECT DeveloperName,Value__c FROM API_SalesforceInternalConstants__mdt WHERE DeveloperName IN:pNames]){
            mdt.add(m);
            mapOfConstNames.put(m.DeveloperName, m.Value__c);
        }
    
    return mapOfConstNames;
    }

    /* @desc: Platform_Country_Mapping__mdt
     * @param: List<String>: platforms
     */
    public static Map<String,Platform_Country_Mapping__mdt> getPlatformCountryMappings(List<String> platforms){
        Map<String,Platform_Country_Mapping__mdt> platformCountriesMap = new Map<String,Platform_Country_Mapping__mdt>();
        for(Platform_Country_Mapping__mdt platformCountryMapping: [SELECT Id,MasterLabel,Platform__c,Region__c,Countries__c,User_Role_Prefix__c,Profiles_to_skip_validation__c FROM Platform_Country_Mapping__mdt WHERE Platform__c IN :platforms]){
            platformCountriesMap.put(platformCountryMapping.MasterLabel,platformCountryMapping);
        }
        return platformCountriesMap;
    }
}