force-app/main/default/objects/Log_Error_Message__c/Log_Error_Message__c.object-meta.xml
<CustomObject>
    <label>Log Error Message</label>
    <nameField>
        <displayFormat>LE-{00000}</displayFormat>
        <label>Log Error Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log_Error_Message__c/fields/Callout_Begin_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Callout_Begin_Timestamp__c</fullName>
    <label>Callout Begin Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Error_Message__c/fields/Callout_End_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Callout_End_Timestamp__c</fullName>
    <label>Callout End Timestamp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Error_Message__c/fields/Callout_Time__c.field-meta.xml
<CustomField>
    <fullName>Callout_Time__c</fullName>
    <formula>( Callout_End_Timestamp__c - Callout_Begin_Timestamp__c ) / 1000</formula>
    <label>Callout Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Log_Error_Message__c/fields/Dump__c.field-meta.xml
<CustomField>
    <fullName>Dump__c</fullName>
    <label>Dump</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Error_Message__c/fields/Error_message__c.field-meta.xml
<CustomField>
    <fullName>Error_message__c</fullName>
    <label>Error message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log_Error_Message__c/fields/Is_Error__c.field-meta.xml
<CustomField>
    <fullName>Is_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logging__c/Logging__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>use this custom setting to disable or enable Logging
1. Disable a particular type to disable the logging for that particular type
2. Enable ONLY_ERROR_LOGGING to log only errors

NOTE: If you can enable only error logging and still you have not disbaled logging for particular type, it will log for both errors and that particular type. If you just want to log error disbale all the other types and enable logging.</description>
    <label>Logging</label>
</CustomObject>

force-app/main/default/objects/Logging__c/fields/DISABLE_MIDAS__c.field-meta.xml
<CustomField>
    <fullName>DISABLE_MIDAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DISABLE_MIDAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logging__c/fields/ONLY_ERROR_LOGGING__c.field-meta.xml
<CustomField>
    <fullName>ONLY_ERROR_LOGGING__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ONLY_ERROR_LOGGING</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UnitTestLoggingUtility.cls
@isTest
public class UnitTestLoggingUtility {
    
    @isTest
    public static void testCreation(){
    	LoggingUtility.createLog('test','test','test',null);
    	LoggingUtility.createLog('test2','test2','test2',null);
    	
    	System.assertEquals(LoggingUtility.logMap.keySet().size(),2);
    	
    	// create duplicate log
    	LoggingUtility.createLog('test','test','test',null);
    	System.assertEquals(LoggingUtility.logMap.keySet().size(),2);
    }
    
    @isTest
    public static void testLog(){
    	LoggingUtility.createLog('test','test','test',null);
    	LoggingUtility.log('test','test');
    	
    	System.assertEquals(LoggingUtility.logMap.get('test').dump__c,'test');
    }
    
    @isTest
    public static void testTimeStampAndCommit(){
    	LoggingUtility.createLog('test','MIDAS','test',null);
    	LoggingUtility.captureTimeStamp('test','Begin');
    	LoggingUtility.captureTimeStamp('test','End');
    	
    	// create custom settings
    	Logging__c logConfig =new Logging__c(SetupOwnerId=Userinfo.getUserId());
    	logConfig.DISABLE_MIDAS__C = false;
    	insert logConfig;
    	
    	LoggingUtility.commitLogs();
    	
    	List<Log_Error_Message__c> logs = [Select Callout_Begin_Timestamp__c,Callout_End_Timestamp__c,callout_time__c
    										FROM Log_Error_Message__c];
		
		System.assertEquals(logs.size(),1);
		
		Decimal calloutTime = ((logs[0].Callout_End_Timestamp__c - logs[0].Callout_Begin_Timestamp__c)/1000).setScale(2);
		System.assertEquals(calloutTime,logs[0].callout_time__c);
    }
    
    @isTest
    public static void testDisabling(){
    	LoggingUtility.createLog('test','MIDAS','test',null);
    	LoggingUtility.captureTimeStamp('test','Begin');
    	LoggingUtility.captureTimeStamp('test','End');
    	
    	// create custom settings
    	Logging__c logConfig =new Logging__c(SetupOwnerId=Userinfo.getUserId());
    	logConfig.DISABLE_MIDAS__C = true;
    	insert logConfig;
    	
    	LoggingUtility.commitLogs();
    	
    	List<Log_Error_Message__c> logs = [Select id FROM Log_Error_Message__c];
		System.assertEquals(logs.size(),0);
		
		// check for error
		LoggingUtility.logError('test','test error');
		logConfig.ONLY_ERROR_LOGGING__c = true;
		update logConfig;
		
		LoggingUtility.commitLogs();
		logs = [Select id FROM Log_Error_Message__c];
		System.assertEquals(logs.size(),1);
    }
    
    @isTest
    public static void testErrorLog(){
    	LoggingUtility.createLog('test','test','test',null);
    	LoggingUtility.logError('test','test');
    	
    	System.assertEquals(LoggingUtility.logMap.get('test').is_Error__c,true);
    	System.assertEquals(LoggingUtility.logMap.get('test').Error_Message__c,'test');
    }
    
}