force-app/main/default/objects/Log_Error_Message__c/Log_Error_Message__c.object-meta.xml
<CustomObject>
    <label>Log Error Message</label>
    <nameField>
        <displayFormat>LE-{00000}</displayFormat>
        <label>Log Error Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logging__c/Logging__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>use this custom setting to disable or enable Logging
1. Disable a particular type to disable the logging for that particular type
2. Enable ONLY_ERROR_LOGGING to log only errors

NOTE: If you can enable only error logging and still you have not disbaled logging for particular type, it will log for both errors and that particular type. If you just want to log error disbale all the other types and enable logging.</description>
    <label>Logging</label>
</CustomObject>

force-app/main/default/objects/Logging__c/fields/NUMBER_OF_DAYS__c.field-meta.xml
<CustomField>
    <fullName>NUMBER_OF_DAYS__c</fullName>
    <label>NUMBER_OF_DAYS</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchLogDeletion.cls
/**
	@Description: This method deletes the log which are older than particular number of days. 
				  Also contains the scheduler to schedule itself
*/
global class BatchLogDeletion implements Database.Batchable<sObject>,Schedulable{
    
    public Integer numberOfDays; // Number of days before which logs should be deleted
    
    global BatchLogDeletion(){
    	Logging__c logConfig = Logging__c.getInstance();
    	numberOfDays = Integer.valueOf(logConfig.NUMBER_OF_DAYS__c);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
		Date filterDate = Date.today().addDays(-numberOfDays);
		return Database.getQueryLocator([SELECT Id
											FROM Log_Error_Message__c 
											where createdDate <= :filterDate]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        if(scope.size() == 0)
        	return;
        	
    	// Delete the logs
    	delete (List<Log_Error_Message__c>)scope;
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
    global void execute(SchedulableContext sc) {
        BatchLogDeletion batch = new BatchLogDeletion();
        Database.executebatch(batch);
    }
    
}