force-app/main/default/objects/Log_Error_Message__c/Log_Error_Message__c.object-meta.xml
<CustomObject>
    <label>Log Error Message</label>
    <nameField>
        <displayFormat>LE-{00000}</displayFormat>
        <label>Log Error Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logging__c/Logging__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>use this custom setting to disable or enable Logging
1. Disable a particular type to disable the logging for that particular type
2. Enable ONLY_ERROR_LOGGING to log only errors

NOTE: If you can enable only error logging and still you have not disbaled logging for particular type, it will log for both errors and that particular type. If you just want to log error disbale all the other types and enable logging.</description>
    <label>Logging</label>
</CustomObject>

force-app/main/default/objects/Logging__c/fields/DISABLE_MIDAS__c.field-meta.xml
<CustomField>
    <fullName>DISABLE_MIDAS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DISABLE_MIDAS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Logging__c/fields/NUMBER_OF_DAYS__c.field-meta.xml
<CustomField>
    <fullName>NUMBER_OF_DAYS__c</fullName>
    <label>NUMBER_OF_DAYS</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitTestBatchLogDeletion.cls
@isTest
public class UnitTestBatchLogDeletion {
   	
   	@isTest
   	public static void testBatch(){
   		// create custom settings
    	Logging__c logConfig =new Logging__c(SetupOwnerId=Userinfo.getUserId());
    	logConfig.DISABLE_MIDAS__C = false;
    	logConfig.NUMBER_OF_DAYS__c = 30;
    	insert logConfig;
    	
   		LoggingUtility.createLog('test','MIDAS','test',null);
   		LoggingUtility.commitLogs();
   		
   		List<Log_error_message__c> logs = [Select Id from Log_Error_message__c];
   		System.assertEquals(logs.size(),1);
   		
   		Test.startTest();
   			BatchLogDeletion bt = new BatchLogDeletion();
   			bt.numberOfDays = -1;
   			Database.executeBatch(bt);
   		Test.stopTest();
   		
   		logs = [Select Id from Log_Error_message__c];
   		System.assertEquals(logs.size(	),0);
   	}
   	
   	@isTest
   	public static void testScheduler(){
   		// create custom settings
    	Logging__c logConfig =new Logging__c(SetupOwnerId=Userinfo.getUserId());
    	logConfig.DISABLE_MIDAS__C = false;
    	logConfig.NUMBER_OF_DAYS__c = 30;
    	insert logConfig;
    	
   		String CRON_EXP = '0 0 0 15 3 ? 2022'; 
   		LoggingUtility.createLog('test','MIDAS','test',null);
   		LoggingUtility.commitLogs();
   		Test.startTest();
        	String jobId = System.schedule('ScheduleApexClassTest', CRON_EXP, new BatchLogDeletion());
        Test.stopTest();
        
        // Default number of days are 20. so no logs should be deleted
        List<Log_error_message__c> logs = [Select Id from Log_Error_message__c];
   		System.assertEquals(logs.size(),1);
   	}
   	 
}