force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Restaurant</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity relating to this Asset</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipment Order</label>
    <referenceTo>Shipment_Order__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Stock Item currently assigned to this Asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5 AND 6)</booleanFilter>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>In Stock</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New from manufacturer, A1 - New used, B - Used few scratches, A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/N</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Yogiyo Stock Item, FI Stock Item, SE Stock Item</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>DH AU Asset</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>Ordered, New - In Stock, Assigned, In Shipping, Delivered, Retour in Progress, Lost, Returned - at Manufacturer, Recycled, Damaged, Writeoff, Tested, Returned - In Stock, Awaiting Delivery/In Shipment, In Stock, Technical Issue, Exchange Requested, Takeov</value>
        </filterItems>
        <filterItems>
            <field>Stock_Item__c.Condition__c</field>
            <operation>equals</operation>
            <value>A - New, B - Used, C - Testing, D - Reparable, E - Dead, N - Brand New, O - Ordered, U - Undefined, A - New from manufacturer, A1 - New used, B - Used few scratches, C - Used, D - Damaged/No longer usable</value>
        </filterItems>
        <infoMessage>In stock devices</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Asset Assignment</relationshipLabel>
    <relationshipName>Asset_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/FP_Asset.recordType-meta.xml
<RecordType>
    <fullName>FP_Asset</fullName>
    <active>true</active>
    <label>FP Asset</label>
</RecordType>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <description>Holds information about the company</description>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Companies</relationshipLabel>
    <relationshipName>Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Add_On__c/List_Add_On__c.object-meta.xml
<CustomObject>
    <label>List Add On</label>
    <nameField>
        <label>List Add On Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Add On</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Add_On__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Add On</relationshipLabel>
    <relationshipName>List_Add_On</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/List_Service_Price__c/List_Service_Price__c.object-meta.xml
<CustomObject>
    <description>this is the template for all kind of services</description>
    <label>List Service Price</label>
    <nameField>
        <label>List Service Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>List Services Price</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Service_Price__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Company to which this service is tied</description>
    <label>User Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>List Services Price</relationshipLabel>
    <relationshipName>List_Services_Price</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity Country. Set when creating an opportunity on lead creation</description>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Opportunity_Quote__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Quote</label>
    <referenceTo>Opportunity_Quote__c</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/Shipment_Order_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment order items</description>
    <label>Shipment Order Line Item</label>
    <nameField>
        <label>Shipment Order Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Shipment_Order__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Order__c</fullName>
    <label>Shipment Order</label>
    <referenceTo>Shipment_Order__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipment_Order_Line_Item__c/fields/Stock_Item__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is to assing the stock item that should be deliver an copy on the asset</description>
    <label>Stock Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>There is not stock Items available</errorMessage>
        <filterItems>
            <field>Stock_Item__c.Status__c</field>
            <operation>equals</operation>
            <value>New - In Stock, In Stock</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Stock_Item__c</referenceTo>
    <relationshipLabel>Shipment Order Line Items</relationshipLabel>
    <relationshipName>Shipment_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssetSelector_Test.cls
/**
 * Created by danish.farooq on 6/25/20.
 * @description Test class for AssetSelector
 */

@IsTest
private class AssetSelector_Test {
    @testSetup
    static void setup() {

        UnitTestDataFactory.getRecordtypeValues();
        Country__c testCountryMY = UnitTestDataFactory.createCountry('MY', Constants.COUNTRY_NAME_MALAYSIA, 'MYR');
        insert testCountryMY;

        Company__c testCompanyMY = UnitTestDataFactory.createCompany('FoodPanda', 'FoodPanda', testCountryMY);
        insert testCompanyMY;

        List<Account> fpAccount = UnitTestDataFactory.createAccounts(2, testCountryMY, Constants.FP_ACCOUNT_DEVELOPERNAME);
        fpAccount[0].phone = '+6012345678';
        fpAccount[1].phone = '+6012345678';
        insert fpAccount;
        List<List_Service_Price__c> fpServices = UnitTestDataFactory.createServices(testCompanyMY, testCountryMY, 10, Constants.FP_LIST_SERVICE_PRICE_DEVELOPERNAME, 13, 13, 15, 10, 1, '% per Order', true, 299, 'Monthly', 'Commission', 'ServiceType');
        List<Contact> fpContact = UnitTestDataFactory.createContacts(fpAccount, 'testContact', 'firstname', null, 'owner', 1, 'testCt', Constants.FP_CONTACT_DEVELOPERNAME);
        List<Opportunity> fpOpportunity = UnitTestDataFactory.createOpportunities(fpAccount, 1, Constants.FP_OPPORTUNITY_DEVELOPERNAME, Date.today().addMonths(2));
        insert fpOpportunity;
        Opportunity_Line_Item__c fpoppServiceItem = UnitTestDataFactory.createOpportunityLineItemService('commission Fee',fpOpportunity[0], fpServices[0].Id, false, Constants.FP_OPPORTUNITY_LINE_ITEM_DEVELOPERNAME, 13, null, Date.today(), 'Commission Fee', null);
        insert fpoppServiceItem;
        List<Opportunity_Quote__c> fpOpportunityQuote = UnitTestDataFactory.createOpportunityQuotes(fpOpportunity[0], 1, Constants.FP_OPPORTUNITY_QUOTE_DEVELOPERNAME, 'Accepted','testdata',10, 10, null,null,0);
        insert fpOpportunityQuote;
        insert UnitTestDataFactory.createOpportunityQuoteLineItem(fpOpportunityQuote[0],fpoppServiceItem,Constants.FP_OPPORTUNITY_QUOTE_LINE_ITEM_DEVELOPERNAME);
        List<List_Add_On__c> fpAddOns   = UnitTestDataFactory.createAddOns(testCountryMY.id,testCompanyMY.id,'Test Add On','Deals','test',
                Constants.FP_LIST_ADD_ON_DEVELOPERNAME,10);

        List<Stock_Item__c> stockItems = UnitTestDataFactory.createStockItems(2, 'FP_Stock_Item', fpAccount[0], null, 'A1 - New used', Date.today(), Date.today().addDays(10), Date.today().addDays(-30), '1234567890', '1234567890', 'Korea Telekom', 'In Stock', 'Other');
        insert stockItems;



        Shipment_Order__c ship = new Shipment_Order__c();
        ship = new Shipment_Order__c(Account__c = fpOpportunity[0].AccountId,
                Opportunity__c = fpOpportunity[0].ID,
                Status__c = CONSTANTS.SHIPMENTORDER_STATUS_READY_TO_BE_SHIPPERD);

        insert ship;

        Shipment_Order_Line_Item__c shipOrdLin = new Shipment_Order_Line_Item__c(Name = 'Test Line',
                Shipment_Order__c = ship.id,
                Quantity__c = 12,
                Stock_Item__c = stockItems[0].Id);

        insert shipOrdLin;

        List<Asset__c> lstAssets = UnitTestDataFactory.createAssets(10, fpAccount[0], fpOpportunity[0], Date.today().addDays(-10), true, stockItems[0], stockItems[1], 'FP_Asset', '12345674',
                '1', '1', Date.today(), Date.today(), 'En Route', true, 'Exchanged', 'Shared Information', 'Take over Information', Constants.ASSET_STATUS_ACTIVATED_SUCCESSFULLY ,
                Date.today().addDays(20), 'Yazi Logistics', '1234', 'none');
        lstAssets[0].Shipment_Order_Line_Item__c = shipOrdLin.ID;
        lstAssets[1].Shipment_Order__c = ship.ID;
        insert lstAssets;
    }

    @IsTest
    static void testAssetSelector() {

        test.startTest();
        Opportunity opptyObj = Opportunity_Selector.getAll()[0];
        List<Asset__c> lstAsset = AssetSelector.getAssetByStatus(new Set<Id>{ opptyObj.ID} , new Set<string> { Constants.ASSET_STATUS_ACTIVATED_SUCCESSFULLY });
        system.assertEquals(lstAsset.size(),10);
        lstAsset = AssetSelector.getActiveAssetsForAccount(opptyObj.AccountId);
        system.assertEquals(lstAsset.size(),10);
        Map<ID,Asset__c> mapOfAssetsByIds = AssetSelector.getAssetsbyId(new Set<ID> {lstAsset[0].ID});
        Asset__c assetObj = AssetSelector.getAssetDetailsById(lstAsset[0].id);
        lstAsset = AssetSelector.findActiveByAccountIds(new Set<Id> { opptyObj.AccountId });
        lstAsset = AssetSelector.getAssetsNotActivated(lstAsset, new Set<Id> {opptyObj.ID});
        system.assertEquals(lstAsset.size(),0);
        test.stopTest();
    }

    @IsTest
    static void testAssetByShipmentOrder() {

        test.startTest();
        Shipment_Order_Line_Item__c shipmentOrderLineItemObj = [Select ID,Shipment_Order__c from Shipment_Order_Line_Item__c LIMIT 1];
        Map<Id, Asset__c> mapOfAssetsByIds  = AssetSelector.getAssetsMapForShipmentOrderLineItems(new Set<Id> {shipmentOrderLineItemObj.ID});
        Map<Id, List<Asset__c>> mapOfAssetsByShipmentOrder = AssetSelector.getAssetsMapForShipmentOrders(new Set<Id> {shipmentOrderLineItemObj.Shipment_Order__c});
        system.assertEquals(mapOfAssetsByIds.size(),1);
        system.assertEquals(mapOfAssetsByShipmentOrder.size(),1);
        test.stopTest();
    }


}