force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Aftership_ID__c.field-meta.xml
<CustomField>
    <fullName>Aftership_ID__c</fullName>
    <label>Aftership ID</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Date_Shipped__c.field-meta.xml
<CustomField>
    <fullName>Date_Shipped__c</fullName>
    <label>Date Shipped</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Tracking_Update__c.field-meta.xml
<CustomField>
    <fullName>Last_Tracking_Update__c</fullName>
    <label>Last Tracking Update</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Tracking_Active__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tracking Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Tracking_Exception__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Exception__c</fullName>
    <label>Tracking Exception</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <description>The tracking number given by the shipping company</description>
    <inlineHelpText>The tracking number given by the shipping company</inlineHelpText>
    <label>Tracking Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClsRestAssetUpdAfterShip.cls
@RestResource(urlMapping='/UpdateAssetStatus/*')
global with sharing class ClsRestAssetUpdAfterShip{
	public static String logName = 'assetStatusUpdate';
	
	@HttpPost	
 	global static void  updateAssetStatus() {
 		LoggingUtility.createLog(logName,'AFTERSHIP','STATUS_UPDATE',null);
 		RestRequest res 	= RestContext.request;
 		String resp 		= res.requestBody.tostring();
 		LoggingUtility.log(logName,'Request Body => '+ resp);
 		JSONParser resJSON 	= JSON.createParser(resp);
 		parseAftershipGetResponse(resJSON);
 		LoggingUtility.commitLogs();
 	}

 	 public static void parseAftershipGetResponse(JSONParser parser ){
        while (parser.nextToken() != null) {               
			if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'msg') {
                system.debug(parser.getCurrentName());
                while (parser.nextToken() != null) {
                    Tracker tc=  (Tracker)parser.readValueAs(Tracker.class);
                    updateInfoOnAsset(tc);
                    break;
                }
            } 
        }
    }


    public static void updateInfoOnAsset(Tracker tc){
        List<Asset__c> assets = [select id,
	    								status__c, 
	    								tracking_number__c,
	    								Last_Tracking_Update__c,
	    								Date_Shipped__c,
	    								Tracking_Exception__c,
	    								tracking_active__c
									from Asset__c 
									where tracking_active__c = true 
									and tracking_number__c =: tc.tracking_number
									and aftership_id__c =:tc.id];

		if(tc.tracking_number == null || tc.tracking_number == '')
			return;
		
    	if(assets.size() == 0)
    		return;
    		
		for(Asset__c ast : assets){
			if(tc.tag=='Exception'){
	            system.debug(tc.checkpoints);
	            for(CheckPoint ch:tc.checkpoints){
	                if(ch.tag=='Exception'){
	                    ast.Tracking_Exception__c=ch.message;
	                    ast.tracking_active__c=false;
	                          
	                }
	            }
			}
			ast.status__c=tc.tag;
	        if(tc.tag=='Delivered')
	            ast.tracking_active__c=false;
	
	        if(tc.updated_at!=null)
	        	ast.Last_Tracking_Update__c=tc.updated_at;
	        if(ast.Date_Shipped__c==null && tc.tracking_ship_date!=null)
	        	ast.Date_Shipped__c=tc.tracking_ship_date;
		}
    	try{
    		update assets;
    	}catch (Exception e){
			LoggingUtility.logError(logName,'Error => ' + e.getMessage() + '\nLine Number : ' + e.getLineNumber());
    	}


    }
   
    public class Tracker{
        public String id;
        public String tracking_number;
        public String expected_delivery;
        public Date tracking_ship_date;
        public String tag;
        //public Datetime shipment_pickup_date;
        public Datetime updated_at;
        public List<CheckPoint> checkpoints;

    }

     public class CheckPoint{
        public String message;
        public String tag;
        

    }
}