force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <description>Asset associated with an Opportunity. (Stock Items are assigned to an Asset)</description>
    <label>Asset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Restaurant</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Opportunity relating to this Asset</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Retour_Date__c.field-meta.xml
<CustomField>
    <fullName>Retour_Date__c</fullName>
    <label>Return Request Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/SIM_Activated__c.field-meta.xml
<CustomField>
    <fullName>SIM_Activated__c</fullName>
    <label>SIM Activated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/SIM_Card_Provider__c.field-meta.xml
<CustomField>
    <fullName>SIM_Card_Provider__c</fullName>
    <description>Used for DE - Express Terminal info (SP-1763)</description>
    <label>SIM Card Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>D1</fullName>
            </value>
            <value>
                <fullName>O2</fullName>
            </value>
            <value>
                <fullName>Vodafone</fullName>
            </value>
            <value>
                <fullName>Datamobile</fullName>
            </value>
            <value>
                <fullName>DU</fullName>
            </value>
            <value>
                <fullName>Etisalat</fullName>
            </value>
            <value>
                <fullName>Virgin</fullName>
            </value>
            <value>
                <fullName>SWYP</fullName>
            </value>
            <value>
                <fullName>Ooredoo</fullName>
            </value>
            <value>
                <fullName>Omantel</fullName>
            </value>
            <value>
                <fullName>Zain</fullName>
            </value>
            <value>
                <fullName>Viva</fullName>
            </value>
            <value>
                <fullName>STC (Jawwy)</fullName>
            </value>
            <value>
                <fullName>Mobily</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/SIM_Id__c.field-meta.xml
<CustomField>
    <fullName>SIM_Id__c</fullName>
    <label>SIM Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New - Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Sent - Awaiting Activation</fullName>
            </value>
            <value>
                <fullName>Activated Successfully</fullName>
            </value>
            <value>
                <fullName>Activated but not in use</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>New - Deposit awaited</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery</fullName>
            </value>
            <value>
                <fullName>Cancelled before Shipment</fullName>
            </value>
            <value>
                <fullName>Cancel Additional Charge</fullName>
            </value>
            <value>
                <fullName>Redeliver</fullName>
            </value>
            <value>
                <fullName>Replacement Requested</fullName>
            </value>
            <value>
                <fullName>Waiting For Replacement</fullName>
            </value>
            <value>
                <fullName>Delivered - Activation Needed</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>InTransit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Stock_Item_Serial_No__c.field-meta.xml
<CustomField>
    <fullName>Stock_Item_Serial_No__c</fullName>
    <label>Stock Item Serial No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Telephone_Number__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Number__c</fullName>
    <description>Field used in Old Org for Express Boxes - SP-1763</description>
    <label>Telephone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>Termination_Date__c</fullName>
    <description>termination date for Asset termination SP-235</description>
    <label>Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/Opportunity_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Opportunity Quote Line Item</label>
    <nameField>
        <label>Opportunity Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Created&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Submitted For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/Shipment_Order__c.object-meta.xml
<CustomObject>
    <description>Object to track shipment requests and their delivery status</description>
    <label>Shipment Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Shipment Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Shipment Orders</relationshipLabel>
    <relationshipName>Shipment_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field to display current status of Shipment Order</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Ready to be shipped</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Returned Shipment</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <description>Items that were or are are held in stock</description>
    <label>Stock Item</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>New - In Stock</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Shipping</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Retour in Progress</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Returned - at Manufacturer</fullName>
            </value>
            <value>
                <fullName>Recycled</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Writeoff</fullName>
            </value>
            <value>
                <fullName>Tested</fullName>
            </value>
            <value>
                <fullName>Returned - In Stock</fullName>
            </value>
            <value>
                <fullName>Awaiting Delivery/In Shipment</fullName>
            </value>
            <value>
                <fullName>In Stock</fullName>
            </value>
            <value>
                <fullName>Technical Issue</fullName>
            </value>
            <value>
                <fullName>Exchange Requested</fullName>
            </value>
            <value>
                <fullName>Takeover</fullName>
            </value>
            <value>
                <fullName>Shared</fullName>
            </value>
            <value>
                <fullName>Pick-up Needed</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetSelector.cls
public inherited sharing class AssetSelector {
    
    public static List<Asset__c> getActiveAssetsForAccount(Id accountId) {
        return [SELECT id, Status__c FROM Asset__c WHERE Account__c =:accountId and termination_date__c = null];
    }
    /*******************************************************************************************************
    * @description Query for get asset not Activated
    * @param  ExcludeAssets list of Asset that should be exclude
    *         OpportunitiesIds Ids of the opportunities related to the assets.
    * @return List of Assets
    */
    public static List<Asset__c> getAssetsNotActivated(List<Asset__c> ExcludeAssets,set<id> OpportunitiesIds ) {
        List<Asset__c> lstAssets = new List<Asset__c>();

        lstAssets = [Select opportunity__c
                        From Asset__c
                        Where opportunity__c in :OpportunitiesIds
                            AND Id not in: ExcludeAssets
                            AND (Status__c NOT IN ('Activated Successfully' , 'Replaced'))
                            AND Retour_date__c = null];
        return lstAssets;
    }
    /*******************************************************************************************************
    * @description Query for get asset by Id
    * @param  assetIds set of Ids that should be query
    * @return map of Assets
    */
    public static Map<Id, Asset__c> getAssetsbyId(set<Id> assetIds ) {
        Map<Id, Asset__c> mpAssets = new Map<Id, Asset__c>();
        mpAssets = new Map<Id, Asset__c>([SELECT Id,
                                                Name,
                                                Telephone_Number__c,
                                                Status__c,
                                                SIM_Activated__c,
                                                SIM_Card_Provider__c,
                                                SIM_Id__c,
                                                Stock_Item_Serial_No__c,
                                                Termination_Date__c,
                                                Stock_Item__c,
                                                Activation_Date__c
                                            FROM Asset__c
                                            WHERE Id IN : assetIds]);
        return mpAssets;
    }


    /*******************************************************************************************************
    * @description Query for get asset details by Id
    * @param  assetId
    * @return asset details
    */
    public static Asset__c getAssetDetailsById(Id assetId)  {
        return [SELECT Id, Name, Status__c, Source_Asset__c, RecordTypeId,
                    Stock_Item__c, Stock_Item__r.RecordTypeId, Stock_Item__r.Name, 
                    Stock_Item__r.Status__c, Stock_Item__r.Condition__c, 
                    Account__r.Name, Account__r.Id, Account__r.Account_Email__c, Account__r.Account_Status__c, CurrencyIsoCode,
                    Id_Opportunity_Quote_Line_Item__r.Id_List_Product_Price__c,
                    Id_Opportunity_Quote_Line_Item__r.Id_List_Product_Price__r.SKU__c, Opportunity__c
                FROM Asset__c
                WHERE Id = :assetId
                LIMIT 1];
    }

    /*******************************************************************************************************
    * @description Query for get new asset details by old asset Id
    * @param  oldAssetId
    * @return asset details
    */
    public static Asset__c getNewAsset(Id oldAssetId)  {
        return [SELECT Id, Name, Status__c
                FROM Asset__c
                WHERE Replaced_Asset__c = :oldAssetId
                LIMIT 1];
    }

    /*******************************************************************************************************
    * @description Query for get all sourced assets based on source asset Id
    * @param  sourceAssetId
    * @return All assets that have this asset as a source
    */
    public static List<Asset__c> getSourcedAssets(Id sourceAssetId)  {
        return [SELECT Id, Source_Asset__c
                FROM Asset__c
                WHERE Source_Asset__c = :sourceAssetId];
    }


    /*******************************************************************************************************
    * @description get list of assets associated to these shipment orders
    * @param  shipmentOrders: st of SO ids
    * @return: map of SO Id and Assets
    */
    public static Map<Id, List<Asset__c>> getAssetsMapForShipmentOrders(Set<Id> shipmentOrders){
        List<Asset__c> assets = [SELECT Id, Name, Status__c, Shipment_Order__c, Shipment_Order_Line_Item__c, Stock_Item__c,
                                 RecordTypeId, RecordType.DeveloperName
                                 FROM Asset__c
                                 WHERE Shipment_Order__c IN :shipmentOrders]; 
        Map<Id, List<Asset__c>> assetsMap = new Map<Id, List<Asset__c>>();
        for(Asset__c a : assets) {
            if(assetsMap.get(a.Shipment_Order__c) != null) {
                assetsMap.get(a.Shipment_Order__c).add(a);
            } else {
                assetsMap.put(a.Shipment_Order__c, new List<Asset__c> {a});
            }
        }
        return assetsMap;
    }

    /*******************************************************************************************************
    * @description get list of assets associated to these shipment order line items
    * @param  soliIds: set of SOLI ids
    * @return: map of SOLI Id and Assets
    */
    public static Map<Id, Asset__c> getAssetsMapForShipmentOrderLineItems(Set<Id> soliIds) {
        Map<Id, Asset__c> soliAssets = new Map<Id, Asset__c>();
        List<Asset__c> assets = [SELECT Id, Name, Status__c, Shipment_Order__c, Shipment_Order_Line_Item__c, Stock_Item__c
                                 FROM Asset__c
                                 WHERE Shipment_Order_Line_Item__c IN :soliIds];
        for(Asset__c a : assets) {
            soliAssets.put(a.Shipment_Order_Line_Item__c, a);
        }
        return soliAssets;
    }
    /**
     *  @description get active assets by their account ids
     *
     * @param Ids
     *
     * @return List<Asset__c>
     */
    public static List<Asset__c> findActiveByAccountIds(Set<Id> Ids) {
        List<Asset__c> assets = new List<Asset__c>();
        assets = [SELECT Id, Status__c, Account__c, Account_Country__c FROM Asset__c WHERE Account__c IN :Ids AND Termination_Date__c = NULL];
        return assets;
    }
    /*******************************************************************************************************
   * @description get list of assets associated opportunity and Status
   * @param  opptyIdSet of oppty Id
   * @param  assetStageSet set of Asset Status
   * @return  List of Assets
   */
    public static List<Asset__c> getAssetByStatus(Set<Id> opptyIdSet,Set<string> assetStatusSet){
        List<Asset__c> assetLst = new List<Asset__c>();
        assetLst = [SELECT id, status__c,
                    opportunity__c FROM asset__c WHERE opportunity__c IN  :opptyIdSet
                    AND Status__c IN : assetStatusSet];
        return assetLst;
    }

}