force-app/main/default/objects/xAL_Address__c/xAL_Address__c.object-meta.xml
<CustomObject>
    <label>xAL Address</label>
    <nameField>
        <displayFormat>XAL-ADD-{0000}</displayFormat>
        <label>xAL Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>xAL Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/xAL_Address__c/fields/Address_Id__c.field-meta.xml
<CustomField>
    <fullName>Address_Id__c</fullName>
    <label>Address Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>City</fullName>
            </value>
            <value>
                <fullName>Country</fullName>
            </value>
            <value>
                <fullName>County</fullName>
            </value>
            <value>
                <fullName>District</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Province</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Suburb</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_AdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>xAL_AdministrativeAreaName__c</fullName>
    <label>Administrative Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_Country__c.field-meta.xml
<CustomField>
    <fullName>xAL_Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_DependentLocalityName__c.field-meta.xml
<CustomField>
    <fullName>xAL_DependentLocalityName__c</fullName>
    <label>Dependent Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_LocalityName__c.field-meta.xml
<CustomField>
    <fullName>xAL_LocalityName__c</fullName>
    <label>Locality</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_SubAdministrativeAreaName__c.field-meta.xml
<CustomField>
    <fullName>xAL_SubAdministrativeAreaName__c</fullName>
    <label>SubAdministrative Area</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_TranslatedAdministrativeArea__c.field-meta.xml
<CustomField>
    <fullName>xAL_TranslatedAdministrativeArea__c</fullName>
    <label>xAL TranslatedAdministrativeArea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/xAL_Address__c/fields/xAL_TranslatedSubAdministrativeArea__c.field-meta.xml
<CustomField>
    <fullName>xAL_TranslatedSubAdministrativeArea__c</fullName>
    <label>xAL TranslatedSubAdministrativeArea</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Uruguay</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Hong Kong</fullName>
    </customValue>
    <customValue>
        <fullName>Laos</fullName>
    </customValue>
    <customValue>
        <fullName>Cambodia</fullName>
    </customValue>
    <customValue>
        <fullName>Myanmar</fullName>
    </customValue>
    <customValue>
        <fullName>Chile</fullName>
    </customValue>
    <customValue>
        <fullName>Singapore</fullName>
    </customValue>
    <customValue>
        <fullName>Malaysia</fullName>
    </customValue>
    <customValue>
        <fullName>Taiwan</fullName>
    </customValue>
    <customValue>
        <fullName>Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Philippines</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Thailand</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Japan</fullName>
    </customValue>
    <description>Countries for xAL model</description>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/xALAddress_Selector.cls
/**
* @author Mantas Jurkunas
* @date 09.09.2019
*
* @description Selector class for xAL_Address
*/

public with sharing class xALAddress_Selector {

    public static List<xAL_Address__c> getByIdAndType(xAL_Address__c address, String addressType, String valueField) {
        List<xAL_Address__c> addresses = new List<xAL_Address__c>();
        String addressId = address.Address_Id__c + '%';
        String query = 'SELECT '+
                'xAL_Country__c,'+
                'xAL_AdministrativeAreaName__c,'+
                'xAL_SubAdministrativeAreaName__c,'+
                'xAL_LocalityName__c,'+
                'xAL_DependentLocalityName__c,'+
                'Type__c,'+
                'Code__c,'+
                'Address_Id__c,'+
                'xAL_TranslatedAdministrativeArea__c,'+
                'xAL_TranslatedSubAdministrativeArea__c'+
                ' FROM xAL_Address__c'+
                ' WHERE Address_Id__c LIKE :addressId'+
                ' AND Type__c = :addressType'+
                ' AND ' + valueField + ' = \''+ String.escapeSingleQuotes((String) address.get(valueField)) + '\''+
                ' Order by xAL_Country__c,xAL_AdministrativeAreaName__c,xAL_SubAdministrativeAreaName__c,xAL_LocalityName__c';
        try {
            addresses = Database.query(query);
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return addresses;
    }

    public static xAL_Address__c  getById(String addressId) {
        xAL_Address__c addresses;
        try {
            addresses = [SELECT
                    xAL_Country__c,
                    xAL_AdministrativeAreaName__c,
                    xAL_SubAdministrativeAreaName__c,
                    xAL_LocalityName__c,
                    xAL_DependentLocalityName__c,
                    Type__c,
                    Code__c,
                    Address_Id__c,
                    xAL_TranslatedAdministrativeArea__c,
                    xAL_TranslatedSubAdministrativeArea__c
            FROM xAL_Address__c
            WHERE  Id = :addressId
            Order by xAL_Country__c,xAL_AdministrativeAreaName__c,xAL_SubAdministrativeAreaName__c,xAL_LocalityName__c];
        } catch (QueryException e) {
            System.debug(e.getMessage());
        }
        return addresses;
    }

}