force-app/main/default/objects/Opportunity_Quote__c/Opportunity_Quote__c.object-meta.xml
<CustomObject>
    <description>this is the quote</description>
    <label>Opportunity Quote</label>
    <nameField>
        <displayFormat>OQ-{0000000000}</displayFormat>
        <label>Opportunity Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Quote__c/fields/Id_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Id_Opportunity__c</fullName>
    <description>this holds the opp id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Quotes</relationshipLabel>
    <relationshipName>Opportunity_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Waiting for answer</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval pending - Regional HOS</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Pending - legal</fullName>
            </value>
            <value>
                <fullName>Approval pending</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Viewed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/DH_AU_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>DH_AU_Opportunity_Quote</fullName>
    <active>true</active>
    <label>DH AU Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/Talabat_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>Talabat_Opportunity_Quote</fullName>
    <active>true</active>
    <label>Talabat Opportunity Quote</label>
</RecordType>

force-app/main/default/objects/Opportunity_Quote__c/recordTypes/Yogiyo_Opportunity_Quote.recordType-meta.xml
<RecordType>
    <fullName>Yogiyo_Opportunity_Quote</fullName>
    <active>true</active>
    <label>Yogiyo Opportunity Quote</label>
</RecordType>

force-app/main/default/classes/BatchAttachOppQuoteOnOpp.cls
global class BatchAttachOppQuoteOnOpp implements Database.Batchable<sObject> {
String rcType {get;set;}

global BatchAttachOppQuoteOnOpp (String rectype){
    rcType = rectype;
}

global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([select id,name,id_opportunity__c from Opportunity_quote__c where id_opportunity__r.stagename='Closed Won' and status__c='Accepted' and recordtype.developername=:rcType  /*and recordtype.developername Not in('Yogiyo_Opportunity_Quote','Talabat_Opportunity_Quote','DH_AU_Opportunity_Quote')*/]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Opportunity_Quote__c> oppQ = (List<Opportunity_Quote__c>)scope;
        List<Attachment> attchLst = new List<Attachment>();
        for(Opportunity_Quote__c oq:oppQ){
            
                Attachment att = new Attachment();
                PageReference pdfQuote = new PageReference('/apex/RenderQuoteAsPDF?id=' + oq.id);
                Blob myBlob ;
                if(!Test.isRunningTest()){
                    att.body = pdfQuote.getContent();
                }else
                att.body=Blob.valueof('test');  
                att.parentid=oq.id_opportunity__c;
                att.name=oq.name;
                att.ContentType='application/pdf';
                attchLst.add(att);
                        
            }
        
        insert attchLst;
    }



    global void finish(Database.BatchableContext BC) {
        
    }

}